'use strict';
const fs=require('fs');const path=require('path');
const{SCHEMAS,SUPPORTED_STRATEGY_IDS,TIME_FIELD_WRITERS,DATA_HEALTH_DIMENSIONS}=require('../contracts/canonical-contracts.cjs');
const REQUIRED_MODULES=['canonical-data','market-calendar','symbol-master','corporate-actions','market-regime','indicators','technical-analysis','support-resistance','relative-strength','vcp','liquidity','strategy-registry','strategy-runner','signal-normalizer','evidence-engine','agreement-engine','ranking-engine','risk-engine','basket-engine','position-sizing','morning-confirmation','portfolio','backtest','walk-forward','forward-ledger','historical-store','migration','data-health','diagnostics','certification'];
const REQUIRED_SCHEMAS=['ImplementationProvenance','SecurityMaster','MarketSession','CanonicalMarketSnapshot','IndicatorSnapshot','StrategyExecution','StrategySignal','EvidenceItem','AgreementSnapshot','DecisionSnapshot','RiskPlan','BasketPlan','RecommendationRecord','MorningConfirmationRecord','ForwardOutcome','PortfolioPosition','DataHealthRecord','DiagnosticRecord','MigrationProvenance'];
function readJson(root,rel){return JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'))}function assert(c,m){if(!c)throw new Error(m)}function setEq(a,b){return a.size===b.size&&[...a].every(x=>b.has(x))}
function certify(root=process.cwd()){
 const engine=readJson(root,'docs/astra/ENGINE_REGISTRY.json'),strategy=readJson(root,'docs/astra/STRATEGY_REGISTRY.json'),stores=readJson(root,'docs/astra/HISTORICAL_STORES.json'),runtime=readJson(root,'docs/astra/RUNTIME_DEPENDENCIES.json'),migration=readJson(root,'docs/astra/MIGRATION_MANIFEST.json'),parity=readJson(root,'docs/astra/PARITY_MANIFEST.json'),bounds=readJson(root,'docs/astra/ARCHITECTURE_BOUNDARIES.json'),removal=readJson(root,'docs/astra/LEGACY_REMOVAL_PLAN.json'),gates=readJson(root,'04_ACCEPTANCE_GATES.json');
 assert(engine.count===20,'baseline engine count changed');assert(strategy.count===18,'baseline strategy count changed');assert(stores.count===19,'baseline historical-store count changed');assert(runtime.legacyRuntimeDependencyCount===8,'baseline runtime dependency count changed');
 assert(REQUIRED_SCHEMAS.every(x=>SCHEMAS[x]),'required executable canonical schema missing');assert(Object.keys(TIME_FIELD_WRITERS).length===6,'time writer contract incomplete');assert(DATA_HEALTH_DIMENSIONS.length===14,'data health dimensions incomplete');
 const strategyIds=new Set(strategy.strategies.map(x=>x.strategyId));assert(setEq(strategyIds,new Set(SUPPORTED_STRATEGY_IDS)),'StrategyExecution contract does not cover all 18 discovered strategies');
 const storeIds=new Set(stores.stores.map(x=>x.storeId)),migrationIds=new Set(migration.sources.map(x=>x.sourceId));assert(migration.sources.length===19&&setEq(storeIds,migrationIds),'migration manifest is not 19/19');
 const runtimeIds=new Set(runtime.legacyDependencies.map(x=>x.id)),removalIds=new Set(removal.dependencies.map(x=>x.dependencyId));assert(removal.dependencies.length===8&&setEq(runtimeIds,removalIds),'legacy removal plan is not 8/8');assert(removal.targetRuntimeLegacyDependencyCount===0,'target runtime legacy dependency count must be zero');assert(removal.policy?.G12Status==='PENDING','G06 historical G12 policy marker changed');const currentG12=gates.gates.find(x=>x.id==='G12')?.status;assert(currentG12==='PENDING'||currentG12==='GREEN',`unexpected current G12 status ${currentG12}`);let currentG12RuntimeLegacyDependencyCount=null;if(currentG12==='GREEN'){const g12=readJson(root,'docs/astra/G12_CERTIFICATION.json');assert(g12.status==='GREEN','current G12 GREEN without certification');assert(g12.runtimeLegacyDependencyCount===0,'G12 GREEN requires zero legacy runtime dependencies');assert(g12.dependencyClosure?.closed===8&&g12.dependencyClosure?.total===8,'G12 closure proof incomplete');assert(g12.productionCutover===false,'G12 certification changed production cutover');currentG12RuntimeLegacyDependencyCount=g12.runtimeLegacyDependencyCount}
 const moduleMap=new Map(bounds.modules.map(x=>[x.module,x]));for(const name of REQUIRED_MODULES){const m=moduleMap.get(name);assert(m,`architecture boundary missing ${name}`);for(const f of['responsibility','allowedImports','forbiddenImports','allowedDataAccess','forbiddenRuntimeServices','inputs','outputs','persistenceOwnership','versioningRequirements'])assert(m[f]!==undefined,`${name} missing ${f}`)}
 assert(bounds.globalRules?.productionRuntimeLegacyDependencyCount===0,'architecture target must require zero legacy runtime dependencies');assert(bounds.globalRules?.noGodEngine===true,'No-God-Engine invariant missing');
 const qe=engine.engines.find(x=>x.engineId==='QUANT_EDGE');assert(qe?.classification==='legacy-output-only','QUANT_EDGE classification changed or invented');const qep=parity.outputPreservationCases.find(x=>x.engine==='QUANT_EDGE');assert(qep?.algorithmicParity===false&&qep?.mode==='OUTPUT_PRESERVATION_ONLY','QUANT_EDGE parity policy invalid');
 const parityStrategies=new Set(parity.cases.map(x=>x.strategy));assert(setEq(parityStrategies,strategyIds),'parity preparation does not cover all 18 recoverable strategy identities');assert(migration.globalContract?.generalLatestRowWins===false,'latest-row-wins is forbidden');assert(migration.globalContract?.rawLegacyArchive==='immutable','raw legacy archive must be immutable');
 const g07Prepared=migration.status==='G07_PREPARED_NOT_EXECUTED',g07Migrated=migration.status==='G07_MIGRATED_RECONCILED';assert(g07Prepared||g07Migrated,`unexpected G07 migration status ${migration.status}`);if(g07Migrated){assert(migration.sources.every(x=>x.status==='G07_MIGRATED_RECONCILED'),'G07 migrated state requires all 19 sources reconciled');assert(migration.sources.every(x=>x.countStatus==='MEASURED_FROM_PINNED_SOURCE'&&Number.isInteger(x.exactDiscoveredCount)&&x.exactDiscoveredCount>=0),'G07 migrated state requires measured exact per-source counts');assert(parity.cases.every(x=>x.sourceCommit),'G07 migrated state requires all parity source commits pinned')}
 const unresolvedCommits=parity.cases.filter(x=>!x.sourceCommit).map(x=>x.caseId);return{status:'PASS',baseline:{engines:20,strategies:18,historicalStores:19,legacyRuntimeDependencies:8},executableSchemas:Object.keys(SCHEMAS).length,architectureModules:bounds.modules.length,migrationSources:migration.sources.length,legacyReplacementContracts:removal.dependencies.length,parityStrategyCases:parity.cases.length,g07Status:migration.status,g12BaselineStatus:removal.policy.G12Status,g12Status:currentG12,currentG12RuntimeLegacyDependencyCount,warnings:unresolvedCommits.length?[`Parity cases requiring exact branch commit pin before G10: ${unresolvedCommits.join(',')}`]:[]}
}
if(require.main===module){try{process.stdout.write(`${JSON.stringify(certify(path.resolve(process.argv[2]||process.cwd())),null,2)}\n`)}catch(e){process.stderr.write(`G06_CERTIFICATION_FAIL ${e.message}\n`);process.exitCode=1}}
module.exports={certify,REQUIRED_MODULES,REQUIRED_SCHEMAS};
