'use strict';
const fs=require('fs');
const path=require('path');
const H=require('../data-health/g11-data-health.cjs');
const ROOT=path.resolve(process.env.GITHUB_WORKSPACE||process.cwd());
const R=p=>path.join(ROOT,p);
const read=(p,d=null)=>{try{return JSON.parse(fs.readFileSync(R(p),'utf8'))}catch{return d}};
const write=(p,v)=>{fs.mkdirSync(path.dirname(R(p)),{recursive:true});fs.writeFileSync(R(p),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n','utf8')};
const ensure=(c,m)=>{if(!c)throw new Error(m)};
const envPass=n=>ensure(process.env[n]==='1',`${n} did not report PASS`);

for(const n of ['G06_REGRESSION_PASS','G07_REGRESSION_PASS','G08_REGRESSION_PASS','G09_REGRESSION_PASS','G10_REGRESSION_PASS','G11_TEST_PASS'])envPass(n);
const testCount=Number(process.env.G11_TEST_COUNT||0);ensure(testCount>=29,`G11 test count too small: ${testCount}`);
const gates=read('04_ACCEPTANCE_GATES.json');const by=new Map(gates.gates.map(x=>[x.id,x]));
for(const id of ['G01','G02','G03','G04','G05','G06','G07','G08','G09','G10'])ensure(by.get(id)?.status==='GREEN',`${id} baseline not GREEN`);
ensure(by.get('G12')?.status==='PENDING','G12 must remain PENDING during G11');
const legacy=read('docs/astra/LEGACY_REMOVAL_PLAN.json',{});ensure(legacy.dependencies?.length===8,'legacy runtime dependency inventory changed');

const h=H.buildHealth();
ensure(h.productionEligibilityInvariant,'production eligibility changed from 1/18');
ensure(h.quarantinePass,'G07 invalid/unresolved quarantine accounting changed');
ensure(h.quantEdgePass,'QUANT_EDGE isolation changed');
ensure(h.pipeline.legacyNetworkCalls===0,'current G11/G09 certification pipeline made a legacy-network call');
ensure(h.pipeline.productionCutover===false,'production cutover occurred during G11');
ensure(h.legacyDependencies===8,'G11 removed or changed legacy dependencies');

write('docs/astra/G11_UNIVERSE_BASELINE.json',h.universe);
write('docs/astra/G11_DATA_HEALTH_SNAPSHOT.json',h.snapshot);
write('docs/astra/G11_DATA_HEALTH_METRICS.json',h.metrics);
write('docs/astra/G11_DATA_HEALTH_ISSUES.json',h.issues);
write('docs/astra/G11_STRATEGY_DATA_READINESS.json',h.strategyReadiness);
write('docs/astra/G11_SESSION_INTEGRITY.json',h.sessionIntegrity);
write('docs/astra/G11_SYMBOL_HEALTH.json',h.symbolHealth);
write('docs/astra/G11_PERFORMANCE_BASELINE.json',h.performance);
write('docs/astra/G11_DESTRUCTIVE_REVIEW.json',h.destructive);
write('docs/astra/G11_SUPPORT_RESISTANCE_HEALTH.json',{schemaVersion:'astra-g11-support-resistance-health-1',evaluatedAt:h.evaluatedAt,summary:h.metrics.supportResistance,records:h.supportResistanceRows});
write('docs/astra/G11_HISTORY_DEPTH.json',{schemaVersion:'astra-g11-history-depth-1',evaluatedAt:h.evaluatedAt,records:h.historyStats});

const testEvidence={
  schemaVersion:'astra-g11-test-evidence-1',generatedAt:h.evaluatedAt,status:'PASS',g11Tests:testCount,
  universeIntegrity:'PASS',latestSessionResolution:'PASS',sessionTimeSemantics:'PASS',ohlcValidation:'PASS',volumeTurnoverValidation:'PASS',historicalDepthReadiness:'PASS',indicatorCoverage:'PASS',supportResistanceDiagnostics:'PASS',symbolMapping:'PASS',duplicateSessionHandling:'PASS',missingSessionHandling:'PASS',staleDataDetection:'PASS',g07QuarantineEnforcement:h.quarantinePass?'PASS':'FAIL',strategyInputReadiness:'PASS',regimeInputHealth:'PASS_WITH_EXPLICIT_DEGRADED_STATUS_WHEN_PARTIAL',currentInternalPipeline:h.pipeline.ok?'PASS':'DATA_HEALTH_BLOCKED',zeroOpportunityDistinction:'PASS',fullMarketSearchReadiness:h.metrics.searchReadiness.missingActive===0?'PASS':'FAIL',legacyNetworkIsolation:h.pipeline.legacyNetworkCalls===0?'PASS':'FAIL',quantEdgeIsolation:h.quantEdgePass?'PASS':'FAIL',productionEligibilityInvariant:h.productionEligibilityInvariant?'PASS':'FAIL',
  g06Regression:'PASS',g07Regression:'PASS',g08Regression:'PASS',g09Regression:'PASS',g10Regression:'PASS',
  focusedDestructiveReview:h.destructive.pass?'PASS':'BLOCKER_CONFIRMED',g19Increment:0,g12Status:'PENDING',productionCutover:false,workflowRunId:Number(process.env.GITHUB_RUN_ID||0),sourceCommit:process.env.GITHUB_SHA||h.codeVersion
};
write('docs/astra/G11_TEST_EVIDENCE.json',testEvidence);

const report=`# G11 Full Data Health Certification\n\n- Gate status: **${h.gateStatus}**\n- Overall data-health status: **${h.overallStatus}**\n- Evaluated source snapshot: ${h.evaluatedAt}\n- Code HEAD evaluated: ${h.codeVersion}\n- Intended mapped universe: ${h.universe.intendedUniverseCount}\n- Active universe: ${h.universe.activeUniverseCount}\n- Intentionally excluded: ${h.universe.intentionallyExcludedCount}\n- Latest expected finalized session: ${h.sessionIntegrity.latestExpectedSession}\n- Latest available canonical session: ${h.sessionIntegrity.latestAvailableCanonicalSession}\n- Session freshness: ${h.sessionIntegrity.freshnessStatus}\n- Valid current canonical securities: ${h.metrics.currentCanonicalSecurities.numerator}/${h.metrics.currentCanonicalSecurities.denominator}\n- Pipeline-ready V16 source-feature securities: ${h.metrics.decisionPipeline.pipelineReadySecurities}/${h.universe.activeUniverseCount}\n- Production strategy readiness: ${h.metrics.strategyInputReadiness.productionCritical.numerator}/${h.metrics.strategyInputReadiness.productionCritical.denominator} Security×Strategy rows\n- Current unified-pipeline valid opportunities: ${h.pipeline.validOpportunities}\n- Current unified-pipeline legacy-network calls: ${h.pipeline.legacyNetworkCalls}\n- CRITICAL unresolved issue classes: ${h.issues.criticalUnresolved}\n- HIGH unresolved issue classes: ${h.issues.highUnresolved}\n- G07 quarantine leakage: ${h.quarantinePass?'PASS':'FAIL'}\n- QUANT_EDGE: OUTPUT_INTEGRITY_ONLY\n- Production eligibility: 1/18 unchanged\n- G12: PENDING; all 8 legacy runtime dependencies remain.\n\n## Material findings\n\n${h.issues.issues.length?h.issues.issues.map(x=>`- **${x.severity} ${x.code}** — ${x.summary} (${x.affectedCount} affected securities).`).join('\n'):'- No unresolved material data-health finding.'}\n\n## Acceptance decision\n\n${h.gateStatus==='GREEN'?'All G11 production-critical conditions are satisfied or covered by deterministic legitimate exclusions.':'G11 is blocked because at least one CRITICAL/HIGH production-critical data-health condition remains unresolved. No aggregate coverage percentage overrides these blockers.'}\n\nThe G11 run is non-cutover/shadow certification only. It does not change strategy eligibility, remove legacy dependencies, or start G12.\n`;
write('docs/astra/G11_DATA_HEALTH_REPORT.md',report);

const evidencePaths=['docs/astra/G11_UNIVERSE_BASELINE.json','docs/astra/G11_DATA_HEALTH_SNAPSHOT.json','docs/astra/G11_DATA_HEALTH_METRICS.json','docs/astra/G11_DATA_HEALTH_ISSUES.json','docs/astra/G11_STRATEGY_DATA_READINESS.json','docs/astra/G11_SESSION_INTEGRITY.json','docs/astra/G11_SYMBOL_HEALTH.json','docs/astra/G11_TEST_EVIDENCE.json','docs/astra/G11_DATA_HEALTH_REPORT.md','docs/astra/G11_PERFORMANCE_BASELINE.json','docs/astra/G11_DESTRUCTIVE_REVIEW.json'];
const gate=by.get('G11');gate.status=h.gateStatus;gate.evidence=evidencePaths;gates.updated_at=h.evaluatedAt;gates.certified=false;
for(const id of ['G12','G13','G14','G15','G16','G17','G18','G19'])ensure(by.get(id)?.status==='PENDING',`${id} changed during G11`);
write('04_ACCEPTANCE_GATES.json',gates);

const state=read('05_WORK_STATE.json',{});state.current_phase=h.gateStatus==='GREEN'?'G11_COMPLETE_G12_NOT_STARTED':'G11_BLOCKED_DATA_HEALTH';state.current_gate=h.gateStatus==='GREEN'?'G12':'G11';state.last_green_gate=h.gateStatus==='GREEN'?'G11':'G10';state.blocking_issues=h.gateStatus==='GREEN'?[]:h.issues.issues.filter(x=>['CRITICAL','HIGH'].includes(x.severity)).map(x=>`${x.severity}:${x.code}:${x.affectedCount}`);state.completed_gates=Array.isArray(state.completed_gates)?state.completed_gates.filter(x=>x!=='G11'):[];if(h.gateStatus==='GREEN')state.completed_gates.push('G11');state.failed_gates=Array.isArray(state.failed_gates)?state.failed_gates.filter(x=>x!=='G11'):[];state.blocked_gates=h.gateStatus==='BLOCKED'?['G11']:[];state.clean_review_streak=0;state.g11_certification={status:h.gateStatus,overallDataHealth:h.overallStatus,workflowRunId:Number(process.env.GITHUB_RUN_ID||0),sourceCommit:process.env.GITHUB_SHA||h.codeVersion,intendedUniverse:h.universe.intendedUniverseCount,activeSecurities:h.universe.activeUniverseCount,latestExpectedSession:h.sessionIntegrity.latestExpectedSession,latestAvailableSession:h.sessionIntegrity.latestAvailableCanonicalSession,sessionFreshness:h.sessionIntegrity.freshnessStatus,currentCanonical:`${h.metrics.currentCanonicalSecurities.numerator}/${h.metrics.currentCanonicalSecurities.denominator}`,pipelineReady:`${h.metrics.decisionPipeline.pipelineReadySecurities}/${h.universe.activeUniverseCount}`,productionEligibility:'1/18',productionCriticalReady:`${h.strategyReadiness.productionCritical.readySecurities}/${h.strategyReadiness.productionCritical.totalActiveSecurities}`,criticalUnresolved:h.issues.criticalUnresolved,highUnresolved:h.issues.highUnresolved,g07QuarantineLeakage:h.quarantinePass?'PASS':'FAIL',legacyNetworkCalls:h.pipeline.legacyNetworkCalls,validOpportunities:h.pipeline.validOpportunities,g11Tests:testCount,g06Regression:'PASS',g07Regression:'PASS',g08Regression:'PASS',g09Regression:'PASS',g10Regression:'PASS',focusedDestructiveReview:h.destructive.pass?'PASS':'BLOCKER_CONFIRMED',g12Status:'PENDING',productionCutover:false};
const finding=`G11 ${h.gateStatus}: ${h.overallStatus}; intended mapped ${h.universe.intendedUniverseCount}, active ${h.universe.activeUniverseCount}, current canonical ${h.metrics.currentCanonicalSecurities.numerator}/${h.metrics.currentCanonicalSecurities.denominator}, pipeline-ready ${h.metrics.decisionPipeline.pipelineReadySecurities}/${h.universe.activeUniverseCount}, CRITICAL ${h.issues.criticalUnresolved}, HIGH ${h.issues.highUnresolved}.`;
state.material_findings=Array.isArray(state.material_findings)?state.material_findings.filter(x=>!String(x).startsWith('G11 ')):[];state.material_findings.push(finding);state.next_action=h.gateStatus==='GREEN'?'Stop. G12 remains PENDING and may start only on explicit request. Do not remove the 8 legacy runtime dependencies or cut over production.':'Repair/restore validation-approved current-session history and symbol verification for the affected active mapped securities, regenerate dependent current indicators/regime inputs, then rerun G11. Do not start G12, remove legacy dependencies, or cut over production.';state.last_updated=h.evaluatedAt;write('05_WORK_STATE.json',state);write('docs/astra/WORK_STATE.json',state);

const logPath=R('07_WORK_LOG.md');const old=fs.existsSync(logPath)?fs.readFileSync(logPath,'utf8'):'';const entry=`\n\n## ${h.evaluatedAt} — G11 Full Data Health Certification\n\n- Status: ${h.gateStatus} / ${h.overallStatus}\n- Universe: ${h.universe.intendedUniverseCount} mapped, ${h.universe.activeUniverseCount} active, ${h.universe.intentionallyExcludedCount} intentional exclusions.\n- Session: expected ${h.sessionIntegrity.latestExpectedSession}, available ${h.sessionIntegrity.latestAvailableCanonicalSession}, ${h.sessionIntegrity.freshnessStatus}.\n- Current canonical: ${h.metrics.currentCanonicalSecurities.numerator}/${h.metrics.currentCanonicalSecurities.denominator}; V16 pipeline-ready: ${h.metrics.decisionPipeline.pipelineReadySecurities}/${h.universe.activeUniverseCount}.\n- Material issue classes: CRITICAL=${h.issues.criticalUnresolved}, HIGH=${h.issues.highUnresolved}.\n- G07 quarantine=${h.quarantinePass?'PASS':'FAIL'}; legacy-network calls=${h.pipeline.legacyNetworkCalls}; production cutover=false; G12=PENDING.\n- G06/G07/G08/G09/G10 regressions: PASS.\n`;
if(!old.includes(`## ${h.evaluatedAt} — G11 Full Data Health Certification`))fs.writeFileSync(logPath,old+entry,'utf8');

console.log('ASTRA_G11 '+JSON.stringify({status:h.gateStatus,overall:h.overallStatus,universe:h.universe.intendedUniverseCount,active:h.universe.activeUniverseCount,expected:h.sessionIntegrity.latestExpectedSession,available:h.sessionIntegrity.latestAvailableCanonicalSession,freshness:h.sessionIntegrity.freshnessStatus,currentCanonical:`${h.metrics.currentCanonicalSecurities.numerator}/${h.metrics.currentCanonicalSecurities.denominator}`,pipelineReady:`${h.metrics.decisionPipeline.pipelineReadySecurities}/${h.universe.activeUniverseCount}`,productionReady:`${h.strategyReadiness.productionCritical.readySecurities}/${h.strategyReadiness.productionCritical.totalActiveSecurities}`,critical:h.issues.criticalUnresolved,high:h.issues.highUnresolved,legacyNetworkCalls:h.pipeline.legacyNetworkCalls,validOpportunities:h.pipeline.validOpportunities,tests:testCount,g12:'PENDING'}));
