(() => {
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch])),n=v=>{if(v===null||v===undefined||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null},num=(v,d=2)=>n(v)===null?'—':n(v).toLocaleString('ar-EG',{maximumFractionDigits:d}),pct=v=>n(v)===null?'—':`${num(v,2)}%`,load=async u=>{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${u}: HTTP ${r.status}`);return r.json()};
const state={tech:null,market:null,q:'',avail:'READY',provider:'ALL',trend:'ALL',rsi:'ALL',macd:'ALL',sort:'MOM20_DESC',evidenceSource:null};
async function loadTechnicalEvidence(){
  try{const raw=await load('../data/v20/full-market-technical.json');state.evidenceSource='RAW_SIDECAR';return raw;}catch(rawError){
    const regression=await load('../data/v20/regression.json');
    if(!regression?.fullMarketTechnical)throw new Error(`Full-market technical evidence unavailable; raw=${rawError.message}; regression fallback missing`);
    if(regression?.fullMarketTechnicalRegression?.ok!==true)throw new Error('Authoritative full-market technical regression is not green');
    state.evidenceSource='REGRESSION_EMBEDDED_AUTHORITATIVE';return regression.fullMarketTechnical;
  }
}
function marketMap(){return new Map((state.market?.rows||[]).map(x=>[x.ticker,x]))}
function atrPct(s){const a=n(s.indicators?.atr14),c=n(s.indicators?.close);return a!==null&&c>0?a/c*100:null}
function trendState(s){const i=s.indicators||{},c=n(i.close),a=n(i.sma20),b=n(i.sma50);if(c===null||a===null||b===null)return'UNKNOWN';if(c>a&&c>b)return'ABOVE_BOTH';if(c<a&&c<b)return'BELOW_BOTH';return'MIXED'}
function rsiState(s){const x=n(s.indicators?.rsi14);return x===null?'UNKNOWN':x<=30?'OVERSOLD':x>=70?'OVERBOUGHT':'BALANCED'}
function providerState(s){return s.sourceKind==='LIVE_STARTA_SECONDARY_REFRESH'?'STARTA':s.sourceKind==='LIVE_YAHOO_REFRESH'?'YAHOO':s.sourceKind==='CACHED_VERIFIED_HISTORY_DOCUMENT'?'CACHED':'OTHER'}
function sourceLabel(s){return providerState(s)==='STARTA'?'Starta · secondary research':providerState(s)==='YAHOO'?'Yahoo · primary research':providerState(s)==='CACHED'?'Cached verified history':s.sourceKind||'—'}
function rows(){const mm=marketMap(),q=state.q.toLowerCase();let a=(state.tech?.symbols||[]).map(s=>({...s,market:mm.get(s.ticker)||null})).filter(s=>(state.avail==='ALL'||(state.avail==='READY'?s.currentReady:s.currentReady!==true))&&(state.provider==='ALL'||providerState(s)===state.provider)&&(!q||`${s.ticker} ${s.market?.nameAr||''} ${s.market?.nameEn||''}`.toLowerCase().includes(q))&&(state.trend==='ALL'||trendState(s)===state.trend)&&(state.rsi==='ALL'||rsiState(s)===state.rsi)&&(state.macd==='ALL'||(state.macd==='POSITIVE'?n(s.indicators?.macdHistogram)>0:n(s.indicators?.macdHistogram)<0)));a.sort((x,y)=>state.sort==='MOM20_DESC'?(n(y.indicators?.momentum20Pct)??-1e9)-(n(x.indicators?.momentum20Pct)??-1e9):state.sort==='RSI_DESC'?(n(y.indicators?.rsi14)??-1e9)-(n(x.indicators?.rsi14)??-1e9):state.sort==='RSI_ASC'?(n(x.indicators?.rsi14)??1e9)-(n(y.indicators?.rsi14)??1e9):state.sort==='ATR_DESC'?(atrPct(y)??-1e9)-(atrPct(x)??-1e9):x.ticker.localeCompare(y.ticker));return a}
function tag(s){return s.currentReady?'<span class="tag ready">Current ready</span>':'<span class="tag blocked">غير متاح</span>'}
function render(){const a=rows();$('resultCount').textContent=`${a.length} سهم`;$('rows').innerHTML='';$('cards').innerHTML='';for(const s of a){const i=s.indicators||{},m=s.market||{},tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(s.ticker)}</strong><small>${esc(m.nameAr||m.nameEn||'—')}</small></td><td>${num(m.price,4)}</td><td>${num(i.rsi14,1)}</td><td class="${n(i.macdHistogram)>0?'pos':n(i.macdHistogram)<0?'neg':''}">${num(i.macdHistogram,4)}</td><td>${num(i.sma20,4)}</td><td>${num(i.sma50,4)}</td><td>${pct(atrPct(s))}</td><td class="${n(i.momentum20Pct)>0?'pos':n(i.momentum20Pct)<0?'neg':''}">${pct(i.momentum20Pct)}</td><td>${esc(sourceLabel(s))}</td><td>${tag(s)}</td>`;tr.addEventListener('click',()=>open(s));$('rows').appendChild(tr);const c=document.createElement('article');c.className='card';c.innerHTML=`<div><strong>${esc(s.ticker)}</strong><small>${esc(m.nameAr||m.nameEn||'—')}</small></div><div class="mini"><span>RSI ${num(i.rsi14,1)}</span><span>Mom20 ${pct(i.momentum20Pct)}</span><span>ATR ${pct(atrPct(s))}</span></div><div class="provider-mini">${esc(sourceLabel(s))}</div>${tag(s)}`;c.addEventListener('click',()=>open(s));$('cards').appendChild(c)}}
function open(s){const i=s.indicators||{},m=s.market||{},isStarta=providerState(s)==='STARTA';$('detail').innerHTML=`<span class="eyebrow">${esc(s.ticker)} • ${esc(s.asOfSession||'—')}</span><h2>${esc(m.nameAr||m.nameEn||s.ticker)}</h2><p class="note">Full Technical Evidence للبحث فقط — لا تدخل Decision Score أو V17 gate أو allocation.${isStarta?' Starta مصدر ثانوي غير رسمي ولا يصبح V17 trusted evidence.':''}</p><div class="detail-grid">${[['السعر',num(m.price,4)],['RSI14',num(i.rsi14,2)],['MACD',num(i.macd,5)],['Signal',num(i.macdSignal,5)],['Histogram',num(i.macdHistogram,5)],['ATR14',num(i.atr14,5)],['ATR%',pct(atrPct(s))],['SMA20',num(i.sma20,4)],['SMA50',num(i.sma50,4)],['SMA200',num(i.sma200,4)],['EMA12',num(i.ema12,4)],['EMA26',num(i.ema26,4)],['Momentum5',pct(i.momentum5Pct)],['Momentum20',pct(i.momentum20Pct)],['Rows',num(s.rowsUsed,0)],['Price diff',pct(s.currentPriceDifferencePct)]].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div><div class="prov"><b>Provenance</b><span>${esc(sourceLabel(s))} • identityVerified=${s.identityVerified===true} • session=${esc(s.asOfSession||'—')}</span><span>Provider role: ${esc(s.providerRole||'—')} • providerBlended=${s.providerBlended===true?'YES':'NO'}</span><span>Decision use: ${esc(s.decisionUse||'—')}</span><span>Evidence container: ${esc(state.evidenceSource||'—')}</span></div>${(s.blockers||[]).length?`<div class="blockers">${s.blockers.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}`;$('dialog').showModal()}
async function init(){try{const [tech,market]=await Promise.all([loadTechnicalEvidence(),load('../data/v20/market-explorer.json')]);state.tech=tech;state.market=market;$('readyCount').textContent=`${num(tech.summary?.currentReadyCount,0)} / ${num(tech.summary?.universeCount,0)}`;$('coverage').textContent=pct(tech.summary?.currentReadyCoveragePct);$('universe').textContent=num(tech.summary?.universeCount,0);$('liveReady').textContent=num(tech.summary?.liveYahooReadyCount,0);$('startaReady').textContent=num(tech.summary?.liveStartaReadyCount,0);$('cachedReady').textContent=num(tech.summary?.cachedReadyCount,0);$('unavailable').textContent=num(tech.summary?.unavailableCount,0);$('session').textContent=tech.asOfSessionDate||'—';for(const [id,key] of [['search','q'],['availability','avail'],['provider','provider'],['trend','trend'],['rsi','rsi'],['macd','macd'],['sort','sort']])$(id).addEventListener(id==='search'?'input':'change',e=>{state[key]=e.target.value;render()});render();$('loading').classList.add('hidden');$('content').classList.remove('hidden')}catch(e){$('loading').classList.add('hidden');$('error').classList.remove('hidden');$('error').textContent=`تعذر تحميل Full Technical Explorer: ${e.message}`}}$('close').addEventListener('click',()=>$('dialog').close());init();
})();