'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {classifyResearchRecommendation}=require('../../scripts/v17/historical-recovery/long-history/research-recommendation.cjs');const {checkPaths}=require('../../scripts/v17/frozen-path-check.cjs');
function row(overrides={}){const h={available:true,currentDrawdownPct:40,recoveryPositionPct:20},technical={rsi14:55,atrPct:2};return{dataQualityStatus:'VALID',corporateActionConfidence:'HIGH_NO_DETECTED_DISCONTINUITY_SOURCE_NOT_AUTHORITATIVE',dataConfidence:95,recoveryStage:'EARLY_RECOVERY',recoveryScore:75,strengthScore:60,horizons:{maxAvailable:{...h,...overrides.horizon},technical:{...technical,...overrides.technical}},...overrides.row}}
test('normal staged candidate passes the staged gates',()=>{const r=row({horizon:{currentDrawdownPct:32,recoveryPositionPct:28},row:{recoveryScore:65,strengthScore:50,dataConfidence:90}});assert.equal(classifyResearchRecommendation(r).labelAr,'مرشح استثماري تدريجي')});
test('strong candidate after confirmation passes every strong gate',()=>{assert.equal(classifyResearchRecommendation(row()).labelAr,'مرشح استثماري قوي بعد التأكيد')});
test('extreme drawdown becomes high-risk recovery rather than normal buy',()=>{const r=row({horizon:{currentDrawdownPct:82,recoveryPositionPct:12},row:{recoveryStage:'RECOVERY_CONFIRMED',recoveryScore:90,strengthScore:80}});assert.equal(classifyResearchRecommendation(r).labelAr,'فرصة تعافٍ عالية المخاطر')});
test('high RSI prevents normal staged classification',()=>{const r=classifyResearchRecommendation(row({technical:{rsi14:85}}));assert.notEqual(r.labelAr,'مرشح استثماري قوي بعد التأكيد');assert.notEqual(r.labelAr,'مرشح استثماري تدريجي')});
test('bottoming stock is a bottom watch',()=>{const r=row({row:{recoveryStage:'BOTTOMING',recoveryScore:40,strengthScore:35}});assert.equal(classifyResearchRecommendation(r).labelAr,'مراقبة قاع')});
test('weak strength produces wait or watch rather than a buy label',()=>{const r=classifyResearchRecommendation(row({row:{strengthScore:20,recoveryScore:45}}));assert.ok(['انتظار','مراقبة إيجابية'].includes(r.labelAr))});
test('unresolved corporate action cannot receive positive label',()=>{const r=row({row:{corporateActionConfidence:'AMBIGUOUS_REVIEW_REQUIRED'}}),x=classifyResearchRecommendation(r);assert.equal(x.labelAr,'انتظار')});
test('recommendation and risk labels are independent',()=>{const lowAtr=classifyResearchRecommendation(row()),highAtr=classifyResearchRecommendation(row({technical:{atrPct:8}}));assert.equal(lowAtr.labelAr,highAtr.labelAr);assert.notEqual(lowAtr.riskLabelAr,highAtr.riskLabelAr)});
test('every recommendation contains two to five Arabic reasons',()=>{for(const r of [row(),row({row:{recoveryStage:'BOTTOMING'}}),row({technical:{rsi14:95}})]){const x=classifyResearchRecommendation(r);assert.ok(x.reasonsAr.length>=2&&x.reasonsAr.length<=5);assert.ok(x.reasonsAr.every(v=>/[\u0600-\u06ff]/.test(v)))}});
test('normal UI renders integrated Arabic labels and does not render raw classification codes',()=>{const app=fs.readFileSync(path.resolve(__dirname,'../../preview-v17/historical-recovery/app.js'),'utf8'),html=fs.readFileSync(path.resolve(__dirname,'../../preview-v17/historical-recovery/index.html'),'utf8');for(const text of ['التصنيف البحثي','المخاطرة','كيف نقرأ النتائج؟','البيانات المالية غير كافية'])assert.ok(html.includes(text));assert.ok(app.includes('row.classificationAr'));assert.ok(!app.includes('${row.classificationCode}'))});
test('V16.9 frozen-path protection remains active',()=>{assert.equal(checkPaths(['preview-v169/x','scripts/stable/x','data/stable/x','.github/workflows/v169-primary-pages-deploy.yml']).violations.length,4)});
