'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const {summarize,buildHorizons,bestReliableHorizon}=require('../../scripts/v17/historical-recovery/long-history/horizons.cjs');
const {inspectSessions}=require('../../scripts/v17/historical-recovery/long-history/quality.cjs');
const {analyze,isRecoveryOpportunity}=require('../../scripts/v17/historical-recovery/long-history/build-market.cjs');
const {checkPaths}=require('../../scripts/v17/frozen-path-check.cjs');
function rows(prices,{raw=prices,volume=1000}={}){const start=Date.UTC(2019,0,1);return prices.map((p,i)=>({date:new Date(start+i*86400000).toISOString().slice(0,10),open:raw[i]??p,high:(raw[i]??p)*1.01,low:(raw[i]??p)*.99,close:raw[i]??p,adjustedClose:p,volume:i>prices.length-6?volume*1.5:volume}));}
function doc(prices,name='شركة اختبار'){const sessions=rows(prices);return{ticker:'TEST',companyNameAr:name,companyNameEn:'Test Co',dataQualityStatus:'VALID',dataQualityReasons:[],corporateActionConfidence:'HIGH_NO_DETECTED_DISCONTINUITY_SOURCE_NOT_AUTHORITATIVE',coverageStart:sessions[0].date,coverageEnd:sessions.at(-1).date,sessionCount:sessions.length,sessions};}
test('positive historical drawdown is exactly 60 percent',()=>{const x=summarize(rows([10,8,4]),'TEST');assert.equal(x.drawdownFromHighPct,60)});
test('split-adjusted series uses adjusted prices rather than distorted raw close',()=>{const adjusted=Array(220).fill(100),raw=adjusted.map((x,i)=>i<110?100:50),s=rows(adjusted,{raw});const x=summarize(s,'TEST'),q=inspectSessions(s);assert.equal(x.drawdownFromHighPct,0);assert.equal(q.anomalies.length,0);assert.equal(q.detectedCorporateActions[0].status,'ADJUSTED_DISCONTINUITY_RESOLVED')});
test('unresolved adjusted discontinuity is quarantined',()=>{const q=inspectSessions(rows([100,100,40]));assert.equal(q.status,'REVIEW_REQUIRED');assert.ok(q.reasons.some(x=>x.startsWith('CORPORATE_ACTION_REVIEW_REQUIRED')))});
test('missing adjusted price is a data-quality failure',()=>{const s=rows([10,9,8]);s[1].adjustedClose=null;const q=inspectSessions(s);assert.ok(q.reasons.some(x=>x.startsWith('MISSING_ADJUSTED_CLOSE')))});
test('three-year and five-year insufficiency remain horizon-specific',()=>{const h=buildHorizons(rows(Array(700).fill(10)));assert.equal(h.year3.available,false);assert.equal(h.year3.unavailableReason,'INSUFFICIENT_3_YEAR_COVERAGE');assert.equal(h.year5.available,false);assert.equal(h.year5.unavailableReason,'INSUFFICIENT_5_YEAR_COVERAGE')});
test('horizon fallback selects the longest available horizon',()=>{const h=buildHorizons(rows(Array(700).fill(10)));h.maxAvailable.available=false;assert.equal(bestReliableHorizon(h),'week52')});
test('exact post-peak low and exact high have zero cycle distance and drawdown',()=>{const low=summarize(rows([10,5]),'X'),high=summarize(rows([5,10]),'X');assert.equal(low.distanceAbovePostPeakLowPct,0);assert.equal(low.recoveryPositionPct,0);assert.equal(high.currentDrawdownPct,0);assert.equal(high.recoveryPositionPct,100)});
test('post-peak low ignores an older absolute low before the selected high',()=>{const x=summarize(rows([2,10,6,7]),'X');assert.equal(x.absoluteHistoricalLow,2);assert.equal(x.postPeakLow,6);assert.equal(x.distanceAbovePostPeakLowPct,16.6667);assert.equal(x.recoveryPositionPct,25)});
test('deep drawdown without rebound remains no recovery or bottoming',()=>{const p=[...Array(2200).fill(100),...Array(300).fill(40)];const r=analyze(doc(p));assert.ok(['NO_RECOVERY','BOTTOMING'].includes(r.recoveryStage));assert.ok(r.historicalDiscountScore>=60)});
test('deep drawdown plus improving momentum produces early recovery evidence',()=>{const p=[...Array(2200).fill(100),...Array(250).fill(40),...Array.from({length:50},(_,i)=>40+i*.1)];const r=analyze(doc(p));assert.ok(['EARLY_RECOVERY','RECOVERY_CONFIRMED'].includes(r.recoveryStage));assert.ok(r.horizons.maxAvailable.recoveryPositionPct<=40)});
test('strong rebound far from low is classified extended',()=>{const p=[...Array(2200).fill(100),...Array(200).fill(40),...Array.from({length:100},(_,i)=>40+i*.5)];assert.equal(analyze(doc(p)).recoveryStage,'RECOVERY_EXTENDED')});
test('verified Arabic company name is the primary display label',()=>{assert.equal(analyze(doc(Array(2500).fill(10),'الشركة العربية')).displayName,'الشركة العربية')});
test('valid output metrics are finite',()=>{const r=analyze(doc(Array.from({length:2500},(_,i)=>50+i*.01)));for(const x of [r.historicalDiscountScore,r.strengthScore,r.recoveryScore,r.horizons.maxAvailable.high,r.horizons.technical.rsi14])assert.ok(Number.isFinite(x))});
test('recovery opportunity gate requires a meaningful historical discount',()=>{const r=analyze(doc([...Array(2400).fill(100),...Array.from({length:100},(_,i)=>95+i*.04)]));assert.ok(r.horizons.maxAvailable.drawdownFromHighPct<20);assert.equal(isRecoveryOpportunity(r),false)});
test('frozen V16.9 paths are rejected',()=>{assert.equal(checkPaths(['preview-v169/x','scripts/stable/x','data/stable/x','.github/workflows/v169-primary-pages-deploy.yml']).violations.length,4)});
test('generated Arabic UI never renders raw review codes',()=>{const app=fs.readFileSync(path.resolve(__dirname,'../../preview-v17/historical-recovery/app.js'),'utf8');assert.ok(app.includes('historyReasonAr'));assert.ok(!app.includes("historicalDataQuality.reasons.join"))});
