(function(global){
'use strict';

const CONTRACT=Object.freeze({module:'EGX_ONE_CHAMPIONSHIP_BOARD',authorityMode:'RESEARCH',researchOnly:true,productionAuthority:false,scoringImpact:'NONE',recommendationMutationAllowed:false,executionAllowed:false,automaticOrders:false});
const TARGET_STATES=new Set(['TARGET1','TARGET2','TARGET_HIT']);
const STOP_STATES=new Set(['STOP','STOP_HIT']);
const TIMEOUT_STATES=new Set(['TIMEOUT','EXPIRED','TIME_EXIT']);
const GROUPS=Object.freeze([
  Object.freeze({groupId:'EARLY_1_4',label:'#1–4',min:1,max:4}),
  Object.freeze({groupId:'MIDDLE_5_8',label:'#5–8',min:5,max:8}),
  Object.freeze({groupId:'LATE_9_12',label:'#9–12',min:9,max:12})
]);

function num(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function round(v,d=2){const n=num(v);if(n===null)return null;const p=10**d;return Math.round(n*p)/p}
function pct(n,d){return Number(d)>0?round(Number(n)/Number(d)*100,2):null}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(v,suffix=''){const n=num(v);return n===null?'—':`${n.toFixed(2)}${suffix}`}
function signed(v,suffix=''){const n=num(v);return n===null?'—':`${n>0?'+':''}${n.toFixed(2)}${suffix}`}
function outcomeOf(r){return String(r?.outcome?.state??r?.outcomeState??r?.result?.state??r?.result??r?.terminalOutcome??r?.status??r?.resolution?.outcome?.state??r?.resolution?.outcome??'').toUpperCase()}
function signalSessionOf(r){return r?.signalSession||r?.session||r?.plan?.signalSession||r?.recommendation?.signalSession||null}
function netReturnOf(r){for(const v of [r?.netReturnPct,r?.outcome?.netReturnPct,r?.netPct,r?.returnPct,r?.outcomeNetReturnPct,r?.resolution?.netReturnPct,r?.resultMetrics?.netReturnPct]){const n=num(v);if(n!==null)return n}return null}
function groupFor(n){return GROUPS.find(g=>n>=g.min&&n<=g.max)||null}
function emptyBucket(extra={}){return {...extra,sample:0,resolved:0,targetHits:0,stops:0,timeouts:0,other:0,_sessions:new Set(),_returns:[]}}
function touch(b,row,session){b.sample++;if(session)b._sessions.add(session);const state=outcomeOf(row);if(TARGET_STATES.has(state)){b.targetHits++;b.resolved++}else if(STOP_STATES.has(state)){b.stops++;b.resolved++}else if(TIMEOUT_STATES.has(state)){b.timeouts++;b.resolved++}else b.other++;const ret=netReturnOf(row);if(ret!==null)b._returns.push(ret)}
function finishBucket(b,contextSessions,baseline){const returns=b._returns||[],pos=returns.filter(x=>x>0).reduce((a,b)=>a+b,0),neg=Math.abs(returns.filter(x=>x<0).reduce((a,b)=>a+b,0)),hit=b.resolved?pct(b.targetHits,b.resolved):null;return {recommendationNumber:b.recommendationNumber,groupId:b.groupId,label:b.label,min:b.min,max:b.max,sample:b.sample,resolved:b.resolved,targetHits:b.targetHits,stops:b.stops,timeouts:b.timeouts,other:b.other,sessions:b._sessions?.size||0,appearanceRatePct:contextSessions?pct(b._sessions?.size||0,contextSessions):null,targetHitRatePct:hit,stopRatePct:b.resolved?pct(b.stops,b.resolved):null,timeoutRatePct:b.resolved?pct(b.timeouts,b.resolved):null,baselineTargetHitRatePct:baseline,targetHitRateLiftPctPoints:hit===null||baseline===null?null:round(hit-baseline,2),averageNetReturnPct:returns.length?round(returns.reduce((a,b)=>a+b,0)/returns.length,4):null,netReturnProfitFactor:neg>0?round(pos/neg,3):null,netReturnSamples:returns.length}}

function currentRecommendationNumberStats(sim,dates){
  const allowed=new Set((dates||[]).map(String)),positionBySession=new Map(),numbers=new Map(),groups=new Map(GROUPS.map(g=>[g.groupId,emptyBucket(g)])),overall=emptyBucket({scope:'ALL_POSITIONS'});
  for(const r of (Array.isArray(sim?.records)?sim.records:[])){
    const session=String(signalSessionOf(r)||'');if(!allowed.has(session))continue;
    const recommendationNumber=(positionBySession.get(session)||0)+1;positionBySession.set(session,recommendationNumber);
    if(!numbers.has(recommendationNumber))numbers.set(recommendationNumber,emptyBucket({recommendationNumber}));
    touch(numbers.get(recommendationNumber),r,session);touch(overall,r,session);const g=groupFor(recommendationNumber);if(g)touch(groups.get(g.groupId),r,session);
  }
  const contextSessions=allowed.size,baselineRaw=finishBucket(overall,contextSessions,null),baseline=baselineRaw.targetHitRatePct;
  const byNumber=[...numbers.values()].sort((a,b)=>a.recommendationNumber-b.recommendationNumber).map(b=>finishBucket(b,contextSessions,baseline));
  const byGroup=[...groups.values()].map(b=>finishBucket(b,contextSessions,baseline));
  const candidates=byNumber.filter(x=>x.resolved>0);
  const mostTargets=candidates.slice().sort((a,b)=>b.targetHits-a.targetHits||(b.targetHitRatePct??-1)-(a.targetHitRatePct??-1)||b.resolved-a.resolved||a.recommendationNumber-b.recommendationNumber)[0]||null;
  const highestHitRate=candidates.slice().sort((a,b)=>(b.targetHitRatePct??-1)-(a.targetHitRatePct??-1)||b.targetHits-a.targetHits||b.resolved-a.resolved||a.recommendationNumber-b.recommendationNumber)[0]||null;
  const bestGroup=byGroup.filter(x=>x.resolved>0).slice().sort((a,b)=>(b.targetHitRatePct??-1)-(a.targetHitRatePct??-1)||b.targetHits-a.targetHits||b.resolved-a.resolved||a.min-b.min)[0]||null;
  const early=byGroup.find(x=>x.groupId==='EARLY_1_4')||null,late=byGroup.find(x=>x.groupId==='LATE_9_12')||null;
  const lateLift=early&&late&&num(early.targetHitRatePct)!==null&&num(late.targetHitRatePct)!==null?round(late.targetHitRatePct-early.targetHitRatePct,2):null;
  const lockGate=x=>x?{...x,gate:{status:'DISCOVERY_ONLY',candidateForForwardValidation:false,positionAdjustmentEligible:false,reasons:['PERSISTED_GATE_EVIDENCE_REQUIRED'],rule:'NO_RANKING_ADJUSTMENT_WITHOUT_SEPARATE_FORWARD_VALIDATION'}}:null;
  return {numbering:'ONE_BASED_SESSION_ORDER',selectionRule:'MOST_TARGET_HITS_THEN_HIT_RATE_THEN_RESOLVED_THEN_LOWER_NUMBER',contextSessions,baseline:{...baselineRaw,baselineTargetHitRatePct:baseline,targetHitRateLiftPctPoints:0},byNumber,byGroup,mostTargets,highestHitRate,bestGroupByHitRate:bestGroup,positionEdge:{bestNumber:lockGate(highestHitRate),bestGroup:lockGate(bestGroup),lateVsEarlyTargetHitRateLiftPctPoints:lateLift,laterPositionSelectionBias:'LATER_POSITIONS_EXIST_ONLY_IN_SESSIONS_WITH_ENOUGH_RECOMMENDATIONS; appearanceRatePct must be reviewed before inference.',rankingAdjustment:{eligible:false,status:'LOCKED_PENDING_FORWARD_VALIDATION'}},evidenceGrade:'POINT_IN_TIME_HISTORICAL_REPLAY',definition:'Rank after the frozen daily candidate sort, before outcomes are known.'};
}

function currentOnCommonDates(sim){
  const lc=sim?.legacyComparison||{},dates=Array.isArray(lc.commonDates)?lc.commonDates.filter(Boolean):[],allowed=new Set(dates),records=Array.isArray(sim?.records)?sim.records:[];let targets=0,stops=0,timeouts=0;const returns=[];
  for(const r of records){if(!allowed.has(signalSessionOf(r)))continue;const o=outcomeOf(r);if(TARGET_STATES.has(o))targets++;else if(STOP_STATES.has(o))stops++;else if(TIMEOUT_STATES.has(o))timeouts++;else continue;const nr=netReturnOf(r);if(nr!==null)returns.push(nr)}
  const resolved=targets+stops,triggered=resolved+timeouts,pos=returns.filter(v=>v>0).reduce((a,b)=>a+b,0),neg=Math.abs(returns.filter(v=>v<0).reduce((a,b)=>a+b,0)),persisted=lc?.newTechnique?.onV16ExactSignalDates?.recommendationNumberStats||null;
  return {engine:'EGX_ONE',evidenceGrade:lc?.newTechnique?.evidenceGrade||'POINT_IN_TIME_HISTORICAL_REPLAY',commonSignalDates:dates.length,commonDates:dates,resolvedMembers:resolved,triggeredMembers:triggered,targetHits:targets,stopHits:stops,timeouts,targetHitRatePct:pct(targets,resolved),stopRatePct:pct(stops,resolved),averageNetReturnPct:returns.length?round(returns.reduce((a,b)=>a+b,0)/returns.length,4):null,netReturnProfitFactor:neg>0?round(pos/neg,3):null,netReturnSamples:returns.length,recommendationNumberStats:persisted||currentRecommendationNumberStats(sim,dates)};
}

function buildComparison(sim,forward){
  const lc=sim?.legacyComparison||{},rules=lc?.comparisonRules||{},current=currentOnCommonDates(sim||{}),legacy=lc?.v16_9||null;
  const v16=legacy?{engine:'V16.9 EGX PRO',evidenceGrade:legacy.evidenceGrade||'UNKNOWN',commonSignalDates:num(legacy.commonSignalDates)??num(legacy.signalSessions),resolvedMembers:num(legacy.resolvedMembers),targetHits:num(legacy.targetHits),stopHits:num(legacy.stopHits),targetHitRatePct:num(legacy.targetHitRatePct),stopRatePct:num(legacy.stopRatePct),averageNetReturnPct:num(legacy.averageNetReturnPct),netReturnProfitFactor:num(legacy.netReturnProfitFactor),estimatedRoundTripCostPct:num(legacy.estimatedRoundTripCostPct),recommendationNumberStats:legacy.recommendationNumberStats||null}:null;
  const currentCost=num(rules.newTechniqueRoundTripCostPct),sameDateScope=!!(v16&&current.commonSignalDates>0&&v16.commonSignalDates===current.commonSignalDates),exactLegacy=!!(v16&&v16.evidenceGrade==='EXACT_LOGGED_LEDGER'),policyAllows=String(rules.v16Comparison||'').includes('DATE_ALIGNED_POLICY_COMPARISON'),outcomeComparable=sameDateScope&&exactLegacy&&policyAllows&&current.targetHitRatePct!==null&&v16.targetHitRatePct!==null;
  let currentScore=0,v16Score=0,outcomeWinner='N/A';if(outcomeComparable){if(current.targetHitRatePct>v16.targetHitRatePct){currentScore++;outcomeWinner='EGX ONE'}else if(current.targetHitRatePct<v16.targetHitRatePct){v16Score++;outcomeWinner='V16.9 EGX PRO'}else outcomeWinner='TIE'}
  const costComparable=!!(v16&&currentCost!==null&&v16.estimatedRoundTripCostPct!==null&&Math.abs(currentCost-v16.estimatedRoundTripCostPct)<1e-9),leader=currentScore>v16Score?'EGX ONE':v16Score>currentScore?'V16.9 EGX PRO':(currentScore+v16Score>0?'TIE':'N/A'),forwardRes=Array.isArray(forward?.resolutions)?forward.resolutions:[],forwardStatus=forwardRes.length?'FORWARD_SHADOW_REALIZED':'FORWARD_SHADOW_PENDING';
  return {contract:CONTRACT,scope:'DATE_ALIGNED_POLICY_COMPARISON',sameDateScope,policyAllows,exactLegacy,currentCostPct:currentCost,v16CostPct:v16?.estimatedRoundTripCostPct??null,costComparable,current,v16,recommendationNumberDefinition:rules.recommendationNumberDefinition||'ONE_BASED_SESSION_ORDER_PRE_OUTCOME',positionEdgePolicy:rules.positionEdgePolicy||'INFO_ONLY_NO_RANKING_MUTATION_PENDING_FORWARD_VALIDATION',score:{current:currentScore,v16:v16Score,leader,qualifiedMetrics:outcomeComparable?1:0},metrics:[{id:'target',label:'Target Hit %',current:current.targetHitRatePct,v16:v16?.targetHitRatePct??null,unit:'%',qualified:outcomeComparable,winner:outcomeWinner,rule:'HIGHER_BETTER'},{id:'failure',label:'Failure / Stop %',current:current.stopRatePct,v16:v16?.stopRatePct??null,unit:'%',qualified:false,winner:'INFO_ONLY',rule:'LOWER_BETTER_SAME_OUTCOME_FAMILY'},{id:'avgNet',label:'Avg Net Return %',current:current.averageNetReturnPct,v16:v16?.averageNetReturnPct??null,unit:'%',qualified:false,winner:'N/A',rule:costComparable?'INFO_ONLY':'N/A_COST_MISMATCH'},{id:'pf',label:'Net Return Profit Factor',current:current.netReturnProfitFactor,v16:v16?.netReturnProfitFactor??null,unit:'',qualified:false,winner:'N/A',rule:costComparable?'INFO_ONLY':'N/A_COST_MISMATCH'}],forwardStatus,forwardResolutions:forwardRes.length,caveat:rules.v16Comparison||'DATE_ALIGNED_POLICY_COMPARISON; execution horizons and costs may differ'};
}

function bestHTML(stats){const x=stats?.mostTargets;if(!x)return '<div class="egx-best-rec">MOST TARGETS: N/A</div>';return `<div class="egx-best-rec">MOST TARGETS · <b>#${x.recommendationNumber}</b> · ${x.targetHits}/${x.resolved} · ${fmt(x.targetHitRatePct,'%')}</div>`}
function recRows(c){const a=c.current?.recommendationNumberStats?.byNumber||[],b=c.v16?.recommendationNumberStats?.byNumber||[],am=new Map(a.map(x=>[Number(x.recommendationNumber),x])),bm=new Map(b.map(x=>[Number(x.recommendationNumber),x])),ns=[...new Set([...am.keys(),...bm.keys()])].filter(Number.isFinite).sort((x,y)=>x-y);if(!ns.length)return '<tr><td colspan="7">Evidence pending</td></tr>';return ns.map(n=>{const x=am.get(n),y=bm.get(n);return `<tr><td><b>#${n}</b></td><td>${x?.resolved??'—'}</td><td>${x?.targetHits??'—'}</td><td>${fmt(x?.targetHitRatePct,'%')}</td><td>${y?.resolved??'—'}</td><td>${y?.targetHits??'—'}</td><td>${fmt(y?.targetHitRatePct,'%')}</td></tr>`}).join('')}
function groupRows(stats){const rows=stats?.byGroup||[];if(!rows.length)return '<tr><td colspan="6">Evidence pending</td></tr>';return rows.map(g=>`<tr><td><b>${esc(g.label)}</b></td><td>${g.resolved??'—'}</td><td>${g.targetHits??'—'}</td><td>${fmt(g.targetHitRatePct,'%')}</td><td>${signed(g.targetHitRateLiftPctPoints,'pp')}</td><td>${fmt(g.appearanceRatePct,'%')}</td></tr>`).join('')}
function positionEdgeHTML(stats,engine){const edge=stats?.positionEdge||{},best=edge.bestNumber||stats?.highestHitRate||null,gate=best?.gate||{},eligible=edge?.rankingAdjustment?.eligible===true;return `<div class="egx-edge"><div class="egx-edge-head"><b>${esc(engine)}</b><span>${esc(gate.status||'DISCOVERY_ONLY')}</span></div><div class="egx-edge-best">Best observed position <strong>${best?.recommendationNumber?`#${best.recommendationNumber}`:'—'}</strong> · <b>${fmt(best?.targetHitRatePct,'%')}</b> · ${best?.targetHits??'—'}/${best?.resolved??'—'}</div><div class="egx-edge-meta"><span>Lift <b>${signed(best?.targetHitRateLiftPctPoints,'pp')}</b></span><span>Sessions <b>${best?.sessions??'—'}</b></span><span>Appearance <b>${fmt(best?.appearanceRatePct,'%')}</b></span><span>Baseline <b>${fmt(stats?.baseline?.targetHitRatePct,'%')}</b></span><span>Avg return <b>${fmt(best?.averageNetReturnPct,'%')}</b></span><span>PF <b>${fmt(best?.netReturnProfitFactor)}</b></span></div><table><thead><tr><th>Group</th><th>Resolved</th><th>Targets</th><th>Hit %</th><th>Lift</th><th>Appearance</th></tr></thead><tbody>${groupRows(stats)}</tbody></table><div class="egx-edge-lock">Late #9–12 vs early #1–4: <b>${signed(edge?.lateVsEarlyTargetHitRateLiftPctPoints,'pp')}</b><br>${esc(edge?.laterPositionSelectionBias||'Later positions appear only in sessions with enough recommendations.')}<br><b>Ranking adjustment: ${eligible?'ELIGIBLE':'LOCKED'}</b> · separate forward validation required.</div></div>`}
function styles(){if(typeof document==='undefined'||document.getElementById('egxChampionshipStyles'))return;const s=document.createElement('style');s.id='egxChampionshipStyles';s.textContent=`.egx-champ{direction:rtl;background:#0d1626;color:#eef4ff;border:1px solid #263852;border-radius:18px;padding:16px}.egx-head{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.egx-title{font-size:24px;font-weight:900}.egx-leader{background:#17263d;border:1px solid #34527b;border-radius:999px;padding:8px 12px}.egx-score{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.egx-fighter,.egx-edge{background:#0a1220;border:1px solid #2d405d;border-radius:14px;padding:12px;text-align:center}.egx-pts{font-size:34px;font-weight:950}.egx-best-rec{margin-top:8px;font-size:12px;color:#b9cae1}.egx-best-rec b,.egx-edge-best strong{color:#f5c96a}.egx-section{margin:16px 0 7px;font-weight:900}.egx-table{overflow:auto;border:1px solid #27354b;border-radius:12px}.egx-champ table{border-collapse:collapse;width:100%;min-width:640px}.egx-champ th,.egx-champ td{padding:9px;border-bottom:1px solid #223047;text-align:center;font-size:12px}.egx-champ th{background:#121e31}.egx-edge-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.egx-edge-head{display:flex;justify-content:space-between}.egx-edge-head span{font-size:10px;color:#f0d58a}.egx-edge-best{margin:10px 0}.egx-edge-best strong{font-size:28px}.egx-edge-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:8px 0}.egx-edge-meta span{background:#101d30;padding:6px;border-radius:8px;font-size:10px}.egx-edge table{min-width:0}.egx-edge-lock,.egx-warn{margin-top:9px;background:#211b10;border:1px solid #5a4a27;color:#e9cf8b;border-radius:9px;padding:8px;font-size:11px;line-height:1.55}.egx-pills{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.egx-pill{border:1px solid #30435f;border-radius:999px;padding:5px 8px;font-size:10px;color:#b9cae1}@media(max-width:760px){.egx-edge-grid,.egx-score{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function renderHTML(c){const v=c.v16,metrics=c.metrics.map(m=>`<tr><td>${esc(m.label)}</td><td>${fmt(m.current,m.unit)}</td><td>${fmt(m.v16,m.unit)}</td><td>${m.qualified?'POINT':'INFO'}</td></tr>`).join('');return `<div class="egx-champ"><div class="egx-head"><div><div class="egx-title">EGX ONE 🆚 V16.9 EGX PRO</div><small>Evidence-first · same-date scope</small></div><div class="egx-leader">LEADER: <b>${esc(c.score.leader)}</b></div></div><div class="egx-score"><div class="egx-fighter"><b>EGX ONE</b><div class="egx-pts">${c.score.current}</div>${bestHTML(c.current.recommendationNumberStats)}</div><div class="egx-fighter"><b>V16.9 EGX PRO</b><div class="egx-pts">${c.score.v16}</div>${bestHTML(v?.recommendationNumberStats)}</div></div><div class="egx-table"><table><thead><tr><th>Metric</th><th>EGX ONE</th><th>V16.9</th><th>Status</th></tr></thead><tbody>${metrics}</tbody></table></div><div class="egx-section">Recommendation # Performance</div><div class="egx-table"><table><thead><tr><th>#</th><th>EGX Resolved</th><th>EGX Targets</th><th>EGX Hit %</th><th>V16 Resolved</th><th>V16 Targets</th><th>V16 Hit %</th></tr></thead><tbody>${recRows(c)}</tbody></table></div><div class="egx-section">POSITION EDGE · INFO ONLY</div><div class="egx-edge-grid">${positionEdgeHTML(c.current.recommendationNumberStats,'EGX ONE')}${positionEdgeHTML(v?.recommendationNumberStats,'V16.9 EGX PRO')}</div><div class="egx-pills"><span class="egx-pill">Policy: ${esc(c.positionEdgePolicy)}</span><span class="egx-pill">Common dates: ${c.current.commonSignalDates}</span><span class="egx-pill">Forward: ${esc(c.forwardStatus)} (${c.forwardResolutions})</span></div><div class="egx-warn">POSITION EDGE is discovery evidence only. التوصيات المتأخرة لا تظهر إلا في الجلسات التي أنتجت عددًا كافيًا من التوصيات، لذلك حجم العينة وAppearance Rate أساسيان. لا يوجد Position Bonus أو إعادة ترتيب قبل Forward Validation مستقل.</div><div class="egx-warn">RESEARCH ONLY · PRODUCTION AUTHORITY: OFF · RECOMMENDATION MUTATION: DISABLED · POSITION ADJUSTMENT: LOCKED · AUTOMATIC ORDERS: DISABLED</div></div>`}
function render(container,c){if(typeof document==='undefined')return false;const el=typeof container==='string'?document.querySelector(container):container;if(!el)return false;styles();el.innerHTML=renderHTML(c);return true}
function mount(root,c){if(!root)return false;let host=document.getElementById('championshipBoardHost');if(!host||host.parentElement!==root){host=document.createElement('div');host.id='championshipBoardHost';host.className='section';root.prepend(host)}return render(host,c)}
async function fetchJSON(url){const r=await fetch(`${url}${url.includes('?')?'&':'?'}cb=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP_${r.status}:${url}`);return r.json()}
async function init(){if(typeof document==='undefined')return null;try{const [sim,forward]=await Promise.all([fetchJSON('/data/research/simulator/latest.json'),fetchJSON('/data/research/shadow-ledger/latest.json').catch(()=>null)]),c=buildComparison(sim,forward),root=document.getElementById('compareArea')||document.querySelector('#compare .grid')||document.getElementById('compare');mount(root,c);if(root&&!root.__egxChampionshipObserver&&typeof MutationObserver!=='undefined'){const observer=new MutationObserver(()=>{if(!document.getElementById('championshipBoardHost'))mount(root,c)});observer.observe(root,{childList:true});root.__egxChampionshipObserver=observer}return c}catch(err){console.error('CHAMPIONSHIP_BOARD_BLOCKED',err);return null}}
const API={CONTRACT,outcomeOf,signalSessionOf,netReturnOf,currentRecommendationNumberStats,currentOnCommonDates,buildComparison,positionEdgeHTML,renderHTML,render,mount,init};global.EGXOneChampionshipBoard=API;if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init(),{once:true});else init()}
})(typeof window!=='undefined'?window:globalThis);
