'use strict';
(()=>{
  const $=id=>document.getElementById(id),state={data:null};
  const esc=v=>String(v??'غير متاح').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>Number.isFinite(Number(v))?Number(v).toLocaleString('ar-EG',{maximumFractionDigits:2}):'غير متاح';
  const pct=v=>Number.isFinite(Number(v))?`${fmt(v)}٪`:'غير متاح';
  const location=p=>p<=10?'عند قاع دورة الهبوط':p<=25?'بالقرب من قاع دورة الهبوط':p<=40?'داخل منطقة قاع دورة الهبوط':'تعافى بعيدًا عن قاع الدورة';
  const reasonAr=r=>{const c=String(r||'');if(c.startsWith('CORPORATE_ACTION_REVIEW_REQUIRED'))return'مراجعة إجراء رأسمالي مطلوبة بسبب انقطاع مشتبه به في السعر المعدل';if(c.startsWith('MISSING_ADJUSTED_CLOSE'))return'بيانات السعر المعدل غير مكتملة';if(c==='INSUFFICIENT_52_WEEK_COVERAGE')return'التغطية لا تكفي لأفق 52 أسبوعًا';if(c==='SOURCE_RETRIEVAL_FAILED')return'تعذر استرجاع التاريخ من المصدر';return'تحتاج البيانات إلى مراجعة فنية قبل المقارنة';};
  const confidenceAr=v=>String(v||'').startsWith('HIGH')?'مرتفعة':String(v||'').startsWith('MEDIUM')?'متوسطة':'تحتاج مراجعة';
  const selected=()=>$('horizon').value,h=r=>r.horizons?.[selected()],query=()=>$('filter').value.trim().toLowerCase();
  const visible=r=>!query()||`${r.displayName||r.companyNameAr||''} ${r.ticker} ${r.companyNameEn||''}`.toLowerCase().includes(query());
  const why=(r,x)=>`السهم أقل من القمة المعدلة بنسبة ${pct(x.currentDrawdownPct)}، واستعاد ${pct(x.recoveryPositionPct)} من المسافة بين قاع ما بعد القمة والقمة السابقة. ${r.recoveryStageAr}.`;
  const identity=r=>`<td>${esc(r.displayName||r.companyNameAr||r.companyNameEn||r.ticker)}</td><td dir="ltr">${esc(r.ticker)}</td>`;
  function render(){
    const d=state.data,all=d.results.filter(visible),valid=all.filter(r=>r.dataQualityStatus==='VALID'&&h(r)?.available),review=all.filter(r=>r.dataQualityStatus!=='VALID');
    const deep=valid.slice().sort((a,b)=>h(b).currentDrawdownPct-h(a).currentDrawdownPct),bottom=valid.slice().sort((a,b)=>h(a).recoveryPositionPct-h(b).recoveryPositionPct);
    const deepNear=valid.filter(r=>h(r).currentDrawdownPct>=35&&h(r).recoveryPositionPct<=30).sort((a,b)=>h(b).currentDrawdownPct-h(a).currentDrawdownPct||h(a).recoveryPositionPct-h(b).recoveryPositionPct);
    const recovery=valid.filter(r=>h(r).currentDrawdownPct>=20&&h(r).recoveryPositionPct<=40&&['BOTTOMING','EARLY_RECOVERY','RECOVERY_CONFIRMED'].includes(r.recoveryStage)).sort((a,b)=>b.recoveryScore-a.recoveryScore);
    const research=valid.filter(r=>r.researchRecommendations?.[selected()]).sort((a,b)=>{const ar=a.researchRecommendations[selected()],br=b.researchRecommendations[selected()];return ar.priority-br.priority||b.recoveryScore-a.recoveryScore||b.strengthScore-a.strengthScore||b.dataConfidence-a.dataConfidence});
    $('scanned').textContent=fmt(d.summary.canonicalOrdinaryEquities);$('valid').textContent=fmt(valid.length);$('review').textContent=fmt(d.summary.dataReviewRequired);$('gte35').textContent=fmt(valid.filter(r=>h(r).currentDrawdownPct>=35).length);$('gte50').textContent=fmt(valid.filter(r=>h(r).currentDrawdownPct>=50).length);$('gte65').textContent=fmt(valid.filter(r=>h(r).currentDrawdownPct>=65).length);$('nearBottom').textContent=fmt(valid.filter(r=>h(r).recoveryPositionPct<=25).length);$('early').textContent=fmt(recovery.filter(r=>r.recoveryStage==='EARLY_RECOVERY').length);$('confirmed').textContent=fmt(recovery.filter(r=>r.recoveryStage==='RECOVERY_CONFIRMED').length);
    $('drawdownRows').innerHTML=deep.map(r=>{const x=h(r);return `<tr>${identity(r)}<td>${fmt(x.high)}</td><td>${esc(x.highDate)}</td><td>${fmt(x.current)}</td><td>${pct(x.currentDrawdownPct)}</td><td>${fmt(x.postPeakLow)}</td><td>${esc(x.postPeakLowDate)}</td><td>${pct(x.recoveryPositionPct)}</td><td>${pct(r.dataConfidence)}</td></tr>`}).join('');
    $('researchRows').innerHTML=research.map(r=>{const x=h(r),rec=r.researchRecommendations[selected()];return `<tr>${identity(r)}<td><strong>${esc(rec.labelAr)}</strong></td><td>${esc(rec.riskLabelAr)}</td><td class="reasons">${esc(rec.reasonsAr.join(' '))}</td><td>${esc(r.recoveryStageAr)}</td><td>${pct(x.currentDrawdownPct)}</td><td>${pct(x.recoveryPositionPct)}</td><td>${fmt(r.strengthScore)}</td><td>${fmt(r.recoveryScore)}</td><td>${pct(r.dataConfidence)}</td></tr>`}).join('');
    $('bottomRows').innerHTML=bottom.map(r=>{const x=h(r);return `<tr>${identity(r)}<td>${fmt(x.postPeakLow)}</td><td>${esc(x.postPeakLowDate)}</td><td>${fmt(x.current)}</td><td>${pct(x.distanceAbovePostPeakLowPct)}</td><td>${pct(x.recoveryPositionPct)}</td><td>${pct(x.currentDrawdownPct)}</td><td>${location(x.recoveryPositionPct)}</td><td>${esc(r.recoveryStageAr)}</td><td class="reasons">${esc(why(r,x))}</td></tr>`}).join('');
    $('deepNearRows').innerHTML=deepNear.map(r=>{const x=h(r);return `<tr>${identity(r)}<td>${fmt(x.high)}</td><td>${fmt(x.postPeakLow)}</td><td>${fmt(x.current)}</td><td>${pct(x.currentDrawdownPct)}</td><td>${pct(x.recoveryPositionPct)}</td><td>${pct(x.distanceAbovePostPeakLowPct)}</td><td>${esc(r.recoveryStageAr)}</td><td class="reasons">${esc(why(r,x))}</td></tr>`}).join('');
    $('recoveryRows').innerHTML=recovery.map(r=>{const x=h(r),t=r.horizons.technical;return `<tr>${identity(r)}<td>${pct(x.currentDrawdownPct)}</td><td>${pct(x.recoveryPositionPct)}</td><td>${fmt(t.rsi14)}</td><td>${fmt(r.historicalDiscountScore)}</td><td>${fmt(r.strengthScore)}</td><td>${fmt(r.recoveryScore)}</td><td>${esc(r.recoveryStageAr)}</td><td class="reasons">${esc(why(r,x))}</td></tr>`}).join('');
    $('reviewRows').innerHTML=review.map(r=>`<tr class="review-row">${identity(r)}<td>${fmt(r.sessionCount)}</td><td>${esc(r.coverageStart)}</td><td>${esc(r.coverageEnd)}</td><td>${esc(confidenceAr(r.corporateActionConfidence))}</td><td class="reasons">${esc((r.dataQualityReasons||[]).map(reasonAr).join(' · '))}</td></tr>`).join('');
  }
  async function load(){try{const res=await fetch(`../../data/v17/historical-recovery/long-history/compact-market.json?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);state.data=await res.json();$('status').textContent=`آخر تحديث: ${new Date(state.data.generatedAt).toLocaleString('ar-EG')}`;render()}catch(e){$('status').textContent=`تعذر تحميل المحرك طويل الأفق: ${e.message}`}}
  $('horizon').addEventListener('change',render);$('filter').addEventListener('input',render);load();
})();
