(function(root,factory){const api=factory(root.GFXMath||(typeof require==='function'?require('./math.js'):null),root.GFXFusion||(typeof require==='function'?require('./fusion.js'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.GFXFusionV3=api;})(typeof self!=='undefined'?self:this,function(M,V1){'use strict';
const WEIGHTS={sepaSelection:30,v16Execution:30,breakoutVolume:15,riskReward:10,gannTime:10,gannPrice:5};
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0));const round=(n,d=2)=>{const p=10**d;return Math.round((Number(n)||0)*p)/p};
function rrScore(rr){rr=Number(rr)||0;return rr>=2.5?100:rr>=2?92:rr>=1.6?82:rr>=1.3?72:rr>=1.15?62:35}
function entryScore(p){return p.breakout?.confirmed?90:p.breakout?.near?78:Math.max(25,Number(p.breakout?.score)||0)}
function sepaSelection(p){const e=entryScore(p),rr=rrScore(p.riskReward?.rr),s=(p.trend?.score||0)*.20+(p.relativeStrength?.score||0)*.15+(p.momentum?.score||0)*.10+(p.volume?.score||0)*.15+e*.15+rr*.15+(p.fundamentals?.score||50)*.10;return{score:round(clamp(s),1),entryScore:e}}
function v16Execution(p){let s=(p.trend?.score||0)*.20+(p.relativeStrength?.score||0)*.10+(p.breakout?.score||0)*.20+(p.volume?.score||0)*.20+(p.momentum?.score||0)*.10+rrScore(p.riskReward?.rr)*.20;if(Number(p.riskReward?.rr||0)<1.15)s-=12;if(p.momentum?.overheated)s-=18;if(Number(p.volume?.ratio20||0)<.8)s-=8;if(p.marketRegime?.regime==='RISK_OFF')s-=10;return{score:round(clamp(s),1)}}
function breakoutVolume(p){return{score:round(clamp((p.breakout?.score||0)*.60+(p.volume?.score||0)*.40),1)}}
function isSepaCandidate(p){const e=entryScore(p),rr=Number(p.riskReward?.rr||0),avoid=(p.trend?.score||0)<60||(p.relativeStrength?.score||0)<20||Boolean(p.momentum?.overheated),actionable=!avoid&&e>=75&&(p.trend?.score||0)>=85&&(p.relativeStrength?.score||0)>=70&&rr>=2&&((p.riskReward.entryHigh-p.riskReward.stopLoss)/Math.max(.0001,p.riskReward.entryHigh)*100)<=8,recommendation=!avoid&&(actionable||p.breakout?.near||p.breakout?.confirmed||sepaSelection(p).score>=72);return{eligible:recommendation,actionable,avoid}}
function analyze(x){const base=V1.analyze(x);if(!base.valid)return base;const p=base.parts,neutralPlan=V1.risk(x.bars,{nextAbove:0},p.breakout),partsForSelection={...p,riskReward:neutralPlan};const sepa=sepaSelection(partsForSelection),v16=v16Execution(partsForSelection),bv=breakoutVolume(partsForSelection),rr={score:rrScore(neutralPlan.rr),rr:neutralPlan.rr},gt={score:clamp(p.gannTime?.score||0),active:Boolean(p.gannTime?.active)},gp={score:clamp(p.gannPrice?.score||0)},score=round(sepa.score*.30+v16.score*.30+bv.score*.15+rr.score*.10+gt.score*.10+gp.score*.05,1),gate=isSepaCandidate(partsForSelection);let classification={code:'WATCH',ar:'مراقبة فقط',tone:'neutral'};if(!x.dataQuality?.fresh)classification={code:'WAIT_DATA',ar:'انتظار تحديث البيانات',tone:'neutral'};else if(x.dataQuality?.conflict)classification={code:'DATA_BLOCKED',ar:'محجوب بسبب تعارض البيانات',tone:'danger'};else if(gate.eligible&&score>=78&&gate.actionable&&p.gannTime?.active)classification={code:'HIGH_CONVICTION',ar:'مرشح قوي — SEPA مؤهل وV16/Gann يدعمان التوقيت',tone:'positive'};else if(gate.eligible&&score>=68)classification={code:'ACTIONABLE',ar:'مرشح للجلسة القادمة — التنفيذ مشروط بالتفعيل والسيولة',tone:'positive'};return{...base,version:'GANN_FUSION_X_V3_ENSEMBLE_GATE',score,classification,plan:neutralPlan,components:{sepaSelection:sepa,v16Execution:v16,breakoutVolume:bv,riskReward:rr,gannTime:gt,gannPrice:gp},sepaGate:gate,explanation:{positives:[gate.eligible?'السهم اجتاز بوابة SEPA للاختيار.':'السهم لم يجتز بوابة SEPA.',v16.score>=70?'قابلية التنفيذ الفنية قوية.':'قابلية التنفيذ تحتاج مزيدًا من التأكيد.',p.gannTime?.active?'Gann يدعم التوقيت ولا يغيّر الخطة السعرية.':'Gann غير نشط؛ لا يُستخدم كمانع للصفقة.'],cautions:[p.momentum?.overheated?'الزخم ساخن.':null,Number(p.volume?.ratio20||0)<.8?'السيولة دون الحد المفضل.':null].filter(Boolean),action:'V3 لا يغيّر وقف/أهداف المرشح بسبب Gann؛ يستخدم Gann وV16 فقط لترتيب وتوقيت الأسهم التي اجتازت بوابة SEPA.'}}}
function rank(xs){const all=(xs||[]).map(analyze).filter(x=>x.valid).sort((a,b)=>b.score-a.score);return{all,dailyTop:all.filter(x=>['HIGH_CONVICTION','ACTIONABLE'].includes(x.classification.code)).slice(0,5)}}
return{WEIGHTS,rrScore,entryScore,sepaSelection,v16Execution,breakoutVolume,isSepaCandidate,analyze,rank};});
