(function(root,factory){const api=factory(root.GFXMath||(typeof require==='function'?require('./math.js'):null),root.GFXFusion||(typeof require==='function'?require('./fusion.js'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.GFXFusionV2=api;})(typeof self!=='undefined'?self:this,function(M,V1){'use strict';
const WEIGHTS={sepaSelection:30,v16Execution:30,breakoutVolume:15,riskReward:10,gannTime:10,gannPrice:5};
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0));
const round=(n,d=2)=>{const p=10**d;return Math.round((Number(n)||0)*p)/p};
function rrScore(rr){rr=Number(rr)||0;return rr>=2.5?100:rr>=2?92:rr>=1.6?82:rr>=1.3?72:rr>=1.15?62:35}
function breakoutEntryScore(p){if(p.breakout?.confirmed)return 92;if(p.breakout?.near)return 80;return Math.max(25,Number(p.breakout?.score)||0)}
function sepaSelection(p){const entry=breakoutEntryScore(p),rr=rrScore(p.riskReward?.rr);const score=clamp((p.trend?.score||0)*.20+(p.relativeStrength?.score||0)*.15+(p.momentum?.score||0)*.10+(p.volume?.score||0)*.15+entry*.15+rr*.15+(p.fundamentals?.score||50)*.10);return{score:round(score,1),entryScore:round(entry,1),labelAr:score>=75?'اختيار SEPA قوي':score>=65?'اختيار SEPA مقبول':'اختيار SEPA ضعيف'}}
function v16Execution(p){let score=(p.trend?.score||0)*.20+(p.relativeStrength?.score||0)*.10+(p.breakout?.score||0)*.20+(p.volume?.score||0)*.20+(p.momentum?.score||0)*.10+rrScore(p.riskReward?.rr)*.20;const penalties=[];if(Number(p.riskReward?.rr||0)<1.15){score-=20;penalties.push('R/R أقل من 1.15');}if(p.momentum?.overheated){score-=22;penalties.push('زخم ساخن');}if(Number(p.volume?.ratio20||0)<.8){score-=10;penalties.push('سيولة ضعيفة');}if(p.marketRegime?.regime==='RISK_OFF'){score-=12;penalties.push('السوق دفاعي');}score=clamp(score);return{score:round(score,1),penalties,labelAr:score>=75?'قابلية تنفيذ قوية':score>=65?'قابلية تنفيذ مقبولة':'قابلية تنفيذ ضعيفة'}}
function breakoutVolume(p){const s=clamp((p.breakout?.score||0)*.60+(p.volume?.score||0)*.40);return{score:round(s,1),labelAr:p.breakout?.confirmed&&p.volume?.confirmed?'اختراق وسيولة مؤكّدان':p.breakout?.near?'قرب اختراق يحتاج تأكيد سيولة':'لا يوجد تأكيد كافٍ'}}
function weighted(c){return round(c.sepaSelection.score*.30+c.v16Execution.score*.30+c.breakoutVolume.score*.15+c.riskReward.score*.10+c.gannTime.score*.10+c.gannPrice.score*.05,1)}
function speculativePlan(base,x){const bars=M.bars(x.bars),cur=M.last(bars),p=base.parts,atr=Math.max(Number(base.plan?.atr14)||M.atr(bars,14)||cur.close*.02,.01),trigger=Number(p.breakout?.trigger||base.plan?.trigger||cur.close);const confirmed=Boolean(p.breakout?.confirmed);let ref=confirmed?cur.close:Math.max(cur.close,trigger);let entryLow=confirmed?ref*.995:trigger*.995,entryHigh=confirmed?ref*1.003:trigger*1.006;const recent=bars.slice(-5),recentLow=recent.length?Math.min(...recent.map(b=>b.low)):ref*.97,atrStop=ref-Math.max(atr,ref*.02);let stop=Math.max(recentLow*.998,atrStop);stop=Math.min(stop,ref*.99);stop=Math.max(stop,ref*.935,.01);const r=Math.max(ref-stop,ref*.01),t1=ref+r*1.15,t2=ref+r*1.8,t3=ref+r*2.5;return{entryLow:round(entryLow,4),entryHigh:round(entryHigh,4),referenceEntry:round(ref,4),trigger:round(trigger,4),stopLoss:round(stop,4),target1:round(t1,4),target2:round(t2,4),target3:round(t3,4),riskPct:round((ref-stop)/ref*100,2),rr1:1.15,rr2:1.8,rr3:2.5,atr14:round(atr,4)}}
function classify(base,c,plan,q){if(!q?.fresh)return{code:'WAIT_DATA',ar:'انتظار تحديث البيانات',tone:'neutral'};if(q?.conflict)return{code:'DATA_BLOCKED',ar:'محجوب بسبب تعارض البيانات',tone:'danger'};const p=base.parts,hasTrigger=Boolean(p.breakout?.confirmed||p.breakout?.near),liq=Number(p.volume?.ratio20||0);if(p.momentum?.overheated)return{code:'COOL_OFF',ar:'تجنب المطاردة — الزخم ساخن',tone:'warn'};if(plan.riskPct>6.5)return{code:'WATCH',ar:'الوقف واسع لمضاربة 1–3 جلسات',tone:'warn'};if(Number(p.riskReward?.rr||0)<1.15)return{code:'WATCH',ar:'العائد/المخاطرة دون الحد الأدنى',tone:'warn'};if(p.marketRegime?.regime==='RISK_OFF'&&c.score<86)return{code:'WATCH',ar:'السوق دفاعي — لا دخول جديد',tone:'warn'};if(!hasTrigger)return{code:'WATCH',ar:'انتظار محفز اختراق واضح',tone:'neutral'};if(liq<.8)return{code:'WATCH',ar:'السيولة غير كافية للتفعيل',tone:'warn'};if(c.score>=80&&c.sepaSelection.score>=72&&c.v16Execution.score>=72&&p.breakout?.confirmed&&p.volume?.confirmed&&p.gannTime?.active)return{code:'HIGH_CONVICTION',ar:'دخول مشروط عالي الثقة',tone:'positive'};if(c.score>=72&&c.sepaSelection.score>=65&&c.v16Execution.score>=65)return{code:'ACTIONABLE',ar:'دخول مشروط بعد تفعيل السعر والسيولة',tone:'positive'};if(c.score>=68&&c.sepaSelection.score>=62&&c.v16Execution.score>=60)return{code:'CONDITIONAL',ar:'مرشح للجلسة القادمة بشرط التأكيد',tone:'positive'};return{code:'WATCH',ar:'مراقبة فقط',tone:'neutral'}}
function analyze(x){const base=V1.analyze(x);if(!base.valid)return base;const p=base.parts,components={sepaSelection:sepaSelection(p),v16Execution:v16Execution(p),breakoutVolume:breakoutVolume(p),riskReward:{score:rrScore(p.riskReward?.rr),rr:Number(p.riskReward?.rr||0)},gannTime:{score:clamp(p.gannTime?.score||0),active:Boolean(p.gannTime?.active)},gannPrice:{score:clamp(p.gannPrice?.score||0)}};components.score=weighted(components);const plan=speculativePlan(base,x),classification=classify(base,components,plan,x.dataQuality||{fresh:true,conflict:false});const positives=[];const cautions=[];if(components.sepaSelection.score>=70)positives.push('اختيار السهم قوي وفق طبقة SEPA.');if(components.v16Execution.score>=70)positives.push('قابلية التنفيذ الفنية والسيولة جيدة وفق طبقة V16-style.');if(p.breakout?.confirmed)positives.push('الاختراق متحقق.');else if(p.breakout?.near)positives.push('السهم قريب من نقطة اختراق.');if(p.volume?.confirmed)positives.push('السيولة تؤكد الحركة.');if(p.gannTime?.active)positives.push('نافذة Gann الزمنية متوافقة وتُستخدم كتوقيت إضافي فقط.');if(!p.gannTime?.active)cautions.push('لا يوجد توافق Gann زمني قوي؛ لا يمنع الصفقة إذا اكتملت بقية الشروط.');if(!p.volume?.confirmed)cautions.push('السيولة لم تؤكد الحركة بالكامل بعد.');if(p.momentum?.overheated)cautions.push('الزخم ساخن؛ لا مطاردة.');return{...base,version:'GANN_FUSION_X_V2_CHALLENGER',score:components.score,classification,components,plan,explanation:{positives,cautions,action:classification.code==='HIGH_CONVICTION'?'الخلاصة: SEPA + V16 + الاختراق والسيولة متوافقة وGann يدعم التوقيت.':classification.code==='ACTIONABLE'?'الخلاصة: الفكرة قابلة للتنفيذ بشرط تفعيل نطاق الدخول والسيولة، وGann عامل توقيت مساعد.':classification.code==='CONDITIONAL'?'الخلاصة: مرشح للجلسة القادمة لكن يحتاج تأكيدًا إضافيًا قبل الدخول.':'الخلاصة: لا دخول جديد حتى تكتمل الشروط.'}}}
function rank(xs){const all=(xs||[]).map(analyze).filter(x=>x.valid).sort((a,b)=>b.score-a.score);return{all,dailyTop:all.filter(x=>['HIGH_CONVICTION','ACTIONABLE','CONDITIONAL'].includes(x.classification.code)).slice(0,5),watch:all.filter(x=>x.classification.code==='WATCH').slice(0,12)}}
return{WEIGHTS,rrScore,sepaSelection,v16Execution,breakoutVolume,speculativePlan,analyze,rank};});
