'use strict';

function finite(v){return v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));}
function num(v){return finite(v)?Number(v):null;}
function mean(values){const a=values.filter(Number.isFinite);return a.length?a.reduce((s,v)=>s+v,0)/a.length:null;}
function std(values){const a=values.filter(Number.isFinite);if(a.length<2)return null;const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+((v-m)**2),0)/a.length);}
function quantile(values,p){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const i=(a.length-1)*p,l=Math.floor(i),u=Math.ceil(i);return l===u?a[l]:a[l]+(a[u]-a[l])*(i-l);}
function round(v,d=3){return Number.isFinite(v)?Number(v.toFixed(d)):null;}
function clamp(v,min=0,max=100){return Math.max(min,Math.min(max,v));}
function normalizeRows(doc,cutoff){const raw=Array.isArray(doc)?doc:(doc?.sessions||doc?.rows||doc?.data||doc?.history||[]);return raw.map(r=>({date:String(r?.date||r?.sessionDate||r?.session||'').slice(0,10),close:num(r?.adjustedClose??r?.close),volume:num(r?.volume)})).filter(r=>r.date&&r.close>0&&(!cutoff||r.date<=cutoff)).sort((a,b)=>a.date.localeCompare(b.date));}
function maxDrawdown(rows,lookback=100){const closes=rows.slice(-lookback).map(r=>r.close);if(!closes.length)return null;let peak=closes[0],worst=0;for(const c of closes){if(c>peak)peak=c;if(peak>0)worst=Math.min(worst,(c/peak)-1);}return Math.abs(worst)*100;}
function downsideDeviation(returns){const a=returns.filter(v=>v<0).map(v=>v*100);return a.length>=2?std(a):a.length===1?0:null;}
function priceRiskFacts(rows){if(rows.length<21)return null;const returns=[];for(let i=1;i<rows.length;i++){const p=rows[i-1].close,c=rows[i].close;if(p>0&&c>0)returns.push((c/p)-1);}if(returns.length<20)return null;const recent=returns.slice(-100),recent20=recent.slice(-20),q05=quantile(recent,.05),volatility20=std(recent20.map(v=>v*100)),downside20=downsideDeviation(recent20),var95=q05===null?null:Math.max(0,-q05*100),drawdown100=maxDrawdown(rows,100);if(![volatility20,downside20,var95,drawdown100].every(Number.isFinite))return null;return{volatility20Pct:round(volatility20),downsideDeviation20Pct:round(downside20),var95OneDayPct:round(var95),maxDrawdown100Pct:round(drawdown100),returnSessions:recent.length};}
function turnoverFacts(rows){const recent=rows.slice(-20);if(recent.length<20)return null;const observed=recent.filter(r=>Number.isFinite(r.volume)&&r.volume>=0);if(observed.length<20)return null;const values=observed.map(r=>r.close*r.volume);const avg=mean(values);return Number.isFinite(avg)?{averageTurnover20Egp:round(avg,2),turnoverSessions:observed.length}:null;}
function deriveUniverseMetrics(items,decisionDate){const base=items.map(item=>{const rows=normalizeRows(item.doc,decisionDate),lastSession=rows.at(-1)?.date||null,fresh=Boolean(decisionDate&&lastSession===decisionDate),turnover=fresh?turnoverFacts(rows):null,riskFacts=fresh?priceRiskFacts(rows):null;return{ticker:item.ticker,source:item.source||null,lastSession,sessions:rows.length,fresh,turnover,riskFacts};});
  const liquid=base.filter(x=>Number.isFinite(x.turnover?.averageTurnover20Egp)).slice().sort((a,b)=>a.turnover.averageTurnover20Egp-b.turnover.averageTurnover20Egp);
  for(const x of base){if(Number.isFinite(x.turnover?.averageTurnover20Egp)&&liquid.length){const rank=liquid.filter(y=>y.turnover.averageTurnover20Egp<=x.turnover.averageTurnover20Egp).length;x.liquidityPercentile=round((rank/liquid.length)*100,1);x.liquidityProvenance={method:'OHLCV_AVG_TURNOVER_20_CROSS_SECTIONAL_PERCENTILE',asOf:decisionDate,sessionsUsed:x.turnover.turnoverSessions,source:x.source};}else{x.liquidityPercentile=null;x.liquidityProvenance=null;}}
  for(const x of base){const f=x.riskFacts,lp=x.liquidityPercentile;if(f&&Number.isFinite(lp)){let score=0;score+=Math.min(22,f.volatility20Pct*6);score+=Math.min(18,f.downsideDeviation20Pct*6);score+=Math.min(20,f.var95OneDayPct*6);score+=Math.min(20,f.maxDrawdown100Pct*.8);score+=Math.max(0,12-(lp*.12));x.riskScore=Math.round(clamp(score));x.riskProvenance={method:'V13_8_CORE_PRICE_RISK_WITH_OHLCV_LIQUIDITY',asOf:decisionDate,sessionsUsed:f.returnSessions+1,source:x.source,components:{volatility20Pct:f.volatility20Pct,downsideDeviation20Pct:f.downsideDeviation20Pct,var95OneDayPct:f.var95OneDayPct,maxDrawdown100Pct:f.maxDrawdown100Pct,liquidityPercentile:lp}};}else{x.riskScore=null;x.riskProvenance=null;}}
  return new Map(base.map(x=>[String(x.ticker||'').toUpperCase(),x]));}

module.exports={finite,normalizeRows,deriveUniverseMetrics};
