#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(process.env.GITHUB_WORKSPACE||'.'),store=path.join(root,'data/v17/historical-recovery/history'),out=path.join(root,'data/v17/historical-recovery/long-history');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),round=v=>Number.isFinite(v)?Number(v.toFixed(4)):null,write=(name,v)=>fs.writeFileSync(path.join(out,name),JSON.stringify(v,null,2)+'\n');
const canonical=new Set((read(path.join(root,'data/symbols.json')).symbols||[]).map(x=>String(x.symbol).toUpperCase().replace(/\.CA$/,''))),docs=fs.readdirSync(store).filter(x=>x.endsWith('.json')).map(x=>read(path.join(store,x)));
const events=[];for(const d of docs.filter(x=>(x.dataQualityReasons||[]).some(r=>String(r).startsWith('CORPORATE_ACTION')))){for(const a of d.adjustmentAnomalies||[]){const i=d.sessions.findIndex(x=>x.date===a.date),p=d.sessions[i-1],c=d.sessions[i];if(!p||!c)continue;const raw=(Number(c.close)/Number(p.close)-1)*100,adjusted=(Number(c.adjustedClose)/Number(p.adjustedClose)-1)*100,pf=Number(p.adjustedClose)/Number(p.close),cf=Number(c.adjustedClose)/Number(c.close),factor=pf>0?(cf/pf-1)*100:null,difference=Math.abs(raw-adjusted);const assessment=(Math.abs(factor)>=10||difference>=10)?'LIKELY_TRUE_CORPORATE_ACTION_OR_ADJUSTMENT_EVENT':difference<=2?'LIKELY_FALSE_POSITIVE_MARKET_MOVE':'UNCERTAIN_REQUIRES_REVIEW';events.push({symbol:d.ticker,suspiciousDate:a.date,percentageDiscontinuity:round(Math.abs(adjusted)),rawCloseMovePct:round(raw),adjustedCloseMovePct:round(adjusted),adjustmentFactorChangePct:round(factor),reasonFlagged:a.reason,assessment})}}
const assessmentCounts=events.reduce((m,x)=>(m[x.assessment]=(m[x.assessment]||0)+1,m),{}),symbolCounts={},symbolAssessmentCounts={};for(const x of events){symbolCounts[x.symbol]=(symbolCounts[x.symbol]||0)+1;(symbolAssessmentCounts[x.assessment]??=new Set()).add(x.symbol)}const symbolAssessmentTotals=Object.fromEntries(Object.entries(symbolAssessmentCounts).map(([k,v])=>[k,v.size]));write('corporate-action-audit.json',{schemaVersion:'17.2.0-corporate-action-audit-1',generatedAt:new Date().toISOString(),quarantinedSymbols:Object.keys(symbolCounts).length,eventCount:events.length,assessmentCounts,symbolAssessmentTotals,note:'Heuristic assessment only; quarantine is not weakened automatically.',events});
const corpMd=['# تدقيق رموز مراجعة الإجراءات الرأسمالية','','> التقييم استدلالي فقط، ولم يُرفع الحجر تلقائيًا عن أي رمز.','','| السهم | التاريخ | الانقطاع % | حركة الإغلاق الخام % | حركة السعر المعدل % | السبب | التقييم |','|---|---:|---:|---:|---:|---|---|',...events.map(x=>`| ${x.symbol} | ${x.suspiciousDate} | ${x.percentageDiscontinuity} | ${x.rawCloseMovePct} | ${x.adjustedCloseMovePct} | ${x.reasonFlagged} | ${x.assessment} |`)];fs.writeFileSync(path.join(root,'docs/v17/LONG_HISTORY_CORPORATE_ACTION_AUDIT.md'),corpMd.join('\n')+'\n');
const internal=new Set(['BLOCKS','BUCKETS','FOLLOW','RISK','RULES']),renamed=new Set(['ASCOM','DOMTY','EGYFERT','ICON','IRAX','NOSCO','PLC','SAE','SCCD','SODIC','TORA']);
const failures=docs.filter(x=>x.dataQualityStatus==='RETRIEVAL_FAILED').map(d=>{let category;if(internal.has(d.ticker))category='INVALID_INTERNAL_SYNTHETIC_SYMBOL';else if(renamed.has(d.ticker))category='DELISTED_OR_SECURITY_RENAMED';else if(!canonical.has(d.ticker))category='ETF_FUND_RIGHTS_OR_OTHER_NON_ORDINARY_SECURITY';else if(/identity score/i.test(d.error||''))category='ORDINARY_EGX_EQUITY_WRONG_OR_MISSING_YAHOO_MAPPING';else category='GENUINELY_UNAVAILABLE_FROM_SELECTED_SOURCE';return{symbol:d.ticker,companyNameAr:d.companyNameAr,companyNameEn:d.companyNameEn,canonicalOrdinaryEquity:canonical.has(d.ticker),category,errorSummary:/identity score/i.test(d.error||'')?(d.error.match(/identity score \d+/i)||[])[0]:'YAHOO_NOT_FOUND_OR_UNAVAILABLE'}}),categories=['ORDINARY_EGX_EQUITY_WRONG_OR_MISSING_YAHOO_MAPPING','DELISTED_OR_SECURITY_RENAMED','ETF_FUND_RIGHTS_OR_OTHER_NON_ORDINARY_SECURITY','INVALID_INTERNAL_SYNTHETIC_SYMBOL','GENUINELY_UNAVAILABLE_FROM_SELECTED_SOURCE'],categoryCounts=Object.fromEntries(categories.map(k=>[k,failures.filter(x=>x.category===k).length]));write('retrieval-failure-audit.json',{schemaVersion:'17.2.0-retrieval-failure-audit-1',generatedAt:new Date().toISOString(),canonicalOrdinaryEquityCount:canonical.size,totalFailures:failures.length,categoryCounts,failures});write('canonical-ordinary-equity-universe.json',{schemaVersion:'17.2.0-canonical-ordinary-equity-universe-1',generatedAt:new Date().toISOString(),source:'data/symbols.json',normalization:'Remove accidental .CA suffix from ticker identity',count:canonical.size,tickers:[...canonical].sort()});
const failureMd=['# تدقيق حالات فشل استرجاع التاريخ','','| السهم | الاسم | سهم عادي ضمن الكون القانوني | الفئة | ملخص الفشل |','|---|---|---|---|---|',...failures.map(x=>`| ${x.symbol} | ${x.companyNameAr||x.companyNameEn||'غير متاح'} | ${x.canonicalOrdinaryEquity?'نعم':'لا'} | ${x.category} | ${x.errorSummary} |`)];fs.writeFileSync(path.join(root,'docs/v17/LONG_HISTORY_RETRIEVAL_FAILURE_AUDIT.md'),failureMd.join('\n')+'\n');
console.log(JSON.stringify({canonicalOrdinaryEquityCount:canonical.size,corporateAction:{symbols:Object.keys(symbolCounts).length,events:events.length,assessmentCounts},retrievalFailures:{total:failures.length,categoryCounts}},null,2));
