'use strict';
const round=(v,d=4)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
function ema(values,period){if(values.length<period)return null;const k=2/(period+1);let e=avg(values.slice(0,period));for(const v of values.slice(period))e=v*k+e*(1-k);return e}
function rsi(values,p=14){if(values.length<=p)return null;const x=values.slice(-(p+1));let g=0,l=0;for(let i=1;i<x.length;i++){const d=x[i]-x[i-1];d>0?g+=d:l-=d}return l===0?(g>0?100:50):100-100/(1+g/l)}
function horizon(sessions,years,label){const end=new Date(`${sessions.at(-1)?.date}T00:00:00Z`);const start=new Date(end);start.setUTCFullYear(start.getUTCFullYear()-years);const rows=sessions.filter(x=>new Date(`${x.date}T00:00:00Z`)>=start);const required={1:200,3:650,5:1100}[years]||1;const toleranceStart=new Date(start);toleranceStart.setUTCDate(toleranceStart.getUTCDate()+45);const spansHorizon=rows[0]&&new Date(`${rows[0].date}T00:00:00Z`)<=toleranceStart;return summarize(rows,label,rows.length>=required&&spansHorizon?null:`INSUFFICIENT_${years===1?'52_WEEK':years+'_YEAR'}_COVERAGE`)}
function summarize(rows,label,unavailableReason=null){if(!rows.length||unavailableReason)return{label,available:false,unavailableReason,sessionCount:rows.length};const prices=rows.map(x=>Number(x.adjustedClose));const current=prices.at(-1),high=Math.max(...prices),absoluteLow=Math.min(...prices),hi=prices.indexOf(high),absoluteLo=prices.indexOf(absoluteLow),postPeakRows=rows.slice(hi),postPeakPrices=prices.slice(hi),postPeakLow=Math.min(...postPeakPrices),postPeakLo=hi+postPeakPrices.indexOf(postPeakLow),cycleRange=high-postPeakLow;const rawPosition=cycleRange>0?(current-postPeakLow)/cycleRange*100:100;return{label,available:true,coverageStart:rows[0].date,coverageEnd:rows.at(-1).date,sessionCount:rows.length,high:round(high),highDate:rows[hi].date,absoluteHistoricalLow:round(absoluteLow),absoluteHistoricalLowDate:rows[absoluteLo].date,postPeakLow:round(postPeakLow),postPeakLowDate:rows[postPeakLo].date,current:round(current),currentDrawdownPct:round((high-current)/high*100),drawdownFromHighPct:round((high-current)/high*100),distanceAbovePostPeakLowPct:round(postPeakLow>0?(current-postPeakLow)/postPeakLow*100:null),recoveryPositionPct:round(Math.max(-25,Math.min(125,rawPosition))),recoveryPositionRawPct:round(rawPosition)}}
function technical(sessions){const p=sessions.map(x=>Number(x.adjustedClose)),v=sessions.map(x=>Number(x.volume)).filter(Number.isFinite),last=p.at(-1);const momentum=n=>p.length>n?round((last/p.at(-(n+1))-1)*100):null;const e20=ema(p,20),e50=ema(p,50),e200=ema(p,200);const prev20=ema(p.slice(0,-5),20),prev50=ema(p.slice(0,-5),50),prev200=ema(p.slice(0,-5),200);const tr=sessions.slice(-15).map((x,i,a)=>i?Math.max(Number(x.high)-Number(x.low),Math.abs(Number(x.high)-Number(a[i-1].close)),Math.abs(Number(x.low)-Number(a[i-1].close))):Number(x.high)-Number(x.low));const recentV=avg(v.slice(-5)),baseV=avg(v.slice(-25,-5));const recentLow=Math.min(...p.slice(-15)),priorLow=Math.min(...p.slice(-40,-15));return{momentum5Pct:momentum(5),momentum20Pct:momentum(20),momentum60Pct:momentum(60),momentum120Pct:momentum(120),rsi14:round(rsi(p)),rsiDirection5:(rsi(p)-rsi(p.slice(0,-5)))>0?'IMPROVING':'NOT_IMPROVING',ema20:round(e20),ema50:round(e50),ema200:round(e200),ema20Slope5Pct:prev20?round((e20/prev20-1)*100):null,ema50Slope5Pct:prev50?round((e50/prev50-1)*100):null,ema200Slope5Pct:prev200?round((e200/prev200-1)*100):null,higherLowConfirmation:priorLow>0&&recentLow>priorLow*1.02,repeatedLowCount:p.filter(x=>x<=Math.min(...p)*(1.05)).length,volumeExpansionRatio:baseV>0?round(recentV/baseV):null,averageVolume20:round(avg(v.slice(-20))),averageValueTraded20:round(avg(sessions.slice(-20).map(x=>Number(x.volume)*Number(x.close)))),atr14:round(avg(tr.slice(-14))),atrPct:last>0?round(avg(tr.slice(-14))/last*100):null}}
function buildHorizons(sessions){return{week52:horizon(sessions,1,'52_WEEK'),year3:horizon(sessions,3,'3_YEAR'),year5:horizon(sessions,5,'5_YEAR'),maxAvailable:summarize(sessions,'MAX_AVAILABLE_HISTORY'),technical:technical(sessions)}}
function bestReliableHorizon(horizons){for(const key of ['maxAvailable','year5','year3','week52'])if(horizons?.[key]?.available)return key;return null}
function discountCategory(p){if(p<20)return'NO_MATERIAL_HISTORICAL_DECLINE';if(p<35)return'MODERATE_DECLINE';if(p<50)return'LARGE_DECLINE';if(p<=65)return'DEEP_DECLINE';return'SEVERE_HISTORICAL_DECLINE'}
module.exports={bestReliableHorizon,buildHorizons,discountCategory,ema,horizon,summarize,technical};
