#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const {fetchHistory}=require('../../../history/adapters/yahoo-history-adapter.cjs');const {inspectSessions}=require('./quality.cjs');
const root=path.resolve(process.env.GITHUB_WORKSPACE||'.'),data=path.join(root,'data/v17/historical-recovery/long-history'),store=path.join(root,'data/v17/historical-recovery/history');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});const t=p+'.tmp';fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');JSON.parse(fs.readFileSync(t));fs.renameSync(t,p)};
function entries(){const raw=read('data/symbol-map.json'),overrides=read('data/v17/historical-recovery/long-history/yahoo-mapping-overrides.json').mappings||{},a=Array.isArray(raw)?raw:(raw.symbols||raw.items||Object.values(raw));return a.filter(x=>x&&x.ticker&&x.active!==false).map(x=>overrides[x.ticker]?{...x,...overrides[x.ticker],v17HistoricalRecoveryMapping:true}:x)}
function localReference(t){try{const d=read(`data/history/${t}.json`),x=d.sessions.at(-1);return x?{close:x.close,source:'shared_history_read_only'}:null}catch{return null}}
async function retrieve(entry,config){const at=new Date().toISOString();try{const r=await fetchHistory(entry,{range:config.yahooRange||'10y',localReference:localReference(entry.ticker),timeoutMs:config.timeoutMs||30000,maxAttempts:config.maxAttempts||2});const sessions=r.sessions.map(x=>({...x,adjustmentFactor:Number(x.close)>0&&Number(x.adjustedClose)>0?Number((Number(x.adjustedClose)/Number(x.close)).toFixed(10)):null,provenance:{source:'YAHOO_CHART_API',sourceSymbol:r.requestedSymbol,adjustedCloseClaim:'SOURCE_PROVIDED_NON_AUTHORITATIVE_FOR_EGX_CORPORATE_ACTIONS',adjustedOhlc:'NOT_DERIVED'}}));const q=inspectSessions(sessions);return{schemaVersion:'17.1.0-long-history-1',ticker:entry.ticker,companyNameAr:entry.companyNameAr||null,companyNameEn:entry.companyNameEn||null,source:'YAHOO_CHART_API',sourceSymbol:r.requestedSymbol,requestedRange:config.yahooRange||'10y',interval:'1d',coverageStart:sessions[0]?.date||null,coverageEnd:sessions.at(-1)?.date||null,sessionCount:sessions.length,rawSessionCount:r.sessions.length,retrievedAt:at,symbolIdentity:r.identity,dataProvenance:{primary:'YAHOO_CHART_API',licensed:false,officialCorporateActionEvidence:false,rawOhlcv:'SOURCE_PROVIDED',adjustedClose:'SOURCE_PROVIDED_NON_AUTHORITATIVE',fallbackUsed:false},corporateActionConfidence:q.corporateActionConfidence,dataQualityStatus:q.status,dataQualityReasons:q.reasons,detectedCorporateActions:q.detectedCorporateActions,adjustmentAnomalies:q.anomalies,sessions}}catch(e){return{schemaVersion:'17.1.0-long-history-1',ticker:entry.ticker,companyNameAr:entry.companyNameAr||null,companyNameEn:entry.companyNameEn||null,source:'YAHOO_CHART_API',sourceSymbol:entry.yahooSymbol||null,requestedRange:config.yahooRange||'10y',retrievedAt:at,sessionCount:0,dataQualityStatus:'RETRIEVAL_FAILED',dataQualityReasons:['SOURCE_RETRIEVAL_FAILED'],error:e.message,sessions:[]}}}
async function main(){const config=read('data/v17/historical-recovery/long-history/config.json');let selected=entries();const arg=process.argv.find(x=>x.startsWith('--symbols='));if(arg){const set=new Set(arg.split('=')[1].split(',').map(x=>x.trim().toUpperCase()));selected=selected.filter(x=>set.has(x.ticker))}fs.mkdirSync(store,{recursive:true});const results=[];let cursor=0;async function worker(){while(cursor<selected.length){const entry=selected[cursor++],doc=await retrieve(entry,config);write(path.join(store,entry.ticker+'.json'),doc);results.push({ticker:entry.ticker,status:doc.dataQualityStatus,sessions:doc.sessionCount,coverageStart:doc.coverageStart||null,coverageEnd:doc.coverageEnd||null,error:doc.error||null});process.stdout.write(`${entry.ticker}:${doc.dataQualityStatus}:${doc.sessionCount}\n`)}}await Promise.all(Array.from({length:Math.max(1,Number(config.concurrency||3))},worker));const report={schemaVersion:'17.1.0-retrieval-report-1',generatedAt:new Date().toISOString(),requestedSymbols:selected.length,successful:results.filter(x=>x.sessions>0).length,failed:results.filter(x=>x.sessions===0).length,results:results.sort((a,b)=>a.ticker.localeCompare(b.ticker))};write(path.join(data,'retrieval-report.json'),report);console.log(JSON.stringify({requested:report.requestedSymbols,successful:report.successful,failed:report.failed},null,2))}
if(require.main===module)main().catch(e=>{console.error(e);process.exit(1)});module.exports={entries,retrieve};
