const state={data:null,selected:null,stockTicker:null,technicalTicker:null,filters:{tier:'all',family:'all',search:'',multi:false},portfolio:[]};
const $=id=>document.getElementById(id);
const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{maximumFractionDigits:d}):'—';
const pct=(v,d=1)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${fmt(v,d)}%`:'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=v=>Number.isFinite(Number(v));
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function tierClass(t){return t?.includes('TIER_A')?'a':t?.includes('TIER_B')?'b':'c'}
function tierShort(t){return t?.includes('TIER_A')?'Tier A':t?.includes('TIER_B_RESEARCH')?'Tier B Research':t?.includes('TIER_B')?'Tier B':'Tier C'}
function familyLabel(f){return({PORTFOLIO_BASKET:'Basket',BREAKOUT:'Breakout',MOMENTUM:'Momentum',TREND_CONTINUATION:'Trend Continuation',PULLBACK:'Pullback',REVERSAL:'Reversal',EMA_MACD:'EMA–MACD',LEADERSHIP:'Relative Strength Leadership',VOLATILITY_CONTRACTION:'VCP / Volatility Contraction',OTHER:'Other'})[f]||f}
function highLabel(l){if(!l)return'—';return l.full52WeekCoverage?'قمة 52 أسبوع':'قمة التاريخ المتاح (Proxy)'}
function metric(label,value,cls=''){return`<div class="tech ${cls}"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function statusBadge(text,ok=true){return`<span class="status-badge ${ok?'ok':'warn'}">${esc(text)}</span>`}
function downloadText(name,text,type='text/plain'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function candidateByTicker(t){return(state.data?.allCandidates||[]).find(x=>x.ticker===t)}
function universeByTicker(t){return(state.data?.universeScreener||[]).find(x=>x.ticker===t)}

function switchTab(tab){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===tab));window.scrollTo({top:0,behavior:'smooth'})}

function renderTop(){const d=state.data;$('sessionId').textContent=d.sessionId||'—';$('regimeLabel').textContent=d.marketRegime?.labelAr||d.marketRegime?.code||'—';$('regimeCode').textContent=`${d.marketRegime?.code||'—'} · Risk x${fmt(d.marketRegime?.riskMultiplier,2)}`;$('regimeScore').textContent=fmt(d.marketRegime?.score,0);$('regimeNote').textContent=`Leadership ${fmt(d.counts?.leadershipResearchEligible,0)} · VCP ${fmt(d.counts?.vcpEligible,0)} · RS قرب القمة ${fmt(d.counts?.relativeStrengthNearHighLeaders,0)}. Evidence-first هو ترتيب العرض.`;$('canonicalCount').textContent=fmt(d.dataHealth?.canonicalUniverse??d.counts?.canonicalStocksLoaded,0);$('mergedCount').textContent=fmt(d.allCandidates?.length,0);$('actionableCount').textContent=fmt(d.counts?.actionableOrConditional,0);$('emaCount').textContent=fmt(d.counts?.emaMacdContinuationEligible,0);const z=$('zeroGuard');if(d.diagnostics?.zeroSignalWarning){z.textContent='⚠ Zero-Signal Regression Detected';z.className='truth-state warn'}else{z.textContent='✓ لا يوجد Zero-Signal تضليلي';z.className='truth-state ok'}const health=d.dataHealth?.status==='PASS';$('engineHealth').innerHTML=health?'✓ PASS':'⚠ FAIL';$('engineHealth').className=`health-state ${health?'ok':'warn'}`;$('engineHealthNote').textContent=`${fmt(d.dataHealth?.currentSessionCoveragePct,1)}% current-session · ${fmt(d.dataHealth?.consistencyMismatchCount,0)} canonical mismatches · ${fmt(d.dataHealth?.criticalFailureCount,0)} critical failures.`}

function renderTopFive(){const rows=state.data.topFiveNow||[];$('topFiveList').innerHTML=rows.map((r,i)=>`<button class="top-card" data-open-ticker="${esc(r.ticker)}"><span>#${i+1}</span><strong>${esc(r.ticker)}</strong><em>${esc(tierShort(r.tier))}</em><b>${fmt(r.decisionScore,1)}</b><small>RS ${fmt(r.leadership?.relativeStrengthComposite,0)}</small></button>`).join('');document.querySelectorAll('[data-open-ticker]').forEach(b=>b.addEventListener('click',()=>{selectTicker(b.dataset.openTicker);switchTab('opportunities')}))}

function renderManifest(){const f=state.data.featureManifest||[];$('featureCount').textContent=`${f.length} ميزة`;$('featureManifest').innerHTML=f.map(x=>`<div class="feature"><b>✓ ${esc(x.labelAr)}</b><span>${esc(x.provenance)}</span></div>`).join('')}

function passesTier(row){if(state.filters.tier==='all')return true;if(state.filters.tier==='A')return row.tier?.includes('TIER_A');if(state.filters.tier==='B')return row.tier?.includes('TIER_B');return !row.tier?.includes('TIER_A')&&!row.tier?.includes('TIER_B')}
function filteredOpportunities(){const q=state.filters.search.trim().toLowerCase();return(state.data?.allCandidates||[]).filter(row=>passesTier(row)&&(state.filters.family==='all'||(row.strategyFamilies||[]).includes(state.filters.family))&&(!state.filters.multi||(row.sources||[]).filter(s=>!String(s).startsWith('V18_')).length>1)&&(!q||row.ticker?.toLowerCase().includes(q)||row.companyNameAr?.toLowerCase().includes(q)))}
function renderOpportunityFilters(){const select=$('familyFilter');const families=[...new Set((state.data.allCandidates||[]).flatMap(x=>x.strategyFamilies||[]))].sort();select.innerHTML='<option value="all">كل الاستراتيجيات</option>'+families.map(f=>`<option value="${esc(f)}">${esc(familyLabel(f))}</option>`).join('')}
function renderOpportunities(){const rows=filteredOpportunities();$('visibleCount').textContent=`${rows.length} فرصة`;$('opportunityList').innerHTML=rows.length?rows.map(row=>{const l=row.leadership||{};return`<div class="opportunity ${state.selected===row.ticker?'active':''}" data-ticker="${esc(row.ticker)}"><div class="rank">#${fmt(row.evidenceRank??row.rank,0)}</div><div class="ticker"><strong>${esc(row.ticker)}</strong><span>${esc(row.companyNameAr)}</span></div><div class="score"><strong>${fmt(row.decisionScore,1)}</strong><span>RS ${fmt(l.relativeStrengthComposite,0)} · ${l.vcp?.passed?'VCP ✓':'VCP —'}</span></div><div class="sources-mini">${(row.sources||[]).slice(0,4).map(s=>`<span class="mini-chip">${esc(s)}</span>`).join('')}</div><div class="tier ${tierClass(row.tier)}">${esc(tierShort(row.tier))}<br>${esc(row.decisionLabelAr||'')}</div></div>`}).join(''):'<div class="empty-detail"><strong>لا توجد نتائج بهذه الفلاتر</strong><span>غيّر الفئة أو العائلة أو البحث.</span></div>';document.querySelectorAll('.opportunity').forEach(el=>el.addEventListener('click',()=>selectTicker(el.dataset.ticker)))}
function selectTicker(ticker){const row=candidateByTicker(ticker);if(!row)return;state.selected=ticker;$('detailEmpty').hidden=true;$('detailContent').hidden=false;$('detailTier').textContent=`${tierShort(row.tier)} · ${row.decisionLabelAr||''}`;$('detailTicker').textContent=row.ticker;$('detailName').textContent=row.companyNameAr||'';$('detailScore').textContent=fmt(row.decisionScore,1);$('sourceChips').innerHTML=(row.sources||[]).map(x=>`<span>${esc(x)}</span>`).join('');$('strategyChips').innerHTML=(row.strategyFamilies||row.strategies||[]).map(x=>`<span>${esc(familyLabel(x))}</span>`).join('');const t=row.technical||{},l=row.leadership||{},v=l.vcp||{},rc=row.regimeCompatibility||{},adj=row.scoreAdjustments||{};$('technicalGrid').innerHTML=[metric('الاتجاه',t.trendCode||'—'),metric('السعر',fmt(t.price,3)),metric('RSI 14',fmt(t.rsi14,1)),metric('MACD',fmt(t.macd,3)),metric('Signal',fmt(t.macdSignal,3)),metric('RVOL',`${fmt(t.volumeRatio20,2)}x`),metric('Turnover',`${fmt((t.averageTurnover20Egp||0)/1e6,1)}m EGP`),metric('ATR%',`${fmt(t.atrPct,2)}%`),metric('RS Composite',fmt(l.relativeStrengthComposite,1)),metric('Leadership',fmt(l.leadershipScore,1)),metric(highLabel(l),fmt(l.availableHigh,3)),metric('بعد عن القمة',l.distanceFromAvailableHighPct==null?'—':`${fmt(l.distanceFromAvailableHighPct,2)}%`),metric('VCP',v.passed?'✓ Passed':'—'),metric('Regime Fit',rc.score==null?'—':`${fmt(rc.score*100,0)}%`),metric('Base Score',fmt(row.baseDecisionScore,1)),metric('Research Δ',adj.total==null?'—':`${Number(adj.total)>=0?'+':''}${fmt(adj.total,1)}`)].join('');const ema=row.emaMacdContinuation||{};$('emaConditions').innerHTML=(ema.conditions||[]).map(c=>`<div class="condition ${c.pass?'pass':'fail'}"><b>${c.pass?'✓':'✕'} ${esc(c.labelAr)}</b><em>${esc(c.detail??'')}</em></div>`).join('')||'<div class="condition"><b>لا توجد تفاصيل EMA–MACD لهذا المسار</b></div>';const p=row.execution?.preferredPlan||{};const bits=[['Entry Low',fmt(p.entryLow,4)],['Entry High',fmt(p.entryHigh,4)],['Stop',fmt(p.stopLoss,4)],['Target 1',fmt(p.target1,4)],['Portfolio Weight',p.portfolioWeightPct?`${fmt(p.portfolioWeightPct,1)}%`:'—'],['Open Confirm',row.execution?.nextSessionOpenConfirmationRequired?'إلزامي':'—']];$('executionPlan').innerHTML=`<div class="plan-grid">${bits.map(([a,b])=>`<div><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')}</div><div>${esc(row.execution?.noteAr||'Shadow/Pilot — ليست أمر شراء تلقائي.')}</div>${l.full52WeekCoverage?'':'<div class="warning-line">High = أعلى التاريخ المتاح Proxy؛ ليس 52 أسبوع.</div>'}`;$('evidenceTrace').innerHTML=(row.evidence||[]).map(e=>`<div class="evidence"><b>${esc(e.source)} · ${esc(e.strategyLabelAr||e.strategyId||'')}</b><p>${esc(e.noteAr||e.status||'')}</p></div>`).join('')||'<div class="evidence"><p>التفاصيل موحدة في Evidence Center.</p></div>';renderOpportunities()}

function filteredUniverse(){const q=$('screenerSearch').value.trim().toLowerCase(),trend=$('trendFilter').value,decision=$('decisionFilter').value,sort=$('sortFilter').value;let rows=(state.data.universeScreener||[]).filter(x=>(!q||x.ticker.toLowerCase().includes(q)||x.companyNameAr.toLowerCase().includes(q)||x.companyNameEn.toLowerCase().includes(q)||x.sector.toLowerCase().includes(q))&&(trend==='all'||x.trendCode===trend)&&(decision==='all'||(x.decision?.status||'UNRANKED')===decision));const sorters={rank:(a,b)=>(a.decision?.evidenceRank??9999)-(b.decision?.evidenceRank??9999),technical:(a,b)=>(b.technicalScore||0)-(a.technicalScore||0),turnover:(a,b)=>(b.averageTurnover20Egp||0)-(a.averageTurnover20Egp||0),rvol:(a,b)=>(b.volumeRatio20||0)-(a.volumeRatio20||0),ret20:(a,b)=>(b.return20Pct||0)-(a.return20Pct||0)};return rows.sort(sorters[sort]||sorters.rank)}
function renderScreener(){const rows=filteredUniverse();$('screenerCount').textContent=`${rows.length} / ${state.data.universeScreener.length}`;$('screenerBody').innerHTML=rows.map(x=>`<tr class="clickable" data-stock="${esc(x.ticker)}"><td><b>${esc(x.ticker)}</b><small>${esc(x.companyNameAr)}</small></td><td>${esc(x.decision?.status||'UNRANKED')}</td><td>${fmt(x.close,3)}</td><td class="${Number(x.change1Pct)>=0?'pos':'neg'}">${pct(x.change1Pct,2)}</td><td class="${Number(x.return20Pct)>=0?'pos':'neg'}">${pct(x.return20Pct,2)}</td><td>${fmt(x.technicalScore,0)} · ${esc(x.trendCode)}</td><td>${fmt(x.rsi14,1)}</td><td>${fmt(x.volumeRatio20,2)}x</td><td>${fmt((x.averageTurnover20Egp||0)/1e6,1)}</td><td>${fmt(x.atrPct,2)}%</td><td>${fmt(x.support20,3)}</td><td>${fmt(x.resistance20,3)}</td></tr>`).join('');document.querySelectorAll('[data-stock]').forEach(tr=>tr.addEventListener('click',()=>{state.stockTicker=tr.dataset.stock;syncStockSelects();renderStockCenter();switchTab('stock')}))}

function stockOptions(){return(state.data.universeScreener||[]).slice().sort((a,b)=>a.ticker.localeCompare(b.ticker)).map(x=>`<option value="${esc(x.ticker)}">${esc(x.ticker)} — ${esc(x.companyNameAr)}</option>`).join('')}
function syncStockSelects(){if($('stockSelect'))$('stockSelect').value=state.stockTicker;if($('technicalStockSelect'))$('technicalStockSelect').value=state.technicalTicker||state.stockTicker}
function renderStockCenter(){const x=universeByTicker(state.stockTicker);if(!x)return;const d=x.decision||{};$('stockCenter').innerHTML=`<div class="stock-hero"><div><span class="tier-badge">${esc(d.status||'UNRANKED')}</span><h2>${esc(x.ticker)} · ${esc(x.companyNameAr)}</h2><p>${esc(x.companyNameEn)} · ${esc(x.sector)}</p></div><div class="big-price"><strong>${fmt(x.close,3)}</strong><span class="${Number(x.change1Pct)>=0?'pos':'neg'}">${pct(x.change1Pct,2)}</span></div></div><div class="technical-grid">${[metric('Evidence Rank',d.evidenceRank??'—'),metric('Decision Score',fmt(d.score,1)),metric('Technical Score',fmt(x.technicalScore,0)),metric('Trend',x.trendCode),metric('RSI',fmt(x.rsi14,1)),metric('RVOL',`${fmt(x.volumeRatio20,2)}x`),metric('Turnover',`${fmt((x.averageTurnover20Egp||0)/1e6,1)}m`),metric('ATR%',`${fmt(x.atrPct,2)}%`),metric('Support 20',fmt(x.support20,3)),metric('Resistance 20',fmt(x.resistance20,3)),metric('SMA20',fmt(x.sma20,3)),metric('SMA50',fmt(x.sma50,3)),metric('MACD',fmt(x.macd,3)),metric('Signal',fmt(x.macdSignal,3)),metric('RS',fmt(d.relativeStrength,1)),metric('VCP',d.vcp?'✓ Passed':'—')].join('')}</div><div class="detail-section"><h3>V13/V15 Adaptive Status</h3><div class="evidence"><b>${esc(x.recommendationStatus)} · ${esc(x.recommendationStrategyAr)}</b><p>${esc(x.recommendationStatusAr)} · Proximity ${fmt(x.adaptiveProximityPct,1)}%</p>${(x.missingRequirementsAr||[]).map(r=>`<p>• ${esc(r)}</p>`).join('')}</div></div><div class="detail-section"><h3>Data Quality</h3><div class="plan-grid"><div><span>History</span><strong>${fmt(x.dataQuality.historySessions,0)} sessions</strong></div><div><span>Confidence</span><strong>${fmt(x.dataQuality.averageConfidence,1)}%</strong></div><div><span>Verified</span><strong>${x.dataQuality.symbolVerified?'✓':'—'}</strong></div><div><span>Last Session</span><strong>${esc(x.dataQuality.lastSession||'—')}</strong></div></div></div>`}

function renderChart(){const x=universeByTicker(state.technicalTicker||state.stockTicker);if(!x)return;const vals=(x.chart?.close||[]).filter(finite).map(Number),dates=x.chart?.dates||[];if(vals.length<2){$('priceChart').innerHTML='<div class="empty-detail">لا توجد بيانات رسم كافية</div>';return}const w=900,h=300,pad=28,min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const pts=vals.map((v,i)=>[pad+i*(w-pad*2)/(vals.length-1),h-pad-(v-min)*(h-pad*2)/span]);const path=pts.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ');$('priceChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Price chart"><path class="chart-line" d="${path}" fill="none"/><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}" class="axis"/><text x="${pad}" y="18">${fmt(max,3)}</text><text x="${pad}" y="${h-6}">${fmt(min,3)}</text><text x="${w-pad}" y="${h-6}" text-anchor="end">${esc(dates[dates.length-1]||'')}</text></svg>`;$('technicalCenterGrid').innerHTML=[metric('Ticker',x.ticker),metric('Close',fmt(x.close,3)),metric('Support 20',fmt(x.support20,3)),metric('Resistance 20',fmt(x.resistance20,3)),metric('High 50',fmt(x.high50,3)),metric('Distance High50',pct(x.distanceFromHigh50Pct,2)),metric('SMA20',fmt(x.sma20,3)),metric('SMA50',fmt(x.sma50,3)),metric('RSI14',fmt(x.rsi14,1)),metric('MACD',fmt(x.macd,3)),metric('Signal',fmt(x.macdSignal,3)),metric('ATR%',`${fmt(x.atrPct,2)}%`),metric('Volatility20',`${fmt(x.volatility20Pct,2)}%`),metric('RVOL',`${fmt(x.volumeRatio20,2)}x`)].join('')}

function renderLeadership(){const rows=(state.data.allCandidates||[]).filter(x=>x.leadership).slice().sort((a,b)=>(b.leadership?.leadershipScore||0)-(a.leadership?.leadershipScore||0));const s=state.data.leadershipSummary||{};$('leadershipCoverage').textContent=`RS ${fmt(s.crossSectionalUniverse,0)} · VCP ${fmt(s.vcpEligible,0)}`;$('highCoverageNotice').textContent=s.full52WeekCoverageCount?`52-week coverage: ${s.full52WeekCoverageCount}`:`تنبيه نزاهة: 0 أسهم لديها ≥220 جلسة؛ المعروض هو Available-History High Proxy لـ ${fmt(s.proxyHighCoverageCount,0)} سهم، وليس 52-Week High.`;$('leadershipBody').innerHTML=rows.map(x=>`<tr><td>#${fmt(x.evidenceRank??x.rank,0)}</td><td><b>${esc(x.ticker)}</b></td><td>${esc(tierShort(x.tier))}</td><td>${fmt(x.leadership?.relativeStrengthComposite,1)}</td><td>${fmt(x.leadership?.leadershipScore,1)}</td><td>${x.leadership?.vcp?.passed?'✓':'—'}</td><td>${x.leadership?.distanceFromAvailableHighPct==null?'—':pct(x.leadership.distanceFromAvailableHighPct,2)}</td><td>${esc(highLabel(x.leadership))}</td><td>${x.regimeCompatibility?.score==null?'—':`${fmt(x.regimeCompatibility.score*100,0)}%`}</td></tr>`).join('')}

function renderAgreement(){const rows=state.data.engineAgreement||[];$('agreementBody').innerHTML=rows.map(x=>`<tr><td>#${fmt(x.evidenceRank,0)}</td><td><b>${esc(x.ticker)}</b></td><td>${esc(tierShort(x.tier))}</td><td>${fmt(x.score,1)}</td><td title="${esc(x.independentSources.join(', '))}">${fmt(x.independentSourceCount,0)}</td><td title="${esc(x.researchSources.join(', '))}">${fmt(x.researchSourceCount,0)}</td><td>${esc(x.agreementLevel)}</td></tr>`).join('');$('sourceStats').innerHTML=(state.data.sourceStats||[]).map(x=>`<div class="evidence"><b>${esc(x.source)}</b><p>${x.candidates} candidates · Tier A ${x.tierA} · Tier B ${x.tierB} · Research ${x.research} · Watch ${x.watch}</p></div>`).join('')}

function renderBasket(){const b=state.data.basketCenter||{};$('basketExposure').textContent=`Exposure ${fmt(b.totalExposurePct,1)}% · Cash ${fmt(b.cashReservePct,1)}%`;$('basketCards').innerHTML=(b.recommendations||[]).map(x=>`<div class="basket-card"><div><span>#${x.rank}</span><strong>${esc(x.ticker)}</strong><em>${fmt(x.portfolioWeightPct,1)}%</em></div><p>Entry ${fmt(x.entryLow,4)}–${fmt(x.entryHigh,4)}</p><p>Stop ${fmt(x.stopLoss,4)} · Target ${fmt(x.target1,4)}</p><small>${x.hotMomentumRisk?'⚠ Hot Momentum · ':''}${x.cashIfNotTriggered?'Failed weight → CASH':'Weight rule missing'}</small></div>`).join('');$('basketStatus').textContent=`${b.statusAr||''} Evidence: ${b.evidenceTier||'—'} · Professional evidence: ${b.professionalEvidenceReady?'YES':'NO'} · Automatic orders: OFF.`}
function calcRisk(){const capital=Number($('capitalInput').value),riskPct=Number($('riskPctInput').value),entry=Number($('entryInput').value),stop=Number($('stopInput').value);if(!(capital>0&&riskPct>0&&entry>0&&stop>0&&entry!==stop)){$('riskCalcResult').textContent='أدخل قيم صحيحة لرأس المال وRisk% وEntry وStop.';return}const riskMoney=capital*riskPct/100,perShare=Math.abs(entry-stop),qty=Math.floor(riskMoney/perShare),exposure=qty*entry,actualRisk=qty*perShare;$('riskCalcResult').innerHTML=`الكمية النظرية <b>${fmt(qty,0)}</b> سهم · Exposure <b>${fmt(exposure,0)} EGP</b> · Risk <b>${fmt(actualRisk,0)} EGP</b> (${fmt(actualRisk/capital*100,3)}%). <span>الحاسبة لا تتجاوز وحدها حد المركز ${fmt(state.data.riskCenter?.maximumSinglePositionPct,1)}%؛ راجع السيولة وحجم المركز.</span>`}
function renderMorningOptions(){const rows=(state.data.allCandidates||[]).filter(x=>x.execution?.preferredPlan);$('morningTicker').innerHTML=rows.map(x=>`<option value="${esc(x.ticker)}">${esc(x.ticker)} — ${esc(tierShort(x.tier))}</option>`).join('');if(rows[0]){const p=rows[0].execution.preferredPlan||{};$('morningOpen').value=p.entryLow||''}renderMorningResult()}
function renderMorningResult(){const row=candidateByTicker($('morningTicker').value),open=Number($('morningOpen').value),liq=$('liquidityConfirm').checked;if(!row||!(open>0)){$('morningResult').textContent='اختر سهمًا وأدخل سعر الافتتاح.';return}const p=row.execution?.preferredPlan||{},close=Number(row.technical?.price||0),gap=close>0?(open/close-1)*100:null,maxGap=Number(state.data.riskCenter?.doNotChaseGapPct||3);let status='WAIT',reason='في انتظار تأكيد الشروط.';if(finite(p.stopLoss)&&open<=Number(p.stopLoss)){status='CANCEL';reason='الافتتاح عند/أسفل مستوى الوقف.'}else if(finite(p.entryHigh)&&open>Number(p.entryHigh)){status='NO CHASE';reason='الافتتاح أعلى نطاق الدخول.'}else if(finite(gap)&&gap>maxGap){status='NO CHASE';reason=`Gap ${fmt(gap,2)}% أكبر من حد ${fmt(maxGap,1)}%.`}else if(!liq){status='WAIT / CANCEL';reason='السيولة أول 10–15 دقيقة غير مؤكدة.'}else if(finite(p.entryLow)&&finite(p.entryHigh)&&open>=Number(p.entryLow)&&open<=Number(p.entryHigh)){status='CONDITIONAL GO';reason='داخل نطاق الدخول والسيولة مؤكدة؛ يظل القرار Pilot/Conditional وليس أمرًا آليًا.'}else{status='WAIT';reason='الافتتاح خارج النطاق المثالي.'}$('morningResult').innerHTML=`<b>${esc(status)}</b> — ${esc(reason)}`}

function loadPortfolio(){try{state.portfolio=JSON.parse(localStorage.getItem('egx-v18-portfolio')||'[]')}catch{state.portfolio=[]}}
function savePortfolio(){try{localStorage.setItem('egx-v18-portfolio',JSON.stringify(state.portfolio))}catch{}renderPortfolio()}
function renderPortfolioOptions(){const options=stockOptions();$('portfolioTicker').innerHTML=options}
function renderPortfolio(){const rows=state.portfolio||[];$('portfolioBody').innerHTML=rows.length?rows.map(x=>{const u=universeByTicker(x.ticker),current=Number(u?.close||0),cost=Number(x.buyPrice)*Number(x.qty),value=current*Number(x.qty),pl=value-cost,plPct=cost?pl/cost*100:0;return`<tr><td><b>${esc(x.ticker)}</b></td><td>${fmt(x.buyPrice,3)}</td><td>${fmt(current,3)}</td><td>${fmt(x.qty,0)}</td><td class="${pl>=0?'pos':'neg'}">${pct(plPct,2)}</td><td class="${pl>=0?'pos':'neg'}">${fmt(pl,0)}</td><td><button class="tiny-btn" data-remove-portfolio="${esc(x.ticker)}">×</button></td></tr>`}).join(''):'<tr><td colspan="7">لا توجد مراكز محفوظة محليًا.</td></tr>';document.querySelectorAll('[data-remove-portfolio]').forEach(b=>b.addEventListener('click',()=>{state.portfolio=state.portfolio.filter(x=>x.ticker!==b.dataset.removePortfolio);savePortfolio()}))}
function addPortfolio(){const ticker=$('portfolioTicker').value,buyPrice=Number($('buyPriceInput').value),qty=Number($('qtyInput').value);if(!ticker||!(buyPrice>0)||!(qty>0)){toast('أدخل سعر شراء وكمية صحيحة');return}const existing=state.portfolio.find(x=>x.ticker===ticker);if(existing){existing.buyPrice=buyPrice;existing.qty=qty}else state.portfolio.push({ticker,buyPrice,qty});savePortfolio();toast('تم الحفظ محليًا')}

function renderMatrix(){const matrix=state.data.strategyRegimeMatrix||{};const regimes=Object.keys(matrix),families=[...new Set(regimes.flatMap(r=>Object.keys(matrix[r]||{})))];$('matrixWrap').innerHTML=`<table><thead><tr><th>Strategy</th>${regimes.map(r=>`<th>${esc(r)}</th>`).join('')}</tr></thead><tbody>${families.map(f=>`<tr><td><b>${esc(familyLabel(f))}</b></td>${regimes.map(r=>{const v=matrix[r]?.[f];return`<td>${finite(v)?`${fmt(Number(v)*100,0)}%`:'—'}</td>`}).join('')}</tr>`).join('')}</tbody></table>`}

function evidenceCard(title,x){if(!x)return'';return`<div class="evidence-card"><h3>${esc(title)}</h3><div class="technical-grid">${metric('Signals',fmt(x.signals,0))}${metric('Entered',fmt(x.entered,0))}${metric('Win Rate',`${fmt(x.winRatePct,1)}%`)}${metric('Avg Return',`${fmt(x.averageReturnPct,2)}%`)}${metric('Profit Factor',fmt(x.profitFactor,2))}</div></div>`}
function renderEvidence(){const e=state.data.evidenceCenter||{},m=e.basketModel||{};$('claimLevel').textContent=e.claimLevel||'—';$('evidenceModel').innerHTML=`<div class="notice">${e.professionalClaimAllowed?'Professional evidence gate passed.':'Pilot/Shadow فقط: لا توجد عينة Professional كافية للادعاء النهائي.'}</div>${evidenceCard('Development',m.development)}${evidenceCard('Validation',m.validation)}${evidenceCard('Test',m.test)}<div class="evidence-card"><h3>Stability</h3><p>${esc(m.stabilityLabelAr||'—')}</p>${(m.stabilityReasonsAr||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')}</div>`;$('evidenceSources').innerHTML=(e.perEngine||[]).map(x=>`<div class="evidence"><b>${esc(x.source)}</b><p>${x.candidates} candidates · A ${x.tierA} · B ${x.tierB} · Research ${x.research}</p></div>`).join('')}

function renderLedger(){const entries=state.data.forwardLedger?.entries||[];$('ledgerCount').textContent=`${entries.length} issued`;$('ledgerBody').innerHTML=entries.map(x=>{const i=x.issued||{},p=i.preferredPlan||{},ev=x.evaluation||{};return`<tr><td>${esc(i.sessionId||'—')}</td><td><b>${esc(i.ticker||'—')}</b></td><td>${esc(tierShort(i.tier))}</td><td>#${fmt(i.rank,0)}</td><td>${fmt(i.decisionScore,1)}</td><td>${finite(p.entryLow)?`${fmt(p.entryLow,4)}–${fmt(p.entryHigh,4)}`:'—'}</td><td>${fmt(p.stopLoss,4)}</td><td>${fmt(p.target1,4)}</td><td>${esc(ev.status||'—')}</td></tr>`}).join('')}

function renderDataHealth(){const h=state.data.dataHealth||{};$('dataHealthBadge').textContent=h.status||'—';$('healthMetrics').innerHTML=[metric('Canonical Universe',fmt(h.canonicalUniverse,0)),metric('Current Session',fmt(h.currentSessionRows,0)),metric('Coverage',`${fmt(h.currentSessionCoveragePct,2)}%`),metric('Verified',fmt(h.verifiedSymbols,0)),metric('History ≥35',fmt(h.history35Plus,0)),metric('52W Full',fmt(h.full52WeekCoverageCount,0)),metric('High Proxy',fmt(h.proxyHighCoverageCount,0)),metric('Avg Confidence',`${fmt(h.averageDataConfidence,1)}%`),metric('Canonical Mismatch',fmt(h.consistencyMismatchCount,0)),metric('Critical Failures',fmt(h.criticalFailureCount,0))].join('');$('dataHealthNote').textContent=h.full52WeekCoverageCount===0?'52-Week label disabled by design until canonical history reaches the minimum. Available-history proxy is explicitly labeled.':'52-week coverage available for a subset of stocks.';$('integrityChecks').innerHTML=(h.integrityChecks||[]).map(x=>`<div class="condition ${x.passed?'pass':'fail'}"><b>${x.passed?'✓':'✕'} ${esc(x.labelAr)}</b><em>${esc(x.id)}</em></div>`).join('');const diag=[];if((h.consistencyMismatches||[]).length)diag.push(...h.consistencyMismatches.map(x=>`${x.ticker} · ${x.field}`));if((h.lowConfidenceTickers||[]).length)diag.push(`Low confidence: ${h.lowConfidenceTickers.join(', ')}`);if(state.data.diagnostics?.zeroSignalWarning)diag.push('Zero-Signal warning active');$('diagnostics').innerHTML=diag.length?diag.map(x=>`<div class="evidence"><p>${esc(x)}</p></div>`).join(''):'<div class="evidence"><b>✓ لا توجد Diagnostics حرجة</b><p>كل بوابات V18.2 الحرجة اجتازت البناء الحالي.</p></div>'}

function exportCsv(){const rows=state.data.universeScreener||[];const headers=['ticker','companyNameAr','sector','close','change1Pct','return20Pct','technicalScore','trendCode','rsi14','volumeRatio20','averageTurnover20Egp','atrPct','support20','resistance20','decisionStatus','decisionScore','evidenceRank'];const csv=[headers.join(',')].concat(rows.map(x=>[x.ticker,x.companyNameAr,x.sector,x.close,x.change1Pct,x.return20Pct,x.technicalScore,x.trendCode,x.rsi14,x.volumeRatio20,x.averageTurnover20Egp,x.atrPct,x.support20,x.resistance20,x.decision?.status||'',x.decision?.score??'',x.decision?.evidenceRank??''].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))).join('\n');downloadText(`EGX_V18_2_Screener_${state.data.sessionId}.csv`,csv,'text/csv;charset=utf-8')}
function renderAll(){renderTop();renderTopFive();renderManifest();renderOpportunityFilters();renderOpportunities();renderScreener();const options=stockOptions();$('stockSelect').innerHTML=options;$('technicalStockSelect').innerHTML=options;state.stockTicker=state.stockTicker||state.data.allCandidates?.[0]?.ticker||state.data.universeScreener?.[0]?.ticker;state.technicalTicker=state.technicalTicker||state.stockTicker;syncStockSelects();renderStockCenter();renderChart();renderLeadership();renderAgreement();renderBasket();renderMorningOptions();renderPortfolioOptions();renderPortfolio();renderMatrix();renderEvidence();renderLedger();renderDataHealth()}

async function load(){try{if(window.__V18_DATA__)state.data=window.__V18_DATA__;else{const r=await fetch(`data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.data=await r.json()}if(state.data.schemaVersion!=='18.2.0-shadow')throw new Error(`Expected V18.2, got ${state.data.schemaVersion}`);renderAll()}catch(err){console.error(err);$('zeroGuard').textContent='تعذر تحميل V18.2';$('zeroGuard').className='truth-state warn';toast('تعذر تحميل V18.2 data') }}

document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
$('tierFilter').addEventListener('change',e=>{state.filters.tier=e.target.value;renderOpportunities()});$('familyFilter').addEventListener('change',e=>{state.filters.family=e.target.value;renderOpportunities()});$('searchInput').addEventListener('input',e=>{state.filters.search=e.target.value;renderOpportunities()});$('multiEngineOnly').addEventListener('change',e=>{state.filters.multi=e.target.checked;renderOpportunities()});
['screenerSearch','trendFilter','decisionFilter','sortFilter'].forEach(id=>$(id).addEventListener(id==='screenerSearch'?'input':'change',renderScreener));
$('stockSelect').addEventListener('change',e=>{state.stockTicker=e.target.value;renderStockCenter()});$('technicalStockSelect').addEventListener('change',e=>{state.technicalTicker=e.target.value;renderChart()});
['capitalInput','riskPctInput','entryInput','stopInput'].forEach(id=>$(id).addEventListener('input',calcRisk));$('morningTicker').addEventListener('change',()=>{const r=candidateByTicker($('morningTicker').value),p=r?.execution?.preferredPlan||{};$('morningOpen').value=p.entryLow||'';renderMorningResult()});$('morningOpen').addEventListener('input',renderMorningResult);$('liquidityConfirm').addEventListener('change',renderMorningResult);
$('addPortfolio').addEventListener('click',addPortfolio);$('clearPortfolio').addEventListener('click',()=>{state.portfolio=[];savePortfolio()});
$('refreshBtn').addEventListener('click',()=>{toast('تحديث V18.2…');load()});$('exportJsonBtn').addEventListener('click',()=>downloadText(`EGX_V18_2_${state.data.sessionId}.json`,JSON.stringify(state.data,null,2),'application/json'));$('exportCsvBtn').addEventListener('click',exportCsv);$('printBtn').addEventListener('click',()=>window.print());
loadPortfolio();load();
