import test from'node:test';
import assert from'node:assert/strict';
import{EgxMarketDataStore}from'../src/market-data-store.js';
import{createCertifiedReconciliationEnvelope,verifyCertifiedReconciliationEnvelope}from'../src/certified-reconciliation-envelope.js';
import{observationBarHash}from'../src/market-observation-certification.js';
import{sha256,canonicalize}from'../src/hash.js';

const session='2026-08-31';
const plan={ticker:'ABUK',session,state:'READY',primary:'OFFICIAL_EGX',crossChecks:['MUBASHER'],providerGroups:{primary:'EGX',crossChecks:['MUBASHER']}};
const primary={ticker:'ABUK',session,sourceId:'OFFICIAL_EGX',sourceClass:'OFFICIAL_EXCHANGE',open:10,high:11,low:9,close:10,volume:1000,capturedAt:'2026-08-31T15:00:00+03:00'};
function entry(o,providerGroup,role,ch){const receiptHash=ch.repeat(64),certificate={certificateKind:'MARKET_OBSERVATION_CERTIFICATE',ticker:o.ticker,session:o.session,sourceId:o.sourceId,sourceClass:o.sourceClass,providerGroup,role,sourceReceiptHash:receiptHash,sourceContentHash:'f'.repeat(64),observationBarHash:observationBarHash(o),parserId:'test-parser',parserVersion:'1',verificationEvidenceHash:'e'.repeat(64),acquisitionPlanHash:sha256(plan)};certificate.certificateHash=sha256(certificate);return{observation:o,runtimeReceipt:{ticker:o.ticker,sourceId:o.sourceId,state:'READY',session:o.session,providerGroup,receiptHash,observationBarHash:certificate.observationBarHash,observationCertificate:certificate,observationCertificateHash:certificate.certificateHash}}}
function entries(){return[entry(primary,'EGX','PRIMARY','a'),entry({...primary,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',close:10.05},'MUBASHER','CROSSCHECK','b')]}
function envelope(){return createCertifiedReconciliationEnvelope({entries:entries(),acquisitionPlan:plan,maxCloseConflictPct:1})}
function insertReconciliation(db,e,sourceManifestHash,{ticker=e.authoritative.ticker}={}){return db.db.prepare(`INSERT INTO certified_reconciliations(reconciliation_manifest_hash,source_manifest_hash,ticker,session,primary_source_id,primary_observation_certificate_hash,payload_json,created_at) VALUES (?,?,?,?,?,?,?,?)`).run(e.sourceManifest.manifestHash,sourceManifestHash,ticker,e.authoritative.session,e.authoritative.sourceId,e.sourceManifest.primaryObservationCertificateHash,canonicalize(e),'2026-08-31T15:02:00Z')}

test('certified reconciliation envelope rebuilds full certificate chain deterministically',()=>{const e=envelope(),v=verifyCertifiedReconciliationEnvelope(e);assert.equal(v.state,'READY');assert.equal(v.sourceManifest.manifestHash,e.sourceManifest.manifestHash);assert.equal(v.authoritative.close,10)});

test('tampered observation is rejected even when attacker recomputes envelope hash',()=>{const e=envelope(),x=JSON.parse(JSON.stringify(e));x.entries[0].observation.close=10.5;delete x.envelopeHash;x.envelopeHash=sha256(x);const v=verifyCertifiedReconciliationEnvelope(x);assert.equal(v.state,'BLOCKED');assert.ok(v.reasons.includes('RECONCILIATION_ENVELOPE_NOT_CERTIFIED_READY'))});

test('direct SQL cannot plant source manifest under a false row hash',()=>{const db=new EgxMarketDataStore();try{const e=envelope();assert.throws(()=>db.db.prepare(`INSERT INTO source_manifests(source_manifest_hash,payload_json,created_at) VALUES (?,?,?)`).run('0'.repeat(64),canonicalize(e.sourceManifest),'2026-08-31T15:01:00Z'),/INVALID_SOURCE_MANIFEST_ROW/)}finally{db.close()}});

test('direct SQL certified reconciliation requires full valid proof and bound columns',()=>{const db=new EgxMarketDataStore();try{const e=envelope(),sourceHash=db.putSourceManifest(e.sourceManifest);insertReconciliation(db,e,sourceHash);const stored=db.db.prepare('SELECT ticker,payload_json FROM certified_reconciliations WHERE reconciliation_manifest_hash=?').get(e.sourceManifest.manifestHash);assert.equal(stored.ticker,'ABUK');assert.equal(JSON.parse(stored.payload_json).envelopeHash,e.envelopeHash);assert.throws(()=>insertReconciliation(db,{...e,sourceManifest:{...e.sourceManifest,manifestHash:'1'.repeat(64)}},sourceHash,{ticker:'ETEL'}),/INVALID_CERTIFIED_RECONCILIATION_ROW/)}finally{db.close()}});

test('direct SQL cannot bind a production current bar that differs from certified authoritative observation',()=>{const db=new EgxMarketDataStore();try{const e=envelope(),sourceHash=db.putSourceManifest(e.sourceManifest);db.startDataSnapshot({dataSnapshotId:'D1',marketSession:session,sourceManifestHash:sourceHash,createdAt:'2026-08-31T15:02:00Z',ingestionMode:'CERTIFIED_PRODUCTION'});insertReconciliation(db,e,sourceHash);const a=e.authoritative,badClose=a.close+0.5,rowHash=sha256({dataSnapshotId:'D1',ticker:a.ticker,session:a.session,open:a.open,high:a.high,low:a.low,close:badClose,volume:a.volume,sourceManifestHash:sourceHash,certifiedReconciliationManifestHash:e.sourceManifest.manifestHash,primaryObservationCertificateHash:e.sourceManifest.primaryObservationCertificateHash});assert.throws(()=>db.db.prepare(`INSERT INTO normalized_bars(data_snapshot_id,ticker,session,open,high,low,close,volume,source_manifest_hash,certified_reconciliation_manifest_hash,primary_observation_certificate_hash,row_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run('D1',a.ticker,a.session,a.open,a.high,a.low,badClose,a.volume,sourceHash,e.sourceManifest.manifestHash,e.sourceManifest.primaryObservationCertificateHash,rowHash),/CERTIFIED_PRODUCTION_CURRENT_BAR_REQUIRES_CERTIFIED_LINEAGE/)}finally{db.close()}});
