import test from'node:test';
import assert from'node:assert/strict';
import{EgxMarketDataStore}from'../src/market-data-store.js';
import{certifiedUniverseFixture}from'./helpers/certified-universe-fixture.mjs';
import{sha256,canonicalize}from'../src/hash.js';
import{issueBaselineAuthorization,fullUniverseReportHash,PHASES}from'../src/phase-transition.js';

const session='2026-08-31';
function registry(ticker='ABUK',companyName='Abu Qir Fertilizers'){const rows=[{ticker,companyName,readiness:'READY',reasons:[],lastSession:session,historyCount:100,sourceStatus:'READY'}];return{version:sha256(rows),total:1,counts:{READY:1},rows}}
function report(registry,universeVersion){const r={state:'PASS',session,calendarVersion:'cal1',universeVersion,registryVersion:registry.version,registry,phase3:{phase:PHASES.DATA,verdict:'PASS',baselineAuthorized:true},coverage:{universeTotal:1,registryTotal:1,withAnyBars:1,missingBars:0,ready:1,readinessCounts:{READY:1}},observationCertificateHashes:['a'.repeat(64)]};r.reportHash=fullUniverseReportHash(r);return r}

test('certified universe enters SSOT only with reproducible authority proof',()=>{const db=new EgxMarketDataStore();try{const{universe}=certifiedUniverseFixture(db);const row=db.db.prepare('SELECT universe_version,as_of_date,authority_proof_hash,payload_json FROM certified_universe_manifests WHERE universe_version=?').get(universe.version);assert.equal(row.universe_version,universe.version);assert.equal(row.as_of_date,session);assert.equal(row.authority_proof_hash,universe.authorityProof.authorityProofHash);assert.equal(row.payload_json,canonicalize(universe))}finally{db.close()}});
test('direct SQL cannot plant fabricated certified universe',()=>{const db=new EgxMarketDataStore();try{const{universe}=certifiedUniverseFixture();const fake={...universe,authorityProof:{...universe.authorityProof,authorityProofHash:'0'.repeat(64)}};assert.throws(()=>db.db.prepare(`INSERT INTO certified_universe_manifests(universe_version,as_of_date,universe_certificate_hash,authority_proof_hash,payload_json,created_at) VALUES (?,?,?,?,?,?)`).run(fake.version,fake.asOfDate,fake.authorityProof.universeExtractionCertificateHash,fake.authorityProof.authorityProofHash,canonicalize(fake),'2026-08-31T15:11:00Z'),/INVALID_CERTIFIED_UNIVERSE/)}finally{db.close()}});
test('baseline registry membership must equal certified universe membership',()=>{const db=new EgxMarketDataStore();try{const{universe}=certifiedUniverseFixture(db),wrong=registry('ETEL','Telecom Egypt');db.putUniverseRegistry(wrong,{marketSession:session,universeVersion:universe.version});const r=report(wrong,universe.version),a=issueBaselineAuthorization(r);assert.equal(a.state,'GRANTED');assert.throws(()=>db.putBaselineAuthorization({authorization:a,fullUniverseReport:r}),/BASELINE_REGISTRY_UNIVERSE_MISMATCH/)}finally{db.close()}});
test('certified universe SSOT is append only',()=>{const db=new EgxMarketDataStore();try{const{universe}=certifiedUniverseFixture(db);assert.throws(()=>db.db.prepare('UPDATE certified_universe_manifests SET as_of_date=? WHERE universe_version=?').run('2026-08-30',universe.version),/IMMUTABLE_CERTIFIED_UNIVERSE/);assert.throws(()=>db.db.prepare('DELETE FROM certified_universe_manifests WHERE universe_version=?').run(universe.version),/IMMUTABLE_CERTIFIED_UNIVERSE/)}finally{db.close()}});
