import test from'node:test';import assert from'node:assert/strict';import{sha256}from'../src/hash.js';import{adaptEgxNewsRecord,adaptEgxListedSnapshot,classifyEgxSecurity}from'../src/egx-official-adapter.js';import{admitOfficialArtifact,bindExtractionManifest}from'../src/official-artifact-admission.js';import{validateSchemaAttestation}from'../src/schema-attestation.js';
const equity={isin:'EGS74801C019',reutersCode:'VERT.CA',publishedAt:'2026-08-31T15:09:00+03:00',title:'Vertika for Industry & Trade (VERT.CA) - Disclosure (SMEs Market)',sourceUrl:'https://beta.egx.com.eg/en'};const bond={isin:'EGB69761S223',reutersCode:'BOND=CA'};const bytes=Buffer.from('%PDF-1.4\nEGX VERIFIED SNAPSHOT TEST\n');const sourceHash=sha256(bytes);const sourceUrl='https://egx.com.eg/downloads/Bulletins/example.pdf';const sourceReceipt={sourceId:'EGX_BULLETIN',sourceClass:'OFFICIAL_EXCHANGE',providerGroup:'EGX',sourceUrl,session:'2026-08-31',capturedAt:'2026-08-31T15:10:00+03:00',provenanceKind:'OFFICIAL_DIRECT_FILE',contentHash:sourceHash};const artifact={artifactKind:'DAILY_BULLETIN_PDF',mimeType:'application/pdf',sourceUrl,session:'2026-08-31',byteLength:bytes.length,contentHash:sourceHash};
function chain(rows){const admission=admitOfficialArtifact({artifact,rawBytes:bytes,sourceReceipt});const extraction=bindExtractionManifest(admission,{extractorId:'egx-bulletin-parser',extractorVersion:'0.1.0',schemaId:'EGX_VERIFIED_SCHEMA_TEST_V1',rowCount:rows.length,extractedOutput:rows,sourceAdmissionHash:admission.admissionHash});const schemaResult=validateSchemaAttestation({admission,extraction,extractedOutput:rows,attestation:{state:'VERIFIED',sourceAdmissionHash:admission.admissionHash,extractionManifestHash:extraction.manifest.manifestHash,schemaId:extraction.manifest.schemaId,schemaDefinitionHash:'d'.repeat(64),verificationEvidenceHash:'e'.repeat(64),semanticFields:['ISIN','SECURITY_CODE','ASSET_CLASS','LISTING_STATUS']},requiredSemanticFields:['ISIN','SECURITY_CODE','ASSET_CLASS','LISTING_STATUS']});const scopeAttestation={state:'VERIFIED',scope:'ALL_LISTED_EQUITIES',declaredTotal:rows.filter(x=>classifyEgxSecurity(x)==='EQUITY').length,evidenceLocator:'document-header:all-listed-equities',sourceAdmissionHash:admission.admissionHash,extractionManifestHash:extraction.manifest.manifestHash,schemaAttestationHash:schemaResult.attestation.attestationHash,scopeDefinitionHash:'1'.repeat(64),verificationEvidenceHash:'2'.repeat(64)};return{extraction,schemaAttestation:schemaResult.attestation,scopeAttestation}}
function meta(rows,extra={}){const c=chain(rows);return{evidenceType:'OFFICIAL_DAILY_BULLETIN',exhaustive:true,asOfDate:'2026-08-31',declaredTotal:rows.filter(x=>classifyEgxSecurity(x)==='EQUITY').length,artifact,rawBytes:bytes,sourceReceipt,extraction:c.extraction,schemaAttestation:c.schemaAttestation,scopeAttestation:c.scopeAttestation,...extra}}
test('official EGX equity news becomes identity evidence only',()=>{const r=adaptEgxNewsRecord(equity);assert.equal(r.state,'READY');assert.equal(r.evidence.evidenceType,'OFFICIAL_DISCLOSURE')});
test('EGX bond rows are excluded from equity evidence',()=>assert.equal(adaptEgxNewsRecord({isin:'EGB69761S223',reutersCode:'BOND=CA',sourceUrl}).state,'IGNORED_NON_EQUITY'));
test('snapshot must be explicitly exhaustive',()=>assert.equal(adaptEgxListedSnapshot([equity],{...meta([equity]),exhaustive:false}).state,'UNIVERSE_INCOMPLETE'));
test('old manual scopeProof shortcut no longer authorizes universe',()=>{const m=meta([equity]);delete m.scopeAttestation;m.scopeProof={state:'VERIFIED',scope:'ALL_LISTED_EQUITIES',evidenceLocator:'manual'};const r=adaptEgxListedSnapshot([equity],m);assert.equal(r.state,'UNIVERSE_INCOMPLETE');assert.ok(r.reasons.includes('MISSING_SCOPE_ATTESTATION'))});
test('full byte extraction schema scope certification chain admits mixed artifact equity subset',()=>{const rows=[equity,bond],r=adaptEgxListedSnapshot(rows,meta(rows));assert.equal(r.state,'READY');assert.equal(r.evidence.length,1);assert.equal(r.ignored.length,1);assert.ok(r.evidence[0].universeCertificateHash);assert.equal(r.manifest.universeCertificateHash,r.evidence[0].universeCertificateHash);assert.ok(r.manifest.scopeAttestationHash)});
test('declared equity total mismatch is a data conflict',()=>{const r=adaptEgxListedSnapshot([equity],meta([equity],{declaredTotal:2}));assert.equal(r.state,'DATA_CONFLICT')});
test('rows changed after extraction are blocked',()=>{const m=meta([equity]),changed=[{...equity,reutersCode:'FAKE.CA'}],r=adaptEgxListedSnapshot(changed,m);assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('SCHEMA_NOT_ATTESTED'))});
test('scope attestation cannot detach from schema chain',()=>{const m=meta([equity]);m.scopeAttestation={...m.scopeAttestation,schemaAttestationHash:'f'.repeat(64)};const r=adaptEgxListedSnapshot([equity],m);assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('SCOPE_SCHEMA_HASH_MISMATCH'))});
test('scope declared total cannot disagree with adapter metadata',()=>{const m=meta([equity]);m.declaredTotal=2;const r=adaptEgxListedSnapshot([equity],m);assert.equal(r.state,'DATA_CONFLICT');assert.ok(r.reasons.some(x=>x.startsWith('SCOPE_META_DECLARED_TOTAL_MISMATCH:')))});
