import test from'node:test';import assert from'node:assert/strict';import{sha256}from'../src/hash.js';import{adaptEgxNewsRecord,adaptEgxListedSnapshot,classifyEgxSecurity}from'../src/egx-official-adapter.js';import{admitOfficialArtifact,bindExtractionManifest}from'../src/official-artifact-admission.js';import{validateSchemaAttestation}from'../src/schema-attestation.js';
const equity={isin:'EGS74801C019',reutersCode:'VERT.CA',publishedAt:'2026-08-31T15:09:00+03:00',title:'Vertika for Industry & Trade (VERT.CA) - Disclosure (SMEs Market)',sourceUrl:'https://beta.egx.com.eg/en'};const bond={isin:'EGB69761S223',reutersCode:'BOND=CA'};const bytes=Buffer.from('%PDF-1.4\nEGX VERIFIED SNAPSHOT TEST\n');const sourceHash=sha256(bytes);const sourceUrl='https://egx.com.eg/downloads/Bulletins/example.pdf';const sourceReceipt={sourceId:'EGX_BULLETIN',sourceClass:'OFFICIAL_EXCHANGE',providerGroup:'EGX',sourceUrl,session:'2026-08-31',capturedAt:'2026-08-31T15:10:00+03:00',provenanceKind:'OFFICIAL_DIRECT_FILE',contentHash:sourceHash};const artifact={artifactKind:'DAILY_BULLETIN_PDF',mimeType:'application/pdf',sourceUrl,session:'2026-08-31',byteLength:bytes.length,contentHash:sourceHash};
function chain(rows){const admission=admitOfficialArtifact({artifact,rawBytes:bytes,sourceReceipt});const extraction=bindExtractionManifest(admission,{extractorId:'egx-bulletin-parser',extractorVersion:'0.1.0',schemaId:'EGX_VERIFIED_SCHEMA_TEST_V1',rowCount:rows.length,extractedOutput:rows,sourceAdmissionHash:admission.admissionHash});const schemaResult=validateSchemaAttestation({admission,extraction,extractedOutput:rows,attestation:{state:'VERIFIED',sourceAdmissionHash:admission.admissionHash,extractionManifestHash:extraction.manifest.manifestHash,schemaId:extraction.manifest.schemaId,schemaDefinitionHash:'d'.repeat(64),verificationEvidenceHash:'e'.repeat(64),semanticFields:['ISIN','SECURITY_CODE','ASSET_CLASS','LISTING_STATUS']},requiredSemanticFields:['ISIN','SECURITY_CODE','ASSET_CLASS','LISTING_STATUS']});const scopeProof={state:'VERIFIED',kind:'OFFICIAL_DOCUMENT_SCOPE',scope:'ALL_LISTED_EQUITIES',evidenceLocator:'document-header:all-listed-equities',sourceAdmissionHash:admission.admissionHash,extractionManifestHash:extraction.manifest.manifestHash,schemaAttestationHash:schemaResult.attestation.attestationHash};return{admission,extraction,schemaAttestation:schemaResult.attestation,scopeProof}}
function meta(rows,extra={}){const c=chain(rows);return{evidenceType:'OFFICIAL_DAILY_BULLETIN',exhaustive:true,asOfDate:'2026-08-31',declaredTotal:rows.filter(x=>classifyEgxSecurity(x)==='EQUITY').length,artifact,rawBytes:bytes,sourceReceipt,extraction:c.extraction,schemaAttestation:c.schemaAttestation,scopeProof:c.scopeProof,...extra}}
test('official EGX equity news becomes identity evidence only',()=>{const r=adaptEgxNewsRecord(equity);assert.equal(r.state,'READY');assert.equal(r.evidence.evidenceType,'OFFICIAL_DISCLOSURE');assert.equal(r.evidence.segment,'SME')});
test('EGX bond rows are excluded from equity evidence',()=>{const r=adaptEgxNewsRecord({isin:'EGB69761S223',reutersCode:'EGBGLSC2P2CCV',sourceUrl:'https://beta.egx.com.eg/en'});assert.equal(r.state,'IGNORED_NON_EQUITY');assert.equal(r.assetClass,'BOND')});
test('asset classifier distinguishes EGS equity and EGB bond',()=>{assert.equal(classifyEgxSecurity(equity),'EQUITY');assert.equal(classifyEgxSecurity({isin:'EGB123'}),'BOND')});
test('snapshot must be explicitly exhaustive to authorize universe input',()=>{const r=adaptEgxListedSnapshot([equity],{...meta([equity]),exhaustive:false});assert.equal(r.state,'UNIVERSE_INCOMPLETE')});
test('exhaustive flag without source receipt is blocked',()=>{const m=meta([equity]);delete m.sourceReceipt;const r=adaptEgxListedSnapshot([equity],m);assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('MISSING_OFFICIAL_ARTIFACT_CHAIN'))});
test('exhaustive source without document scope proof remains incomplete',()=>{const m=meta([equity]);delete m.scopeProof;const r=adaptEgxListedSnapshot([equity],m);assert.equal(r.state,'UNIVERSE_INCOMPLETE');assert.ok(r.reasons.includes('NO_EXHAUSTIVE_SCOPE_PROOF'))});
test('verified byte extraction schema and scope chain admits exhaustive snapshot',()=>{const rows=[equity,bond],r=adaptEgxListedSnapshot(rows,meta(rows));assert.equal(r.state,'READY');assert.equal(r.evidence.length,1);assert.equal(r.ignored.length,1);assert.ok(r.evidence[0].sourceReceiptHash);assert.ok(r.evidence[0].scopeProofHash);assert.ok(r.manifest.artifactAdmissionHash);assert.ok(r.manifest.extractionManifestHash);assert.ok(r.manifest.schemaAttestationHash);assert.ok(r.manifest.manifestHash)});
test('declared equity total mismatch is a data conflict',()=>{const r=adaptEgxListedSnapshot([equity],meta([equity],{declaredTotal:2}));assert.equal(r.state,'DATA_CONFLICT');assert.ok(r.reasons[0].startsWith('DECLARED_EQUITY_TOTAL_MISMATCH:'))});
test('rows changed after extraction are blocked before universe admission',()=>{const original=[equity],m=meta(original);const changed=[{...equity,reutersCode:'FAKE.CA'}];const r=adaptEgxListedSnapshot(changed,m);assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('SCHEMA_NOT_ATTESTED'));assert.ok(r.reasons.includes('EXTRACTION_OUTPUT_HASH_MISMATCH'))});
test('scope proof must bind same artifact extraction and schema attestation',()=>{const m=meta([equity]);m.scopeProof={...m.scopeProof,extractionManifestHash:'f'.repeat(64)};const r=adaptEgxListedSnapshot([equity],m);assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('SCOPE_EXTRACTION_HASH_MISMATCH'))});
