import test from'node:test';import assert from'node:assert/strict';import{sha256}from'../src/hash.js';import{runFullUniverseReadiness}from'../src/full-universe-readiness.js';import{observationBarHash}from'../src/market-observation-certification.js';
const universe={state:'READY',asOfDate:'2026-08-31',version:'U1',total:2,rows:[{ticker:'ABUK',companyName:'A'},{ticker:'COMI',companyName:'C'}]};const series=n=>Array.from({length:n},(_,i)=>{const d=new Date(Date.UTC(2026,0,1+i));return{session:d.toISOString().slice(0,10),open:10,high:11,low:9,close:10,volume:100000}}).map((r,i,a)=>i===a.length-1?{...r,session:'2026-08-31'}:r);const baseSeries=series(100),dates=[...new Set(baseSeries.map(x=>x.session))].sort(),exchangeCalendar={version:'CAL1',sessions:dates.map(session=>({session,closeAt:`${session}T14:30:00+03:00`}))},sessionAuthority={state:'READY',currentSession:'2026-08-31',calendarVersion:'CAL1'};const plan=ticker=>({ticker,session:'2026-08-31',state:'READY',primary:'OFFICIAL_EGX',crossChecks:['MUBASHER'],providerGroups:{primary:'EGX',crossChecks:['MUBASHER']}}),plans=[plan('ABUK'),plan('COMI')];
function rec(ticker,sourceId,providerGroup,hashChar,role,bar){const receiptHash=hashChar.repeat(64),barHash=observationBarHash({ticker,...bar}),certificate={certificateKind:'MARKET_OBSERVATION_CERTIFICATE',ticker,session:'2026-08-31',sourceId,sourceClass:sourceId==='OFFICIAL_EGX'?'OFFICIAL_EXCHANGE':'PUBLIC_MARKET',providerGroup,role,sourceReceiptHash:receiptHash,sourceContentHash:'f'.repeat(64),observationBarHash:barHash,parserId:'test',parserVersion:'1',verificationEvidenceHash:'e'.repeat(64),acquisitionPlanHash:sha256(plan(ticker))};certificate.certificateHash=sha256(certificate);return{ticker,sourceId,state:'READY',session:'2026-08-31',providerGroup,receiptHash,observationBarHash:barHash,observationCertificate:certificate,observationCertificateHash:certificate.certificateHash}}
function receiptsFor(barsByTicker){const out=[];for(const [ticker,bars] of Object.entries(barsByTicker)){if(!bars.length)continue;const bar=bars[bars.length-1];out.push(rec(ticker,'OFFICIAL_EGX','EGX',ticker==='ABUK'?'a':'c','PRIMARY',bar),rec(ticker,'MUBASHER','MUBASHER',ticker==='ABUK'?'b':'d','CROSSCHECK',bar))}return out}
const allBars={ABUK:series(100),COMI:series(100)},receipts=receiptsFor(allBars);
test('full universe runner passes only when registry latest bars are bound to primary observation certificates',()=>{const r=runFullUniverseReadiness({universe,sessionAuthority,exchangeCalendar,barsByTicker:allBars,acquisitionPlans:plans,sourceReceipts:receipts});assert.equal(r.state,'PASS');assert.equal(r.phase3.baselineAuthorized,true);assert.equal(r.observationCertificateHashes.length,4)});
test('changed bar after certificate creation is structural failure',()=>{const changed={...allBars,ABUK:allBars.ABUK.map((x,i,a)=>i===a.length-1?{...x,close:10.5,high:11.5}:x)};const r=runFullUniverseReadiness({universe,sessionAuthority,exchangeCalendar,barsByTicker:changed,acquisitionPlans:plans,sourceReceipts:receipts});assert.equal(r.state,'FAIL');assert.ok(r.structuralBlockers.some(x=>x.startsWith('PRIMARY_BAR_CERTIFICATE:ABUK:')))});
test('missing member bars are visible and block phase 3',()=>{const bars={ABUK:series(100)};const r=runFullUniverseReadiness({universe,sessionAuthority,exchangeCalendar,barsByTicker:bars,acquisitionPlans:plans,sourceReceipts:receiptsFor(bars)});assert.equal(r.state,'FAIL')});
test('data outside universe is structural contamination',()=>{const fake={...allBars,FAKE:series(100)};const r=runFullUniverseReadiness({universe,sessionAuthority,exchangeCalendar,barsByTicker:fake,acquisitionPlans:plans,sourceReceipts:receipts});assert.ok(r.structuralBlockers.some(x=>x.startsWith('DATA_OUTSIDE_UNIVERSE:')))});
test('insufficient history remains explicit exclusion with certified current bar',()=>{const bars={ABUK:series(100),COMI:series(50)},r=runFullUniverseReadiness({universe,sessionAuthority,exchangeCalendar,barsByTicker:bars,acquisitionPlans:plans,sourceReceipts:receiptsFor(bars)});assert.equal(r.registry.counts.INSUFFICIENT_HISTORY,1);assert.equal(r.state,'PASS')});
test('missing runtime certificates fail before registry authorization',()=>{const r=runFullUniverseReadiness({universe,sessionAuthority,exchangeCalendar,barsByTicker:allBars,acquisitionPlans:plans,sourceReceipts:[]});assert.equal(r.state,'FAIL');assert.ok(r.structuralBlockers.includes('PRIMARY_OBSERVATION_RECEIPT_MISSING:ABUK'))});
test('missing exchange calendar fails structurally',()=>assert.equal(runFullUniverseReadiness({universe,sessionAuthority,barsByTicker:allBars,acquisitionPlans:plans,sourceReceipts:receipts}).state,'FAIL'));
test('calendar version mismatch fails structurally',()=>{const r=runFullUniverseReadiness({universe,sessionAuthority:{...sessionAuthority,calendarVersion:'OTHER'},exchangeCalendar,barsByTicker:allBars,acquisitionPlans:plans,sourceReceipts:receipts});assert.ok(r.structuralBlockers.some(x=>x.startsWith('CALENDAR_VERSION_MISMATCH:')))});
