import test from'node:test';import assert from'node:assert/strict';import{runFullUniverseReadiness}from'../src/full-universe-readiness.js';
const universe={state:'READY',asOfDate:'2026-08-31',version:'U1',total:2,rows:[{ticker:'ABUK',companyName:'A'},{ticker:'COMI',companyName:'C'}]};
const sessionAuthority={state:'READY',currentSession:'2026-08-31'};
const series=n=>Array.from({length:n},(_,i)=>{const d=new Date(Date.UTC(2026,0,1+i));return{session:d.toISOString().slice(0,10),open:10,high:11,low:9,close:10,volume:100000}}).map((r,i,a)=>i===a.length-1?{...r,session:'2026-08-31'}:r);
const plans=[{ticker:'ABUK',state:'READY'},{ticker:'COMI',state:'READY'}];
test('full universe runner passes when every member is current and eligible',()=>{const r=runFullUniverseReadiness({universe,sessionAuthority,barsByTicker:{ABUK:series(100),COMI:series(100)},acquisitionPlans:plans});assert.equal(r.state,'PASS');assert.equal(r.phase3.baselineAuthorized,true);assert.equal(r.coverage.ready,2);assert.ok(r.reportHash)});
test('missing member bars are visible as SOURCE_UNAVAILABLE and block phase 3',()=>{const r=runFullUniverseReadiness({universe,sessionAuthority,barsByTicker:{ABUK:series(100)},acquisitionPlans:plans});assert.equal(r.state,'FAIL');assert.equal(r.coverage.missingBars,1);assert.equal(r.registry.counts.SOURCE_UNAVAILABLE,1)});
test('data for ticker outside authoritative universe is structural contamination',()=>{const r=runFullUniverseReadiness({universe,sessionAuthority,barsByTicker:{ABUK:series(100),COMI:series(100),FAKE:series(100)},acquisitionPlans:plans});assert.equal(r.state,'FAIL');assert.ok(r.structuralBlockers[0].startsWith('DATA_OUTSIDE_UNIVERSE:'))});
test('insufficient history is explicit exclusion not fabricated readiness',()=>{const r=runFullUniverseReadiness({universe,sessionAuthority,barsByTicker:{ABUK:series(100),COMI:series(50)},acquisitionPlans:plans});assert.equal(r.registry.counts.INSUFFICIENT_HISTORY,1);assert.ok(r.phase3.warnings.includes('COMI:INSUFFICIENT_HISTORY'));assert.equal(r.state,'PASS')});
