import test from'node:test';
import assert from'node:assert/strict';
import{issueBaselineAuthorization,assertBaselineAuthorization,fullUniverseReportHash,verifyFullUniverseReport,PHASES}from'../src/phase-transition.js';
function passingReport(overrides={}){const report={state:'PASS',session:'2026-08-31',calendarVersion:'CAL1',universeVersion:'U1',registryVersion:'R1',phase3:{phase:PHASES.DATA,verdict:'PASS',baselineAuthorized:true},coverage:{universeTotal:1,registryTotal:1,withAnyBars:1,missingBars:0,ready:1,readinessCounts:{READY:1}},observationCertificateHashes:['a'.repeat(64)],...overrides};report.reportHash=fullUniverseReportHash(report);return report}

test('baseline authorization is denied unless full Phase 3 report passes',()=>{const pass=passingReport(),bad={...pass,state:'FAIL',phase3:{...pass.phase3,verdict:'FAIL',baselineAuthorized:false}};bad.reportHash=fullUniverseReportHash(bad);const r=issueBaselineAuthorization(bad);assert.equal(r.state,'DENIED');assert.equal(r.authorizationToken,null)});
test('passing immutable Phase 3 report issues deterministic baseline authorization',()=>{const pass=passingReport(),a=issueBaselineAuthorization(pass),b=issueBaselineAuthorization({...pass});assert.equal(a.state,'GRANTED');assert.equal(a.authorizationToken,b.authorizationToken);assert.equal(assertBaselineAuthorization(a,pass),true)});
test('fabricated passing report hash is rejected',()=>{const pass=passingReport();pass.reportHash='b'.repeat(64);const v=verifyFullUniverseReport(pass);assert.equal(v.valid,false);assert.ok(v.reasons.includes('SOURCE_REPORT_HASH_MISMATCH'));assert.equal(issueBaselineAuthorization(pass).state,'DENIED')});
test('authorization cannot be replayed against a different report hash',()=>{const pass=passingReport(),a=issueBaselineAuthorization(pass),other=passingReport({registryVersion:'R2'});assert.throws(()=>assertBaselineAuthorization(a,other),/REPORT_MISMATCH/)});
test('report content tampering is detected even when claimed report hash is retained',()=>{const pass=passingReport(),a=issueBaselineAuthorization(pass),tampered={...pass,coverage:{...pass.coverage,ready:0}};assert.throws(()=>assertBaselineAuthorization(a,tampered),/SOURCE_REPORT_INVALID/)});
test('tampered authorization token fails closed',()=>{const pass=passingReport(),a=issueBaselineAuthorization(pass);assert.throws(()=>assertBaselineAuthorization({...a,authorizationToken:'c'.repeat(64)},pass),/TAMPERED/)});
