import test from'node:test';import assert from'node:assert/strict';import{sha256}from'../src/hash.js';import{evaluatePhase3Gate}from'../src/phase3-gate.js';
const universe={state:'READY',asOfDate:'2026-08-31',total:2,rows:[{ticker:'ABUK'},{ticker:'COMI'}]},registry={total:2,counts:{READY:2},rows:[{ticker:'ABUK',readiness:'READY'},{ticker:'COMI',readiness:'READY'}]},sessionAuthority={state:'READY',currentSession:'2026-08-31'};const plan=ticker=>({ticker,session:'2026-08-31',state:'READY',primary:'OFFICIAL_EGX',crossChecks:['MUBASHER'],providerGroups:{primary:'EGX',crossChecks:['MUBASHER']}}),plans=[plan('ABUK'),plan('COMI')];
function rec(ticker,sourceId,providerGroup,hashChar,role){const receiptHash=hashChar.repeat(64),observationBarHash=(hashChar==='a'||hashChar==='c'?'1':'2').repeat(64),certificate={certificateKind:'MARKET_OBSERVATION_CERTIFICATE',ticker,session:'2026-08-31',sourceId,sourceClass:sourceId==='OFFICIAL_EGX'?'OFFICIAL_EXCHANGE':'PUBLIC_MARKET',providerGroup,role,sourceReceiptHash:receiptHash,sourceContentHash:'f'.repeat(64),observationBarHash,parserId:'test',parserVersion:'1',verificationEvidenceHash:'e'.repeat(64),acquisitionPlanHash:sha256(plan(ticker))};certificate.certificateHash=sha256(certificate);return{ticker,sourceId,state:'READY',session:'2026-08-31',providerGroup,receiptHash,observationBarHash,observationCertificate:certificate,observationCertificateHash:certificate.certificateHash}}
const receipts=[rec('ABUK','OFFICIAL_EGX','EGX','a','PRIMARY'),rec('ABUK','MUBASHER','MUBASHER','b','CROSSCHECK'),rec('COMI','OFFICIAL_EGX','EGX','c','PRIMARY'),rec('COMI','MUBASHER','MUBASHER','d','CROSSCHECK')];
test('phase 3 passes only when certified universe session registry acquisition and observations agree',()=>{const r=evaluatePhase3Gate({universe,registry,sessionAuthority,acquisitionPlans:plans,sourceReceipts:receipts});assert.equal(r.verdict,'PASS');assert.equal(r.baselineAuthorized,true)});
test('universe incompleteness prevents baseline',()=>assert.equal(evaluatePhase3Gate({universe:{...universe,state:'UNIVERSE_INCOMPLETE'},registry,sessionAuthority,acquisitionPlans:plans,sourceReceipts:receipts}).baselineAuthorized,false));
test('stale state blocks phase 3',()=>assert.equal(evaluatePhase3Gate({universe,registry:{...registry,counts:{READY:1,STALE:1},rows:[registry.rows[0],{ticker:'COMI',readiness:'STALE'}]},sessionAuthority,acquisitionPlans:plans,sourceReceipts:receipts}).verdict,'FAIL'));
test('explicit illiquidity is warning not data-integrity blocker',()=>{const r=evaluatePhase3Gate({universe,registry:{...registry,counts:{READY:1,ILLIQUID:1},rows:[registry.rows[0],{ticker:'COMI',readiness:'ILLIQUID'}]},sessionAuthority,acquisitionPlans:plans,sourceReceipts:receipts});assert.equal(r.verdict,'PASS');assert.ok(r.warnings.includes('COMI:ILLIQUID'))});
test('missing acquisition plan blocks symbol',()=>assert.equal(evaluatePhase3Gate({universe,registry,sessionAuthority,acquisitionPlans:[plans[0]],sourceReceipts:receipts}).verdict,'FAIL'));
test('missing primary receipt blocks baseline',()=>{const r=evaluatePhase3Gate({universe,registry,sessionAuthority,acquisitionPlans:plans,sourceReceipts:receipts.filter(x=>!(x.ticker==='COMI'&&x.sourceId==='OFFICIAL_EGX'))});assert.ok(r.blockers.includes('COMI:PRIMARY_SOURCE_RECEIPT:MISSING'))});
test('receipt without observation certificate is rejected',()=>{const bad=receipts.map(x=>x.ticker==='ABUK'&&x.sourceId==='OFFICIAL_EGX'?{...x,observationCertificate:null}:x);const r=evaluatePhase3Gate({universe,registry,sessionAuthority,acquisitionPlans:plans,sourceReceipts:bad});assert.ok(r.blockers.includes('ABUK:PRIMARY_SOURCE_RECEIPT:READY'))});
test('certificate from different acquisition plan is rejected',()=>{const bad=receipts.map(x=>x.ticker==='ABUK'&&x.sourceId==='OFFICIAL_EGX'?{...x,observationCertificate:{...x.observationCertificate,acquisitionPlanHash:'0'.repeat(64)}}:x);const r=evaluatePhase3Gate({universe,registry,sessionAuthority,acquisitionPlans:plans,sourceReceipts:bad});assert.ok(r.blockers.includes('ABUK:PRIMARY_SOURCE_RECEIPT:READY'))});
test('same-provider runtime cross-check is rejected',()=>{const bad=receipts.map(x=>x.ticker==='COMI'&&x.sourceId==='MUBASHER'?{...x,providerGroup:'EGX'}:x);const r=evaluatePhase3Gate({universe,registry,sessionAuthority,acquisitionPlans:plans,sourceReceipts:bad});assert.ok(r.blockers.includes('COMI:INDEPENDENT_CROSSCHECK_RECEIPT:MISSING'))});
