import test from'node:test';
import assert from'node:assert/strict';
import{EgxMarketDataStore}from'../src/market-data-store.js';
import{createSessionManifest}from'../src/session-manifest.js';
import{reconcileCertifiedObservations}from'../src/reconciliation.js';
import{observationBarHash}from'../src/market-observation-certification.js';
import{sha256}from'../src/hash.js';

const session='2026-08-31';
const plan={ticker:'ABUK',session,state:'READY',primary:'OFFICIAL_EGX',crossChecks:['MUBASHER'],providerGroups:{primary:'EGX',crossChecks:['MUBASHER']}};
const primary={ticker:'ABUK',session,sourceId:'OFFICIAL_EGX',sourceClass:'OFFICIAL_EXCHANGE',open:10,high:11,low:9,close:10,volume:1000,capturedAt:'2026-08-31T15:00:00+03:00'};
function entry(o,providerGroup,role,ch){const receiptHash=ch.repeat(64),certificate={certificateKind:'MARKET_OBSERVATION_CERTIFICATE',ticker:o.ticker,session:o.session,sourceId:o.sourceId,sourceClass:o.sourceClass,providerGroup,role,sourceReceiptHash:receiptHash,sourceContentHash:'f'.repeat(64),observationBarHash:observationBarHash(o),parserId:'test-parser',parserVersion:'1',verificationEvidenceHash:'e'.repeat(64),acquisitionPlanHash:sha256(plan)};certificate.certificateHash=sha256(certificate);return{observation:o,runtimeReceipt:{ticker:o.ticker,sourceId:o.sourceId,state:'READY',session:o.session,providerGroup,receiptHash,observationBarHash:certificate.observationBarHash,observationCertificate:certificate,observationCertificateHash:certificate.certificateHash}}}
function productionEntries(){return[entry(primary,'EGX','PRIMARY','a'),entry({...primary,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',close:10.05},'MUBASHER','CROSSCHECK','b')]}
function raw(db,id='A1'){db.startAcquisition({acquisitionId:id,expectedSession:session,startedAt:'2026-08-31T14:30:00Z'});db.putRawBar({acquisitionId:id,ticker:'ABUK',session,sourceId:'OFFICIAL_EGX',payload:{open:10,high:11,low:9,close:10,volume:1000}});return db.finalizeAcquisition(id)}
function baseManifest({rawDataVersion,normalizedDataVersion,sourceManifest,authorityMode}){return createSessionManifest({marketSession:session,authorityMode,exchangeCalendarVersion:'cal1',universeVersion:'u1',rawDataVersion,normalizedDataVersion,sourceManifest,corporateActionVersion:'ca1',fundamentalsCutoff:'2026-08-31T12:00:00Z',featureVersion:'f0',modelVersion:'baseline0',engineVersion:'0.6.0',configVersion:'cfg1',commitHash:'TEST',generatedAt:'2026-08-31T15:10:00Z'})}
function productionSession(db){const es=productionEntries(),rec=reconcileCertifiedObservations(es,{acquisitionPlan:plan}),rawDataVersion=raw(db,'AP');assert.equal(rec.status,'READY');const sourceManifest=db.putSourceManifest(rec.sourceManifest);db.startDataSnapshot({dataSnapshotId:'DP',marketSession:session,sourceManifestHash:sourceManifest,createdAt:'2026-08-31T15:02:00Z',ingestionMode:'CERTIFIED_PRODUCTION'});db.putCertifiedNormalizedBar({dataSnapshotId:'DP',entries:es,acquisitionPlan:plan});const normalizedDataVersion=db.finalizeDataSnapshot('DP'),manifest=baseManifest({rawDataVersion,normalizedDataVersion,sourceManifest,authorityMode:'CERTIFIED_PRODUCTION'});db.putSessionManifest(manifest);return manifest}
function researchSession(db){const rawDataVersion=raw(db,'AR'),sourceManifest=db.putSourceManifest({mode:'RESEARCH',session,source:'fixture'});db.startDataSnapshot({dataSnapshotId:'DR',marketSession:session,sourceManifestHash:sourceManifest,createdAt:'2026-08-31T15:02:00Z'});db.putNormalizedBar({dataSnapshotId:'DR',ticker:'ABUK',session,open:10,high:11,low:9,close:10,volume:1000,sourceManifestHash:sourceManifest});const normalizedDataVersion=db.finalizeDataSnapshot('DR'),manifest=baseManifest({rawDataVersion,normalizedDataVersion,sourceManifest,authorityMode:'RESEARCH'});db.putSessionManifest(manifest);return manifest}
function rec(snapshotHash,id='R1'){return{recommendationId:id,ticker:'ABUK',companyName:'Abu Qir Fertilizers',signalSession:session,createdAt:'2026-08-31T15:11:00Z',snapshotId:'SNAP-1',snapshotHash,engineVersion:'0.6.0',featureVersion:'f0',modelVersion:'baseline0',configVersion:'cfg1',configHash:'cfghash',commitHash:'TEST',decision:'WATCH',finalRankScore:55,confidence:'UNRATED',entryLow:null,entryHigh:null,entryCondition:'TRIGGER_REQUIRED',entryExpiry:null,stop:null,target1:null,target2:null,expectedHoldingWindow:'UNKNOWN',maximumHoldingSessions:5,grossRiskReward:null,netRiskReward:null,transactionCostAssumption:0.006,slippageAssumption:0.001,liquidityStatus:'UNKNOWN',dataQuality:'READY',marketRegime:'UNKNOWN',whySelected:'Potential setup',whyNotBuyNow:'Trigger not confirmed',riskFactors:[],invalidationConditions:[],evidenceType:'LIVE',status:'OPEN'}}

test('production recommendation is admitted only from certified production Session Manifest',()=>{const db=new EgxMarketDataStore();try{const m=productionSession(db);db.appendRecommendation(rec(m.snapshotHash));const row=db.db.prepare("SELECT authority_mode,snapshot_hash FROM recommendation_ledger WHERE recommendation_id='R1'").get();assert.equal(row.authority_mode,'CERTIFIED_PRODUCTION');assert.equal(row.snapshot_hash,m.snapshotHash)}finally{db.close()}});
test('production append cannot consume research Session Manifest',()=>{const db=new EgxMarketDataStore();try{const m=researchSession(db);assert.throws(()=>db.appendRecommendation(rec(m.snapshotHash)),/RECOMMENDATION_AUTHORITY_MODE_MISMATCH/)}finally{db.close()}});
test('research append cannot consume certified production Session Manifest',()=>{const db=new EgxMarketDataStore();try{const m=productionSession(db);assert.throws(()=>db.appendResearchRecommendation(rec(m.snapshotHash)),/RECOMMENDATION_AUTHORITY_MODE_MISMATCH/)}finally{db.close()}});
test('SQL direct insert cannot relabel research recommendation as production',()=>{const db=new EgxMarketDataStore();try{const m=researchSession(db),r=rec(m.snapshotHash);assert.throws(()=>db.db.prepare(`INSERT INTO recommendation_ledger(recommendation_id,snapshot_hash,signal_session,ticker,decision,authority_mode,payload_json,created_at) VALUES (?,?,?,?,?,?,?,?)`).run(r.recommendationId,r.snapshotHash,r.signalSession,r.ticker,r.decision,'CERTIFIED_PRODUCTION','{}',r.createdAt),/RECOMMENDATION_AUTHORITY_MODE_MISMATCH/)}finally{db.close()}});
test('stored Session Manifest authority cannot be mutated after recommendation lineage exists',()=>{const db=new EgxMarketDataStore();try{const m=productionSession(db);db.appendRecommendation(rec(m.snapshotHash));assert.throws(()=>db.db.prepare("UPDATE session_manifests SET authority_mode='RESEARCH' WHERE snapshot_hash=?").run(m.snapshotHash),/IMMUTABLE_SESSION_MANIFEST/);assert.throws(()=>db.db.prepare("DELETE FROM session_manifests WHERE snapshot_hash=?").run(m.snapshotHash),/IMMUTABLE_SESSION_MANIFEST/)}finally{db.close()}});
