import test from'node:test';import assert from'node:assert/strict';import{sha256}from'../src/hash.js';import{reconcileObservations,reconcileCertifiedObservations}from'../src/reconciliation.js';import{observationBarHash}from'../src/market-observation-certification.js';
const a={ticker:'ABUK',session:'2026-08-31',sourceId:'OFFICIAL_EGX',sourceClass:'OFFICIAL_EXCHANGE',open:10,high:11,low:9,close:10,volume:1000,capturedAt:'2026-08-31T15:00:00+03:00'};const plan={ticker:'ABUK',session:'2026-08-31',state:'READY',primary:'OFFICIAL_EGX',crossChecks:['MUBASHER'],providerGroups:{primary:'EGX',crossChecks:['MUBASHER']}};
function entry(o,provider,role,ch,planArg=plan){const receiptHash=ch.repeat(64),certificate={certificateKind:'MARKET_OBSERVATION_CERTIFICATE',ticker:o.ticker,session:o.session,sourceId:o.sourceId,sourceClass:o.sourceClass,providerGroup:provider,role,sourceReceiptHash:receiptHash,sourceContentHash:'f'.repeat(64),observationBarHash:observationBarHash(o),parserId:'test',parserVersion:'1',verificationEvidenceHash:'e'.repeat(64),acquisitionPlanHash:sha256(planArg)};certificate.certificateHash=sha256(certificate);return{observation:o,runtimeReceipt:{ticker:o.ticker,sourceId:o.sourceId,state:'READY',session:o.session,providerGroup:provider,receiptHash,observationBarHash:certificate.observationBarHash,observationCertificate:certificate,observationCertificateHash:certificate.certificateHash}}}
test('research primitive reconciles consistent observations without averaging',()=>{const b={...a,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',close:10.05};const r=reconcileObservations([b,a],{maxCloseConflictPct:1});assert.equal(r.status,'READY');assert.equal(r.authoritative.sourceId,'OFFICIAL_EGX');assert.equal(r.authoritative.close,10)});
test('material close conflict fails closed',()=>{const b={...a,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',high:13,close:12};assert.equal(reconcileObservations([a,b]).status,'DATA_CONFLICT')});
test('single source is not production-ready when cross-check required',()=>assert.equal(reconcileObservations([a]).status,'SOURCE_UNAVAILABLE'));
test('mixed sessions are blocked',()=>{const b={...a,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',session:'2026-08-30'};assert.equal(reconcileObservations([a,b]).status,'BLOCKED')});
test('production reconciliation requires certified primary and crosscheck bound to same plan',()=>{const b={...a,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',close:10.05};const r=reconcileCertifiedObservations([entry(a,'EGX','PRIMARY','a'),entry(b,'MUBASHER','CROSSCHECK','b')],{acquisitionPlan:plan});assert.equal(r.status,'READY');assert.equal(r.authoritative.sourceId,plan.primary);assert.equal(r.sourceManifest.mode,'CERTIFIED_PRODUCTION');assert.equal(r.sourceManifest.observationCertificateHashes.length,2);assert.equal(r.sourceManifest.primaryObservationCertificateHash,r.sourceManifest.observationCertificateHashes.find(x=>x===r.sourceManifest.primaryObservationCertificateHash));assert.equal(r.sourceManifest.authoritativeBarHash,observationBarHash(r.authoritative))});
test('production designated primary remains authoritative even when crosscheck class has higher global priority',()=>{const primary={...a,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET'},cross={...a,sourceId:'OFFICIAL_EGX',sourceClass:'OFFICIAL_EXCHANGE',close:10.02},p={ticker:'ABUK',session:'2026-08-31',state:'READY',primary:'MUBASHER',crossChecks:['OFFICIAL_EGX'],providerGroups:{primary:'MUBASHER',crossChecks:['EGX']}};const r=reconcileCertifiedObservations([entry(primary,'MUBASHER','PRIMARY','c',p),entry(cross,'EGX','CROSSCHECK','d',p)],{acquisitionPlan:p});assert.equal(r.status,'READY');assert.equal(r.authoritative.sourceId,'MUBASHER')});
test('uncertified direct row cannot enter production reconciliation',()=>{const r=reconcileCertifiedObservations([{observation:a,runtimeReceipt:null}],{acquisitionPlan:plan});assert.equal(r.status,'BLOCKED');assert.ok(r.reasons.includes('CERTIFIED_ENTRY_INCOMPLETE'))});
test('certificate replayed under different plan is blocked',()=>{const b={...a,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',close:10.05},entries=[entry(a,'EGX','PRIMARY','a'),entry(b,'MUBASHER','CROSSCHECK','b')],changed={...plan,crossChecks:['TRADINGVIEW'],providerGroups:{primary:'EGX',crossChecks:['TRADINGVIEW']}};const r=reconcileCertifiedObservations(entries,{acquisitionPlan:changed});assert.equal(r.status,'BLOCKED');assert.ok(r.reasons.some(x=>x.includes('CERTIFICATE_ACQUISITION_PLAN_MISMATCH')||x.includes('SOURCE_NOT_IN_ACQUISITION_PLAN')))});
test('tampered certified observation is blocked before price comparison',()=>{const b={...a,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',close:10.05},e=entry(a,'EGX','PRIMARY','a');e.observation={...e.observation,close:10.2};const r=reconcileCertifiedObservations([e,entry(b,'MUBASHER','CROSSCHECK','b')],{acquisitionPlan:plan});assert.equal(r.status,'BLOCKED');assert.ok(r.reasons.some(x=>x.includes('CERTIFICATE_BAR_HASH_MISMATCH')))});
