import test from'node:test';import assert from'node:assert/strict';import{validateRecommendationContract}from'../src/recommendation-contract.js';
const base=(overrides={})=>({recommendationId:'R1',ticker:'ABUK',companyName:'Abu Qir',signalSession:'2026-08-31',createdAt:'2026-08-31T15:01:00+03:00',snapshotId:'S1',snapshotHash:'a'.repeat(64),engineVersion:'0.4.0',featureVersion:'F1',modelVersion:'M0',configVersion:'C1',configHash:'b'.repeat(64),commitHash:'TEST',decision:'WATCH',finalRankScore:50,confidence:'UNRATED',entryLow:null,entryHigh:null,entryCondition:'TRIGGER_REQUIRED',entryExpiry:null,stop:null,target1:null,target2:null,expectedHoldingWindow:'UNKNOWN',maximumHoldingSessions:5,grossRiskReward:null,netRiskReward:null,transactionCostAssumption:.006,slippageAssumption:.001,liquidityStatus:'READY',dataQuality:'READY',marketRegime:'UNKNOWN',whySelected:'watch',whyNotBuyNow:'not triggered',riskFactors:[],invalidationConditions:[],evidenceType:'OUT_OF_SAMPLE',status:'OPEN',...overrides});
test('watch may remain non-executable without fabricated geometry',()=>assert.equal(validateRecommendationContract(base()),true));
test('buy candidate requires coherent long geometry and expiry',()=>assert.equal(validateRecommendationContract(base({decision:'BUY_CANDIDATE',entryLow:10,entryHigh:10.2,stop:9.5,target1:11,target2:12,entryExpiry:'2026-09-01T11:00:00+03:00',grossRiskReward:1.5,netRiskReward:1.3})),true));
test('buy candidate missing geometry is rejected',()=>assert.throws(()=>validateRecommendationContract(base({decision:'BUY_CANDIDATE'})),/EXECUTABLE_DECISION_MISSING_GEOMETRY/));
test('stop above entry is rejected',()=>assert.throws(()=>validateRecommendationContract(base({decision:'WAIT_FOR_ENTRY',entryLow:10,entryHigh:10.2,stop:10.1,target1:11,target2:null,entryExpiry:'2026-09-01T11:00:00+03:00',grossRiskReward:1.5,netRiskReward:1.3})),/stop_not_below_entry/));
test('target below entry is rejected',()=>assert.throws(()=>validateRecommendationContract(base({decision:'WAIT_FOR_ENTRY',entryLow:10,entryHigh:10.2,stop:9.5,target1:10.1,target2:null,entryExpiry:'2026-09-01T11:00:00+03:00',grossRiskReward:1.5,netRiskReward:1.3})),/target1_not_above_entry/));
test('net risk reward cannot exceed gross',()=>assert.throws(()=>validateRecommendationContract(base({decision:'BUY_CANDIDATE',entryLow:10,entryHigh:10.2,stop:9.5,target1:11,target2:null,entryExpiry:'2026-09-01T11:00:00+03:00',grossRiskReward:1.2,netRiskReward:1.3})),/NET_RISK_REWARD_EXCEEDS_GROSS/));
test('unknown evidence class is rejected',()=>assert.throws(()=>validateRecommendationContract(base({evidenceType:'FORWARDISH'})),/INVALID_RECOMMENDATION_EVIDENCE_TYPE/));
