import test from'node:test';
import assert from'node:assert/strict';
import{EgxMarketDataStore}from'../src/market-data-store.js';
import{createRegistryManifest}from'../src/registry-manifest.js';
import{sha256,canonicalize}from'../src/hash.js';
const session='2026-08-31',universeVersion='U1';
function registry(){const rows=[{ticker:'ABUK',companyName:'A',readiness:'READY',reasons:[],lastSession:session,historyCount:100,sourceStatus:'READY'}];return{version:sha256(rows),total:1,counts:{READY:1},rows}}

test('registry enters SSOT only with hash-valid immutable manifest',()=>{const db=new EgxMarketDataStore();try{const r=registry();assert.equal(db.putUniverseRegistry(r,{marketSession:session,universeVersion}),r.version);const m=db.db.prepare('SELECT * FROM universe_registry_manifests WHERE registry_version=?').get(r.version);assert.equal(m.market_session,session);assert.equal(m.universe_version,universeVersion);assert.equal(db.db.prepare('SELECT COUNT(*) n FROM universe_registry WHERE universe_version=?').get(r.version).n,1);assert.throws(()=>db.db.prepare("UPDATE universe_registry SET readiness='BLOCKED'").run(),/IMMUTABLE_UNIVERSE_REGISTRY/);assert.throws(()=>db.db.prepare('DELETE FROM universe_registry_manifests').run(),/IMMUTABLE_UNIVERSE_REGISTRY_MANIFEST/)}finally{db.close()}});
test('direct SQL cannot add a member absent from frozen registry manifest',()=>{const db=new EgxMarketDataStore();try{const r=registry();db.putUniverseRegistry(r,{marketSession:session,universeVersion});assert.throws(()=>db.db.prepare(`INSERT INTO universe_registry(universe_version,ticker,company_name,readiness,reasons_json,last_session,history_count,source_status) VALUES (?,?,?,?,?,?,?,?)`).run(r.version,'FAKE','Fake','READY','[]',session,100,'READY'),/UNIVERSE_REGISTRY_MEMBER_NOT_IN_MANIFEST/)}finally{db.close()}});
test('direct SQL cannot plant manifest whose columns disagree with hash-valid payload',()=>{const db=new EgxMarketDataStore();try{const r=registry(),m=createRegistryManifest(r,{marketSession:session,universeVersion});assert.throws(()=>db.db.prepare(`INSERT INTO universe_registry_manifests(registry_version,market_session,universe_version,manifest_hash,payload_json,created_at) VALUES (?,?,?,?,?,?)`).run(r.version,'2026-08-30',universeVersion,m.manifestHash,canonicalize(m),'2026-08-31T15:00:00Z'),/INVALID_UNIVERSE_REGISTRY_MANIFEST/)}finally{db.close()}});
test('registry API rejects row mutation under stale registry version',()=>{const db=new EgxMarketDataStore();try{const r=registry(),bad={...r,rows:[{...r.rows[0],historyCount:99}]};assert.throws(()=>db.putUniverseRegistry(bad,{marketSession:session,universeVersion}),/REGISTRY_VERSION_HASH_MISMATCH/)}finally{db.close()}});
