import test from 'node:test';
import assert from 'node:assert/strict';
import { buildResearchRecommendation,simulateResearchPlan,summarizeOutcomes,RESEARCH_STRATEGY_PRESETS } from '../src/research-strategy-engine.js';

function history(){const sessions=[];for(let i=0;i<80;i++){const close=100+i*0.42;const session=`2026-${String(1+Math.floor(i/28)).padStart(2,'0')}-${String(1+(i%28)).padStart(2,'0')}`;sessions.push({session,open:close-0.3,high:close+0.8,low:close-0.9,close,volume:1_000_000+i*8000,researchState:'READY_RESEARCH'})}return{sessions}}
function feature(){return{ticker:'TEST',signalSession:'2026-04-01',featureReady:true,groups:[{name:'TECHNICAL',payload:{close:134,sma20:130,sma50:124,rsi14:61,atr14:2.1,atrPct:1.57,momentum20Pct:8,momentum60Pct:20,closeVsSma20Pct:3.08,distanceToPrior20dHighPct:-1,breakoutAbovePrior20dHigh:false}},{name:'LIQUIDITY',payload:{relativeVolume20:1.6,medianTradedValue20:55_000_000}}]}}
function current(){return{state:'READY_RESEARCH',authoritativeResearch:{session:'2026-04-01',open:132.8,high:135,low:132,close:134,volume:1_800_000}}}

test('quality research setup produces bounded non-production execution geometry',()=>{const p=buildResearchRecommendation({featureRecord:feature(),history:history(),currentRecord:current(),preset:RESEARCH_STRATEGY_PRESETS[0]});assert.equal(p.authorityMode,'RESEARCH');assert.equal(p.productionAuthority,false);assert.equal(p.automaticOrders,false);assert.equal(p.executableResearchPlan,true);assert.ok(['BUY_CANDIDATE','WAIT_FOR_ENTRY'].includes(p.decision));assert.ok(p.stop<p.entryLow&&p.entryLow<=p.entryHigh&&p.entryHigh<p.target1&&p.target1<p.target2);assert.ok(p.netRiskReward>=1.25);assert.match(p.planHash,/^[a-f0-9]{64}$/)});

test('weak structure remains WATCH and cannot fabricate targets',()=>{const f=feature();f.groups[0].payload={...f.groups[0].payload,close:119,sma20:125,sma50:127,momentum20Pct:-5,rsi14:39};const p=buildResearchRecommendation({featureRecord:f,history:history(),currentRecord:{state:'READY_RESEARCH',authoritativeResearch:{session:'2026-04-01',open:120,high:121,low:118,close:119,volume:1_800_000}},preset:RESEARCH_STRATEGY_PRESETS[0]});assert.equal(p.decision,'WATCH');assert.equal(p.executableResearchPlan,false);assert.equal('entryLow' in p,false);assert.ok(p.reasons.length>0)});

test('same-bar stop and target ambiguity is resolved stop-first',()=>{const p=buildResearchRecommendation({featureRecord:feature(),history:history(),currentRecord:current(),preset:RESEARCH_STRATEGY_PRESETS[0]});const b={session:'2026-04-02',open:p.entryHigh,high:p.target2+1,low:p.stop-1,close:p.entryHigh,volume:1_000_000};const o=simulateResearchPlan(p,[b]);assert.equal(o.state,'STOP');assert.equal(o.rMultiple,-1)});

test('not touched entry is NOT_TRIGGERED rather than a false loss or win',()=>{const p=buildResearchRecommendation({featureRecord:feature(),history:history(),currentRecord:current(),preset:RESEARCH_STRATEGY_PRESETS[0]});const bars=Array.from({length:4},(_,i)=>({session:`2026-04-0${i+2}`,open:p.entryHigh+10,high:p.entryHigh+12,low:p.entryHigh+5,close:p.entryHigh+9,volume:1_000_000}));assert.equal(simulateResearchPlan(p,bars).state,'NOT_TRIGGERED')});

test('outcome summary reports hit rate and expectancy without counting untriggered setups as wins',()=>{const s=summarizeOutcomes([{state:'TARGET1',rMultiple:1.4},{state:'STOP',rMultiple:-1},{state:'TIMEOUT',rMultiple:.2},{state:'NOT_TRIGGERED',rMultiple:0}]);assert.equal(s.eligible,4);assert.equal(s.triggered,3);assert.equal(s.target1OrBetter,1);assert.equal(s.target1HitRatePct,33.33);assert.ok(s.expectancyR>0)});
