import test from 'node:test';
import assert from 'node:assert/strict';
import { buildPointInTimeCandidate, runHistoricalMarketSimulator, summarizeV169ExactLedger, compareWithLegacyEngines } from '../src/research-historical-simulator.js';

function sessions(n=90){const out=[];for(let i=0;i<n;i++){const d=new Date(Date.UTC(2026,0,1+i)),session=d.toISOString().slice(0,10),base=100+i*0.18,close=base+Math.sin(i*1.25)*1.5,open=close-Math.sin(i*.7)*.45,high=Math.max(open,close)+1.15,low=Math.min(open,close)-1.15;out.push({ticker:'TEST',session,open,high,low,close,volume:1_500_000+(i%7)*120_000,researchState:'READY_RESEARCH'})}return out}
function history(ticker='TEST',n=90){return {schemaVersion:'egx-one-research-history-1',ticker,companyNameEn:ticker,authorityMode:'RESEARCH',researchOnly:true,productionAuthority:false,sessions:sessions(n).map(x=>({...x,ticker}))}}

test('point-in-time candidate cannot see future history mutations',()=>{const h=history('TEST',95),bar=h.sessions[72],a=buildPointInTimeCandidate({history:h,currentBar:bar});const mutated=structuredClone(h);for(let i=80;i<mutated.sessions.length;i++){mutated.sessions[i].high*=4;mutated.sessions[i].close*=3;mutated.sessions[i].open=mutated.sessions[i].close;mutated.sessions[i].low=Math.min(mutated.sessions[i].low,mutated.sessions[i].close)}const b=buildPointInTimeCandidate({history:mutated,currentBar:mutated.sessions[72]});assert.equal(a.informationHash,b.informationHash);assert.deepEqual(a.feature,b.feature);assert.deepEqual(a.plan,b.plan)});

test('historical market replay is deterministic and research-only',()=>{const docs=[history('AAA',92),history('BBB',92)],a=runHistoricalMarketSimulator({histories:docs}),b=runHistoricalMarketSimulator({histories:structuredClone(docs)});assert.equal(a.simulationHash,b.simulationHash);assert.equal(a.authorityMode,'RESEARCH');assert.equal(a.productionAuthority,false);assert.equal(a.forwardEvidence,false);assert.equal(a.sameBarTargetStop,'STOP_FIRST');assert.equal(a.historyTickers,2)});

test('V16.9 exact ledger summary keeps exact evidence grade',()=>{const ledger={engine:'V16_9_EQUAL_WEIGHT_BASKET',sessions:[{signalDate:'2026-08-04',estimatedRoundTripCostPct:.6,members:[{ticker:'AAA',memberStatus:'TARGET_HIT',netReturnPct:3.4},{ticker:'BBB',memberStatus:'STOP_HIT',netReturnPct:-2.1}]}]},s=summarizeV169ExactLedger(ledger);assert.equal(s.evidenceGrade,'EXACT_LOGGED_LEDGER');assert.equal(s.members,2);assert.equal(s.targetHitRatePct,50);assert.equal(s.stopRatePct,50);assert.equal(s.averageNetReturnPct,.65)});

test('legacy comparison never fabricates unavailable engine metrics',()=>{const plan={decision:'BUY_CANDIDATE',qualityScore:85,netRiskReward:1.3},outcome={state:'TARGET1',rMultiple:1.2},simulation={presetId:'CONTROLLED_PULLBACK',costBps:25,performance:{allDailySignals:{}},records:[{ticker:'AAA',signalSession:'2026-08-04',plan,outcome,netReturnPct:2.5}]},ledger={engine:'V16_9_EQUAL_WEIGHT_BASKET',sessions:[{signalDate:'2026-08-04',estimatedRoundTripCostPct:.6,members:[{ticker:'AAA',memberStatus:'TARGET_HIT',netReturnPct:2}]}]},c=compareWithLegacyEngines({simulation,legacyV169:ledger});assert.equal(c.v16_9.evidenceGrade,'EXACT_LOGGED_LEDGER');assert.equal(c.v16_9.commonSignalDates,1);assert.equal(c.v16_9.sameTickerSameDateOverlap,1);assert.equal(c.gannFusionX,null);assert.equal(c.sepaX,null);assert.ok(c.otherLegacyEngines.every(x=>x.evidenceGrade.startsWith('NOT_COMPARABLE_')))});
