import test from 'node:test';
import assert from 'node:assert/strict';
import { sha256 } from '../src/hash.js';
import { importLegacyMarketSnapshot } from '../src/research-legacy-market-import.js';
import { resolveResearchCurrentSession,evaluateResearchDataReadiness } from '../src/research-current-session.js';
import { stampResearchRecord } from '../src/research-source-policy.js';

const commit='a'.repeat(40),fileHash='b'.repeat(64),expectedSession='2026-08-31';
const snapshot={generatedAt:'2026-08-31T19:34:23Z',updatedAt:'2026-08-31T19:35:40Z',source:'mubasher_symbol_pages_precise_enriched',rows:[{symbol:'ABUK',price:79.98,open:79.4,high:80.9,low:78.26,volume:1882974,valueTraded:149807824,source:'mubasher_symbol_pages',sourceUrl:'https://english.mubasher.info/markets/EGX/stocks/ABUK/',sourceSessionDate:'2026-08-31',sourceSessionEvidence:'mubasher_time_only_same_day_cross_symbol_quorum_stale_minority_quarantined'}]};

test('exact-commit legacy market snapshot imports current session as research only',()=>{const r=importLegacyMarketSnapshot(snapshot,{legacyCommit:commit,sourceFileHash:fileHash,expectedSession});assert.equal(r.state,'READY_RESEARCH');assert.equal(r.observations.length,1);assert.equal(r.observations[0].sourceId,'LEGACY_MARKET_IMPORT');assert.equal(r.observations[0].productionAuthority,false);assert.equal(r.observations[0].verificationState,'LEGACY_MUBASHER_SESSION_QUORUM');assert.equal(r.manifest.counts.expectedSessionRows,1)});

test('legacy market stale row cannot satisfy current-session gate',()=>{const stale={...snapshot,rows:[{...snapshot.rows[0],sourceSessionDate:'2026-08-30'}]};const r=importLegacyMarketSnapshot(stale,{legacyCommit:commit,sourceFileHash:fileHash,expectedSession});assert.equal(r.observations[0].researchState,'STALE_RESEARCH');const resolved=resolveResearchCurrentSession({ticker:'ABUK',expectedSession,observations:r.observations});assert.equal(resolved.state,'STALE_RESEARCH');assert.ok(resolved.reasons.includes('EXPECTED_SESSION_MISSING:2026-08-31'))});

test('fresh legacy Mubasher snapshot beats stale Yahoo for current research session',()=>{const imported=importLegacyMarketSnapshot(snapshot,{legacyCommit:commit,sourceFileHash:fileHash,expectedSession}).observations[0];const yahoo=stampResearchRecord({ticker:'ABUK',session:'2026-08-30',open:75,high:76,low:74,close:75.5,volume:100,researchState:'READY_RESEARCH',rowHash:sha256('y')},{sourceId:'YAHOO_RESEARCH'});const r=resolveResearchCurrentSession({ticker:'ABUK',expectedSession,observations:[yahoo,imported]});assert.equal(r.state,'READY_RESEARCH');assert.equal(r.authoritativeResearch.sourceId,'LEGACY_MARKET_IMPORT');assert.equal(r.authoritativeResearch.session,expectedSession)});

test('same-session Yahoo and legacy Mubasher disagreement is quarantined',()=>{const imported=importLegacyMarketSnapshot(snapshot,{legacyCommit:commit,sourceFileHash:fileHash,expectedSession}).observations[0];const yahoo=stampResearchRecord({ticker:'ABUK',session:expectedSession,open:90,high:92,low:89,close:91,volume:100,researchState:'READY_RESEARCH',rowHash:sha256('y')},{sourceId:'YAHOO_RESEARCH'});const r=resolveResearchCurrentSession({ticker:'ABUK',expectedSession,observations:[yahoo,imported]});assert.equal(r.state,'DATA_CONFLICT');assert.equal(r.authoritativeResearch.researchState,'QUARANTINED_RESEARCH');assert.ok(r.reasons.some(x=>x.startsWith('CLOSE_CONFLICT:')))});

test('Mubasher direct and legacy snapshot do not count as independent providers',()=>{const imported=importLegacyMarketSnapshot(snapshot,{legacyCommit:commit,sourceFileHash:fileHash,expectedSession}).observations[0];const direct=stampResearchRecord({ticker:'ABUK',session:expectedSession,open:79.4,high:80.9,low:78.26,close:79.98,volume:1882974,researchState:'READY_RESEARCH',rowHash:sha256('m')},{sourceId:'MUBASHER_RESEARCH'});const r=resolveResearchCurrentSession({ticker:'ABUK',expectedSession,observations:[direct,imported]});assert.equal(r.state,'READY_RESEARCH');assert.equal(r.evidence.independent.length,1);assert.equal(r.authoritativeResearch.sourceId,'MUBASHER_RESEARCH')});

test('research data readiness fails stale-session majority even if stale coverage is high',()=>{const rows=Array.from({length:80},(_,i)=>({state:'READY_RESEARCH',authoritativeResearch:stampResearchRecord({ticker:`T${i}`,session:'2026-08-30',researchState:'READY_RESEARCH'},{sourceId:'YAHOO_RESEARCH'})}));const g=evaluateResearchDataReadiness({expectedSession,universeSize:100,records:rows});assert.equal(g.state,'FAIL');assert.equal(g.counts.coveragePct,0)});

test('research data readiness passes only expected-session coverage threshold',()=>{const rows=Array.from({length:80},(_,i)=>({state:'READY_RESEARCH',authoritativeResearch:stampResearchRecord({ticker:`T${i}`,session:expectedSession,researchState:'READY_RESEARCH',currentSessionEvidence:{providers:['MUBASHER']}},{sourceId:'LEGACY_MARKET_IMPORT'})}));const g=evaluateResearchDataReadiness({expectedSession,universeSize:100,records:rows});assert.equal(g.state,'PASS');assert.equal(g.counts.coveragePct,80)});
