import test from'node:test';import assert from'node:assert/strict';import{sha256}from'../src/hash.js';import{validateUniverseScopeAttestation}from'../src/scope-attestation.js';
const equityRows=[{ticker:'ABUK',isin:'EGS38161C013'},{ticker:'COMI',isin:'EGS60121C018'}],bond={ticker:'BOND',isin:'EGB123456789'};const extracted=[...equityRows,bond];const admission={state:'READY_FOR_SCHEMA_VALIDATION',admissionHash:'a'.repeat(64)};const manifest={sourceAdmissionHash:admission.admissionHash,manifestHash:'b'.repeat(64),outputHash:sha256(extracted)};const extraction={state:'READY_FOR_SEMANTIC_VALIDATION',manifest};const schemaAttestation={sourceAdmissionHash:admission.admissionHash,extractionManifestHash:manifest.manifestHash,attestationHash:'c'.repeat(64)};const schemaResult={state:'READY_FOR_SCOPE_VALIDATION',attestation:schemaAttestation};const att={state:'VERIFIED',scope:'ALL_LISTED_EQUITIES',declaredTotal:2,evidenceLocator:'page-1:all-listed-equities',sourceAdmissionHash:admission.admissionHash,extractionManifestHash:manifest.manifestHash,schemaAttestationHash:schemaAttestation.attestationHash,scopeDefinitionHash:'d'.repeat(64),verificationEvidenceHash:'e'.repeat(64)};
test('verified exhaustive equity scope advances only to universe certification',()=>{const r=validateUniverseScopeAttestation({admission,extraction,schemaResult,extractedOutput:extracted,universeRows:equityRows,attestation:att});assert.equal(r.state,'READY_FOR_UNIVERSE_CERTIFICATION');assert.equal(r.universeAuthorityEligible,false);assert.equal(r.attestation.extractionOutputHash,sha256(extracted));assert.equal(r.attestation.universeOutputHash,sha256(equityRows));assert.ok(r.attestation.attestationHash)});
test('mixed official artifact may contain bonds while equity declared total remains exact',()=>{const r=validateUniverseScopeAttestation({admission,extraction,schemaResult,extractedOutput:extracted,universeRows:equityRows,attestation:att});assert.equal(r.state,'READY_FOR_UNIVERSE_CERTIFICATION');assert.equal(r.attestation.declaredTotal,2)});
test('partial page scope is blocked',()=>{const r=validateUniverseScopeAttestation({admission,extraction,schemaResult,extractedOutput:extracted,universeRows:equityRows,attestation:{...att,scope:'PAGE_ONLY'}});assert.ok(r.reasons.includes('SCOPE_NOT_ALL_LISTED_EQUITIES'))});
test('declared equity total must equal universe rows not raw extracted rows',()=>{const r=validateUniverseScopeAttestation({admission,extraction,schemaResult,extractedOutput:extracted,universeRows:equityRows,attestation:{...att,declaredTotal:3}});assert.ok(r.reasons.includes('DECLARED_TOTAL_MISMATCH:3:2'))});
test('universe row not present in extraction is blocked',()=>{const r=validateUniverseScopeAttestation({admission,extraction,schemaResult,extractedOutput:extracted,universeRows:[...equityRows,{ticker:'FAKE',isin:'EGS00000C019'}],attestation:{...att,declaredTotal:3}});assert.ok(r.reasons.includes('UNIVERSE_ROW_NOT_IN_EXTRACTION'))});
test('scope attestation cannot detach from schema attestation',()=>{const r=validateUniverseScopeAttestation({admission,extraction,schemaResult,extractedOutput:extracted,universeRows:equityRows,attestation:{...att,schemaAttestationHash:'f'.repeat(64)}});assert.ok(r.reasons.includes('SCOPE_SCHEMA_HASH_MISMATCH'))});
test('scope evidence locator is mandatory',()=>{const r=validateUniverseScopeAttestation({admission,extraction,schemaResult,extractedOutput:extracted,universeRows:equityRows,attestation:{...att,evidenceLocator:''}});assert.ok(r.reasons.includes('MISSING_SCOPE_EVIDENCE_LOCATOR'))});
