import test from'node:test';
import assert from'node:assert/strict';
import{EgxMarketDataStore}from'../src/market-data-store.js';
import{createSessionManifest,validateSessionManifest}from'../src/session-manifest.js';
import{reconcileCertifiedObservations}from'../src/reconciliation.js';
import{observationBarHash}from'../src/market-observation-certification.js';
import{sha256}from'../src/hash.js';

const session='2026-08-31';
const plan={ticker:'ABUK',session,state:'READY',primary:'OFFICIAL_EGX',crossChecks:['MUBASHER'],providerGroups:{primary:'EGX',crossChecks:['MUBASHER']}};
const primary={ticker:'ABUK',session,sourceId:'OFFICIAL_EGX',sourceClass:'OFFICIAL_EXCHANGE',open:10,high:11,low:9,close:10,volume:1000,capturedAt:'2026-08-31T15:00:00+03:00'};
function entry(o,providerGroup,role,ch){const receiptHash=ch.repeat(64),certificate={certificateKind:'MARKET_OBSERVATION_CERTIFICATE',ticker:o.ticker,session:o.session,sourceId:o.sourceId,sourceClass:o.sourceClass,providerGroup,role,sourceReceiptHash:receiptHash,sourceContentHash:'f'.repeat(64),observationBarHash:observationBarHash(o),parserId:'test-parser',parserVersion:'1',verificationEvidenceHash:'e'.repeat(64),acquisitionPlanHash:sha256(plan)};certificate.certificateHash=sha256(certificate);return{observation:o,runtimeReceipt:{ticker:o.ticker,sourceId:o.sourceId,state:'READY',session:o.session,providerGroup,receiptHash,observationBarHash:certificate.observationBarHash,observationCertificate:certificate,observationCertificateHash:certificate.certificateHash}}}
function entries(){const cross={...primary,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',close:10.05};return[entry(primary,'EGX','PRIMARY','a'),entry(cross,'MUBASHER','CROSSCHECK','b')]}
function manifestInput({rawDataVersion,normalizedDataVersion,sourceManifest,authorityMode}={}){return{marketSession:session,...(authorityMode?{authorityMode}:{}),exchangeCalendarVersion:'cal1',universeVersion:'u1',rawDataVersion,normalizedDataVersion,sourceManifest,corporateActionVersion:'ca1',fundamentalsCutoff:'2026-08-31T12:00:00Z',featureVersion:'f0',modelVersion:'baseline0',engineVersion:'0.5.0',configVersion:'cfg1',commitHash:'TEST',generatedAt:'2026-08-31T15:10:00Z'}}
function rawVersion(db,{id='A-PROD',expectedSession=session}={}){db.startAcquisition({acquisitionId:id,expectedSession,startedAt:'2026-08-31T14:40:00Z'});db.putRawBar({acquisitionId:id,ticker:'ABUK',session:expectedSession,sourceId:'OFFICIAL_EGX',payload:{open:10,high:11,low:9,close:10,volume:1000}});return db.finalizeAcquisition(id,'2026-08-31T14:50:00Z')}
function productionLineage(db){const es=entries(),rec=reconcileCertifiedObservations(es,{acquisitionPlan:plan});assert.equal(rec.status,'READY');const rawDataVersion=rawVersion(db),sourceManifest=db.putSourceManifest(rec.sourceManifest,'2026-08-31T15:01:00Z');db.startDataSnapshot({dataSnapshotId:'D-PROD',marketSession:session,sourceManifestHash:sourceManifest,createdAt:'2026-08-31T15:02:00Z',ingestionMode:'CERTIFIED_PRODUCTION'});db.putCertifiedNormalizedBar({dataSnapshotId:'D-PROD',entries:es,acquisitionPlan:plan});const normalizedDataVersion=db.finalizeDataSnapshot('D-PROD','2026-08-31T15:03:00Z');return{rawDataVersion,normalizedDataVersion,sourceManifest}}
function researchLineage(db){const rawDataVersion=rawVersion(db,{id:'A-RES'}),sourceManifest=db.putSourceManifest({mode:'RESEARCH',session,source:'fixture'});db.startDataSnapshot({dataSnapshotId:'D-RES',marketSession:session,sourceManifestHash:sourceManifest,createdAt:'2026-08-31T15:02:00Z'});db.putNormalizedBar({dataSnapshotId:'D-RES',ticker:'ABUK',session,open:10,high:11,low:9,close:10,volume:1000,sourceManifestHash:sourceManifest});const normalizedDataVersion=db.finalizeDataSnapshot('D-RES');return{rawDataVersion,normalizedDataVersion,sourceManifest}}

test('missing authority mode fails safe to RESEARCH and is hash bound',()=>{const m=createSessionManifest(manifestInput({rawDataVersion:'r',normalizedDataVersion:'n',sourceManifest:'s'}));assert.equal(m.authorityMode,'RESEARCH');assert.equal(validateSessionManifest(m).valid,true);const tampered={...m,authorityMode:'CERTIFIED_PRODUCTION'};assert.equal(validateSessionManifest(tampered).valid,false)});
test('certified production session manifest is admitted only over certified production normalized lineage',()=>{const db=new EgxMarketDataStore();try{const x=productionLineage(db),m=createSessionManifest(manifestInput({...x,authorityMode:'CERTIFIED_PRODUCTION'}));assert.equal(db.putSessionManifest(m),m.snapshotHash)}finally{db.close()}});
test('research normalized snapshot cannot be relabeled as certified production session',()=>{const db=new EgxMarketDataStore();try{const x=researchLineage(db),m=createSessionManifest(manifestInput({...x,authorityMode:'CERTIFIED_PRODUCTION'}));assert.throws(()=>db.putSessionManifest(m),/SESSION_MANIFEST_AUTHORITY_MODE_MISMATCH/)}finally{db.close()}});
test('certified production normalized snapshot cannot be downgraded to research session manifest',()=>{const db=new EgxMarketDataStore();try{const x=productionLineage(db),m=createSessionManifest(manifestInput(x));assert.equal(m.authorityMode,'RESEARCH');assert.throws(()=>db.putSessionManifest(m),/SESSION_MANIFEST_AUTHORITY_MODE_MISMATCH/)}finally{db.close()}});
test('session manifest source hash must be exactly the source frozen into normalized snapshot',()=>{const db=new EgxMarketDataStore();try{const x=productionLineage(db),other=db.putSourceManifest({mode:'RESEARCH',session,source:'other'}),m=createSessionManifest(manifestInput({...x,sourceManifest:other,authorityMode:'CERTIFIED_PRODUCTION'}));assert.throws(()=>db.putSessionManifest(m),/SESSION_MANIFEST_SOURCE_SNAPSHOT_MISMATCH/)}finally{db.close()}});
test('raw acquisition session must match immutable session manifest',()=>{const db=new EgxMarketDataStore();try{const x=productionLineage(db),wrong=rawVersion(db,{id:'A-WRONG',expectedSession:'2026-08-30'}),m=createSessionManifest(manifestInput({...x,rawDataVersion:wrong,authorityMode:'CERTIFIED_PRODUCTION'}));assert.throws(()=>db.putSessionManifest(m),/SESSION_MANIFEST_RAW_SESSION_MISMATCH/)}finally{db.close()}});
