import test from'node:test';import assert from'node:assert/strict';import{validateSourceReceipt,validateIndependentReceipts}from'../src/source-provenance.js';import{DEFAULT_SOURCE_POLICY}from'../src/acquisition-policy.js';
const cal={session:'2026-08-31',closeAt:'2026-08-31T14:30:00+03:00'};const h='a'.repeat(64);const base={sourceId:'OFFICIAL_EGX',sourceClass:'OFFICIAL_EXCHANGE',providerGroup:'EGX',sourceUrl:'https://beta.egx.com.eg/en/market/equities',session:'2026-08-31',capturedAt:'2026-08-31T15:00:00+03:00',provenanceKind:'OFFICIAL_DIRECT_PAGE',contentHash:h};
test('direct official post-close source receipt is ready',()=>assert.equal(validateSourceReceipt(base,{policy:DEFAULT_SOURCE_POLICY.OFFICIAL_EGX,calendarEntry:cal,decisionTime:'2026-08-31T15:15:00+03:00'}).state,'READY'));
test('search result cannot be authoritative raw evidence',()=>{const r=validateSourceReceipt({...base,provenanceKind:'SEARCH_SNIPPET'},{policy:DEFAULT_SOURCE_POLICY.OFFICIAL_EGX,calendarEntry:cal});assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('NON_RAW_EVIDENCE_KIND'))});
test('official source must resolve to EGX domain',()=>{const r=validateSourceReceipt({...base,sourceUrl:'https://example.com/egx-copy'},{policy:DEFAULT_SOURCE_POLICY.OFFICIAL_EGX,calendarEntry:cal});assert.ok(r.reasons.includes('OFFICIAL_DOMAIN_MISMATCH'))});
test('pre-close official capture is blocked',()=>assert.ok(validateSourceReceipt({...base,capturedAt:'2026-08-31T14:00:00+03:00'},{policy:DEFAULT_SOURCE_POLICY.OFFICIAL_EGX,calendarEntry:cal}).reasons.includes('PRE_CLOSE_SOURCE_CAPTURE')));
test('capture after decision time is a look-ahead violation',()=>assert.ok(validateSourceReceipt({...base,capturedAt:'2026-08-31T15:20:00+03:00'},{policy:DEFAULT_SOURCE_POLICY.OFFICIAL_EGX,calendarEntry:cal,decisionTime:'2026-08-31T15:10:00+03:00'}).reasons.includes('CAPTURE_AFTER_DECISION_TIME')));
test('same provider cannot be presented as independent evidence',()=>{const r=validateIndependentReceipts(base,{...base,sourceId:'EGX_MIRROR',contentHash:'b'.repeat(64)});assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('SAME_PROVIDER_GROUP'))});
test('identical payload across different providers is suspicious not independent',()=>{const r=validateIndependentReceipts(base,{...base,sourceId:'MUBASHER',sourceClass:'PUBLIC_MARKET',providerGroup:'MUBASHER',sourceUrl:'https://www.mubasher.info',contentHash:h});assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('IDENTICAL_CONTENT_HASH'))});
