import test from'node:test';
import assert from'node:assert/strict';
import{EgxMarketDataStore}from'../src/market-data-store.js';
import{sha256,canonicalize}from'../src/hash.js';

const session='2026-08-31';
function seedRaw(db){db.startAcquisition({acquisitionId:'A1',expectedSession:session,startedAt:'2026-08-31T14:00:00Z'});db.putRawBar({acquisitionId:'A1',ticker:'ABUK',session,sourceId:'OFFICIAL_EGX',payload:{open:10,high:11,low:9,close:10,volume:1000}})}
function seedNormalized(db){const sourceManifestHash=db.putSourceManifest({mode:'RESEARCH',session,source:'fixture'});db.startDataSnapshot({dataSnapshotId:'D1',marketSession:session,sourceManifestHash,createdAt:'2026-08-31T15:00:00Z'});db.putNormalizedBar({dataSnapshotId:'D1',ticker:'ABUK',session,open:10,high:11,low:9,close:10,volume:1000,sourceManifestHash});return sourceManifestHash}

test('acquisition cannot be inserted already finalized',()=>{const db=new EgxMarketDataStore();try{assert.throws(()=>db.db.prepare(`INSERT INTO acquisition_runs(acquisition_id,expected_session,started_at,finalized_at,content_hash) VALUES (?,?,?,?,?)`).run('X',session,'2026-08-31T14:00:00Z','2026-08-31T15:00:00Z','0'.repeat(64)),/ACQUISITION_MUST_START_UNFINALIZED/)}finally{db.close()}});

test('data snapshot cannot be inserted already finalized',()=>{const db=new EgxMarketDataStore();try{const sourceManifestHash=db.putSourceManifest({mode:'RESEARCH',session,source:'fixture'});assert.throws(()=>db.db.prepare(`INSERT INTO data_snapshots(data_snapshot_id,market_session,source_manifest_hash,created_at,finalized_at,content_hash,ingestion_mode) VALUES (?,?,?,?,?,?,?)`).run('X',session,sourceManifestHash,'2026-08-31T15:00:00Z','2026-08-31T15:01:00Z','0'.repeat(64),'RESEARCH'),/DATA_SNAPSHOT_MUST_START_UNFINALIZED/)}finally{db.close()}});

test('direct SQL cannot first-finalize acquisition with arbitrary aggregate hash',()=>{const db=new EgxMarketDataStore();try{seedRaw(db);assert.throws(()=>db.db.prepare(`UPDATE acquisition_runs SET content_hash=?,finalized_at=? WHERE acquisition_id='A1'`).run('0'.repeat(64),'2026-08-31T15:00:00Z'),/INVALID_ACQUISITION_FINALIZATION_HASH/);assert.equal(db.db.prepare(`SELECT content_hash FROM acquisition_runs WHERE acquisition_id='A1'`).get().content_hash,null)}finally{db.close()}});

test('direct SQL can only first-finalize acquisition with hash of exact persisted ordered rows',()=>{const db=new EgxMarketDataStore();try{seedRaw(db);const rows=db.db.prepare(`SELECT raw_hash,ticker,session,source_id,payload_json FROM raw_bars WHERE acquisition_id='A1' ORDER BY ticker,session,source_id,raw_hash`).all(),contentHash=sha256({acquisitionId:'A1',expectedSession:session,rows});db.db.prepare(`UPDATE acquisition_runs SET content_hash=?,finalized_at=? WHERE acquisition_id='A1'`).run(contentHash,'2026-08-31T15:00:00Z');assert.equal(db.db.prepare(`SELECT content_hash FROM acquisition_runs WHERE acquisition_id='A1'`).get().content_hash,contentHash)}finally{db.close()}});

test('direct SQL cannot first-finalize data snapshot with arbitrary aggregate hash',()=>{const db=new EgxMarketDataStore();try{seedNormalized(db);assert.throws(()=>db.db.prepare(`UPDATE data_snapshots SET content_hash=?,finalized_at=? WHERE data_snapshot_id='D1'`).run('0'.repeat(64),'2026-08-31T15:01:00Z'),/INVALID_DATA_SNAPSHOT_FINALIZATION_HASH/);assert.equal(db.db.prepare(`SELECT content_hash FROM data_snapshots WHERE data_snapshot_id='D1'`).get().content_hash,null)}finally{db.close()}});

test('direct SQL can only first-finalize data snapshot with hash of exact persisted ordered rows',()=>{const db=new EgxMarketDataStore();try{const sourceManifestHash=seedNormalized(db),rows=db.db.prepare(`SELECT ticker,session,open,high,low,close,volume,source_manifest_hash,certified_reconciliation_manifest_hash,primary_observation_certificate_hash,row_hash FROM normalized_bars WHERE data_snapshot_id='D1' ORDER BY ticker,session`).all(),contentHash=sha256({dataSnapshotId:'D1',marketSession:session,sourceManifestHash,ingestionMode:'RESEARCH',rows});db.db.prepare(`UPDATE data_snapshots SET content_hash=?,finalized_at=? WHERE data_snapshot_id='D1'`).run(contentHash,'2026-08-31T15:01:00Z');assert.equal(db.db.prepare(`SELECT content_hash FROM data_snapshots WHERE data_snapshot_id='D1'`).get().content_hash,contentHash)}finally{db.close()}});

test('acquisition and snapshot identity metadata cannot change before finalization',()=>{const db=new EgxMarketDataStore();try{seedRaw(db);assert.throws(()=>db.db.prepare(`UPDATE acquisition_runs SET expected_session='2026-08-30' WHERE acquisition_id='A1'`).run(),/IMMUTABLE_ACQUISITION_METADATA/);const sourceManifestHash=seedNormalized(db);assert.throws(()=>db.db.prepare(`UPDATE data_snapshots SET market_session='2026-08-30' WHERE data_snapshot_id='D1'`).run(),/IMMUTABLE_DATA_SNAPSHOT_METADATA/);assert.ok(sourceManifestHash)}finally{db.close()}});
