import test from'node:test';
import assert from'node:assert/strict';
import{EgxMarketDataStore}from'../src/market-data-store.js';
import{sha256,canonicalize}from'../src/hash.js';

const session='2026-08-31';

test('direct SQL raw bar rejects a false raw_hash',()=>{const db=new EgxMarketDataStore();try{db.startAcquisition({acquisitionId:'A1',expectedSession:session,startedAt:'2026-08-31T14:00:00Z'});const payload={open:10,high:11,low:9,close:10,volume:1000};assert.throws(()=>db.db.prepare(`INSERT INTO raw_bars(raw_hash,acquisition_id,ticker,session,source_id,payload_json) VALUES (?,?,?,?,?,?)`).run('0'.repeat(64),'A1','ABUK',session,'OFFICIAL_EGX',canonicalize(payload)),/INVALID_RAW_BAR_HASH/)}finally{db.close()}});

test('direct SQL raw bar with canonical matching hash preserves exact row identity',()=>{const db=new EgxMarketDataStore();try{db.startAcquisition({acquisitionId:'A1',expectedSession:session,startedAt:'2026-08-31T14:00:00Z'});const payload={open:10,high:11,low:9,close:10,volume:1000},rawHash=sha256({acquisitionId:'A1',ticker:'ABUK',session,sourceId:'OFFICIAL_EGX',payload});db.db.prepare(`INSERT INTO raw_bars(raw_hash,acquisition_id,ticker,session,source_id,payload_json) VALUES (?,?,?,?,?,?)`).run(rawHash,'A1','ABUK',session,'OFFICIAL_EGX',canonicalize(payload));assert.equal(db.db.prepare('SELECT raw_hash FROM raw_bars').get().raw_hash,rawHash)}finally{db.close()}});

test('direct SQL normalized row rejects a false row_hash',()=>{const db=new EgxMarketDataStore();try{const sourceManifestHash=db.putSourceManifest({mode:'RESEARCH',session,source:'fixture'});db.startDataSnapshot({dataSnapshotId:'D1',marketSession:session,sourceManifestHash,createdAt:'2026-08-31T15:00:00Z'});assert.throws(()=>db.db.prepare(`INSERT INTO normalized_bars(data_snapshot_id,ticker,session,open,high,low,close,volume,source_manifest_hash,certified_reconciliation_manifest_hash,primary_observation_certificate_hash,row_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run('D1','ABUK',session,10,11,9,10,1000,sourceManifestHash,null,null,'0'.repeat(64)),/INVALID_NORMALIZED_BAR_HASH/)}finally{db.close()}});

test('direct SQL normalized research row with canonical matching hash preserves exact row identity',()=>{const db=new EgxMarketDataStore();try{const sourceManifestHash=db.putSourceManifest({mode:'RESEARCH',session,source:'fixture'});db.startDataSnapshot({dataSnapshotId:'D1',marketSession:session,sourceManifestHash,createdAt:'2026-08-31T15:00:00Z'});const row={dataSnapshotId:'D1',ticker:'ABUK',session,open:10,high:11,low:9,close:10,volume:1000,sourceManifestHash,certifiedReconciliationManifestHash:null,primaryObservationCertificateHash:null},rowHash=sha256(row);db.db.prepare(`INSERT INTO normalized_bars(data_snapshot_id,ticker,session,open,high,low,close,volume,source_manifest_hash,certified_reconciliation_manifest_hash,primary_observation_certificate_hash,row_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run('D1','ABUK',session,10,11,9,10,1000,sourceManifestHash,null,null,rowHash);assert.equal(db.db.prepare('SELECT row_hash FROM normalized_bars').get().row_hash,rowHash)}finally{db.close()}});
