import test from'node:test';import assert from'node:assert/strict';import{sha256}from'../src/hash.js';import{certifyUniverseExtraction,verifyUniverseExtractionCertificate}from'../src/universe-extraction-certification.js';
const rows=[{ticker:'ABUK',isin:'EGS38161C013'},{ticker:'COMI',isin:'EGS60121C018'}];
const manifest={sourceAdmissionHash:'a'.repeat(64),sourceContentHash:'b'.repeat(64),extractorId:'egx-bulletin-parser',extractorVersion:'0.1.0',schemaId:'EGX_BULLETIN_EQUITIES_V1',rowCount:rows.length,outputHash:sha256(rows)};manifest.manifestHash=sha256(manifest);const extraction={state:'READY_FOR_SEMANTIC_VALIDATION',manifest};const schema={state:'VERIFIED',fields:['ticker','isin','companyName','segment']};const scope={state:'VERIFIED',scope:'ALL_LISTED_EQUITIES',evidenceLocator:'page-1:listed-equities-section'};
test('semantic and scope verified extraction can be certified for universe authority',()=>{const r=certifyUniverseExtraction(extraction,{parsedRows:rows,schemaValidation:schema,scopeValidation:scope});assert.equal(r.state,'CERTIFIED_FOR_UNIVERSE_AUTHORITY');assert.equal(r.universeAuthorityEligible,true);assert.equal(r.ohlcvAuthorityEligible,false);assert.equal(verifyUniverseExtractionCertificate(r,{parsedRows:rows,extractionManifest:manifest}).state,'READY')});
test('wrong parser output hash blocks certification',()=>{const bad={...extraction,manifest:{...manifest,outputHash:'c'.repeat(64)}};const r=certifyUniverseExtraction(bad,{parsedRows:rows,schemaValidation:schema,scopeValidation:scope});assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('EXTRACTION_OUTPUT_HASH_MISMATCH'))});
test('scope must explicitly prove all listed equities',()=>{const r=certifyUniverseExtraction(extraction,{parsedRows:rows,schemaValidation:schema,scopeValidation:{...scope,scope:'PAGE_ONLY'}});assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('SCOPE_NOT_ALL_LISTED_EQUITIES'))});
test('required identity fields are enforced by semantic schema gate',()=>{const r=certifyUniverseExtraction(extraction,{parsedRows:rows,schemaValidation:{state:'VERIFIED',fields:['ticker']},scopeValidation:scope});assert.equal(r.state,'BLOCKED');assert.ok(r.reasons.includes('SCHEMA_MISSING_FIELD:isin'))});
test('certificate cannot be replayed with different parsed rows',()=>{const r=certifyUniverseExtraction(extraction,{parsedRows:rows,schemaValidation:schema,scopeValidation:scope});const changed=[...rows,{ticker:'SWDY',isin:'EGS3G0Z1C014'}];const v=verifyUniverseExtractionCertificate(r,{parsedRows:changed,extractionManifest:manifest});assert.equal(v.state,'BLOCKED');assert.ok(v.reasons.includes('PARSED_ROWS_HASH_MISMATCH'));assert.ok(v.reasons.includes('PARSED_ROWS_COUNT_MISMATCH'))});
test('tampered certificate hash is rejected',()=>{const r=certifyUniverseExtraction(extraction,{parsedRows:rows,schemaValidation:schema,scopeValidation:scope});const tampered={...r,certificate:{...r.certificate,rowCount:99}};const v=verifyUniverseExtractionCertificate(tampered,{parsedRows:rows,extractionManifest:manifest});assert.equal(v.state,'BLOCKED');assert.ok(v.reasons.includes('CERTIFICATE_HASH_MISMATCH'))});
