#!/usr/bin/env python3
from pathlib import Path
import re

ROOT=Path.cwd(); CENTER=ROOT/'preview-v13/app/unified-decision-center.html'; INDEX=ROOT/'preview-v13/app/index.html'; MARKER='V13_20_MULTI_SESSION_PRIORITY'
CSS=r'''
/* V13_20_MULTI_SESSION_PRIORITY */
.v20-top3{display:grid;grid-template-columns:repeat(3,minmax(220px,1fr));gap:9px;margin:9px 0}.v20-rec{background:linear-gradient(180deg,#102d47,#0a2034);border:1px solid #3b7193;border-radius:13px;padding:13px;min-height:205px}.v20-rec.first{border-color:#d5ad48;box-shadow:0 0 0 1px #6f5926 inset}.v20-rec.second{border-color:#8aa2b5}.v20-rec.third{border-color:#9c724c}.v20-rec h3{margin:0 0 8px;font-size:17px}.v20-rec .prob{font-size:27px;font-weight:bold;color:var(--g);margin:7px 0}.v20-rec .line{display:flex;justify-content:space-between;gap:8px;border-top:1px solid #21455d;padding-top:6px;margin-top:6px;font-size:10px}.v20-rec .line span{color:var(--m)}.v20-toolbar{display:flex;gap:7px;flex-wrap:wrap;align-items:end;margin:9px 0}.v20-toolbar .field{min-width:160px}.v20-pill{display:inline-block;border:1px solid #315f7d;border-radius:999px;padding:4px 7px;font-size:9px}.v20-pill.target{border-color:#2e8b64;color:#c7ffe1}.v20-pill.stop{border-color:#8c4252;color:#ffc7cf}.v20-pill.open{border-color:#8a7130;color:#ffe8aa}.v20-table td{white-space:nowrap}.v20-table .wrap-cell{white-space:normal;min-width:180px}.v20-method{padding:10px;border:1px solid #315f7d;border-radius:10px;background:#091d30;font-size:10px;line-height:1.9}.v20-confidence.high{color:var(--g)}.v20-confidence.medium{color:var(--a)}.v20-confidence.low{color:var(--r)}
@media(max-width:950px){.v20-top3{grid-template-columns:1fr}} 
'''
PANEL=r'''
<div class="panel hidden" id="v1320BacktestPanel" data-v13-20-backtest="true"><div class="section-head"><h2>أفضلية الشراء ونتائج الاختبار المستمر V13.20</h2><span class="muted">التوصية الأولى ثم الثانية ثم الثالثة وفق الاحتمالية التاريخية المقدرة لتحقيق الهدف الأول قبل الوقف خلال 5 جلسات بعد دخول صحيح.</span></div><div class="body">
  <div id="v1320Status"></div>
  <div class="v20-top3" id="v1320RecommendationCards"></div>
  <div class="cards" id="v1320SummaryCards"></div>
  <div class="v20-method" id="v1320Method"></div>
  <div class="section-head" style="padding-right:0;margin-top:10px"><h2>أداء التوصية الأولى والثانية والثالثة</h2><span class="muted">Walk-Forward: كل جلسة تستخدم نتائج حُسمت قبلها فقط.</span></div>
  <div class="table"><table class="v20-table"><thead><tr><th>الترتيب</th><th>الإشارات</th><th>دخلت</th><th>الهدف خلال 1</th><th>3</th><th>5</th><th>10</th><th>الوقف خلال 5</th><th>هبط ثم تعافى</th></tr></thead><tbody id="v1320RankRows"></tbody></table></div>
  <div class="section-head" style="padding-right:0;margin-top:10px"><h2>نتائج التوصيات السابقة والحالية</h2><span class="muted">توصيات اليوم تبدأ بانتظار الجلسة القادمة، ثم تتحدث بعد 1 و2 و3 و5 و10 جلسات.</span></div>
  <div class="v20-toolbar"><div class="field"><label>الحالة<select id="v1320Filter"><option value="ALL">كل النتائج</option><option value="CURRENT">توصيات اليوم</option><option value="OPEN">قيد المتابعة</option><option value="TARGET">حققت الهدف</option><option value="STOP">ضربت الوقف</option><option value="RECOVERED">هبطت ثم تعافت</option><option value="NO_ENTRY">لم تدخل منطقة الشراء</option></select></label></div><div class="field"><label>السهم<input id="v1320Ticker" placeholder="مثال TMGH"></label></div></div>
  <div class="table" style="max-height:520px"><table class="v20-table"><thead><tr><th>جلسة التوصية</th><th>الأولوية</th><th>السهم</th><th>الطبقة</th><th>احتمالية الهدف</th><th>العينة</th><th>الدخول</th><th>بعد 1</th><th>بعد 3</th><th>بعد 5</th><th>بعد 10</th><th>الهدف/الوقف</th><th>الحالة</th></tr></thead><tbody id="v1320ResultRows"></tbody></table></div>
  <div class="notice" style="margin-top:9px">هذه احتمالات تاريخية تقديرية وليست ضمانًا. التوصية مشروطة بدخول السعر في المنطقة المحددة وعدم وجود فجوة خطرة، والتحقق اليدوي من السعر والوسيط. لا توجد أوامر شراء أو بيع تلقائية.</div>
</div></div>
'''
JS=r'''
/* V13_20_MULTI_SESSION_PRIORITY */
const V1320_RESULTS='../../data/research/v13-20-multi-session-results.json';let v1320=null;
function v20Pct(v){return Number.isFinite(Number(v))?`${N(v,1)}%`:'—'}
function v20H(e,h){const x=e?.horizons?.[h];if(!x)return '—';const cls=x.event==='STOP_HIT'?'badText':String(x.event).startsWith('TARGET')?'goodText':Number(x.realisedReturnPct)>=0?'goodText':'badText';return `<span class="${cls}">${v20Pct(x.realisedReturnPct)}</span>`}
function v20State(e,current=false){if(current)return '<span class="v20-pill open">بانتظار الجلسة القادمة</span>';const s=e?.status||'DATA_INCOMPLETE',c=s==='STOP_HIT'?'stop':String(s).startsWith('TARGET')?'target':'open';return `<span class="v20-pill ${c}">${E(e?.statusAr||s)}</span>`}
function v20RecommendationCard(r,i){if(!r)return `<div class="v20-rec"><h3>${['التوصية الأولى','التوصية الثانية','التوصية الثالثة'][i]}</h3><div class="empty">لا توجد فرصة مؤهلة لهذا المركز.</div></div>`;const cls=i===0?'first':i===1?'second':'third',conf=String(r.confidenceLabelAr||'منخفضة'),cc=conf==='مرتفعة'?'high':conf==='متوسطة'?'medium':'low';return `<div class="v20-rec ${cls}"><h3>${E(r.recommendationLabelAr)}</h3><div><b class="ticker">${E(r.ticker)}</b> — ${E(r.companyNameAr||'')}</div><div class="prob">${v20Pct(r.targetProbabilityPct)}</div><small>احتمالية تاريخية تقديرية لتحقيق الهدف الأول قبل الوقف خلال 5 جلسات بعد دخول صحيح.</small><div class="line"><span>الطبقة</span><b>${E(r.tier==='STRICT_PAPER'?'صارمة':'A')}</b></div><div class="line"><span>الدخول</span><b>${N(r.entryLow,3)}–${N(r.entryHigh,3)}</b></div><div class="line"><span>الهدف الأول / الوقف</span><b>${N(r.target1,3)} / ${N(r.stopLoss,3)}</b></div><div class="line"><span>العينة الفعالة</span><b>${N(r.effectiveSample,1)} — <span class="v20-confidence ${cc}">${E(conf)}</span></b></div><div class="line"><span>حالة النموذج</span><b>${r.modelStatus==='WALK_FORWARD'?'Walk-Forward':'عينة محدودة'}</b></div></div>`}
function renderV1320(){const panel=document.getElementById('v1320BacktestPanel');if(!panel)return;if(!v1320){document.getElementById('v1320Status').innerHTML='<div class="status warn">نتائج V13.20 غير متاحة بعد. شغّل Workflow التثبيت/الإنتاج لبناء الاختبار.</div>';document.getElementById('v1320RecommendationCards').innerHTML=[0,1,2].map(i=>v20RecommendationCard(null,i)).join('');return}const cur=A(v1320.currentSession?.recommendations);document.getElementById('v1320RecommendationCards').innerHTML=[0,1,2].map(i=>v20RecommendationCard(cur[i],i)).join('');const h=v1320.historical||{},m=v1320.model||{},h5=A(h.horizons).find(x=>Number(x.horizonSessions)===5)||{};document.getElementById('v1320SummaryCards').innerHTML=[card('جلسات تاريخية',N(h.sessions,0),`${h.firstSignalDate||'—'} → ${h.lastSignalDate||'—'}`),card('إشارات مختبرة',N(h.signals,0),`دخلت ${N(h.entered,0)}`),card('تحقيق الهدف خلال 5',v20Pct(h5.target1HitRatePct),`عينة ${N(h5.sample,0)}`,'goodText'),card('ضرب الوقف خلال 5',v20Pct(h5.stopRatePct),'STOP_FIRST عند الغموض','badText'),card('هبط ثم تعافى',N(h.initialDownThenRecovered,0),'حقق الهدف بعد هبوط مبدئي'),card('عينة التدريب المحسومة',N(m.resolvedTrainingSignals,0),`دخلت ${N(m.enteredTrainingSignals,0)}`),card('وضع النموذج',m.status==='WALK_FORWARD_AVAILABLE'?'متاح':'عينة محدودة','بحثي ولا يغير الإنتاج',m.status==='WALK_FORWARD_AVAILABLE'?'goodText':'warnText'),card('جلسة اليوم',v1320.currentSession?.sessionDate||'—',`${N(cur.length,0)} توصية مشروطة`)].join('');document.getElementById('v1320Status').innerHTML=`<div class="status ${cur.length?'warn':'bad'}"><b>${cur.length?'تم ترتيب الفرص المؤهلة تلقائيًا':'لا توجد توصية شراء مؤهلة حاليًا'}</b><br>${E(m.warningAr||'')}</div>`;document.getElementById('v1320Method').innerHTML=`<b>منهج الاختبار:</b> ${E(v1320.methodology?.rankingRuleAr||'')}<br>نافذة الدخول: ${N(v1320.methodology?.entryExpirySessions,0)} جلسات — نافذة القياس الأساسية: ${N(v1320.methodology?.primaryHorizonSessions,0)} جلسات — المتابعة: ${A(v1320.methodology?.horizons).join('، ')} جلسة.<br>أسهم B للمراقبة فقط ولا تتقدم على A. بيانات أي جلسة مستقبلية ممنوعة من تدريب جلسة أقدم.`;document.getElementById('v1320RankRows').innerHTML=A(v1320.rankPerformance).map(r=>{const h1=A(r.horizons).find(x=>x.horizonSessions===1)||{},h3=A(r.horizons).find(x=>x.horizonSessions===3)||{},h5=A(r.horizons).find(x=>x.horizonSessions===5)||{},h10=A(r.horizons).find(x=>x.horizonSessions===10)||{};return `<tr><td><b>${E(r.recommendationLabelAr)}</b></td><td>${N(r.signals,0)}</td><td>${N(r.entered,0)}</td><td>${v20Pct(h1.target1HitRatePct)}</td><td>${v20Pct(h3.target1HitRatePct)}</td><td>${v20Pct(h5.target1HitRatePct)}</td><td>${v20Pct(h10.target1HitRatePct)}</td><td>${v20Pct(h5.stopRatePct)}</td><td>${N(r.initialDownThenRecovered,0)}</td></tr>`}).join('')||'<tr><td colspan="9" class="empty">لا توجد جلسات كافية لترتيب تاريخي بعد.</td></tr>';renderV1320Rows()}
function renderV1320Rows(){if(!v1320)return;const filter=document.getElementById('v1320Filter')?.value||'ALL',q=String(document.getElementById('v1320Ticker')?.value||'').trim().toUpperCase(),today=v1320.currentSession?.sessionDate;let rows=[];for(const s of A(v1320.sessions)){for(const r of A(s.recommendations))rows.push({sessionDate:s.sessionDate,...r,evaluation:r.evaluation,current:false})}for(const r of A(v1320.currentSession?.recommendations))rows.push({sessionDate:today,...r,evaluation:null,current:true});rows=rows.filter(r=>!q||String(r.ticker).includes(q)).filter(r=>{const e=r.evaluation;if(filter==='ALL')return true;if(filter==='CURRENT')return r.current;if(filter==='OPEN')return !r.current&&['OPEN','TEMPORARY_DRAWDOWN','PENDING_ENTRY'].includes(e?.status);if(filter==='TARGET')return e?.target1Hit;if(filter==='STOP')return e?.stopHit;if(filter==='RECOVERED')return e?.initialDownThenRecovered;if(filter==='NO_ENTRY')return e?.status==='NOT_ENTERED';return true}).sort((a,b)=>String(b.sessionDate).localeCompare(String(a.sessionDate))||a.recommendationRank-b.recommendationRank);document.getElementById('v1320ResultRows').innerHTML=rows.map(r=>{const e=r.evaluation;return `<tr><td>${E(r.sessionDate||'—')}</td><td><b>${E(r.recommendationLabelAr)}</b></td><td><b class="ticker">${E(r.ticker)}</b></td><td>${E(r.tier==='STRICT_PAPER'?'صارمة':'A')}</td><td>${v20Pct(r.targetProbabilityPct)}<br><span class="muted">${E(r.confidenceLabelAr||'')}</span></td><td>${N(r.effectiveSample,1)}</td><td>${r.current?'مشروط':e?.entered?`${E(e.entryDate)} @ ${N(e.entryPrice,3)}`:E(e?.statusAr||'—')}</td><td>${v20H(e,1)}</td><td>${v20H(e,3)}</td><td>${v20H(e,5)}</td><td>${v20H(e,10)}</td><td>${e?.target1Hit?`هدف1 بعد ${N(e.target1Session,0)}`:e?.stopHit?`وقف بعد ${N(e.stopSession,0)}`:'—'}</td><td>${v20State(e,r.current)}</td></tr>`}).join('')||'<tr><td colspan="13" class="empty">لا توجد نتائج مطابقة.</td></tr>'}
async function v1320Refresh(){v1320=await fetchOptional(V1320_RESULTS);renderV1320()}
'''

def replace_once(text, old, new, label):
    if old not in text: raise SystemExit(f'Missing insertion point: {label}')
    return text.replace(old,new,1)

def main():
    if not CENTER.exists(): raise SystemExit(f'Missing {CENTER}')
    html=CENTER.read_text('utf-8')
    if MARKER in html:
        print('V13.20 UI already installed.')
        return
    if 'V13_19_RECOMMENDATION_HISTORY_RISK_HEALTH' not in html:
        raise SystemExit('V13.19 must be installed before V13.20')
    html=replace_once(html,'</style>',CSS+'\n</style>','style end')
    html=html.replace('<title>V13.19 — التوصيات والمحفظة والمخاطر</title>','<title>V13.20 — أفضلية الشراء والاختبار المستمر</title>',1)
    html=html.replace('<h1>V13.19 — التوصيات والمحفظة والمخاطر</h1>','<h1>V13.20 — أفضلية الشراء والاختبار المستمر</h1>',1)
    html=html.replace('إصدار متابعة متكامل: سجل التوصيات، دورة حياة الصفقة، مخاطر المحفظة وصحة النظام، مع بقاء التنفيذ لدى الوسيط يدويًا.','ترتيب تلقائي واضح: التوصية الأولى والثانية والثالثة، مع اختبار مستمر عبر 1 و2 و3 و5 و10 جلسات، والمحفظة والمخاطر وصحة النظام.',1)
    html=replace_once(html,'<button class="btn" id="toggleRecommendationHistory">سجل التوصيات</button>','<button class="btn" id="toggleRecommendationHistory">سجل التوصيات</button><button class="btn primary" id="toggleV1320Backtest">أفضلية الشراء والاختبار</button>','hero button')
    html=replace_once(html,'<div class="panel hidden" id="portfolioRiskPanel"',PANEL+'\n<div class="panel hidden" id="portfolioRiskPanel"','panel')
    html=replace_once(html,'function renderOperations(){',JS+'\nfunction renderOperations(){','js functions')
    html=replace_once(html,'await v1319Refresh();selected=', 'await v1319Refresh();await v1320Refresh();selected=','load integration')
    html=replace_once(html,"document.getElementById('toggleRecommendationHistory').onclick=", "document.getElementById('toggleV1320Backtest').onclick=()=>{document.getElementById('v1320BacktestPanel').classList.toggle('hidden');renderV1320()};document.getElementById('v1320Filter').onchange=renderV1320Rows;document.getElementById('v1320Ticker').oninput=renderV1320Rows;document.getElementById('toggleRecommendationHistory').onclick=",'events')
    html=html.replace("metric('واجهة المتابعة','13.19')","metric('واجهة المتابعة','13.20')",1)
    html=html.replace("تعذر تحميل مركز V13.19","تعذر تحميل مركز V13.20",1)
    html=html.replace("EGX Pro V13.19","EGX Pro V13.20",1)
    CENTER.write_text(html,'utf-8')
    if INDEX.exists():
        idx=INDEX.read_text('utf-8')
        idx=idx.replace('V13.19 — التوصيات والمحفظة والمخاطر','V13.20 — أفضلية الشراء والاختبار المستمر')
        INDEX.write_text(idx,'utf-8')
    print('V13.20 UI installed.')
if __name__=='__main__': main()
