'use strict';
const fs=require('node:fs'); const path=require('node:path'); const {compareEngines}=require('./tracking');
function tickerOf(x){return String(x?.ticker||x?.symbol||x?.code||'').toUpperCase().trim()}
function isBullishMain(x){const s=String(x?.direction||x?.status||x?.recommendation||x?.signal||'').toUpperCase();return ['BUY','STRONG_BUY','HIGH_CONVICTION_BUY','شراء','شراء قوي','تجميع'].some(v=>s.includes(v))&&!['بيع','SELL','رفض','REJECT'].some(v=>s.includes(v))}
function extractMainRecommendations(payload){for(const key of ['recommendations','top5','topRecommendations','selected','basket'])if(Array.isArray(payload?.[key]))return payload[key].filter(x=>tickerOf(x));if(Array.isArray(payload?.all))return payload.all.filter(x=>tickerOf(x)&&isBullishMain(x));return[]}
function buildComparison(mainPayload,quantResult){const main=extractMainRecommendations(mainPayload),quant=quantResult?.recommendations||[],mm=new Map(main.map(x=>[tickerOf(x),x])),qm=new Map(quant.map(x=>[tickerOf(x),x])),tickers=[...new Set([...mm.keys(),...qm.keys()])].sort(),rows=tickers.map(t=>{const m=mm.get(t)||null,q=qm.get(t)||null;return{ticker:t,classification:compareEngines(m,q),main:m?{direction:m.direction||m.status||m.recommendation||m.signal||null,confidence:m.finalConfidence??m.confidence??null}:null,quant:q?{direction:q.direction,status:q.status,coreConfidence:q.coreConfidence,finalConfidence:q.finalConfidence,probability:q.probability,trade:q.trade}:null}}),counts={};for(const r of rows)counts[r.classification]=(counts[r.classification]||0)+1;return{schemaVersion:1,generatedAt:new Date().toISOString(),comparisonOnly:true,fedBackIntoQuant:false,mainEngine:mainPayload?.engine||null,mainGeneratedAt:mainPayload?.generatedAt||null,quantEngine:quantResult?.engine||'QUANT EDGE',quantGeneratedAt:quantResult?.generatedAt||null,mainRecommendationCount:main.length,quantRecommendationCount:quant.length,counts,rows}}
function compareFiles(mainPath,quantPath,outPath){const main=JSON.parse(fs.readFileSync(mainPath,'utf8')),quant=JSON.parse(fs.readFileSync(quantPath,'utf8')),result=buildComparison(main,quant);if(outPath){fs.mkdirSync(path.dirname(outPath),{recursive:true});fs.writeFileSync(outPath,JSON.stringify(result,null,2)+'\n')}return result}
if(require.main===module){const main=process.argv[2],quant=process.argv[3],out=process.argv[4];if(!main||!quant)throw new Error('Usage: compare-main.js <main.json> <quant.json> [out.json]');console.log(JSON.stringify(compareFiles(main,quant,out),null,2))}
module.exports={tickerOf,isBullishMain,extractMainRecommendations,buildComparison,compareFiles};
