'use strict';

const fs = require('node:fs');
const path = require('node:path');
const config = require('./config');
const { analyzeSymbol } = require('./engine');
const { tripleBarrierOutcome } = require('./tracking');
const { EmpiricalProbabilityCalibrator } = require('./probability');
const { validateIndependentSnapshot } = require('./data-boundary');

const DEFAULT_BINS=[{minScore:68,maxScore:74.999},{minScore:75,maxScore:81.999},{minScore:82,maxScore:88.999},{minScore:89,maxScore:100}];
function barsUpTo(bars,date){return bars.filter(b=>!b.date||b.date<=date)}
function buildObservations(snapshot,options={}){validateIndependentSnapshot(snapshot);const stride=Number(options.stride||process.env.QE_WF_STRIDE||3),maxSamplesPerSymbol=Number(options.maxSamplesPerSymbol||process.env.QE_WF_MAX_PER_SYMBOL||70),observations=[],skipped=[];for(const symbol of snapshot.symbols){const bars=symbol.bars,minI=config.engine.minBars-1,horizon=Number(options.maxHorizon||20),start=Math.max(minI,bars.length-(maxSamplesPerSymbol*stride+horizon+1));for(let i=start;i<bars.length-5;i+=stride){const signalBar=bars[i],benchmarkBars=barsUpTo(snapshot.benchmark.bars,signalBar.date);if(benchmarkBars.length<config.engine.minBars)continue;try{const result=analyzeSymbol({ticker:symbol.ticker,bars:bars.slice(0,i+1),benchmarkBars,brokerRecommendations:[]});if(result.direction!=='BUY'||!result.trade)continue;const future=bars.slice(i+1,i+1+result.trade.timeStopSessions);if(future.length<3)continue;const entry=(result.trade.entryZone[0]+result.trade.entryZone[1])/2,outcome=tripleBarrierOutcome({entry,stop:result.trade.stop,tp1:result.trade.tp1,tp2:result.trade.tp2,bars:future,maxSessions:result.trade.timeStopSessions});observations.push({ticker:symbol.ticker,signalDate:signalBar.date,coreConfidence:result.coreConfidence,setup:result.selectedSetup.name,regime:result.regime.code,tp1BeforeSl:outcome.tp1BeforeSl,tp2BeforeSl:outcome.tp2BeforeSl,firstBarrier:outcome.firstBarrier,mfe:outcome.mfe,mae:outcome.mae,sessionsObserved:outcome.sessionsObserved})}catch(err){skipped.push({ticker:symbol.ticker,date:signalBar.date,error:err.message})}}}observations.sort((a,b)=>String(a.signalDate).localeCompare(String(b.signalDate))||a.ticker.localeCompare(b.ticker));return{observations,skipped}}
function wilson(successes,n,z=1.96){if(!n)return[null,null];const p=successes/n,den=1+z*z/n,center=(p+z*z/(2*n))/den,margin=(z*Math.sqrt((p*(1-p)+z*z/(4*n))/n))/den;return[Math.max(0,center-margin),Math.min(1,center+margin)]}
function makeBuckets(observations,bins=DEFAULT_BINS){return bins.map(bin=>{const rows=observations.filter(o=>o.coreConfidence>=bin.minScore&&o.coreConfidence<=bin.maxScore),n=rows.length,s1=rows.filter(o=>o.tp1BeforeSl).length,s2=rows.filter(o=>o.tp2BeforeSl).length;return{...bin,samples:n,tp1BeforeSl:n?s1/n:null,tp2BeforeSl:n?s2/n:null,tp1Wilson95:wilson(s1,n),tp2Wilson95:wilson(s2,n),calibrated:n>=30}})}
function brierValidation(rows,buckets,target='tp1BeforeSl'){let sum=0,n=0;for(const r of rows){const b=buckets.find(x=>r.coreConfidence>=x.minScore&&r.coreConfidence<=x.maxScore&&x.samples>=30);if(!b)continue;const p=b[target];if(!Number.isFinite(p))continue;const y=r[target]?1:0;sum+=(p-y)**2;n++}return{samples:n,brier:n?sum/n:null}}
function buildWalkForwardCalibration(snapshot,options={}){const{observations,skipped}=buildObservations(snapshot,options),cut=Math.floor(observations.length*.8),train=observations.slice(0,cut),validation=observations.slice(cut),trainBuckets=makeBuckets(train,options.bins||DEFAULT_BINS),productionBuckets=makeBuckets(observations,options.bins||DEFAULT_BINS),validatedBuckets=trainBuckets.filter(b=>b.samples>=30).length;return{schemaVersion:1,engine:config.engine.name,engineVersion:config.engine.version,method:'EXPANDING_PAST_ONLY_SIGNALS_WITH_TEMPORAL_80_20_HOLDOUT',generatedAt:new Date().toISOString(),snapshotAsOf:snapshot.asOf,totalCompletedSignals:observations.length,trainSignals:train.length,validationSignals:validation.length,validatedBuckets,calibrationReady:productionBuckets.some(b=>b.samples>=30),trainBuckets,productionBuckets,validation:{tp1:brierValidation(validation,trainBuckets,'tp1BeforeSl'),tp2:brierValidation(validation,trainBuckets,'tp2BeforeSl')},observations,skippedCount:skipped.length,notes:['Every signal uses only bars available on its signal date.','Future bars are used only for outcome labeling.','Broker research is excluded from calibration so empirical probabilities calibrate the quantitative core.']}}
function calibratorFromReport(report){return new EmpiricalProbabilityCalibrator((report?.productionBuckets||[]).filter(b=>b.samples>=30))}
function loadCalibrator(filePath){if(!filePath||!fs.existsSync(filePath))return null;const report=JSON.parse(fs.readFileSync(filePath,'utf8'));return report.calibrationReady?calibratorFromReport(report):null}
function cli(){const input=process.argv[2]||path.join(__dirname,'data','independent-snapshot.json'),out=process.argv[3]||path.join(__dirname,'data','calibration.json'),snapshot=JSON.parse(fs.readFileSync(input,'utf8')),report=buildWalkForwardCalibration(snapshot);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({ok:true,totalSignals:report.totalCompletedSignals,calibrationReady:report.calibrationReady,validatedBuckets:report.validatedBuckets,output:out}))}
if(require.main===module){try{cli()}catch(err){console.error(err.stack||err);process.exit(1)}}
module.exports={DEFAULT_BINS,barsUpTo,buildObservations,wilson,makeBuckets,brierValidation,buildWalkForwardCalibration,calibratorFromReport,loadCalibrator};
