#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'../..'),OUT=path.join(ROOT,'gann-fusion-x','data'),HIST=path.join(ROOT,'data','history');
const I=require(path.join(ROOT,'gann-fusion-x','engine','indicators.js')),Fusion=require(path.join(ROOT,'gann-fusion-x','engine','fusion.js'));
const COST=.6,HOLD=3,TOPN=3,EXTENDED_DATES=60;
const read=(p,d=null)=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return d}};
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const num=v=>finite(v)?Number(v):null;
const round=(v,d=4)=>finite(v)?Number(Number(v).toFixed(d)):null;
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
function median(a){if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;}
const pct=(a,b)=>finite(a)&&finite(b)&&Number(b)!==0?((Number(a)/Number(b))-1)*100:null;
function normalizeBars(doc,adjusted=false){return(doc?.sessions||[]).map(x=>{const rawClose=num(x.close),adjClose=num(x.adjustedClose),close=adjusted?(adjClose??rawClose):rawClose,f=adjusted&&rawClose>0&&close>0?close/rawClose:1;return{date:String(x.date||''),open:num(x.open)===null?null:Number(x.open)*f,high:num(x.high)===null?null:Number(x.high)*f,low:num(x.low)===null?null:Number(x.low)*f,close,volume:num(x.volume)};}).filter(x=>x.date&&x.close>0&&x.high>0&&x.low>0&&x.open>0).sort((a,b)=>a.date.localeCompare(b.date));}
const toDate=(bs,date)=>bs.filter(x=>x.date<=date),future=(bs,date,n=HOLD)=>bs.filter(x=>x.date>date).slice(0,n);
const files=fs.readdirSync(HIST).filter(x=>x.endsWith('.json')),universe=[];
for(const file of files){const doc=read(path.join(HIST,file));if(!doc)continue;const raw=normalizeBars(doc,false),adj=normalizeBars(doc,true);if(adj.length<55)continue;universe.push({ticker:String(doc.ticker||file.replace(/\.json$/i,'')).toUpperCase(),nameAr:doc.companyNameAr||doc.companyNameEn||'',raw,adj});}
const byTicker=new Map(universe.map(x=>[x.ticker,x]));
function buildBenchmark(date){const map=new Map();for(const u of universe){const bs=toDate(u.adj,date);if(bs.length<30||bs.at(-1)?.date!==date)continue;const base=bs[0].close;if(!(base>0))continue;for(const b of bs){if(!map.has(b.date))map.set(b.date,[]);map.get(b.date).push(b.close/base*100);}}return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([d,v])=>{const c=mean(v);return{date:d,open:c,high:c,low:c,close:c,volume:null};});}
function technicalProxyCandidates(date){const market=buildBenchmark(date),rows=[];for(const u of universe){const bs=toDate(u.adj,date);if(bs.length<50||bs.at(-1)?.date!==date)continue;const trend=I.trend(bs),rs=I.rs(bs,market),mom=I.momentum(bs),vol=I.volume(bs),bo=I.breakout(bs);if([trend,rs,mom,vol,bo].some(x=>x?.known!==true||!finite(x?.score)))continue;const rp=Fusion.risk(bs,{nextAbove:0},bo);if(rp?.known!==true||!finite(rp?.score)||!finite(rp?.rr))continue;const entry=bo.confirmed?90:bo.near?78:Math.max(25,Number(bo.score)),score=round(Number(trend.score)*.24+Number(rs.score)*.18+Number(mom.score)*.12+Number(vol.score)*.18+entry*.16+Number(rp.score)*.12,1),avoid=Number(trend.score)<60||Number(rs.score)<20||mom.overheated,recommendation=!avoid&&(bo.near||bo.confirmed||Number(score)>=72);if(!recommendation)continue;const e=(Number(rp.entryLow)+Number(rp.entryHigh))/2,r=Math.max(.0001,e-Number(rp.stopLoss));rows.push({engine:'SEPA_TECHNICAL_PROXY',date,ticker:u.ticker,score,levels:{entryLow:rp.entryLow,entryHigh:rp.entryHigh,trigger:rp.trigger,stopLoss:rp.stopLoss,target1:rp.target1,target2:rp.target2,target3:round(e+r*3,4)},sourceScale:'adjusted',meta:{technicalProxy:true,pointInTimeFundamentalsUsed:false,trend:trend.score,rs:rs.score,momentum:mom.score,volume:vol.score,risk:rp.score}});}return rows.sort((a,b)=>Number(b.score)-Number(a.score)||a.ticker.localeCompare(b.ticker)).slice(0,TOPN);}
function v16Candidates(session){return(session.members||[]).map(m=>({engine:'V16_9_LIVE',date:session.signalDate,ticker:String(m.ticker||'').toUpperCase(),score:null,levels:{entryLow:num(m.entryLow),entryHigh:num(m.entryHigh),trigger:num(m.entryHigh),stopLoss:num(m.stopLoss),target1:num(m.target1),target2:null,target3:null},sourceScale:'raw',meta:{logged:true,weightPct:num(m.weightPct)}})).filter(x=>byTicker.has(x.ticker)&&[x.levels.entryLow,x.levels.entryHigh,x.levels.stopLoss,x.levels.target1].every(v=>finite(v)&&v>0));}
function evaluate(sig){const u=byTicker.get(sig.ticker);if(!u)return{...sig,status:'NO_HISTORY',entryPrice:null,exitPrice:null,grossReturnPct:null,netReturnPct:null};const bs=sig.sourceScale==='raw'?u.raw:u.adj,win=future(bs,sig.date,HOLD),l=sig.levels;if(win.length<HOLD)return{...sig,status:'INSUFFICIENT_FUTURE',entryPrice:null,exitPrice:null,grossReturnPct:null,netReturnPct:null};let entered=false,entry=null,entryDate=null,exit=null,exitDate=null,status='UNFILLED';for(const b of win){if(!entered){if(b.open>=l.entryLow&&b.open<=l.entryHigh){entry=b.open;entered=true;entryDate=b.date;}else if(b.low<=l.entryHigh&&b.high>=l.entryLow){entry=b.open>l.entryHigh?l.entryHigh:b.open<l.entryLow?l.entryLow:l.entryHigh;entered=true;entryDate=b.date;}else continue;}const hitStop=b.low<=l.stopLoss,hitTarget=b.high>=l.target1;if(hitStop&&hitTarget){exit=l.stopLoss;exitDate=b.date;status='STOP_SAME_BAR';break;}if(hitStop){exit=l.stopLoss;exitDate=b.date;status='STOP_HIT';break;}if(hitTarget){exit=l.target1;exitDate=b.date;status='TARGET_HIT';break;}}
if(!entered)return{...sig,status:'UNFILLED',entryPrice:null,entryDate:null,exitPrice:null,exitDate:null,grossReturnPct:null,netReturnPct:null,window:win.map(x=>x.date)};if(exit===null){exit=win.at(-1).close;exitDate=win.at(-1).date;status='TIME_EXIT';}const gross=pct(exit,entry),net=finite(gross)?Number(gross)-COST:null;return{...sig,status,entryPrice:round(entry),entryDate,exitPrice:round(exit),exitDate,grossReturnPct:round(gross,3),netReturnPct:round(net,3),window:win.map(x=>x.date)};}
function maxDrawdown(values){if(!values.length)return null;let eq=1,peak=1,mdd=0;for(const r of values){eq*=1+Number(r)/100;peak=Math.max(peak,eq);mdd=Math.min(mdd,(eq/peak-1)*100);}return mdd;}
function summarize(rows){const valid=rows.filter(x=>!['NO_HISTORY','INSUFFICIENT_FUTURE'].includes(x.status)),filled=valid.filter(x=>x.status!=='UNFILLED'&&finite(x.netReturnPct)),nets=filled.map(x=>Number(x.netReturnPct)),pos=nets.filter(x=>x>0),neg=nets.filter(x=>x<0),byDate=new Map();for(const r of filled){if(!byDate.has(r.date))byDate.set(r.date,[]);byDate.get(r.date).push(Number(r.netReturnPct));}const daily=[...byDate.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,v])=>({date,netPct:round(mean(v),3),trades:v.length}));let eq=1;for(const d of daily)eq*=1+d.netPct/100;const noSample=filled.length===0,profitFactor=neg.length?pos.reduce((a,b)=>a+b,0)/Math.abs(neg.reduce((a,b)=>a+b,0)):null;return{signals:valid.length,filled:filled.length,unfilled:valid.filter(x=>x.status==='UNFILLED').length,fillRatePct:valid.length?round(filled.length/valid.length*100,1):null,positiveTradeRatePct:noSample?null:round(pos.length/filled.length*100,1),targetHitPct:noSample?null:round(filled.filter(x=>x.status==='TARGET_HIT').length/filled.length*100,1),stopHitPct:noSample?null:round(filled.filter(x=>x.status.startsWith('STOP')).length/filled.length*100,1),timeExitPct:noSample?null:round(filled.filter(x=>x.status==='TIME_EXIT').length/filled.length*100,1),averageNetPct:noSample?null:round(mean(nets),3),medianNetPct:noSample?null:round(median(nets),3),profitFactor:round(profitFactor,2),profitFactorInfinite:!noSample&&neg.length===0&&pos.length>0,sessions:daily.length,winningSessionRatePct:daily.length?round(daily.filter(x=>x.netPct>0).length/daily.length*100,1):null,avgBasketNetPct:daily.length?round(mean(daily.map(x=>x.netPct)),3):null,compoundedBasketPct:daily.length?round((eq-1)*100,3):null,maxDrawdownPct:daily.length?round(maxDrawdown(daily.map(x=>x.netPct)),3):null,daily};}
const live=read(path.join(ROOT,'data','stable','v16-v169-live-evaluation.json'),{sessions:[]}),liveSessions=(live.sessions||[]).filter(s=>s.signalDate&&Array.isArray(s.members)&&s.members.length),commonDates=[];
for(const s of liveSessions){if((s.members||[]).some(m=>{const u=byTicker.get(String(m.ticker||'').toUpperCase());return u&&future(u.raw,s.signalDate,HOLD).length===HOLD;}))commonDates.push(s.signalDate);}
const uniqCommon=[...new Set(commonDates)].sort(),commonRows=[];for(const date of uniqCommon){const s=liveSessions.find(x=>x.signalDate===date);commonRows.push(...[...v16Candidates(s),...technicalProxyCandidates(date)].map(evaluate));}
const allDates=[...new Set(universe.flatMap(u=>u.adj.map(b=>b.date)))].sort(),lastUsable=allDates.filter(d=>universe.some(u=>future(u.adj,d,HOLD).length===HOLD)),extDates=lastUsable.slice(-EXTENDED_DATES),extRows=[];for(const date of extDates)extRows.push(...technicalProxyCandidates(date).map(evaluate));
const unavailable={signals:0,filled:0,unfilled:0,fillRatePct:null,positiveTradeRatePct:null,targetHitPct:null,stopHitPct:null,timeExitPct:null,averageNetPct:null,medianNetPct:null,profitFactor:null,profitFactorInfinite:false,sessions:0,winningSessionRatePct:null,avgBasketNetPct:null,compoundedBasketPct:null,maxDrawdownPct:null,daily:[],status:'NOT_VALIDATED_HISTORICALLY'};
const result={schemaVersion:'gann-fusion-x-comparison-v2-diagnostic',generatedAt:new Date().toISOString(),validation:{fullEngineBacktestValid:false,pointInTimeFundamentalsAvailable:false,reason:'The current engine requires verified fundamentals. No immutable point-in-time market-wide fundamental history is verified in the repository, so a full historical GANN_FUSION_X performance claim would introduce leakage or fabrication.',performanceAcceptanceAllowed:false},method:{holdingSessions:HOLD,roundTripCostPct:COST,sameBarTargetStop:'STOP_CONSERVATIVE',entry:'NEXT_SESSION_ZONE_TOUCH',topSignalsPerSession:TOPN,lookaheadForbidden:true,missingNumericValuesRemainUnknown:true},comparability:{V16_9_LIVE:'Exact logged V16.9 recommendations re-evaluated under the stated execution rule.',GANN_FUSION_X:'Not historically performance-validated because point-in-time verified fundamentals are unavailable.',SEPA_TECHNICAL_PROXY:'Technical-only reconstructed diagnostic. It excludes fundamentals and is not an exact SEPA-X historical ledger.'},limitations:['Current history-file universe can introduce survivorship/coverage bias.','No cross-engine ranking is produced while survivorship bias or model-fidelity gaps remain.','SEPA technical proxy is diagnostic only and cannot validate the current full engine.','Results are research diagnostics and do not establish future profitability.'],universe:{historyFiles:files.length,eligibleHistories:universe.length},commonDateTest:{dates:uniqCommon,summary:{V16_9_LIVE:summarize(commonRows.filter(x=>x.engine==='V16_9_LIVE')),GANN_FUSION_X:unavailable,SEPA_TECHNICAL_PROXY:summarize(commonRows.filter(x=>x.engine==='SEPA_TECHNICAL_PROXY'))},ranking:[],rows:commonRows},extendedWalkForward:{dates:extDates,summary:{GANN_FUSION_X:unavailable,SEPA_TECHNICAL_PROXY:summarize(extRows)},ranking:[],rows:extRows}};
fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,'backtest-comparison.json'),JSON.stringify(result,null,2)+'\n');
const md=['# EGX Backtest / Leakage Diagnostic','',`Generated: ${result.generatedAt}`,'',`Full current-engine historical validation: **NO**`,'','Reason: verified point-in-time fundamentals are unavailable for a market-wide historical run. Missing values were not replaced with neutral fundamentals or zeros.','','The V16.9 logged series and the SEPA technical proxy remain diagnostic evidence only. No cross-engine ranking is produced while survivorship/model-fidelity limitations remain.'];fs.writeFileSync(path.join(OUT,'backtest-comparison.md'),md.join('\n')+'\n');console.log(JSON.stringify({validation:result.validation,universe:result.universe,commonDates:uniqCommon.length,extendedDates:extDates.length,commonSummary:result.commonDateTest.summary,extendedSummary:result.extendedWalkForward.summary},null,2));
