#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'../..'),GFX=path.join(ROOT,'gann-fusion-x'),DATA=path.join(GFX,'data'),HIST=path.join(ROOT,'data','history');
const Fusion=require(path.join(GFX,'engine','fusion.js')),Planner=require(path.join(GFX,'engine','planner.js'));
const COST=.6,HOLD=3,TOPN=3;
function read(f,d=null){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){return d}}
function write(f,x){fs.writeFileSync(f,JSON.stringify(x,null,2)+'\n')}
function round(n,d=4){return Number.isFinite(Number(n))?Number(Number(n).toFixed(d)):null}
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function pct(a,b){return b?((a/b)-1)*100:0}
function normBars(doc){return(doc?.sessions||[]).map(x=>{const c=Number(x.close),a=Number(x.adjustedClose??x.close),f=c?a/c:1;return{date:x.date,open:Number(x.open)*f,high:Number(x.high)*f,low:Number(x.low)*f,close:a,volume:Number(x.volume||0)}}).filter(x=>x.close>0&&x.high>0&&x.low>0).sort((a,b)=>a.date.localeCompare(b.date))}
const files=fs.existsSync(HIST)?fs.readdirSync(HIST).filter(x=>x.endsWith('.json')):[],universe=[];for(const file of files){const doc=read(path.join(HIST,file));if(!doc)continue;const bars=normBars(doc);if(bars.length<50)continue;universe.push({ticker:String(doc.ticker||file.replace(/\.json$/i,'')).toUpperCase(),nameAr:doc.companyNameAr||doc.companyNameEn||'',bars})}const byTicker=new Map(universe.map(x=>[x.ticker,x]));
function barsTo(u,date){return u.bars.filter(x=>x.date<=date)}
function future(u,date,n=HOLD){return u.bars.filter(x=>x.date>date).slice(0,n)}
function benchmark(date){const map=new Map();for(const u of universe){const bs=barsTo(u,date);if(bs.length<30||bs.at(-1)?.date!==date)continue;const base=bs[0].close;if(!base)continue;for(const b of bs){if(!map.has(b.date))map.set(b.date,[]);map.get(b.date).push(b.close/base*100)}}return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,v])=>{const c=mean(v);return{date,open:c,high:c,low:c,close:c,volume:1}})}
function currentMarket(){const m=read(path.join(ROOT,'data','quant','market-search-index-v13-17.json'),{});return{date:m.marketDate||m.analysisSession||null,generatedAt:m.generatedAt||null,stocks:Array.isArray(m.stocks)?m.stocks:[]}}
function gannSignals(date,marketStocks){if(!date)return[];const market=benchmark(date),liq=new Map((marketStocks||[]).map(x=>[String(x.ticker).toUpperCase(),Number(x.liquidityPercentile)])),rows=[];for(const u of universe){const bs=barsTo(u,date);if(bs.length<50||bs.at(-1)?.date!==date)continue;const a=Fusion.analyze({ticker:u.ticker,nameAr:u.nameAr,bars:bs,marketBars:market,fundamentals:{score:50,verified:false},dataQuality:{fresh:true,conflict:false}});if(!a.valid)continue;const p=Planner.buildPlan(a,'speculative',{portfolioValue:100000,riskPct:.5,verifiedFundamentals:false});if(!p.eligible)continue;const lp=liq.get(u.ticker);if(Number.isFinite(lp)&&lp<20)continue;rows.push({ticker:u.ticker,nameAr:u.nameAr,rank:0,score:round(p.score,1),action:p.decision?.code||a.classification?.code||'RESEARCH',entryLow:round(p.levels.entryLow),entryHigh:round(p.levels.entryHigh),stopLoss:round(p.levels.stopLoss),target1:round(p.levels.target1),target2:round(p.levels.target2),target3:round(p.levels.target3),portfolioPct:round(p.position?.portfolioPct??p.portfolioPct??0,2),source:'GANN_FUSION_X_V1'})}return rows.sort((a,b)=>b.score-a.score).slice(0,TOPN).map((x,i)=>({...x,rank:i+1}))}
function v16Signals(doc){const date=doc?.sessionDate||null,rows=(doc?.recommendations||[]).filter(x=>x.currentSessionEligible!==false&&!x.referenceOnly).slice(0,TOPN).map((x,i)=>({ticker:String(x.ticker||'').toUpperCase(),nameAr:x.companyNameAr||'',rank:i+1,score:round(x.estimatedTop10ProbabilityPct,2),action:x.status||x.category||'PENDING_OPEN',entryLow:round(x.entryLow),entryHigh:round(x.entryHigh),stopLoss:round(x.stopLoss),target1:round(x.target1),target2:null,target3:null,portfolioPct:round(x.portfolioWeightPct,2),source:'V16_9_LIVE'})).filter(x=>x.ticker&&x.entryLow>0&&x.entryHigh>0&&x.stopLoss>0&&x.target1>0);return{date,generatedAt:doc?.generatedAt||null,rows}}
function sepaSignals(doc){const date=doc?.sessionDate||doc?.meta?.marketSession||null,src=(doc?.rows||doc?.views?.top||[]).slice(0,TOPN),rows=[];for(let i=0;i<src.length;i++){const x=src[i],ticker=String(x.symbol||x.ticker||'').toUpperCase(),pivot=Number(x.pivot),riskPct=Number(x.risk_pct),rr=Number(x.reward_risk);if(!ticker||!Number.isFinite(pivot)||pivot<=0)continue;const stop=Number.isFinite(riskPct)&&riskPct>0?pivot*(1-riskPct/100):pivot*.94,risk=Math.max(.0001,pivot-stop),target=Number.isFinite(rr)&&rr>0?pivot+risk*rr:pivot+risk*2;rows.push({ticker,nameAr:x.nameAr||x.name||'',rank:i+1,score:round(x.final_score,1),action:x.action||x.status||'WATCH_TRIGGER',entryLow:round(pivot*.995),entryHigh:round(pivot*1.005),stopLoss:round(stop),target1:round(target),target2:null,target3:null,portfolioPct:null,source:'SEPA_X_LIVE_SHADOW',meta:{pivot:round(pivot),riskPct:round(riskPct,2),rewardRisk:round(rr,2),status:x.status||null}})}return{date,generatedAt:doc?.generatedAt||doc?.meta?.sourceSnapshotGeneratedAt||null,rows}}
function signalKey(session,engine,ticker){return`${session}|${engine}|${ticker}`}
function evaluate(sig){const u=byTicker.get(sig.ticker);if(!u)return null;const win=future(u,sig.signalSession,HOLD);if(win.length<HOLD)return null;let entered=false,entry=null,entryDate=null,exit=null,exitDate=null,status='UNFILLED';for(const b of win){if(!entered){if(b.open>=sig.entryLow&&b.open<=sig.entryHigh){entry=b.open;entryDate=b.date;entered=true}else if(b.low<=sig.entryHigh&&b.high>=sig.entryLow){entry=b.open>sig.entryHigh?sig.entryHigh:b.open<sig.entryLow?sig.entryLow:b.open;entryDate=b.date;entered=true}else continue}const hs=b.low<=sig.stopLoss,ht=b.high>=sig.target1;if(hs&&ht){exit=sig.stopLoss;exitDate=b.date;status='STOP_SAME_BAR';break}if(hs){exit=sig.stopLoss;exitDate=b.date;status='STOP_HIT';break}if(ht){exit=sig.target1;exitDate=b.date;status='TARGET_HIT';break}}if(!entered)return{signalKey:sig.key,signalSession:sig.signalSession,engine:sig.engine,ticker:sig.ticker,status:'UNFILLED',evaluatedThrough:win.at(-1).date,netReturnPct:0,holdingSessions:HOLD};if(exit==null){exit=win.at(-1).close;exitDate=win.at(-1).date;status='TIME_EXIT'}return{signalKey:sig.key,signalSession:sig.signalSession,engine:sig.engine,ticker:sig.ticker,status,entryPrice:round(entry),entryDate,exitPrice:round(exit),exitDate,evaluatedThrough:win.at(-1).date,grossReturnPct:round(pct(exit,entry),3),netReturnPct:round(pct(exit,entry)-COST,3),holdingSessions:HOLD}}
function summarize(ledger){const engines=[...new Set(ledger.signals.map(x=>x.engine))],summary={};for(const engine of engines){const outs=ledger.outcomes.filter(x=>x.engine===engine),filled=outs.filter(x=>x.status!=='UNFILLED'),nets=filled.map(x=>x.netReturnPct||0),pos=nets.filter(x=>x>0),neg=nets.filter(x=>x<0);summary[engine]={signalsIssued:ledger.signals.filter(x=>x.engine===engine).length,evaluated:outs.length,filled:filled.length,positiveRatePct:round(filled.length?pos.length/filled.length*100:0,1),averageNetPct:round(mean(nets),3),profitFactor:round(neg.length?pos.reduce((a,b)=>a+b,0)/Math.abs(neg.reduce((a,b)=>a+b,0)):pos.length?999:0,2),targetHitPct:round(filled.length?filled.filter(x=>x.status==='TARGET_HIT').length/filled.length*100:0,1),stopHitPct:round(filled.length?filled.filter(x=>x.status.startsWith('STOP')).length/filled.length*100:0,1)}}return summary}
function main(){const ledgerPath=path.join(DATA,'forward-shadow-ledger.json'),ledger=read(ledgerPath,{schemaVersion:'gann-fusion-x-forward-shadow-v1',createdAt:new Date().toISOString(),signals:[],outcomes:[],policy:{holdingSessions:HOLD,roundTripCostPct:COST,appendOnlySignals:true,appendOnlyOutcomes:true,consensusRequiresSameSession:true,minimumForwardSessionsForPromotion:20}});ledger.signals=Array.isArray(ledger.signals)?ledger.signals:[];ledger.outcomes=Array.isArray(ledger.outcomes)?ledger.outcomes:[];
  const market=currentMarket(),v16=v16Signals(read(path.join(ROOT,'data','stable','v16-main-app-current.json'),{})),sepa=sepaSignals(read(path.join(DATA,'sepa-x-snapshot.json'),{})),gann={date:market.date,generatedAt:new Date().toISOString(),rows:gannSignals(market.date,market.stocks)};
  const sources=[{engine:'V16_9_LIVE',...v16},{engine:'SEPA_X_LIVE_SHADOW',...sepa},{engine:'GANN_FUSION_X_V1',...gann}],existing=new Set(ledger.signals.map(x=>x.key));let addedSignals=0;
  for(const src of sources){if(!src.date)continue;for(const r of src.rows){const key=signalKey(src.date,src.engine,r.ticker);if(existing.has(key))continue;ledger.signals.push({key,recordedAt:new Date().toISOString(),signalSession:src.date,sourceGeneratedAt:src.generatedAt||null,engine:src.engine,ticker:r.ticker,nameAr:r.nameAr||'',rank:r.rank,score:r.score??null,action:r.action||null,entryLow:r.entryLow,entryHigh:r.entryHigh,stopLoss:r.stopLoss,target1:r.target1,target2:r.target2??null,target3:r.target3??null,portfolioPct:r.portfolioPct??null,meta:r.meta||null});existing.add(key);addedSignals++}}
  const outKeys=new Set(ledger.outcomes.map(x=>x.signalKey)),pending=ledger.signals.filter(x=>!outKeys.has(x.key));let addedOutcomes=0;for(const s of pending){const o=evaluate(s);if(!o)continue;ledger.outcomes.push({...o,recordedAt:new Date().toISOString()});outKeys.add(s.key);addedOutcomes++}
  const sessions={market:market.date,v16:v16.date,sepa:sepa.date,gann:gann.date},same=Boolean(sessions.market&&sessions.market===sessions.v16&&sessions.market===sessions.sepa&&sessions.market===sessions.gann),overlap={};for(const src of sources){for(const r of src.rows){overlap[r.ticker]=(overlap[r.ticker]||[]).concat(src.engine)}}const consensus=Object.entries(overlap).filter(([,a])=>a.length>=2).map(([ticker,engines])=>({ticker,engines,count:engines.length})).sort((a,b)=>b.count-a.count||a.ticker.localeCompare(b.ticker));
  ledger.lastRun={at:new Date().toISOString(),sessions,sameSession:same,consensusStatus:same?'ELIGIBLE_FOR_REVIEW':'BLOCKED_SESSION_MISMATCH',consensus,addedSignals,addedOutcomes,summary:summarize(ledger)};write(ledgerPath,ledger);write(path.join(DATA,'forward-shadow-report.json'),{schemaVersion:'gann-fusion-x-forward-shadow-report-v1',generatedAt:ledger.lastRun.at,sessions,sameSession:same,status:ledger.lastRun.consensusStatus,consensus,summary:ledger.lastRun.summary,forwardSessions:[...new Set(ledger.signals.map(x=>x.signalSession))].sort(),minimumForwardSessionsForPromotion:ledger.policy?.minimumForwardSessionsForPromotion||20,notesAr:['V16 يسجل بمستوياته التنفيذية الأصلية.','SEPA يسجل من لقطة Stable الحية؛ مستويات الاختبار مشتقة من Pivot + risk_pct + reward_risk وتظل موسومة Shadow وليست سجل تنفيذ SEPA أصليًا.','Gann Fusion X يسجل باستخدام الكود الحالي وبيانات الجلسة فقط.','لا توجد توصية مشتركة قابلة للعرض إذا اختلف تاريخ الجلسة بين المصادر.','التقييم بعد ثلاث جلسات وبصافي تكلفة 0.6% ومعاملة target+stop في الجلسة نفسها كوقف تحفظيًا.']});console.log(JSON.stringify(ledger.lastRun,null,2))}
main();
