(function(){'use strict';
const S={view:'summary',data:null,loading:false,error:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=n=>n!==null&&n!==undefined&&n!==''&&Number.isFinite(Number(n))?new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(Number(n)):'—';
const titles={summary:'الخلاصة',daily:'أفضل فرص اليوم',weekly:'أفضل فرص الأسبوع',gann:'رادار جان الزمني',breakout:'رادار الاختراق',accumulation:'التجميع والفرص المبكرة',avoid:'تجنب المطاردة / الخروج',market:'تحليل السوق',consensus:'توافق المحركات',history:'سجل الإشارات',backtest:'الاختبار التاريخي',quality:'جودة البيانات',methodology:'المنهجية والمصطلحات'};
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function validSnapshot(d){return Boolean(d&&d.schemaVersion==='gann-fusion-x-live-ui-v1-ready-only'&&d.publication?.status==='PUBLISHED_READY_GATED'&&d.guardrails?.readinessGate===true&&d.guardrails?.recommendationsReadyOnly===true&&d.guardrails?.nonReadyAllocationZero===true&&Array.isArray(d.stocks))}
async function load(){S.loading=true;S.error=null;render();try{const d=await json('../data/live-ui-current-v1.json');if(!validSnapshot(d))throw new Error('SAFE_PUBLICATION_CONTRACT_FAILED');S.data=d}catch(e){S.data=null;S.error=String(e?.message||e)}finally{S.loading=false;status();render()}}
function status(){const d=S.data,session=$('#sessionBadge'),fresh=$('#freshBadge');if(!session||!fresh)return;session.textContent='جلسة القرار: '+(d?.sessionDate||'—');fresh.textContent=d?'المصدر: READY-GATED':'البيانات: BLOCKED';fresh.className='badge '+(d?'positive':'danger')}
const stockMap=()=>new Map((S.data?.stocks||[]).map(x=>[x.ticker,x]));
function list(name){const m=stockMap();return(S.data?.lists?.[name]||[]).map(t=>m.get(t)).filter(Boolean)}
function kpi(label,val,sub){return`<div class="card"><div class="kpi-label">${esc(label)}</div><div class="kpi-value">${esc(val)}</div><div class="kpi-sub">${esc(sub||'')}</div></div>`}
function chip(s){if(s.status!=='READY')return'<span class="action-chip warn">DATA_INCOMPLETE — لا دخول</span>';const d=s.decision||{};return`<span class="action-chip ${d.code==='ACTIONABLE'?'positive':'neutral'}">${esc(d.ar||'مراقبة')}</span>`}
function row(s){return`<tr><td class="ticker">${esc(s.ticker)}</td><td>${esc(s.nameAr||s.nameEn||'')}</td><td>${fmt(s.close)}</td><td>${s.status==='READY'?fmt(s.score)+'/100':'—'}</td><td>${chip(s)}</td><td>${fmt(s.risk?.liquidityPercentile)}</td><td>${fmt(s.risk?.riskScore)}</td><td>${s.actionable?fmt(s.plan?.allocationPct)+'%':'0%'}</td><td><button class="tab details" data-ticker="${esc(s.ticker)}">التفاصيل</button></td></tr>`}
function table(xs){if(!xs.length)return'<div class="card empty">لا توجد عناصر مطابقة ضمن البيانات المسموح بعرضها.</div>';return`<div class="table-wrap"><table><thead><tr><th>الكود</th><th>الشركة</th><th>السعر</th><th>التقييم</th><th>القرار</th><th>السيولة</th><th>المخاطر</th><th>الحجم</th><th></th></tr></thead><tbody>${xs.map(row).join('')}</tbody></table></div>`}
function coverageAlert(){const c=S.data?.coverage;if(!c)return'';return`<div class="alert warn"><b>نطاق التوصيات:</b> ${esc(c.disclosureAr)} التغطية الحالية ${fmt(c.coveragePct)}%، والـQUARANTINED خارج الترتيب بالكامل.</div>`}
function summary(){const c=S.data.coverage,top=list('dailyTop'),hero=top[0];return`${coverageAlert()}<div class="grid kpis">${kpi('السوق النشط',c.activeUniverse,'إجمالي الكون المستقل')}${kpi('READY',c.ready,'فقط هذه الأسهم تدخل الترتيب')}${kpi('QUARANTINED',c.quarantined,'بيانات غير مكتملة وليست إشارات سلبية')}${kpi('ACTIONABLE',c.actionable,'داخل READY universe فقط')}</div>${hero?`<div class="hero"><div class="card"><div class="kpi-label">أعلى قراءة داخل READY universe</div><div class="hero-decision">${esc(hero.decision?.ar||'')}</div><h2>${esc(hero.ticker)} · ${esc(hero.nameAr||'')}</h2><p class="muted">${esc(hero.decision?.reasonAr||'')}</p><p><b>الحجم الأقصى من الخطة:</b> ${fmt(hero.plan?.allocationPct)}%</p><button class="primary details" data-ticker="${esc(hero.ticker)}">تفاصيل البوابة والخطة</button></div><div class="card"><div class="kpi-label">مصدر القرار</div><h2>Data Readiness Gate</h2><p>لا تعيد الواجهة حساب Fusion أو Gann ولا ترتب المصادر الخام. ما يظهر هنا نسخة منشورة بعد اجتياز Data + Engine + Ranking + Forward gates.</p><p class="muted">تاريخ توليد المصدر: ${esc(S.data.sourceGeneratedAt||'—')}</p></div></div>`:''}<div class="toolbar"><div class="section-title">التوصيات الحالية داخل READY فقط</div></div>${table(top)}`}
function listView(name,note){return`${coverageAlert()}${note?`<div class="alert">${esc(note)}</div>`:''}${table(list(name))}`}
function market(){const c=S.data.coverage;return`${coverageAlert()}<div class="grid kpis">${kpi('Active Universe',c.activeUniverse,'لا يتغير بتقلص READY')}${kpi('READY',c.ready,'مكتمل الشروط الحرجة')}${kpi('DATA_INCOMPLETE',c.quarantined,'حجم التنفيذ = صفر')}${kpi('جلسة القرار',S.data.sessionDate,'مصدر واحد لكل القوائم')}</div><div class="card" style="margin-top:16px"><h2>قاعدة السوق</h2><p>نقص البيانات لا يُسجل كنقطة سلبية ولا كقيمة صفر. الأسهم غير المكتملة تبقى خارج كل ترتيب تنفيذي حتى اكتمال المتطلبات.</p></div>`}
function consensus(){return`${coverageAlert()}<div class="card"><h2>اتساق Backend ↔ UI</h2><p>قائمة <b>recommendations</b> في ملف النشر مطابقة لـ<b>dailyTop</b> بالترتيب، ولا توجد إعادة ترتيب داخل المتصفح.</p><p class="muted">Publication: ${esc(S.data.publication?.status)} · Schema: ${esc(S.data.schemaVersion)}</p></div>${table(list('recommendations'))}`}
function forwardView(){const f=S.data.forward;return`<div class="card"><h2>Forward / Shadow</h2><p><b>الحالة:</b> ${esc(f.status)}</p><p><b>الجلسات المقيمة:</b> ${fmt(f.evaluatedForwardSessions)} / ${fmt(f.minimumForwardSessionsRequired)}</p><p>${esc(f.noteAr)}</p>${f.performanceClaimAllowed?'<div class="alert warn">اكتملت عينة الحد الأدنى للمراجعة، لكن لا توجد ترقية تلقائية.</div>':'<div class="alert warn">لا تُعرض نسبة نجاح أو Profit Factor أو عائد متوسط قبل اكتمال العينة الحقيقية.</div>'}</div>`}
function backtest(){const b=S.data.backtest;return`<div class="card"><h2>الاختبار التاريخي</h2><div class="hero-decision">${esc(b.fullGannHistoricalStatus)}</div><p>${esc(b.noteAr)}</p><div class="alert warn">لا توجد مطالبة بأداء Full Gann التاريخي ولا تُعرض أرقام أداء تاريخية غير صالحة.</div></div>`}
function quality(){const c=S.data.coverage,g=S.data.publication?.gates||{};return`${coverageAlert()}<div class="grid kpis">${kpi('Data Gate',g.data?'PASS':'BLOCKED','')}${kpi('Engine Gate',g.engine?'PASS':'BLOCKED','')}${kpi('Ranking Gate',g.ranking?'PASS':'BLOCKED','')}${kpi('Forward Gate',g.forward?'PASS':'BLOCKED','')}</div><div class="card" style="margin-top:16px"><h2>شفافية التغطية</h2><p>${esc(c.disclosureAr)}</p><p>القيم المفقودة = Unknown/null، ولا تتحول إلى صفر. الحجم الصفري لغير READY هو حظر تنفيذ وليس قياسًا لقوة السهم.</p></div>`}
function methodology(){return`<div class="card"><h2>منهجية العرض</h2><ul class="reason-list"><li>مصدر الواجهة الوحيد هو <b>live-ui-current-v1.json</b> المشتق من Data Readiness Gate.</li><li>لا توجد fallback إلى V16 أو market index أو current.json عند فشل ملف النشر.</li><li>الأسهم DATA_INCOMPLETE قابلة للبحث فقط لتوضيح سبب الحجب، ولا تدخل ترتيبًا أو توصية.</li><li>Forward يظل COLLECTION_PENDING حتى تتراكم جلسات حقيقية لاحقة، ولا تُختلق نتائج.</li><li>Full Gann التاريخي غير معتمد لغياب fundamentals تاريخية point-in-time كافية.</li></ul></div>`}
function searchStock(q){q=String(q||'').trim().toUpperCase();if(!q)return null;return(S.data?.stocks||[]).find(s=>s.ticker===q||String(s.nameAr||'').includes(q)||String(s.nameEn||'').toUpperCase().includes(q))||null}
function detail(s){const missing=s.missing?.length?s.missing.join('، '):'لا يوجد';const plan=s.plan||{};const levels=s.actionable?`<div class="metric-grid"><div class="metric"><span>الدخول</span><b>${fmt(plan.entryLow)} – ${fmt(plan.entryHigh)}</b></div><div class="metric"><span>Trigger</span><b>${fmt(plan.trigger)}</b></div><div class="metric"><span>وقف الخسارة</span><b>${fmt(plan.stopLoss)}</b></div><div class="metric"><span>هدف 1</span><b>${fmt(plan.target1)}</b></div><div class="metric"><span>الحجم</span><b>${fmt(plan.allocationPct)}%</b></div></div>`:'<div class="alert warn">حجم التنفيذ = 0%. لا تُعرض مستويات دخول تنفيذية لسهم غير ACTIONABLE.</div>';return`<h2>${esc(s.ticker)} · ${esc(s.nameAr||s.nameEn||'')}</h2>${chip(s)}<p><b>Data Readiness:</b> ${esc(s.status)}</p><p><b>جلسة القرار:</b> ${esc(s.decisionDate||'—')}</p><p><b>المفقود:</b> ${esc(missing)}</p><p><b>سبب القرار:</b> ${esc(s.decision?.reasonAr||'')}</p>${levels}`}
function openDetail(s){if(!s)return;const dlg=$('#stockDialog'),body=$('#stockDialogBody');if(!dlg||!body)return;body.innerHTML=detail(s);if(!dlg.open)dlg.showModal()}
function runSearch(q){if(!S.data)return;const s=searchStock(q),host=$('#alertHost');if(s){if(host)host.innerHTML='';openDetail(s);return}if(host)host.innerHTML='<div class="alert warn">السهم غير موجود في Active Universe المنشور.</div>'}
function render(){const host=$('#view');if(!host)return;if(S.loading){host.innerHTML='<div class="card empty">تحميل ملف النشر الآمن...</div>';return}if(S.error||!S.data){host.innerHTML=`<div class="card empty"><h2>BLOCKED</h2><p>تعذر تحميل ملف النشر READY-gated. تم حجب كل التوصيات بدل استخدام fallback خام.</p><p class="muted">${esc(S.error||'SAFE_PUBLICATION_UNAVAILABLE')}</p></div>`;return}const v=S.view;let html='';if(v==='summary')html=summary();else if(v==='daily')html=listView('dailyTop','هذه ليست أفضل أسهم السوق كله؛ هي الأعلى فقط داخل READY universe الحالي.');else if(v==='weekly')html=listView('weeklyTop','ترتيب أسبوعي داخل READY فقط.');else if(v==='gann')html=listView('gannCalendar','رادار Gann المنشور بعد بوابة البيانات فقط.');else if(v==='breakout')html=listView('breakoutRadar','اختراقات READY فقط.');else if(v==='accumulation')html=listView('accumulationRadar','تجميع READY فقط.');else if(v==='avoid')html=listView('avoidExitRadar','هذه القائمة لا تضم DATA_INCOMPLETE لمجرد نقص البيانات.');else if(v==='market')html=market();else if(v==='consensus')html=consensus();else if(v==='history')html=forwardView();else if(v==='backtest')html=backtest();else if(v==='quality')html=quality();else html=methodology();host.innerHTML=html;$$('.details').forEach(b=>b.addEventListener('click',()=>openDetail(stockMap().get(b.dataset.ticker))))}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;S.view=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));const t=$('#viewTitle');if(t)t.textContent=titles[S.view]||'Gann Fusion X';render()});$('#refreshBtn')?.addEventListener('click',load);$('#menuBtn')?.addEventListener('click',()=>$('#sidebar')?.classList.toggle('open'));$('#dialogClose')?.addEventListener('click',()=>$('#stockDialog')?.close());$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();runSearch($('#searchInput')?.value)})}
bind();load();
})();
