#!/usr/bin/env node
'use strict';

const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(process.env.GITHUB_WORKSPACE||'.'),P=r=>path.join(root,r),OUT='data/v17/destructive-critic.json';
const read=(r,d={})=>{try{return JSON.parse(fs.readFileSync(P(r),'utf8'))}catch{return d}},text=r=>{try{return fs.readFileSync(P(r),'utf8')}catch{return''}},exists=r=>fs.existsSync(P(r));
function write(r,v){const f=P(r);fs.mkdirSync(path.dirname(f),{recursive:true});const t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');JSON.parse(fs.readFileSync(t,'utf8'));fs.renameSync(t,f)}
const n=(v,d=null)=>{if(v===null||v===undefined||v==='')return d;const x=Number(v);return Number.isFinite(x)?x:d},sym=v=>String(v||'').trim().toUpperCase().replace(/\.CA$/,'').replace(/[^A-Z0-9.]/g,''),validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(String(d||''));
const regular=d=>validDate(d)&&new Date(`${d}T12:00:00Z`).getUTCDay()<=4,near=(a,b,t=0.0002)=>n(a)!==null&&n(b)!==null&&Math.abs(n(a)-n(b))<=t*Math.max(1,Math.abs(n(a)),Math.abs(n(b)));
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const findings=[];function add(severity,code,message,location=null){findings.push({severity,code,message,location})}

const required=['data/v17/current.json','data/v17/ledger.json','data/v17/challenger-status.json','data/v17/review.json','data/v17/regression.json','data/v17/resilient-session-status.json','data/v17/internal-ohlc-support-resistance.json','data/v17/liquidity-gate.json','data/today-decision-center.json','scripts/v17/resolve-ledger.cjs','scripts/v17/build-snapshot.cjs','scripts/v17/build-internal-ohlc-sr.cjs','scripts/v17/build-liquidity-gate.cjs','scripts/v17/market-session-truth.cjs','scripts/v17/repair-session-history.cjs','scripts/v17/finalize-snapshot.cjs','.github/workflows/update-market-data.yml'];
for(const r of required)if(!exists(r))add('CRITICAL','MISSING_REQUIRED_FILE',r,r);

const current=read('data/v17/current.json'),ledger=read('data/v17/ledger.json',{entries:[]}),challenger=read('data/v17/challenger-status.json'),review=read('data/v17/review.json'),regression=read('data/v17/regression.json'),resilient=read('data/v17/resilient-session-status.json'),internal=read('data/v17/internal-ohlc-support-resistance.json'),liquidity=read('data/v17/liquidity-gate.json'),decision=read('data/today-decision-center.json'),truth=read('data/v17/market-session-truth.json'),repair=read('data/v17/session-history-repair.json'),market=read('data/market.json',{rows:[]}),history50=read('data/history-50.json',{symbols:{}}),history=read('data/history.json',{sessionsBySymbol:{}});
const workflow=text('.github/workflows/update-market-data.yml'),resolver=text('scripts/v17/resolve-ledger.cjs'),snapshotSource=text('scripts/v17/build-snapshot.cjs'),sessionTruthSource=text('scripts/v17/market-session-truth.cjs'),runtime=text('preview-v17/app/index.html')+'\n'+text('preview-v17/app/app.js')+'\n'+text('preview-v17/app/confidence-governance.js');

// 1) Session truth: the workflow clock must never become the market session clock.
if(truth.executionSafe===true){
  const s=truth.selectedSessionDate;
  if(!validDate(s)||!regular(s))add('CRITICAL','INVALID_VERIFIED_SESSION',`verified session ${s} is not a regular EGX weekday`,'data/v17/market-session-truth.json');
  if(truth.priceSourceVerified!==true)add('CRITICAL','SESSION_MARKED_SAFE_WITHOUT_PRICE_CONFIRMATION','executionSafe=true while priceSourceVerified!=true','data/v17/market-session-truth.json');
  for(const [label,value] of [['market',market.sessionDate],['history',history.sessionDate],['internal',internal.referenceSessionDate],['liquidity',liquidity.referenceSessionDate],['decision',decision.sessionDate],['snapshot',current.sessionDate]])if(value!==s)add('CRITICAL','SESSION_CHAIN_MISMATCH',`${label}=${value}; verified=${s}`,label);
  if(repair.applied!==true||repair.verifiedSessionDate!==s)add('CRITICAL','HISTORY_REPAIR_NOT_APPLIED',`repair applied=${repair.applied}; date=${repair.verifiedSessionDate}`,'data/v17/session-history-repair.json');
}else{
  if(resilient.executionGrade===true||current?.systemHealth?.executionGrade===true||decision?.sessionTruth?.executionGrade===true)add('CRITICAL','EXECUTION_WITHOUT_VERIFIED_SESSION','execution leaked while source session is not verified','session truth');
}
if(truth.directValidation?.role&&truth.directValidation.role!=='VALIDATION_ONLY_NOT_HARD_DEPENDENCY')add('MAJOR','VALIDATION_BECAME_HARD_DEPENDENCY',truth.directValidation.role,'market-session-truth');
if(!sessionTruthSource.includes('conflictBlocksPriceSessionTruth:false'))add('MAJOR','SESSION_TRUTH_EXTERNAL_DEPENDENCY_RISK','price session truth is not explicitly independent from S/R validation','scripts/v17/market-session-truth.cjs');

const verified=truth.executionSafe===true?truth.selectedSessionDate:null;
function scanHistory(container,label){for(const [s,rows] of Object.entries(container||{})){for(const row of Array.isArray(rows)?rows:[]){const d=String(row?.date||'');if(!validDate(d))continue;if(!regular(d))add('MAJOR','WEEKEND_HISTORY_ROW',`${label}:${s}:${d}`,label);if(verified&&d>verified)add('CRITICAL','FUTURE_HISTORY_ROW',`${label}:${s}:${d} > ${verified}`,label);}}}
scanHistory(history50.symbols,'data/history-50.json');scanHistory(history.sessionsBySymbol,'data/history.json');

// 2) Internal S/R: recompute classic pivots from the stored OHLC provenance.
const srRows=Array.isArray(internal.rows)?internal.rows:[],srMap=new Map(srRows.map(r=>[sym(r.symbol),r]));
for(const r of srRows){const o=n(r?.provenance?.open),h=n(r?.provenance?.high),l=n(r?.provenance?.low),c=n(r?.provenance?.close);if([o,h,l,c].some(v=>v===null)||!(h>l&&h>=Math.max(o,c)&&l<=Math.min(o,c))){add('CRITICAL','INVALID_SR_OHLC',r.symbol,`internal:${r.symbol}`);continue}const p=(h+l+c)/3,s1=2*p-h,r1=2*p-l,s2=p-(h-l),r2=p+(h-l);for(const [k,v] of [['pivot',p],['support1',s1],['support2',s2],['resistance1',r1],['resistance2',r2]])if(!near(r[k],v,0.0005))add('CRITICAL','SR_FORMULA_DRIFT',`${r.symbol} ${k}=${r[k]} expected ${v}`,`internal:${r.symbol}`);if(!(r.support2<r.support1&&r.support1<r.resistance1&&r.resistance1<r.resistance2))add('MAJOR','SR_ORDER_INVALID',r.symbol,`internal:${r.symbol}`);if(r.executionEligible===true&&(r.provenance?.trustedForExecution!==true||internal.sourceSessionVerified!==true||internal.sessionCompletionConfirmed!==true||r.sessionDate!==internal.referenceSessionDate))add('CRITICAL','SR_EXECUTION_WITHOUT_TRUST_CHAIN',r.symbol,`internal:${r.symbol}`);}
const candidates=Array.isArray(internal.candidateSymbols)?internal.candidateSymbols.map(sym).filter(Boolean):[];
const derivedCandidates=candidates.filter(s=>srMap.has(s)),trustedCandidates=candidates.filter(s=>srMap.get(s)?.provenance?.trustedForExecution===true),freshTrusted=candidates.filter(s=>srMap.get(s)?.provenance?.trustedForExecution===true&&srMap.get(s)?.sessionDate===internal.levelSessionDate);
const pct=(a,b)=>b?Math.round(a/b*10000)/100:0;
if(!near(internal.researchCoveragePct,pct(derivedCandidates.length,candidates.length),0.0001))add('MAJOR','SR_RESEARCH_COVERAGE_MISMATCH',`${internal.researchCoveragePct} vs ${pct(derivedCandidates.length,candidates.length)}`,'internal coverage');
if(!near(internal.coveragePct,pct(trustedCandidates.length,candidates.length),0.0001))add('CRITICAL','SR_TRUSTED_COVERAGE_MISMATCH',`${internal.coveragePct} vs ${pct(trustedCandidates.length,candidates.length)}`,'internal coverage');
if(!near(internal.freshnessPct,pct(freshTrusted.length,candidates.length),0.0001))add('CRITICAL','SR_FRESHNESS_MISMATCH',`${internal.freshnessPct} vs ${pct(freshTrusted.length,candidates.length)}`,'internal freshness');
if((internal.sourceConflicts||[]).length>0&&resilient.executionGrade===true)add('CRITICAL','EXECUTION_WITH_CRITICAL_SR_CONFLICTS',`${internal.sourceConflicts.length} conflicts`,'resilient gate');

// 3) Liquidity: independently recompute the frozen V11.1 score and execution predicate.
function score(currentTurnover,avg20,trades=0){let s=0;s+=currentTurnover>=5e6?35:Math.min(35,currentTurnover/5e6*35);s+=avg20>=2e6?35:Math.min(35,avg20/2e6*35);if(currentTurnover>=1e7||avg20>=5e6)s+=15;s+=trades>=100?15:Math.min(15,trades/100*15);return Math.round(Math.max(0,Math.min(100,s)))}
const lrows=Array.isArray(liquidity.rows)?liquidity.rows:[];for(const r of lrows){const expected=score(n(r.currentTurnover,0),n(r.avg20Turnover,0),n(r.trades,0));if(n(r.liquidityScore)!==expected)add('CRITICAL','LIQUIDITY_SCORE_DRIFT',`${r.symbol}: ${r.liquidityScore} vs ${expected}`,`liquidity:${r.symbol}`);const ok=n(r.currentTurnover,0)>=5e6&&n(r.avg20Turnover,0)>=2e6&&n(r.currentVolume,0)>0&&expected>=65;if((r.executionLiquidityOk===true)!==ok)add('CRITICAL','LIQUIDITY_EXECUTION_PREDICATE_DRIFT',r.symbol,`liquidity:${r.symbol}`);if(n(r.historicalSessionsUsed,0)>20)add('MAJOR','LIQUIDITY_HISTORY_OVER_20',r.symbol,`liquidity:${r.symbol}`);}
const lc=lrows.filter(r=>r.candidate===true),le=lc.filter(r=>r.evidenceAvailable===true),lx=lc.filter(r=>r.executionLiquidityOk===true);if(lc.length!==n(liquidity.candidateUniverseCount,-1))add('CRITICAL','LIQUIDITY_CANDIDATE_COUNT_MISMATCH',`${lc.length} vs ${liquidity.candidateUniverseCount}`,'liquidity');if(!near(liquidity.candidateEvidenceCoveragePct,pct(le.length,lc.length),0.0001))add('CRITICAL','LIQUIDITY_COVERAGE_MISMATCH',`${liquidity.candidateEvidenceCoveragePct} vs ${pct(le.length,lc.length)}`,'liquidity');if(lx.length!==n(liquidity.candidateExecutionOkCount,-1))add('CRITICAL','LIQUIDITY_EXECUTION_COUNT_MISMATCH',`${lx.length} vs ${liquidity.candidateExecutionOkCount}`,'liquidity');if(liquidity.gatePassed===true&&(liquidity.sessionAligned!==true||liquidity.sourceSessionVerified!==true||n(liquidity.candidateEvidenceCoveragePct,0)<95||lx.length<1))add('CRITICAL','FALSE_LIQUIDITY_GATE_PASS','gatePassed without full predicate','liquidity');

// 4) Decision and snapshot execution leakage.
const drows=Array.isArray(decision.rankedOpportunities)?decision.rankedOpportunities:[],dex=drows.filter(r=>r.executionAllowed===true||r.opportunityState==='EXECUTABLE');if(n(decision?.summary?.rankedCount,-1)!==drows.length)add('MAJOR','DECISION_RANK_COUNT_MISMATCH',`${decision?.summary?.rankedCount} vs ${drows.length}`,'decision');if(n(decision?.summary?.executionCount,-1)!==dex.length)add('CRITICAL','DECISION_EXECUTION_COUNT_MISMATCH',`${decision?.summary?.executionCount} vs ${dex.length}`,'decision');if(dex.length&&resilient.executionGrade!==true)add('CRITICAL','DECISION_EXECUTION_LEAK','executable rows while resilient gate is not execution grade','decision');for(const r of dex){if(r?.supportResistance?.executionEligible!==true)add('CRITICAL','EXECUTABLE_WITHOUT_SR',r.symbol,'decision');if(r?.liquidity?.executionLiquidityOk!==true)add('CRITICAL','EXECUTABLE_WITHOUT_LIQUIDITY',r.symbol,'decision');}
const currentExecution=current?.systemHealth?.executionGrade===true||current?.readiness?.executionReady===true,crecs=Array.isArray(current.recommendations)?current.recommendations:[];if(!currentExecution){if(n(current?.portfolioPolicy?.plannedAllocationPct,0)!==0||n(current?.portfolioPolicy?.cashReservePct,0)!==100)add('CRITICAL','RESEARCH_PORTFOLIO_NOT_ALL_CASH','non-execution snapshot carries exposure','snapshot');for(const r of crecs)if(n(r.portfolioWeightPct,0)!==0||r.executionAllowed===true||r.monitorOnly!==true)add('CRITICAL','RESEARCH_RECOMMENDATION_EXECUTION_LEAK',r.ticker,'snapshot');}
if(current?.championReference?.currentForMarketSession===false){for(const r of current?.championReference?.recommendations||[])if(r.executionAllowed===true||r.monitorOnly===false||r.state==='PENDING_OPEN_CONFIRMATION')add('MAJOR','STALE_CHAMPION_EXECUTION_SEMANTICS',r.ticker,'championReference');if(current?.championReference?.executionAllowedForCurrentSession!==false)add('MINOR','STALE_CHAMPION_CURRENT_FLAG_MISSING','historical champion is not explicitly disabled for current session','championReference');}
if(current?.finalization?.immutableSignalHashTouched!==false||current?.finalization?.ledgerTouched!==false)add('CRITICAL','FINALIZER_TOUCHED_IMMUTABLE_STATE','snapshot finalizer must never mutate signal contract','snapshot');

// 5) Ledger and conservative outcome policy.
const entries=Array.isArray(ledger.entries)?ledger.entries:[];const ids=new Set();for(const e of entries){if(ids.has(e.signalId))add('CRITICAL','DUPLICATE_SIGNAL_ID',e.signalId,'ledger');ids.add(e.signalId);const recs=Array.isArray(e.recommendations)?e.recommendations:[],payload={sessionDate:e.sessionDate,engineId:e.engineId,recommendations:recs.map(r=>({ticker:r.ticker,entryLow:r.entryLow,entryHigh:r.entryHigh,target:r.target,stop:r.stop,portfolioWeightPct:r.portfolioWeightPct}))};if(!e.signalHash||hash(payload)!==e.signalHash)add('CRITICAL','IMMUTABLE_SIGNAL_HASH_MISMATCH',e.signalId,'ledger');if(recs.reduce((s,r)=>s+n(r.portfolioWeightPct,0),0)>50.0001)add('CRITICAL','LEDGER_ALLOCATION_OVER_50',e.signalId,'ledger');}
if(!resolver.includes('targetTouched && stopTouched')||!resolver.includes('AMBIGUOUS_TREATED_AS_STOP')||!resolver.includes('conservativeAmbiguityPolicy'))add('CRITICAL','AMBIGUITY_POLICY_WEAKENED','same-candle target/stop is not conservatively resolved','resolve-ledger.cjs');

// 6) Champion/challenger and runtime isolation.
if(challenger.activeEngine!=='V16_9_EQUAL_WEIGHT_BASKET')add('CRITICAL','CHAMPION_CHANGED',challenger.activeEngine,'challenger');if(challenger.promotionAllowed!==false)add('CRITICAL','AUTO_PROMOTION_ENABLED','promotionAllowed must remain false','challenger');if(current?.engine?.id!=='V16_9_EQUAL_WEIGHT_BASKET')add('CRITICAL','SNAPSHOT_ENGINE_CHANGED',current?.engine?.id,'snapshot');
for(const token of ['v15-practical-decision.json','v15-update-status.json','decision-source.js','adaptive-daily-recommendations.json','v13-5-adaptive','adaptive-recommendations.html'])if(runtime.includes(token))add('CRITICAL','LEGACY_OR_ADAPTIVE_RUNTIME_REFERENCE',token,'preview-v17/app');
if(/git push[^\n]*origin[^\n]*main|git push[^\n]*HEAD:main/.test(workflow))add('CRITICAL','MAIN_PUSH_PATH_PRESENT','V17 workflow contains a main push path','workflow');if(!workflow.includes('destructive-critic.cjs'))add('MAJOR','CRITIC_NOT_IN_WORKFLOW','destructive critic is not mandatory in market workflow','workflow');if(!workflow.includes('market-session-truth.cjs')||!workflow.includes('repair-session-history.cjs')||!workflow.includes('finalize-snapshot.cjs'))add('MAJOR','SESSION_SAFETY_CHAIN_NOT_IN_WORKFLOW','session truth/repair/finalizer chain incomplete','workflow');
if(review.verdict==='REJECTED'||n(review?.counts?.CRITICAL,0)>0||n(review?.counts?.MAJOR,0)>0)add('CRITICAL','INDEPENDENT_REVIEW_NOT_CLEAN',review.verdict,'review');if(regression.ok!==true||n(regression.criticalFailedCount,0)!==0)add('CRITICAL','REGRESSION_NOT_CLEAN',`ok=${regression.ok}; critical=${regression.criticalFailedCount}`,'regression');

const counts=findings.reduce((a,f)=>(a[f.severity]=(a[f.severity]||0)+1,a),{CRITICAL:0,MAJOR:0,MINOR:0,INFO:0});
const report={schemaVersion:'17.0.0-destructive-critic-1',generatedAt:new Date().toISOString(),critic:'V17_DESTRUCTIVE_ADVERSARIAL_REVIEWER',verdict:findings.length===0?'NO_COMMENTS':'COMMENTS_FOUND',counts,totalFindings:findings.length,findings,coverage:{sessionTruth:true,historyTemporalIntegrity:true,internalSrFormula:true,liquidityIndependentRecompute:true,decisionExecutionLeak:true,snapshotHistoricalChampionLeak:true,immutableLedger:true,ambiguityPolicy:true,championChallenger:true,runtimeIsolation:true,workflowIsolation:true},rule:'NO_COMMENTS requires zero CRITICAL, MAJOR, MINOR, or INFO findings.'};
write(OUT,report);console.log(JSON.stringify(report,null,2));if(findings.length)process.exitCode=2;
