#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(process.env.GITHUB_WORKSPACE||'.'),P=r=>path.join(root,r),OUT='data/v17/regression.json';
const read=(r,d={})=>{try{return JSON.parse(fs.readFileSync(P(r),'utf8'))}catch{return d}},text=r=>{try{return fs.readFileSync(P(r),'utf8')}catch{return''}},exists=r=>fs.existsSync(P(r));
function write(r,v){const f=P(r);fs.mkdirSync(path.dirname(f),{recursive:true});const t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');JSON.parse(fs.readFileSync(t,'utf8'));fs.renameSync(t,f)}
const n=(v,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d},validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(String(d||'')),regular=d=>validDate(d)&&new Date(`${d}T12:00:00Z`).getUTCDay()<=4;
const base=cp.spawnSync(process.execPath,[P('scripts/v17/regression.cjs')],{cwd:root,encoding:'utf8'}),baseReport=read(OUT,{tests:[]});
const tests=Array.isArray(baseReport.tests)?[...baseReport.tests]:[];
function test(name,ok,message,severity='CRITICAL'){tests.push({name,ok:ok===true,severity,message:String(message||'')});}
if(base.status!==0&&n(baseReport.failedCount,0)===0)test('base-regression:process',false,`exit=${base.status}; ${base.stderr||base.stdout||''}`.slice(0,500));
for(const rel of ['scripts/v17/market-session-truth.cjs','scripts/v17/repair-session-history.cjs','scripts/v17/finalize-snapshot.cjs','scripts/v17/review-v5.cjs','scripts/v17/regression-v3.cjs','scripts/v17/destructive-critic-v3.cjs','data/v17/market-session-truth.json','data/v17/session-history-repair.json'])test(`file:${rel}`,exists(rel),exists(rel)?'exists':'missing');
const current=read('data/v17/current.json'),truth=read('data/v17/market-session-truth.json'),repair=read('data/v17/session-history-repair.json'),internal=read('data/v17/internal-ohlc-support-resistance.json'),liquidity=read('data/v17/liquidity-gate.json'),resilient=read('data/v17/resilient-session-status.json'),review=read('data/v17/review.json'),history50=read('data/history-50.json',{symbols:{}}),history=read('data/history.json',{sessionsBySymbol:{}}),workflow=text('.github/workflows/update-market-data.yml'),buildReview=text('.github/workflows/v17-build-review.yml');
const execution=resilient.executionGrade===true;
const s=regular(truth.selectedSessionDate)?truth.selectedSessionDate:null;
const executionTruth=Boolean(execution&&s&&truth.executionSafe===true&&truth.priceSourceVerified===true);
const researchTruth=Boolean(!execution&&s&&truth.researchSessionVerified===true&&truth.executionSafe!==true);
test('session-truth:verified-source-session',execution?executionTruth:researchTruth,execution?`execution session=${s}; priceVerified=${truth.priceSourceVerified}`:`research session=${s}; researchVerified=${truth.researchSessionVerified}; executionSafe=${truth.executionSafe}`);
test('session-truth:validation-not-hard-dependency',truth?.directValidation?.role==='VALIDATION_ONLY_NOT_HARD_DEPENDENCY'&&truth?.directValidation?.conflictBlocksPriceSessionTruth===false,'Mubasher S/R validation cannot define price session truth');
const executionChain=Boolean(executionTruth&&current.sessionDate===s&&internal.referenceSessionDate===s&&liquidity.referenceSessionDate===s&&history.sessionDate===s);
const researchChain=Boolean(researchTruth&&current.sessionDate===s&&internal.referenceSessionDate===s&&liquidity.referenceSessionDate===s&&regular(internal.levelSessionDate)&&internal.levelSessionDate<=s&&(!validDate(history.sessionDate)||history.sessionDate<=s));
test('session-truth:canonical-chain',execution?executionChain:researchChain,`mode=${execution?'EXECUTION':'RESEARCH'}; snapshot=${current.sessionDate}; sr=${internal.referenceSessionDate}; levels=${internal.levelSessionDate}; liq=${liquidity.referenceSessionDate}; history=${history.sessionDate}; expected=${s}`);
const repairExecutionOk=repair.applied===true&&repair.verifiedSessionDate===s&&repair?.policy?.noFabricatedOhlc===true&&repair?.policy?.allFridaySaturdayHistoryRowsRemoved===true;
const repairResearchOk=repair.applied!==true&&truth.executionSafe!==true&&regular(internal.levelSessionDate)&&internal.levelSessionDate<=s;
test('history-repair:applied',execution?repairExecutionOk:repairResearchOk,execution?`execution repair applied=${repair.applied}; date=${repair.verifiedSessionDate}`:`research mode: repairApplied=${repair.applied}; completedLevelSession=${internal.levelSessionDate}; selected=${s}`);
let temporalOk=true,temporalIssues=[];function scan(container,label){for(const [symbol,rows] of Object.entries(container||{}))for(const row of Array.isArray(rows)?rows:[]){const d=String(row?.date||'');if(!validDate(d))continue;if(!regular(d)||(s&&d>s)){temporalOk=false;if(temporalIssues.length<10)temporalIssues.push(`${label}:${symbol}:${d}`);}}}scan(history50.symbols,'h50');scan(history.sessionsBySymbol,'hist');test('history-repair:no-weekend-or-future-rows',temporalOk,temporalIssues.join(', ')||'clean temporal history');
test('snapshot-finalizer:immutable',current?.finalization?.immutableSignalHashTouched===false&&current?.finalization?.ledgerTouched===false,'finalizer did not touch immutable state');
test('snapshot-finalizer:historical-weights-zeroed',current?.finalization?.staleChampionCurrentWeightsZeroed===true&&current?.championReference?.currentForMarketSession!==false||(n(current?.championReference?.plannedAllocationPct)===0&&(current?.championReference?.recommendations||[]).every(r=>n(r.portfolioWeightPct)===0&&n(r.basketWeightPct)===0&&n(r.currentSessionWeightPct)===0&&r.executionAllowed===false&&r.monitorOnly===true)),`championCurrentAllocation=${current?.championReference?.plannedAllocationPct}`);
test('execution:verified-session-required',resilient.executionGrade!==true||truth.executionSafe===true,'execution grade requires verified session');
test('execution:liquidity-and-sr-required',resilient.executionGrade!==true||(liquidity.gatePassed===true&&internal.executionCandidateReady===true&&resilient.sessionAligned===true),'execution grade requires liquidity + internal SR + alignment');
if(!execution)test('research:watch-only-contract',n(current?.portfolioPolicy?.plannedAllocationPct)===0&&n(current?.portfolioPolicy?.cashReservePct)===100&&(current.recommendations||[]).every(r=>n(r.portfolioWeightPct)===0&&r.executionAllowed!==true&&r.monitorOnly===true),'research session must remain zero-allocation watch-only');
test('review:v5-clean',review.schemaVersion==='17.0.0-review-5'&&review.verdict==='NO_COMMENTS'&&Object.values(review.counts||{}).every(v=>n(v)===0),`schema=${review.schemaVersion}; verdict=${review.verdict}`);
for(const [name,token] of [['market:review-v5','review-v5.cjs'],['market:regression-v3','regression-v3.cjs'],['market:critic-v3','destructive-critic-v3.cjs'],['market:finalizer','finalize-snapshot.cjs'],['market:playwright-current','playwright@1.62.0'],['build:review-v5','review-v5.cjs'],['build:regression-v3','regression-v3.cjs'],['build:critic-v3','destructive-critic-v3.cjs'],['build:finalizer','finalize-snapshot.cjs']])test(`workflow:${name}`,(name.startsWith('market:')?workflow:buildReview).includes(token),token);
const failed=tests.filter(t=>!t.ok),criticalFailed=failed.filter(t=>t.severity==='CRITICAL');
const report={schemaVersion:'17.0.0-regression-3',generatedAt:new Date().toISOString(),contract:'V17_CANONICAL_RUNTIME_SESSION_TRUTH_FINALIZATION_AND_GOVERNANCE',ok:failed.length===0,total:tests.length,passed:tests.length-failed.length,failedCount:failed.length,criticalFailedCount:criticalFailed.length,failed:failed.map(t=>t.name),tests,baseRegression:{schemaVersion:baseReport.schemaVersion||null,total:n(baseReport.total,0),passed:n(baseReport.passed,0),failedCount:n(baseReport.failedCount,0)},sessionContract:{mode:execution?'EXECUTION':'RESEARCH_WATCH_ONLY',selectedSession:s,executionTruth,researchTruth,executionChain,researchChain}};
write(OUT,report);console.log(JSON.stringify({schemaVersion:report.schemaVersion,ok:report.ok,total:report.total,passed:report.passed,failedCount:report.failedCount,criticalFailedCount:report.criticalFailedCount,failed:report.failed,sessionContract:report.sessionContract},null,2));if(failed.length)process.exitCode=2;
