'use strict';
const U={d:'../../data/stable/v15-practical-decision.json',v:'../../data/research/v15-practical-validation.json',e:'../../data/stable/v15-recommendation-evaluation.json',h:'../../data/stable/v16-v169-live-evaluation.json',p:'../../data/stable/v15-price-truth.json',u:'../../data/stable/v15-update-status.json',m:'../../data/quant/market-search-index-v13-17.json'},K={pf:'egx-v16-professional-portfolio',f:'egx-v16-fundamentals',s:'egx-v16-risk-settings'},S={d:null,v:null,e:null,h:null,p:null,u:null,m:null,sel:null,pf:[],f:{},s:{portfolioRiskLimit:2,portfolioPositionLimit:5,strategyExposureLimit:40}},$=x=>document.getElementById(x),A=x=>Array.isArray(x)?x:[],N=x=>Number.isFinite(Number(x))?Number(x):null,F=(x,d=2)=>N(x)===null?'—':Number(x).toLocaleString('en-GB',{maximumFractionDigits:d}),P=x=>N(x)===null?'—':F(x,1)+'%',M=x=>N(x)===null?'—':Number(x).toLocaleString('en-GB',{maximumFractionDigits:0})+' ج.م',C=(x,a,b)=>Math.max(a,Math.min(b,x)),E=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),L=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},W=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const toast=t=>{let e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)},J=async(u,o=false)=>{try{let r=await fetch(u+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch(e){if(o)return null;throw e}},norm=x=>String(x||'').toLowerCase().normalize('NFKD').replace(/[\u064b-\u065f\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').replace(/\s+/g,' ').trim(),model=id=>A(S.v?.models).find(x=>x.id===id),market=t=>A(S.m?.stocks).find(x=>x.ticker===t),fund=t=>S.f[t]||null;
function fs(d,price){if(!d||!d.auditedData)return{score:0,label:'غير مكتمل',cls:'bad',notes:['لا توجد أرقام مالية موثقة ومدققة.']};let s=0,n=[],r=N(d.revenueGrowth),p=N(d.profitGrowth),roe=N(d.roe),de=N(d.debtEquity),pe=N(d.pe),fv=N(d.fairValue),cp=N(price);if(r!==null){s+=r>=15?15:r>0?8:0;n.push(r>0?'نمو الإيرادات موجب.':'الإيرادات لا تنمو.')}if(p!==null){s+=p>=20?20:p>0?10:0;n.push(p>0?'نمو الأرباح موجب.':'ضغط في الأرباح.')}if(roe!==null){s+=roe>=20?20:roe>=12?12:roe>0?5:0;n.push('ROE '+P(roe))}if(de!==null){s+=de<=.5?15:de<=1?9:de<=2?3:0;if(de>2)n.push('مديونية مرتفعة.')}if(pe!==null){s+=pe>0&&pe<=12?12:pe<=20?7:pe>0?2:0;n.push('P/E '+F(pe,1))}if(d.positiveCfo){s+=10;n.push('التدفق التشغيلي موجب.')}else n.push('التدفق التشغيلي غير مؤكد.');if(fv!==null&&cp>0){let u=(fv/cp-1)*100;s+=u>=20?8:u>=8?4:0;n.push('هامش القيمة العادلة '+P(u))}s=C(s,0,100);return{score:s,label:s>=70?'قوي':s>=50?'مقبول':s>=30?'ضعيف':'غير كافٍ',cls:s>=70?'good':s>=50?'warn':'bad',notes:n}}
function stab(m){if(!m)return{score:0,label:'غير متاح',cls:'bad',reason:'لا توجد نتائج.'};let s=100,r=[],d=m.development||{},v=m.validation||{},t=m.test||{};if((N(d.averageReturnPct)||0)<=0){s-=35;r.push('فترة التطوير خاسرة.')}if((N(d.profitFactor)||0)<1){s-=20;r.push('PF التطوير أقل من 1.')}if((N(t.profitFactor)||0)<1.3){s-=15;r.push('أفضلية الاختبار محدودة.')}if(Math.abs((N(v.winRatePct)||0)-(N(t.winRatePct)||0))>15){s-=15;r.push('اختلاف كبير بين التحقق والاختبار.')}if((S.v?.sessions?.test||0)<20){s-=20;r.push('الاختبار النهائي يغطي '+(S.v?.sessions?.test||0)+' جلسات فقط.')}s=C(s,0,100);return{score:s,label:s>=70?'مستقر نسبيًا':s>=45?'حساس لدورة السوق':'غير مستقر',cls:s>=70?'good':s>=45?'warn':'bad',reason:r.join(' ')||'نتائج متقاربة.'}}
function live(){let x=S.e?.summary||{},r=N(x.resolvedTrades)||0;return{resolved:r,entered:N(x.enteredTrades)||0,archived:N(x.archivedRecommendations)||0,score:C(r,0,100),stage:r>=100?'مثبت تشغيليًا':r>=30?'تجريبي متقدم':r>=10?'تجريبي':'بحثي',msg:r>=100?'حجم عينة حي كافٍ مبدئيًا.':r>=30?'سجل حي أولي دون معيار الاعتماد الكامل.':'لا توجد صفقات حية منتهية تكفي لإثبات الأداء.'}}
function ready(){let l=live(),p=S.p||{},ms=A(S.v?.models).filter(x=>x.validationPassed&&x.testPassed).map(x=>stab(x).score),md=ms.length?ms.reduce((a,b)=>a+b,0)/ms.length:0,ds=p.executionGrade?C((N(p.acceptedRows)||0)/(N(p.source?.inputRows)||1)*100,0,100):0,rs=A(S.d?.recommendations).filter(x=>fund(x.ticker)?.auditedData).length/Math.max(1,A(S.d?.recommendations).length)*100,rr=S.d?.guardrails?.automaticOrders===false?80:40,score=Math.round(ds*.25+md*.25+l.score*.25+rs*.15+rr*.1);return{score,ds,md,ls:l.score,fs:rs,rr,l}}
function gate(r){let st=stab(model(r.strategyId)),f=fs(fund(r.ticker),r.close),i=[],ok=[];if((N(r.riskReward)||0)<1)i.push(['warn','العائد/المخاطرة '+F(r.riskReward)+' أقل من 1.']);else ok.push('عائد/مخاطرة مقبول.');if((N(r.rsi14)||0)>=80)i.push(['fail','RSI مرتفع جدًا '+F(r.rsi14,1)+' — خطر مطاردة.']);else if((N(r.rsi14)||0)>=75)i.push(['warn','RSI مرتفع '+F(r.rsi14,1)+'.']);else ok.push('لا توجد سخونة مفرطة.');if((N(r.ret5Pct)||0)>=15)i.push(['warn','صعود '+P(r.ret5Pct)+' خلال 5 جلسات.']);if(st.score<45)i.push(['fail',st.reason]);else if(st.score<70)i.push(['warn',st.reason]);else ok.push('ثبات النموذج مقبول.');if(!S.p?.executionGrade)i.push(['fail','أسعار التنفيذ غير موثقة.']);else ok.push('الأسعار موثقة.');if(f.score<50)i.push(['warn','التحليل المالي غير مكتمل؛ لا يصلح كقرار طويل الأجل.']);else ok.push('المراجعة المالية مقبولة.');let hard=i.some(x=>x[0]==='fail'),status=hard?'blocked':i.length?'caution':'eligible';return{status,label:hard?'محجوبة مهنيًا':i.length?'مراجعة بحذر':'صالحة للمراجعة',cls:hard?'bad':i.length?'warn':'good',i,ok,st,f}}
function row(a,b,c=''){return'<div class="detail-row"><span>'+E(a)+'</span><b class="'+c+'">'+E(b)+'</b></div>'}
function renderReady(){let r=ready(),g=$('readinessGauge');g.style.background=`conic-gradient(${r.score>=70?'var(--green)':r.score>=45?'var(--amber)':'var(--red)'} ${r.score*3.6}deg,#17344a 0)`;g.innerHTML='<strong>'+r.score+'</strong><span>من 100</span>';$('readinessBreakdown').innerHTML=[['جودة الأسعار',r.ds],['ثبات النماذج',r.md],['السجل الحي',r.ls],['التحليل المالي',r.fs],['إدارة المخاطر',r.rr]].map(x=>`<div class="breakdown-row"><span>${x[0]}</span><div class="bar"><i style="width:${C(x[1],0,100)}%"></i></div><b>${Math.round(x[1])}</b></div>`).join('');let st=r.score>=70&&r.l.resolved>=100?'منتج مهني مثبت':r.score>=50?'Pilot احترافي':'نسخة بحثية',cl=st==='منتج مهني مثبت'?'good':st==='Pilot احترافي'?'warn':'bad';$('productStage').textContent=st;$('productStage').className='badge '+cl;$('professionalVerdict').className='professional-verdict '+cl;$('professionalVerdict').innerHTML='<b>'+st+'</b><br>'+(cl==='good'?'اجتاز بوابات الاعتماد الأساسية.':'مناسب للمسح والمراجعة المنظمة، وليس للاعتماد المنفرد بعد.')}
function renderTruth(){let l=live(),t=S.d?.selectedModel?.test||{},p=S.p||{};$('truthGrid').innerHTML=[['الأسعار المقبولة',F(p.acceptedRows,0)+'/'+F(p.source?.inputRows,0),'اجتازت فحص الانحراف'],['جلسات الاختبار النهائي',F(S.v?.sessions?.test,0),'حجم زمني محدود'],['نسبة موجبة Backtest',P(t.winRatePct),'تاريخية وليست حية'],['صفقات حية منتهية',F(l.resolved,0),l.msg]].map(x=>`<div class="truth-card"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}
function renderRecs(){let f=$('recommendationFilter').value,rows=A(S.d?.recommendations).map(r=>[r,gate(r)]).filter(x=>f==='all'||x[1].status===f);$('recommendationGrid').innerHTML=rows.length?rows.map(([r,g])=>{let t=model(r.strategyId)?.test||{};return`<article class="rec-card ${S.sel?.ticker===r.ticker?'selected':''}"><div class="rec-rank">${E(r.rank)}</div><h3>${E(r.ticker)}</h3><div class="rec-name">${E(r.companyNameAr)}</div><div class="tag-row"><span class="tag good">${E(r.strategyLabelAr)}</span><span class="tag ${g.cls}">${g.label}</span></div><div class="rec-metrics"><div class="mini">الإغلاق<b>${F(r.close,3)}</b></div><div class="mini">الدخول<b>${F(r.entryLow,3)}–${F(r.entryHigh,3)}</b></div><div class="mini">الهدف<b>${F(r.target1,3)}</b></div><div class="mini">الوقف<b>${F(r.stopLoss,3)}</b></div><div class="mini">Backtest موجب<b>${P(t.winRatePct)}</b></div><div class="mini">PF النهائي<b>${F(t.profitFactor)}</b></div></div><div class="gate-list">${g.ok.slice(0,2).map(x=>`<div class="gate pass"><span>${E(x)}</span><b>✓</b></div>`).join('')}${g.i.slice(0,3).map(x=>`<div class="gate ${x[0]}"><span>${E(x[1])}</span><b>${x[0]==='fail'?'✕':'!'}</b></div>`).join('')}</div><div class="rec-verdict ${g.cls}">${g.status==='eligible'?'مؤهلة للمراجعة اليدوية، وليست أمر شراء.':g.status==='caution'?'تأكيد الافتتاح ومعالجة التحذيرات إلزامي.':'تُستبعد مهنيًا في وضعها الحالي.'}</div><button class="btn" data-s="${E(r.ticker)}">تحليل كامل</button></article>`}).join(''):'<div class="empty">لا توجد فرص.</div>';$('recommendationGrid').querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>select(b.dataset.s))}
async function select(t){let r=A(S.d?.recommendations).find(x=>x.ticker===t),m=market(t);S.sel=r||m&&{ticker:m.ticker,companyNameAr:m.companyNameAr,close:m.price,strategyLabelAr:'خارج توصيات اليوم',rsi14:m.momentumMoneyFlow?.rsi14,volumeRatio20:m.momentumMoneyFlow?.relativeVolume20,statusAr:'ليس ضمن توصيات اليوم'};renderRecs();renderSelected();if(m?.chartPath)draw(m.chartPath);else $('chartBox').innerHTML='<div class="empty">لا يتوفر رسم.</div>'}
function renderSelected(){let r=S.sel;if(!r)return;let is=A(S.d?.recommendations).some(x=>x.ticker===r.ticker),g=is?gate(r):null,m=market(r.ticker),f=fs(fund(r.ticker),r.close);$('selectedTitle').textContent=r.ticker+' — '+(r.companyNameAr||'');$('selectedSubtitle').textContent=is?(r.strategyLabelAr+' | خطة '+F(r.holdingSessions,0)+' جلسات'):'السهم متاح في البحث لكنه ليس ضمن توصيات اليوم.';$('selectedDecision').textContent=is?g.label:'ليس ضمن توصيات اليوم';$('selectedDecision').className='badge '+(is?g.cls:'neutral');$('technicalDetail').innerHTML=[row('الحالة',is?g.label:'بحث فقط'),row('RSI 14',F(r.rsi14??m?.momentumMoneyFlow?.rsi14,1)),row('نشاط الحجم',F(r.volumeRatio20??m?.momentumMoneyFlow?.relativeVolume20,2)+'×'),row('زخم 20 جلسة',P(r.ret20Pct)),row('احتمال الهدف Backtest',P(r.estimatedTargetProbabilityPct)),row('احتمال الوقف Backtest',P(r.estimatedStopProbabilityPct))].join('');$('riskDetail').innerHTML=[row('الدخول',is?F(r.entryLow,3)+'–'+F(r.entryHigh,3):'غير متاح'),row('الهدف',F(r.target1,3)),row('الوقف',F(r.stopLoss,3)),row('العائد/المخاطرة',F(r.riskReward),N(r.riskReward)<1?'amber':''),row('السيولة',M(r.averageTurnover20Egp)),row('ثبات النموذج',is?g.st.label:'غير مطبق')].join('');$('fundamentalDetail').innerHTML=[row('الدرجة المالية',Math.round(f.score)+'/100',f.cls==='good'?'green':f.cls==='warn'?'amber':'red'),row('الحكم',f.label),row('المصدر المدقق',fund(r.ticker)?.auditedData?'نعم':'لا'),row('القيمة العادلة',F(fund(r.ticker)?.fairValue)),row('التدفق التشغيلي',fund(r.ticker)?.positiveCfo?'موجب':'غير مؤكد'),row('القرار طويل الأجل',f.score>=70?'قابل للمراجعة':'محجوب حتى اكتمال البيانات')].join('');$('addPortfolioBtn').disabled=!is||g.status==='blocked';calc()}
function calc(){let r=S.sel,c=N($('capitalInput').value)||0,rp=N($('riskPctInput').value)||0,mw=N($('maxWeightInput').value)||0;if(!r?.entryHigh||!r?.stopLoss){$('positionResult').innerHTML='<div class="empty">لا توجد خطة قابلة للحساب.</div>';return}let ra=c*rp/100,ps=r.entryHigh-r.stopLoss,qr=ps>0?Math.floor(ra/ps):0,qw=Math.floor(c*mw/100/r.entryHigh),ql=Math.floor((N(r.averageTurnover20Egp)||0)*.005/r.entryHigh),q=Math.max(0,Math.min(qr,qw,ql||qr)),nv=q*r.entryHigh,risk=q*ps;$('positionResult').innerHTML=[['الكمية القصوى',F(q,0)],['قيمة المركز',M(nv)],['الخطر عند الوقف',M(risk)],['وزن المركز',c?P(nv/c*100):'—'],['حد السيولة','0.5% من المتوسط']].map(x=>`<div class="result-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');Object.assign($('addPortfolioBtn').dataset,{q,nv,risk})}
async function draw(path){try{let d=await J(path,true),rs=Array.isArray(d)?d:A(d?.sessions).length?d.sessions:A(d?.rows).length?d.rows:A(d?.history),a=rs.map(x=>({d:x.date||x.sessionDate||x.session,c:N(x.close)})).filter(x=>x.d&&x.c!==null).sort((x,y)=>String(x.d).localeCompare(String(y.d))).slice(-80);if(a.length<2)throw Error('بيانات غير كافية');let W=1000,H=320,l=55,r=20,t=20,b=38,v=a.map(x=>x.c),mn=Math.min(...v),mx=Math.max(...v),rg=mx-mn||1,X=i=>l+i/(a.length-1)*(W-l-r),Y=x=>t+(mx-x)/rg*(H-t-b),pts=a.map((p,i)=>X(i).toFixed(1)+','+Y(p.c).toFixed(1)).join(' '),grid=[0,.25,.5,.75,1].map(k=>{let y=t+k*(H-t-b);return`<line x1="${l}" y1="${y}" x2="${W-r}" y2="${y}" stroke="#18394d"/>`}).join('');$('chartBox').innerHTML=`<svg viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#061521"/>${grid}<polyline points="${pts}" fill="none" stroke="#39bdf0" stroke-width="3"/><text x="${l}" y="${H-10}" fill="#91afc1" font-size="11">${E(a[0].d)}</text><text x="${W-r}" y="${H-10}" fill="#91afc1" font-size="11" text-anchor="end">${E(a.at(-1).d)}</text></svg>`}catch(e){$('chartBox').innerHTML='<div class="empty">تعذر تحميل الرسم: '+E(e.message)+'</div>'}}
function renderMarket(){let q=norm($('marketSearch').value),sc=$('marketScope').value,R=new Set(A(S.d?.recommendations).map(x=>x.ticker)),a=A(S.m?.stocks).filter(x=>{let ok=!q||String(x.searchText||norm(x.ticker+' '+x.companyNameAr)).includes(q),ir=R.has(x.ticker);return ok&&(sc==='all'||sc==='recommended'&&ir||sc==='outside'&&!ir)}).slice(0,60);$('marketResults').innerHTML=a.length?a.map(x=>{let ir=R.has(x.ticker);return`<div class="market-row" data-m="${E(x.ticker)}"><div><b class="blue">${E(x.ticker)}</b><br><small>${ir?'ضمن توصيات اليوم':'ليس ضمن توصيات اليوم'}</small></div><div>${E(x.companyNameAr||x.companyNameEn)}</div><div>${F(x.price,3)}</div><div class="hide-mobile">${P(x.changePct)}</div><div class="hide-tablet">${P(x.liquidityPercentile)}</div><div class="hide-tablet optional-col">${F(x.momentumMoneyFlow?.moneyFlowQualityScore,1)}</div><div class="hide-mobile"><span class="badge ${ir?'good':'neutral'}">${ir?'مراجعة توصية':'تحليل فقط'}</span></div></div>`}).join(''):'<div class="empty">لا توجد نتائج.</div>';$('marketResults').querySelectorAll('[data-m]').forEach(x=>x.onclick=()=>{view('dashboard');select(x.dataset.m)})}
function add(){let r=S.sel,q=N($('addPortfolioBtn').dataset.q)||0;if(!r||q<=0)return toast('الكمية غير صالحة.');S.pf.push({id:r.ticker+'-'+Date.now(),ticker:r.ticker,name:r.companyNameAr,strategyId:r.strategyId,strategyLabel:r.strategyLabelAr,entry:r.entryHigh,stop:r.stopLoss,target:r.target1,quantity:q,notional:N($('addPortfolioBtn').dataset.nv)||0,risk:N($('addPortfolioBtn').dataset.risk)||0});W(K.pf,S.pf);renderPF();toast('تمت الإضافة للمحفظة التجريبية.')}
function pfMetrics(){let c=N($('capitalInput').value)||100000,tr=S.pf.reduce((s,x)=>s+(N(x.risk)||0),0),tn=S.pf.reduce((s,x)=>s+(N(x.notional)||0),0),bs={};S.pf.forEach(x=>bs[x.strategyId]=(bs[x.strategyId]||0)+(N(x.notional)||0));let mx=Math.max(0,...Object.values(bs));return{c,tr,tn,rp:c?tr/c*100:0,ep:c?tn/c*100:0,sp:tn?mx/tn*100:0,n:S.pf.length}}
function renderPF(){let m=pfMetrics(),rl=N($('portfolioRiskLimit').value)||S.s.portfolioRiskLimit,pl=N($('portfolioPositionLimit').value)||S.s.portfolioPositionLimit,sl=N($('strategyExposureLimit').value)||S.s.strategyExposureLimit;S.s={portfolioRiskLimit:rl,portfolioPositionLimit:pl,strategyExposureLimit:sl};W(K.s,S.s);$('portfolioSummary').innerHTML=[['عدد المراكز',m.n+'/'+pl,m.n>pl?'red':''],['الخطر المفتوح',P(m.rp),m.rp>rl?'red':''],['إجمالي التعرض',P(m.ep),m.ep>70?'amber':''],['أعلى تركّز استراتيجية',P(m.sp),m.sp>sl?'red':''],['قيمة المراكز',M(m.tn),''],['الخطر النقدي',M(m.tr),'']].map(x=>`<div class="summary-card"><small>${x[0]}</small><b class="${x[2]}">${x[1]}</b></div>`).join('');$('portfolioRows').innerHTML=S.pf.length?S.pf.map(x=>`<tr><td><b class="blue">${E(x.ticker)}</b><br>${E(x.name)}</td><td>${E(x.strategyLabel)}</td><td>${F(x.entry,3)}</td><td>${F(x.stop,3)}</td><td>${F(x.quantity,0)}</td><td>${M(x.notional)}</td><td>${M(x.risk)}</td><td><span class="model-status ${m.rp>rl||m.n>pl||m.sp>sl?'warn':'good'}">${m.rp>rl||m.n>pl||m.sp>sl?'مراجعة مطلوبة':'ضمن الحدود'}</span></td><td><button class="btn danger" data-r="${E(x.id)}">حذف</button></td></tr>`).join(''):'<tr><td colspan="9" class="empty">لا توجد مراكز تجريبية.</td></tr>';$('portfolioRows').querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{S.pf=S.pf.filter(x=>x.id!==b.dataset.r);W(K.pf,S.pf);renderPF()})}
function fillF(){let z=new Map();A(S.m?.stocks).forEach(x=>z.set(x.ticker,x.companyNameAr||x.companyNameEn));A(S.d?.recommendations).forEach(x=>z.set(x.ticker,x.companyNameAr));$('fundamentalTicker').innerHTML=[...z].sort().map(x=>`<option value="${E(x[0])}">${E(x[0])} — ${E(x[1])}</option>`).join('');if(S.sel?.ticker&&z.has(S.sel.ticker))$('fundamentalTicker').value=S.sel.ticker;loadF()}
function loadF(){let d=fund($('fundamentalTicker').value)||{};['revenueGrowth','profitGrowth','roe','debtEquity','pe','fairValue','fundamentalNotes'].forEach(i=>$(i).value=d[i]??'');$('positiveCfo').checked=!!d.positiveCfo;$('auditedData').checked=!!d.auditedData;renderF()}
function saveF(){let t=$('fundamentalTicker').value;S.f[t]={revenueGrowth:N($('revenueGrowth').value),profitGrowth:N($('profitGrowth').value),roe:N($('roe').value),debtEquity:N($('debtEquity').value),pe:N($('pe').value),fairValue:N($('fairValue').value),positiveCfo:$('positiveCfo').checked,auditedData:$('auditedData').checked,fundamentalNotes:$('fundamentalNotes').value.trim()};W(K.f,S.f);renderF();renderReady();renderRecs();if(S.sel?.ticker===t)renderSelected();toast('تم حفظ المراجعة المالية.')}
function renderF(){let t=$('fundamentalTicker').value,m=market(t),r=A(S.d?.recommendations).find(x=>x.ticker===t),s=fs(fund(t),r?.close??m?.price);$('fundamentalScoreCard').innerHTML=`<div class="score-circle" style="background:conic-gradient(${s.score>=70?'var(--green)':s.score>=50?'var(--amber)':'var(--red)'} ${s.score*3.6}deg,#17364b 0)"><strong>${Math.round(s.score)}</strong><span>${E(s.label)}</span></div><div class="score-notes">${s.notes.map(x=>`<div class="score-note">${E(x)}</div>`).join('')}${fund(t)?.fundamentalNotes?`<div class="score-note">ملاحظات: ${E(fund(t).fundamentalNotes)}</div>`:''}</div>`}
function renderEvidence(){
  const history=S.h||{};
  const ms=history.memberSummary||{};
  const sessions=A(history.sessions);
  const records=sessions.flatMap(session=>
    A(session.members).map(member=>({
      ...member,
      recommendationDate:session.signalDate,
      strategyLabelAr:'سلة V16.9 الرئيسية'
    }))
  ).sort((a,b)=>
    String(b.recommendationDate||'').localeCompare(String(a.recommendationDate||'')) ||
    (N(a.rank)||999)-(N(b.rank)||999)
  );

  const total=N(ms.totalRecommendations)??records.length;
  const targetHits=N(ms.targetHits)??records.filter(x=>x.memberStatus==='TARGET_HIT').length;
  const stopHits=N(ms.stopHits)??records.filter(x=>x.memberStatus==='STOP_HIT').length;
  const waiting=N(ms.waiting)??records.filter(x=>x.memberStatus==='WAITING').length;
  const resolved=targetHits+stopHits;
  const successRate=N(ms.successRatePct)??(resolved?targetHits/resolved*100:null);
  const progress=total?C(resolved/total*100,0,100):0;

  $('liveEvidenceSummary').innerHTML=[
    ['إجمالي التوصيات الرئيسية',F(total,0)],
    ['حققت الهدف',F(targetHits,0)],
    ['وقف خسارة',F(stopHits,0)],
    ['ما زالت في الانتظار',F(waiting,0)],
    ['نسبة النجاح للمحسوم',P(successRate)],
    ['الجلسات الرئيسية',F(sessions.length,0)]
  ].map(x=>`<div class="summary-card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');

  $('confidenceGate').innerHTML=`
    <div class="confidence-box">
      <span class="badge ${waiting===0&&total?'good':resolved?'warn':'bad'}">متابعة التوصيات الرئيسية</span>
      <div class="confidence-progress"><i style="width:${progress}%"></i></div>
      <b>${resolved}/${total} توصية محسومة</b>
      <div class="professional-verdict warn">
        نسبة النجاح = حققت الهدف ÷ (حققت الهدف + وقف الخسارة). التوصيات المنتظرة لا تدخل في النسبة.
      </div>
    </div>`;

  $('evaluationRows').innerHTML=records.map(x=>{
    const status=x.memberStatus||'WAITING';
    const cls=status==='TARGET_HIT'?'good':status==='STOP_HIT'?'bad':'warn';
    const statusAr=x.statusAr||(status==='TARGET_HIT'?'تم تحقيق الهدف':status==='STOP_HIT'?'تم ضرب وقف الخسارة':'ما زالت داخل الانتظار');
    const realized=status==='TARGET_HIT'||status==='STOP_HIT';
    return `<tr>
      <td>${E(x.recommendationDate)}</td>
      <td><b class="blue">${E(x.ticker)}</b></td>
      <td>${E(x.strategyLabelAr)}</td>
      <td>${F(x.entryPrice??x.entryHigh,3)}</td>
      <td>${F(x.target1,3)}</td>
      <td>${F(x.stopLoss,3)}</td>
      <td><span class="model-status ${cls}">${E(statusAr)}</span></td>
      <td>${realized?P(x.netReturnPct):'—'}</td>
    </tr>`;
  }).join('')||'<tr><td colspan="8" class="empty">لا يوجد سجل للتوصيات الرئيسية.</td></tr>';

  $('modelRows').innerHTML=A(S.v?.models).map(m=>{let s=stab(m);return`<tr><td><b>${E(m.labelAr)}</b><br><small>${E(m.id)}</small></td><td>${P(m.development?.averageReturnPct)} | PF ${F(m.development?.profitFactor)}</td><td>${P(m.validation?.averageReturnPct)} | PF ${F(m.validation?.profitFactor)}</td><td>${P(m.test?.averageReturnPct)} | PF ${F(m.test?.profitFactor)}</td><td>${F(m.test?.profitFactor)}</td><td>${Math.round(s.score)}/100</td><td><span class="model-status ${s.cls}">${E(s.label)}</span><br><small>${E(s.reason)}</small></td></tr>`}).join('');
}
function view(n){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===n));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+n));if(n==='market')renderMarket();if(n==='portfolio')renderPF();if(n==='fundamentals')fillF();if(n==='evidence')renderEvidence();scrollTo({top:0,behavior:'smooth'})}
function bind(){document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>view(x.dataset.view));$('refreshBtn').onclick=load;$('recommendationFilter').onchange=renderRecs;$('marketSearch').oninput=renderMarket;$('marketScope').onchange=renderMarket;['capitalInput','riskPctInput','maxWeightInput'].forEach(i=>$(i).oninput=()=>{calc();renderPF()});$('addPortfolioBtn').onclick=add;['portfolioRiskLimit','portfolioPositionLimit','strategyExposureLimit'].forEach(i=>$(i).oninput=renderPF);$('clearPortfolioBtn').onclick=()=>{S.pf=[];W(K.pf,[]);renderPF()};$('fundamentalTicker').onchange=loadF;$('saveFundamentalBtn').onclick=saveF}
async function load(){try{$('lastUpdate').textContent='جارٍ تحديث البيانات…';[S.d,S.v,S.e,S.h,S.p,S.u,S.m]=await Promise.all([J(U.d),J(U.v),J(U.e),J(U.h,true),J(U.p),J(U.u,true),J(U.m,true)]);S.pf=L(K.pf,[]);S.f=L(K.f,{});S.s={...S.s,...L(K.s,{})};$('portfolioRiskLimit').value=S.s.portfolioRiskLimit;$('portfolioPositionLimit').value=S.s.portfolioPositionLimit;$('strategyExposureLimit').value=S.s.strategyExposureLimit;let t=S.u?.lastAutomaticScanAt||S.d.generatedAt;$('lastUpdate').textContent='آخر مسح: '+new Date(t).toLocaleString('ar-EG',{dateStyle:'medium',timeStyle:'short'});renderReady();renderTruth();renderRecs();renderMarket();renderPF();renderEvidence();let f=A(S.d.recommendations)[0];if(f)await select(f.ticker);fillF();toast('تم تحميل V16 الاحترافية.')}catch(e){document.querySelector('main').innerHTML='<div class="panel"><div class="empty red">تعذر التحميل: '+E(e.message)+'</div></div>'}}
bind();load();setInterval(load,300000);
