import fs from'node:fs';import path from'node:path';import{adaptEgxNewsRecord}from'../src/egx-official-adapter.js';import{buildAuthoritativeUniverse}from'../src/universe-authority.js';import{evaluatePhase3Gate}from'../src/phase3-gate.js';import{issueBaselineAuthorization}from'../src/phase-transition.js';import{sha256}from'../src/hash.js';
const root=process.cwd();
const fixture=JSON.parse(fs.readFileSync(path.join(root,'evidence/official/egx-beta-identity-sample-2026-08-31.json'),'utf8'));
const discoveryPath=path.join(root,'evidence/official/source-discovery-status.json');
const discovery=fs.existsSync(discoveryPath)?JSON.parse(fs.readFileSync(discoveryPath,'utf8')):null;
const adapted=fixture.records.map(r=>adaptEgxNewsRecord(r,{sourceId:fixture.source.id}));
const identityEvidence=adapted.filter(x=>x.state==='READY').map(x=>x.evidence);
const ignored=adapted.filter(x=>x.state==='IGNORED_NON_EQUITY').length;
const universe=buildAuthoritativeUniverse(identityEvidence,{asOfDate:fixture.asOfDate,requireSnapshot:true});
const gate=evaluatePhase3Gate({universe,registry:null,sessionAuthority:null,acquisitionPlans:[],sourceReceipts:[]});
const phase4Authorization=issueBaselineAuthorization({state:'FAIL',session:fixture.asOfDate,calendarVersion:null,universeVersion:universe.version,registryVersion:null,registry:null,coverage:null,observationCertificateHashes:[],reportHash:null,phase3:gate});
const report={
  schemaVersion:'egx-one-phase3-status-12',generatedFrom:'reproducible_checked_in_official_identity_sample',asOfDate:fixture.asOfDate,
  policy:{sourceReceiptsRequired:true,independentProviderCrossCheckRequired:true,searchSnippetsMayBeAuthoritativeRawEvidence:false,unverifiedBulletinContentMayAuthorizeBaseline:false,officialInclusionEvidenceRequiresReceiptScopeAndUniverseCertificate:true,certifiedUniverseBindsExtractionCertificate:true,productionSessionRequiresPersistedCertifiedUniverse:true,currentSessionBarsRequireMarketObservationCertificates:true,productionHistoricalBarsRequireCertifiedLineage:true,historicalProductionAuthorityExcludesPublicAndHistoryOnlySources:true,licensedEodHistoricalLineageRequiresDatasetAdmissionCertificate:true,licensedDatasetAdmissionBindsEntitlementRawDatasetCoverageParserAndIndependentCrossCheck:true,licensedDatasetAdmissionCapabilityEvidenceBodyReverified:true,licensedDatasetAdmissionDoesNotGrantProductionAuthority:true,licensedEntitlementHashIsEvidenceAnchorNotVendorSignature:true,productionMarketFeaturesRequireExactCertifiedInputLineage:true,productionFeatureSourceVersionMustEqualNormalizedSnapshot:true,productionFeatureInputLineageBindsCurrentAndHistoryCertificates:true,productionSsotRequiresCertifiedReconciliation:true,productionSessionManifestRequiresCertifiedSnapshot:true,sessionManifestDirectSqlAdmissionVerified:true,rawAndNormalizedRowHashesVerifiedAtSqlAdmission:true,ssotAggregateHashesRecomputedFromPersistedRows:true,productionRecommendationRequiresCertifiedSessionManifest:true,productionRecommendationRequiresVerifiedBaselineAuthorization:true,researchRecommendationsAreAuthoritySeparated:true,baselineAuthorizationIsAppendOnly:true,baselineSourceReportHashIsRecomputed:true,baselineRequiresPersistedRegistryManifest:true,baselineRegistryMembershipMustEqualCertifiedUniverse:true,registryManifestBindsExactRows:true,registryRowsAreAppendOnly:true},
  officialEvidence:{source:fixture.source,identityEquities:identityEvidence.length,ignoredNonEquity:ignored,exhaustive:fixture.exhaustive,evidenceHash:sha256(fixture)},
  sourceDiscovery:discovery?{state:discovery.state,officialDirectPage:discovery.officialDirectPage,bulletinDiscovery:discovery.bulletinDiscovery,discoveryHash:sha256(discovery)}:{state:'NOT_RECORDED'},
  sourceProvenance:{state:'NOT_EVALUATED_UNTIL_EXHAUSTIVE_UNIVERSE_AND_CURRENT_SESSION',requiredRuntimeProofs:['PRIMARY_AUTHORITATIVE_RECEIPT','PRIMARY_MARKET_OBSERVATION_CERTIFICATE','INDEPENDENT_CROSSCHECK_RECEIPT','INDEPENDENT_CROSSCHECK_MARKET_OBSERVATION_CERTIFICATE','CERTIFIED_PRODUCTION_RECONCILIATION_MANIFEST','HISTORICAL_OBSERVATION_LINEAGE_CERTIFICATES','LICENSED_EOD_DATASET_ADMISSION_CERTIFICATE_WHEN_LICENSED_HISTORY_USED','PRODUCTION_FEATURE_INPUT_LINEAGE_MANIFEST'],requiredUniverseProofs:['OFFICIAL_SOURCE_RECEIPT_HASH','OFFICIAL_DOCUMENT_SCOPE_PROOF_HASH','UNIVERSE_EXTRACTION_CERTIFICATE_HASH'],requiredSsotProofs:['CERTIFIED_UNIVERSE_AUTHORITY_PROOF','CERTIFIED_PRODUCTION_SOURCE_MANIFEST','CERTIFIED_RECONCILIATION_MANIFEST_HASH','PRIMARY_OBSERVATION_CERTIFICATE_HASH','CERTIFIED_HISTORICAL_OBSERVATION_LINEAGE','LICENSED_DATASET_ADMISSION_HASH_WHEN_APPLICABLE','PRODUCTION_FEATURE_INPUT_LINEAGE_HASH','CERTIFIED_PRODUCTION_SESSION_MANIFEST','HASH_VERIFIED_IMMUTABLE_REGISTRY_MANIFEST','VERIFIED_BASELINE_AUTHORIZATION_AND_SOURCE_REPORT'],downstreamAuthorityGuards:['PERSISTED_CERTIFIED_UNIVERSE_REQUIRED_FOR_PRODUCTION_SESSION','CERTIFIED_UNIVERSE_BINDS_EXTRACTION_CERTIFICATE','DIRECT_SQL_PRODUCTION_SESSION_REQUIRES_CERTIFIED_LINEAGE','PRODUCTION_HISTORY_REQUIRES_OFFICIAL_OR_LICENSED_SOURCE_LINEAGE','PUBLIC_MARKET_AND_HISTORY_ONLY_SOURCES_CANNOT_AUTHORIZE_PRODUCTION_HISTORY','LICENSED_EOD_HISTORY_REQUIRES_VERIFIED_DATASET_ADMISSION','LICENSED_EOD_ADMISSION_BINDS_RAW_DATASET_RECEIPT_AND_EXACT_BAR_PROOFS','LICENSED_EOD_ADMISSION_REQUIRES_ENTITLEMENT_AND_APPLICATION_USE_EVIDENCE','LICENSED_EOD_ADMISSION_CAPABILITY_BODY_IS_REEVALUATED_AND_HASH_BOUND','LICENSED_EOD_ADMISSION_REQUIRES_REGISTERED_PARSER_REPLAY','LICENSED_EOD_ADMISSION_REQUIRES_INDEPENDENT_PROVIDER_CROSSCHECK','LICENSE_HASH_IS_EVIDENCE_ANCHOR_NOT_VENDOR_SIGNATURE','LICENSED_DATASET_ADMISSION_IS_NOT_PRODUCTION_AUTHORITY','PRODUCTION_FUTURE_BARS_FORBIDDEN','PRODUCTION_FEATURE_SOURCE_VERSION_EQUALS_NORMALIZED_SNAPSHOT','PRODUCTION_FEATURE_INPUT_LINEAGE_BINDS_CURRENT_AND_HISTORY_CERTIFICATES','PRODUCTION_FEATURE_HISTORY_COVERAGE_MUST_MATCH_DECLARATION','RAW_AND_NORMALIZED_ROW_HASHES_RECOMPUTED_AT_SQL_ADMISSION','FIRST_FINALIZATION_HASH_RECOMPUTED_FROM_EXACT_PERSISTED_ROWS','REGISTRY_VERSION_EQUALS_HASH_OF_EXACT_ROWS','REGISTRY_MEMBER_MUST_EXIST_IN_FROZEN_MANIFEST','REGISTRY_ROWS_AND_MANIFEST_APPEND_ONLY','BASELINE_REGISTRY_MEMBERSHIP_EQUALS_CERTIFIED_UNIVERSE','BASELINE_REQUIRES_MATCHING_PERSISTED_REGISTRY','PRODUCTION_RECOMMENDATION_REQUIRES_CERTIFIED_PRODUCTION_SESSION','PRODUCTION_RECOMMENDATION_REQUIRES_MATCHING_BASELINE_AUTHORIZATION','BASELINE_AUTHORIZATION_SOURCE_REPORT_HASH_RECOMPUTED','BASELINE_AUTHORIZATION_SQL_INSERT_VERIFIED','RESEARCH_RECOMMENDATION_REQUIRES_RESEARCH_SESSION','RECOMMENDATION_LEDGER_AUTHORITY_MODE_MATCH','SESSION_UNIVERSE_REGISTRY_BASELINE_AND_RECOMMENDATION_APPEND_ONLY']},
  universe:{state:universe.state,reasons:universe.reasons,total:universe.total},phase3:{verdict:gate.verdict,baselineAuthorized:gate.baselineAuthorized,blockers:gate.blockers},phase4:{state:'LOCKED',authorizationState:phase4Authorization.state,authorizationToken:phase4Authorization.authorizationToken,reasons:phase4Authorization.reasons},
  interpretation:'Architecture and contracts may pass CI while operational Phase 3 remains FAIL. Identity/disclosure evidence is intentionally insufficient. Phase 4 is machine-locked until an exhaustive receipt-, scope-, extraction-certificate-, and Certified-Universe-authority-bound official EGX equity universe is persisted, together with versioned session authority, authoritative post-close current-session observations with independent certified cross-checks, and Certified Historical Observation Lineage for every historical bar used by the Production snapshot. OFFICIAL_EXCHANGE history requires direct receipt and deterministic parser replay. LICENSED_EOD history additionally requires a verified Dataset Admission Certificate binding entitlement/application-use evidence, a normalized self-contained provider capability evidence body that is re-evaluated and hash-bound, the exact raw dataset receipt and hash, a registered parser, exact traded-universe coverage and bar proofs, and an independent-provider receipt. The licenseReceiptHash is an evidence/document anchor, not a vendor cryptographic signature, and a Licensed Dataset Admission Certificate never grants Production authority by itself. Production market-derived feature bundles must use the exact normalized snapshot and bind the current observation certificate plus exact historical lineage certificate coverage. Public-market and history-only feeds remain Research/cross-check evidence and can never silently authorize Production history. A CERTIFIED_PRODUCTION reconciliation manifest, hash-bound CERTIFIED_PRODUCTION Session Manifest, and hash-verified immutable Registry Manifest whose exact membership equals the persisted Certified Universe are required. Baseline Authorization must reference that persisted registry and a recomputed source-report hash before any production recommendation can be admitted; research lineage remains authority-separated.'
};
fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});fs.writeFileSync(path.join(root,'artifacts/phase3-current-status.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));