import test from 'node:test';
import assert from 'node:assert/strict';
import { assessHolding, buildAllocation } from '../public/portfolio-manager.js';

const base={publicationEligible:true,publicationState:'RESEARCH_CANDIDATE',quality:{state:'REVIEW'},reasonCodes:[],scores:{core:80,fusionRank:78},tradePlan:{entryLow:9.8,entryHigh:10.2,stop:9.2,target1:11,target2:12}};

test('portfolio manager exits on stop breach and never executes automatically',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:100,avgCost:10,stop:9.5},analysis:base,price:9.4,equity:10000,maxWeightPct:20});assert.equal(r.action,'EXIT');assert.equal(r.executionAllowed,false)});
test('portfolio manager takes partial profit after T1',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:100,avgCost:9.5},analysis:base,price:11.2,equity:20000,maxWeightPct:20});assert.equal(r.action,'T1')});
test('portfolio manager allows only conditional add inside entry',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:20,avgCost:10},analysis:base,price:10,equity:10000,maxWeightPct:20});assert.equal(r.action,'ADD');assert.equal(r.scoringImpact,'NONE')});
test('overweight position is reduced before add',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:300,avgCost:9},analysis:base,price:10,equity:10000,maxWeightPct:20});assert.equal(r.action,'REDUCE')});
test('cash allocation respects reserve, risk and weight caps',()=>{const a=buildAllocation({cash:50000,equity:100000,positions:[],reservePct:20,riskPerTradePct:.5,maxWeightPct:10,totalRiskPct:2,recommendations:[{ticker:'AAA',rank:1,scores:{fusionRank:80},tradePlan:{entryLow:9.8,entryHigh:10,stop:9,target1:11,target2:12}},{ticker:'BBB',rank:2,scores:{fusionRank:75},tradePlan:{entryLow:19.5,entryHigh:20,stop:18,target1:22,target2:24}}]});assert.equal(a.blocked,false);assert.equal(a.executionAllowed,false);assert.equal(a.automaticOrders,false);assert.ok(a.allocated<=40000+1e-9);assert.ok(a.plannedRisk<=2000+1e-9);assert.ok(a.rows.every(r=>r.weightPct<=10.001))});
test('unknown active risk blocks new cash allocation fail closed',()=>{const a=buildAllocation({cash:50000,equity:100000,positions:[{ticker:'OLD',action:'HOLD',riskKnown:false,riskCash:null,value:20000}],recommendations:[{ticker:'AAA',tradePlan:{entryLow:9.8,entryHigh:10,stop:9,target1:11,target2:12}}]});assert.equal(a.blocked,true);assert.equal(a.rows.length,0)});
test('portfolio manager source cannot import Alpha or enable execution',async()=>{const fs=await import('node:fs/promises');const src=await fs.readFile(new URL('../public/portfolio-manager.js',import.meta.url),'utf8');assert.equal(/src\/(engine|policy|confidence|originalScore|repository)/.test(src),false);assert.equal(/executionAllowed\s*[:=]\s*true/i.test(src),false);assert.equal(/automaticOrders\s*[:=]\s*true/i.test(src),false)});
