import test from 'node:test';
import assert from 'node:assert/strict';
import { assessHolding, buildAllocation } from '../public/portfolio-manager.js';

const base={publicationEligible:true,publicationState:'RESEARCH_CANDIDATE',quality:{state:'REVIEW'},reasonCodes:[],scores:{core:80,fusionRank:78},tradePlan:{entryLow:9.8,entryHigh:10.2,stop:9.2,target1:11,target2:12}};
const rec=(ticker,rank=1,entry=10,stop=9)=>({ticker,rank,scores:{fusionRank:80-rank},tradePlan:{entryLow:entry*.98,entryHigh:entry,stop,target1:entry*1.1,target2:entry*1.2}});

test('portfolio manager exits on stop breach and never executes automatically',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:100,avgCost:10,stop:9.5},analysis:base,price:9.4,equity:10000,maxWeightPct:20});assert.equal(r.action,'EXIT');assert.equal(r.executionAllowed,false)});
test('portfolio manager takes partial profit after T1',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:100,avgCost:9.5},analysis:base,price:11.2,equity:20000,maxWeightPct:20});assert.equal(r.action,'T1')});
test('portfolio manager allows only conditional add inside entry',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:20,avgCost:10},analysis:base,price:10,equity:10000,maxWeightPct:20});assert.equal(r.action,'ADD');assert.equal(r.scoringImpact,'NONE')});
test('overweight position is reduced before add',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:300,avgCost:9},analysis:base,price:10,equity:10000,maxWeightPct:20});assert.equal(r.action,'REDUCE')});
test('cash allocation respects reserve, risk and weight caps',()=>{const a=buildAllocation({cash:50000,equity:100000,positions:[],reservePct:20,riskPerTradePct:.5,maxWeightPct:10,totalRiskPct:2,recommendations:[{ticker:'AAA',rank:1,scores:{fusionRank:80},tradePlan:{entryLow:9.8,entryHigh:10,stop:9,target1:11,target2:12}},{ticker:'BBB',rank:2,scores:{fusionRank:75},tradePlan:{entryLow:19.5,entryHigh:20,stop:18,target1:22,target2:24}}]});assert.equal(a.blocked,false);assert.equal(a.executionAllowed,false);assert.equal(a.automaticOrders,false);assert.ok(a.allocated<=40000+1e-9);assert.ok(a.plannedRisk<=2000+1e-9);assert.ok(a.rows.every(r=>r.weightPct<=10.001))});
test('unknown active risk blocks new cash allocation fail closed',()=>{const a=buildAllocation({cash:50000,equity:100000,positions:[{ticker:'OLD',action:'HOLD',riskKnown:false,riskCash:null,value:20000}],recommendations:[{ticker:'AAA',tradePlan:{entryLow:9.8,entryHigh:10,stop:9,target1:11,target2:12}}]});assert.equal(a.blocked,true);assert.equal(a.rows.length,0)});
test('portfolio manager source cannot import Alpha or enable execution',async()=>{const fs=await import('node:fs/promises');const src=await fs.readFile(new URL('../public/portfolio-manager.js',import.meta.url),'utf8');assert.equal(/src\/(engine|policy|confidence|originalScore|repository)/.test(src),false);assert.equal(/executionAllowed\s*[:=]\s*true/i.test(src),false);assert.equal(/automaticOrders\s*[:=]\s*true/i.test(src),false)});

test('F1 duplicate recommendation ticker is deduplicated and best rank kept',()=>{const a=buildAllocation({cash:50000,equity:100000,positions:[],reservePct:0,riskPerTradePct:.5,maxWeightPct:10,totalRiskPct:2,recommendations:[rec('NNN',2),{...rec('NNN',1),scores:{fusionRank:90}}]});assert.equal(a.rows.length,1);assert.equal(a.rows[0].ticker,'NNN');assert.equal(a.rows[0].rank,1);assert.ok(a.rows[0].weightPct<=10.000001)});
test('EXIT REDUCE REVIEW tickers are excluded from tomorrow allocation',()=>{const positions=[{ticker:'AAA',action:'EXIT',riskKnown:false,riskCash:null,value:1000},{ticker:'BBB',action:'REDUCE',riskKnown:true,riskCash:50,value:1000},{ticker:'CCC',action:'REVIEW',riskKnown:false,riskCash:null,value:1000}];const a=buildAllocation({cash:50000,equity:100000,positions,recommendations:[rec('AAA',1),rec('BBB',2),rec('CCC',3),rec('DDD',4)]});assert.equal(a.blocked,false);assert.deepEqual(a.rows.map(x=>x.ticker),['DDD'])});
test('malformed plans are excluded from allocation',()=>{const a=buildAllocation({cash:50000,equity:100000,positions:[],recommendations:[{ticker:'BAD1',tradePlan:{entryLow:9,entryHigh:9,stop:9}},{ticker:'BAD2',tradePlan:{entryLow:9,entryHigh:10,stop:0}},{ticker:'BAD3',tradePlan:{entryLow:9,entryHigh:8,stop:9}},rec('GOOD',4,10,9)]});assert.deepEqual(a.rows.map(x=>x.ticker),['GOOD'])});
test('T2 profit-taking has precedence over overweight reduce',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:300,avgCost:9},analysis:base,price:12.5,equity:10000,maxWeightPct:20});assert.equal(r.action,'T2')});
test('user stop at or above current price stays fail-closed EXIT with explicit warning',()=>{const r=assessHolding({holding:{ticker:'TEST',qty:100,avgCost:10,stop:50},analysis:base,price:12,equity:20000,maxWeightPct:20});assert.equal(r.action,'EXIT');assert.ok(r.reasons.some(x=>x.includes('Stop المستخدم')))});
test('100 percent reserve allocates nothing',()=>{const a=buildAllocation({cash:50000,equity:100000,positions:[],reservePct:100,recommendations:[rec('AAA')]});assert.equal(a.rows.length,0);assert.equal(a.allocated,0);assert.equal(a.remainingCash,50000)});
test('existing position exactly at max weight receives no additional allocation',()=>{const positions=[{ticker:'AAA',action:'HOLD',riskKnown:true,riskCash:100,value:10000}];const a=buildAllocation({cash:50000,equity:100000,positions,maxWeightPct:10,recommendations:[rec('AAA')]});assert.equal(a.rows.length,0)});
test('permanent deterministic 2000-trial allocation invariants',()=>{let seed=0xC0FFEE;const rnd=()=>((seed=(1664525*seed+1013904223)>>>0)/2**32);for(let trial=0;trial<2000;trial++){const equity=10000+Math.floor(rnd()*990000),cash=Math.floor(rnd()*equity),reservePct=Math.floor(rnd()*51),riskPerTradePct=.05+rnd()*1.95,maxWeightPct=2+rnd()*23,totalRiskPct=.5+rnd()*4.5,positions=[],held=new Map(),pc=Math.floor(rnd()*5);for(let i=0;i<pc;i++){const ticker='H'+i,value=rnd()*equity*maxWeightPct/100,riskCash=rnd()*value*.08;positions.push({ticker,action:'HOLD',riskKnown:true,riskCash,value});held.set(ticker,value)}const recommendations=[],rc=1+Math.floor(rnd()*8);for(let i=0;i<rc;i++){const ticker=rnd()<.2&&i>0?'R0':'R'+i,entry=.2+rnd()*100,distance=Math.max(.01,entry*(.01+rnd()*.08));recommendations.push(rec(ticker,i+1,entry,Math.max(.001,entry-distance)))}const a=buildAllocation({cash,equity,positions,recommendations,reservePct,riskPerTradePct,maxWeightPct,totalRiskPct});assert.equal(a.blocked,false);const usable=cash*(1-reservePct/100);assert.ok(a.allocated<=usable+1e-6,`cash trial ${trial}`);assert.ok((a.plannedRisk||0)<=a.remainingRisk+1e-6,`risk trial ${trial}`);assert.equal(new Set(a.rows.map(x=>x.ticker)).size,a.rows.length,`dedupe trial ${trial}`);for(const row of a.rows){const old=held.get(row.ticker)||0,cap=equity*maxWeightPct/100;assert.ok(old+row.value<=cap+1e-6,`weight trial ${trial} ${row.ticker}`)}}});
