'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{SPECS,executeStrategy,v19Vector}=require('../../astra/strategies/g08-strict-overlay.cjs');
function history(n=260){return Array.from({length:n},(_,i)=>({sessionDate:`2026-${String(1+Math.floor(i/28)).padStart(2,'0')}-${String(1+i%28).padStart(2,'0')}`,close:100+i*.1,volume:1000000+i,validationStatus:'VALID',migrationValidationStatus:'VALID'}))}
function base(){return{snapshot:{snapshotId:'STRICT',ticker:'COMI',sessionDate:'2026-09-15',validationStatus:'VALID',migrationValidationStatus:'VALID'},history:history()}}
function v16Sessions(count=50,size=60){return Array.from({length:count},(_,d)=>Array.from({length:size},(_,i)=>({ticker:`T${i}`,xNew:[1,(i-size/2)/size,(d%5)/5],yTop10:i<10?1:0,yNetPositive:(i+d)%2===0?1:0,yLargeLoss:(i+d)%17===0?1:0})))}
function v16Current(size=60){return Array.from({length:size},(_,i)=>({ticker:`T${i}`,xNew:[1,(i-size/2)/size,.4],momentumFailureRisk:.1,effectiveSupport:1,turnover20:30000000,rsi14:60,ret20:10,ret5:2,breakout20:0,atr14:2,close:100+i*.1}))}
function feature(i=0){return{ret1:1,ret3:2,ret5:3,ret10:4,ret20:8,rs1:1,rs5:2,rs20:3,rsi:58,atrPct:2+(i%4),volumeRatio20:1.2,turnover20:2e7,sma5Dist:1,sma10Dist:2,sma20Dist:3,range20:.7,breakout20:0,volatility20:2,closePosition:.7,bodyPct:1,gapPct:0,distSupportAtr:1,distResistanceAtr:2,market1:.5,market5:1,market20:2,breadth:.55}}
function v19Sessions(count=50,size=60){return Array.from({length:count},(_,d)=>Array.from({length:size},(_,i)=>({ticker:`V${i}`,feature:feature(i),yTop10:i<10?1:0})))}
function v19Current(size=60){return Array.from({length:size},(_,i)=>({ticker:`V${i}`,feature:feature(i)}))}
test('V16 rejects fewer than 50 labeled signal sessions',()=>{const x=base();x.trainingSessions=v16Sessions(49);x.currentRows=v16Current();const out=executeStrategy('V16_TWO_STAGE_TOP_GAINER',x);assert.equal(out.eligibility,'INELIGIBLE');assert.equal(out.diagnostics[0].code,'INSUFFICIENT_LABELED_SIGNAL_SESSIONS')});
test('V16 rejects any cross-section below 60 and executes deterministically at the exact boundary',()=>{const bad=base();bad.trainingSessions=v16Sessions();bad.trainingSessions[7]=bad.trainingSessions[7].slice(0,59);bad.currentRows=v16Current();assert.equal(executeStrategy('V16_TWO_STAGE_TOP_GAINER',bad).diagnostics[0].code,'INSUFFICIENT_CROSS_SECTION');const x=base();x.trainingSessions=v16Sessions();x.currentRows=v16Current();const a=executeStrategy('V16_TWO_STAGE_TOP_GAINER',x),b=executeStrategy('V16_TWO_STAGE_TOP_GAINER',x);assert.equal(a.eligibility,'ELIGIBLE');assert.equal(a.executionHash,b.executionHash);assert.deepEqual(a,b)});
test('V19 TOP10 probability is trained internally at the evidenced 50x60 boundary before V6 selection',()=>{const x=base();x.trainingSessions=v19Sessions();x.currentRows=v19Current();x.priorLossStreak=2;const a=executeStrategy('V19_TOP10_PROBABILITY_INV_VOL_3',x),b=executeStrategy('V19_TOP10_PROBABILITY_INV_VOL_3',x);assert.equal(a.eligibility,'ELIGIBLE');assert.equal(a.componentScores.portfolioExposurePct,40);assert.equal(a.evidenceItems.length,3);assert.ok(a.evidenceItems.every(m=>m.atrPct<=8));assert.equal(a.executionHash,b.executionHash);assert.deepEqual(a,b)});
test('V19 feature vector is internal, fixed-width and deterministic',()=>{const a=v19Vector(feature(1)),b=v19Vector(feature(1));assert.equal(a.length,28);assert.deepEqual(a,b);assert.ok(a.every(Number.isFinite));assert.equal(SPECS.V19_TOP10_PROBABILITY_INV_VOL_3.parameters.basePolicy,'S0.00|R0|A8|INV_VOL|N3')});
