'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const{SPECS,executeStrategy,trainLogistic,calibratedProbability}=require('../../astra/strategies/g08-recovery-overlay.cjs');
function history(n=260){return Array.from({length:n},(_,i)=>({sessionDate:`2026-${String(1+Math.floor(i/28)).padStart(2,'0')}-${String(1+i%28).padStart(2,'0')}`,close:100+i*.1,volume:1000000+i,validationStatus:'VALID',migrationValidationStatus:'VALID'}))}
function base(){return{snapshot:{snapshotId:'S-G08',ticker:'COMI',sessionDate:'2026-09-15',validationStatus:'VALID',migrationValidationStatus:'VALID'},history:history()}}

test('destructive-review recovery leaves all 18 strategies internally executable',()=>{assert.equal(Object.keys(SPECS).length,18);for(const s of Object.values(SPECS))assert.equal(s.canExecuteInternally,true,s.strategyId)});
test('V15 MOMENTUM_ACCELERATION exact recovered conditions execute',()=>{const x=base();x.features={close:110,sma10:108,sma20:105,sma50:100,ret3:2,ret5:4,ret10:6,ret20:10,rs20:4,volumeRatio20:1.2,rsi14:60,rangePosition20:.8};const a=executeStrategy('MOMENTUM',x);assert.equal(a.eligibility,'ELIGIBLE');const y=structuredClone(x);y.features.rsi14=90;assert.equal(executeStrategy('MOMENTUM',y).eligibility,'INELIGIBLE')});
test('V15 REVERSAL_CONFIRMATION exact recovered conditions execute',()=>{const x=base();x.features={open:99,close:102,sma10:100,sma20:104,sma50:105,ret1:2,ret3:1,ret5:-2,volumeRatio20:1.5,rsi14:45};const a=executeStrategy('REVERSAL',x);assert.equal(a.eligibility,'ELIGIBLE');const y=structuredClone(x);y.features.volumeRatio20=.5;assert.equal(executeStrategy('REVERSAL',y).eligibility,'INELIGIBLE')});
test('V16 two-stage logistic training/scoring is deterministic and produces explicit execution result',()=>{const rows=[];for(let i=0;i<30;i++)rows.push({xNew:[1,(i-15)/15,i%2],yTop10:i%3===0?1:0,yNetPositive:i%2===0?1:0,yLargeLoss:i%7===0?1:0});const x=base();x.trainingRows=rows;x.currentRows=[{ticker:'COMI',xNew:[1,.2,1],momentumFailureRisk:.1,effectiveSupport:1.2,turnover20:30000000,rsi14:60,ret20:12,ret5:3,breakout20:1,atr14:2,close:100},{ticker:'SWDY',xNew:[1,-.1,0],momentumFailureRisk:.2,effectiveSupport:.5,turnover20:25000000,rsi14:58,ret20:8,ret5:2,breakout20:0,atr14:1.5,close:50}];const a=executeStrategy('V16_TWO_STAGE_TOP_GAINER',x),b=executeStrategy('V16_TWO_STAGE_TOP_GAINER',x);assert.equal(a.eligibility,'ELIGIBLE');assert.equal(a.executionHash,b.executionHash);assert.deepEqual(a,b);assert.ok(a.entryData&&a.stopData&&a.targets.length)});
test('V16 calibration helper is repeatable for identical training rows',()=>{const rows=[{x:[1,-1],y:0},{x:[1,1],y:1},{x:[1,.5],y:1},{x:[1,-.5],y:0}],w=trainLogistic([0,0],rows,'y','x',20,.02,.01,12),r={x:[1,.25]};assert.deepEqual(w,trainLogistic([0,0],rows,'y','x',20,.02,.01,12));assert.equal(calibratedProbability(w,r,rows,'y','x'),calibratedProbability(w,r,rows,'y','x'))});
test('V19 V6 exact base policy selects three ATR<=8 names with inverse-volatility weights and loss-streak exposure',()=>{const x=base();x.priorLossStreak=2;x.rankedCandidates=[{ticker:'A',top10:.8,atrPct:4},{ticker:'B',top10:.7,atrPct:8},{ticker:'C',top10:.6,atrPct:2},{ticker:'D',top10:.9,atrPct:12}];const out=executeStrategy('V19_TOP10_PROBABILITY_INV_VOL_3',x);assert.equal(out.eligibility,'ELIGIBLE');assert.equal(out.componentScores.portfolioExposurePct,40);assert.equal(out.evidenceItems.length,3);assert.ok(out.evidenceItems.every(m=>m.atrPct<=8));assert.ok(Math.abs(out.evidenceItems.reduce((s,m)=>s+m.baseWeightPct,0)-100)<.02)});
test('GANN V4 router follows exact evidenced regime rule and abstains in risk-off',()=>{const x=base();x.regime='RISK_ON';x.v1Candidates=[{ticker:'A',score:90},{ticker:'B',score:80}];x.sepaCandidates=[{ticker:'S',score:99}];const a=executeStrategy('GANN_REGIME_ROUTER',x);assert.equal(a.rawSignal,'V1_TREND');assert.equal(a.evidenceItems[0].ticker,'A');const y=base();y.regime='RISK_OFF';const b=executeStrategy('GANN_REGIME_ROUTER',y);assert.equal(b.rawSignal,'ABSTAIN');assert.equal(b.eligibility,'INELIGIBLE')});
test('SEPA QVUA internal selector is local, versioned and applies near-first-then-forming fallback',()=>{const x=base();x.candidates=[{symbol:'FORM',status:'FORMING',final_score:90,vcp:{score:60},eligibleForTop:false},{symbol:'NEAR',status:'NEAR PIVOT',final_score:70,entry_readiness_score:82,eligibleForTop:false},{symbol:'NEAR2',status:'NEAR PIVOT',final_score:65,entry_readiness_score:75,eligibleForTop:false}];const out=executeStrategy('SEPA_QVUA_NEAR_FIRST_THEN_FORMING',x);assert.equal(out.eligibility,'ELIGIBLE');assert.equal(out.rawSignal,'NEAR_FIRST_THEN_FORMING');assert.equal(out.evidenceItems[0].symbol,'NEAR');assert.equal(out.provenance.sourceCommit,'bf63dc85f515e58a7be1c6de6633eed87228a021')});
test('new recovery overlay contains no network/legacy runtime calls',()=>{const src=fs.readFileSync(path.resolve(__dirname,'../../astra/strategies/g08-recovery-overlay.cjs'),'utf8');for(const token of ['fetch(','axios','http.request','https.request','vercel.app','child_process'])assert.equal(src.includes(token),false,token)});
test('all recovered parameters remain source-pinned and retired/experimental strategies remain non-production',()=>{for(const s of Object.values(SPECS)){assert.match(s.sourceCommit,/^[a-f0-9]{40}$/);for(const p of s.parameterProvenance||[])assert.equal(p.sourceCommit,s.sourceCommit);if(['retired','experimental'].includes(s.lifecycleStatus))assert.equal(s.productionEligible,false,s.strategyId)}});
