'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const{SPECS,executeStrategy}=require('../../astra/strategies/g08-internal-strategies.cjs');
function history(n=260){return Array.from({length:n},(_,i)=>({sessionDate:`2026-${String(1+Math.floor(i/28)).padStart(2,'0')}-${String(1+i%28).padStart(2,'0')}`,open:100+i*.1,high:102+i*.1,low:99+i*.1,close:101+i*.1,volume:1000000+i,turnover:10000000+i,validationStatus:'VALID',migrationValidationStatus:'VALID'}))}
function base(n=260){return{snapshot:{snapshotId:'S1',ticker:'COMI',sessionDate:'2026-09-15',ohlc:{open:100,high:104,low:99,close:103},volume:2000000,turnover:30000000,validationStatus:'VALID',migrationValidationStatus:'VALID'},history:history(n),indicators:{close:103,sma20:100,sma50:95,rsi14:58,volumeRatio20:1.5,relativeStrength20:5,resistanceUpsidePct:3,breakoutPct:1,distanceSma20Pct:1,macd:2,macdSignal:1,atrPct:2,averageTurnover20Egp:30000000,relativeStrengthComposite:90,distanceFromAvailableHighPct:-3,contractionRatio:.5,volumeDryUpRatio:.7},components:{legacyOpportunity:70,dataEvidence:80,liquidity:85,supportResistance:75,netRiskReward:80,tradePlanAlignment:90,currentTechnical:88,technicalScore:80,researchScore:82,liquidityScore:70,liquidityEligible:true,srConfluenceScore:70,srStrongMethods:3,netRiskReward:1.2,pullbackAtr:.4,entryState:'READY'},parts:{gannTime:{score:80,active:true},gannPrice:{score:75},trend:{score:80},relativeStrength:{score:78},breakout:{score:80,confirmed:true,near:true},volume:{score:85,confirmed:true},momentum:{score:75,overheated:false,rsi14:60},fundamentals:{score:70},entryQuality:{score:80},riskReward:{score:80,rr:1.8},marketRegime:{score:75,regime:'RISK_ON'}},dataQuality:{fresh:true,conflict:false},levels:{riskPct:4,rr1:1.8},triggerDistancePct:1.2,moneyFlowQualityScore:70,dataConfidenceScore:75,candidates:[{ticker:'COMI',eligible:true},{ticker:'SWDY',eligible:true}],entryPrice:100,atr14:2,forwardBars:[{high:101,low:99},{high:103,low:99},{high:104,low:100}],config:{configuration:'BALANCED_3D'}}}

test('all 18 discovered strategies have explicit G08 dispositions',()=>{assert.equal(Object.keys(SPECS).length,18);for(const s of Object.values(SPECS)){assert.ok(s.reconstructionStatus);assert.equal(typeof s.canExecuteInternally,'boolean');assert.equal(typeof s.productionEligible,'boolean');assert.ok(s.sourceCommit);assert.ok(s.sourcePaths.length)}});
test('retired/experimental reconstruction never auto-enables production',()=>{for(const s of Object.values(SPECS).filter(x=>['retired','experimental'].includes(x.lifecycleStatus)))assert.equal(s.productionEligible,false,s.strategyId)});
test('blocked strategies return diagnostic rather than fabricated signal',()=>{for(const s of Object.values(SPECS).filter(x=>!x.canExecuteInternally)){const out=executeStrategy(s.strategyId,base());assert.equal(out.eligibility,'INELIGIBLE');assert.equal(out.normalizedSignal,'UNKNOWN');assert.equal(out.diagnostics[0].code,'STRATEGY_NOT_RECONSTRUCTED')}});
test('raw legacy archive cannot enter strategy execution',()=>{const x=base();x.snapshot.rawLegacy=true;const out=executeStrategy('TREND_FOLLOW',x);assert.equal(out.eligibility,'INELIGIBLE');assert.equal(out.diagnostics[0].code,'RAW_LEGACY_INPUT_FORBIDDEN')});
test('unresolved migration row cannot enter live history',()=>{const x=base();x.history[3].migrationValidationStatus='UNRESOLVED';const out=executeStrategy('TREND_FOLLOW',x);assert.equal(out.eligibility,'INELIGIBLE');assert.equal(out.diagnostics[0].code,'MIGRATION_HISTORY_NOT_ELIGIBLE')});
test('invalid canonical candidate is excluded',()=>{const x=base();x.snapshot.validationStatus='INVALID';const out=executeStrategy('TREND_FOLLOW',x);assert.equal(out.eligibility,'INELIGIBLE');assert.equal(out.diagnostics[0].code,'SNAPSHOT_NOT_VALID')});
test('insufficient valid history produces diagnostic, not a signal',()=>{const out=executeStrategy('TREND_FOLLOW',base(10));assert.equal(out.eligibility,'INELIGIBLE');assert.equal(out.diagnostics[0].code,'INSUFFICIENT_VALID_HISTORY');assert.equal(out.normalizedSignal,'UNKNOWN')});
test('V13 trend/breakout/pullback reconstructed evaluators execute',()=>{for(const id of ['TREND_FOLLOW','BREAKOUT','PULLBACK']){const out=executeStrategy(id,base());assert.match(out.executionHash,/^[a-f0-9]{64}$/);assert.equal(out.eligibility,'ELIGIBLE')}});
test('V18 EMA-MACD evaluator enforces evidenced thresholds',()=>{const out=executeStrategy('EMA_MACD_TREND_CONTINUATION',base());assert.equal(out.eligibility,'ELIGIBLE');const x=base();x.indicators.averageTurnover20Egp=1000;assert.equal(executeStrategy('EMA_MACD_TREND_CONTINUATION',x).eligibility,'INELIGIBLE')});
test('V18 leadership requires full 220-session label coverage',()=>{assert.equal(executeStrategy('RELATIVE_STRENGTH_HIGH_PROXIMITY',base(220)).eligibility,'ELIGIBLE');const x=base(219);const out=executeStrategy('RELATIVE_STRENGTH_HIGH_PROXIMITY',x);assert.equal(out.diagnostics[0].code,'INSUFFICIENT_VALID_HISTORY')});
test('V18 VCP returns explicit pass/fail from evidenced contraction limits',()=>{assert.equal(executeStrategy('VOLATILITY_CONTRACTION_PATTERN',base()).eligibility,'ELIGIBLE');const x=base();x.indicators.contractionRatio=.9;assert.equal(executeStrategy('VOLATILITY_CONTRACTION_PATTERN',x).eligibility,'INELIGIBLE')});
test('V16 retired triple barrier is internally executable but not production eligible',()=>{const s=SPECS.V16_TRIPLE_BARRIER_GATE,out=executeStrategy(s.strategyId,base());assert.equal(s.productionEligible,false);assert.ok(['BUY','REJECT','HOLD'].includes(out.normalizedSignal));assert.match(out.executionHash,/^[a-f0-9]{64}$/)});
test('V20 component score uses frozen documented weights',()=>{const out=executeStrategy('V20_NATIVE_MULTI_COMPONENT_COMPOSITE',base());assert.equal(out.rawScore,82.14)});
test('GANN fusion reconstructs documented weighted/classification boundary',()=>{const out=executeStrategy('GANN_FUSION',base());assert.equal(out.eligibility,'ELIGIBLE');assert.equal(out.rawSignal,'STRONG_RESEARCH')});
test('GANN execution quality is deterministic and locally executable',()=>{const a=executeStrategy('GANN_ENTRY_EXECUTION_QUALITY',base()),b=executeStrategy('GANN_ENTRY_EXECUTION_QUALITY',base());assert.equal(a.executionHash,b.executionHash);assert.deepEqual(a,b)});
test('TFE hard-gate fusion rejects failed hard gate without fabricating positive signal',()=>{assert.equal(executeStrategy('TFE_EVIDENCE_AWARE_HARD_GATE_FUSION',base()).eligibility,'ELIGIBLE');const x=base();x.components.netRiskReward=.4;const out=executeStrategy('TFE_EVIDENCE_AWARE_HARD_GATE_FUSION',x);assert.equal(out.eligibility,'INELIGIBLE');assert.equal(out.normalizedSignal,'NO_SIGNAL')});
test('basket keeps explicit equal weights and never activates failed members',()=>{const x=base();x.candidates.push({ticker:'BAD',eligible:false});const out=executeStrategy('PORTFOLIO_BASKET_EQUAL_WEIGHT',x);assert.equal(out.evidenceItems.length,2);assert.equal(out.evidenceItems.reduce((s,m)=>s+m.weightPct,0),100)});
test('identical execution inputs produce byte-stable semantic outputs for every reconstructed strategy',()=>{for(const s of Object.values(SPECS).filter(x=>x.canExecuteInternally)){const a=executeStrategy(s.strategyId,base()),b=executeStrategy(s.strategyId,base());assert.equal(JSON.stringify(a),JSON.stringify(b),s.strategyId);assert.equal(a.executionHash,b.executionHash,s.strategyId)}});
test('execution hash changes when meaningful canonical input changes',()=>{const a=executeStrategy('TREND_FOLLOW',base());const x=base();x.snapshot.snapshotId='S2';const b=executeStrategy('TREND_FOLLOW',x);assert.notEqual(a.executionHash,b.executionHash)});
test('G08 internal strategy layer has zero legacy-network/runtime calls',()=>{const src=fs.readFileSync(path.resolve(__dirname,'../../astra/strategies/g08-internal-strategies.cjs'),'utf8');for(const token of ['fetch(','axios','http.request','https.request','child_process','quant-edge-shadow.vercel.app','stable-sepax.vercel.app'])assert.equal(src.includes(token),false,token)});
test('strategy parameters carry source commit/path provenance',()=>{for(const s of Object.values(SPECS)){for(const p of s.parameterProvenance){assert.equal(p.sourceCommit,s.sourceCommit);assert.equal(p.sourcePath,s.sourcePaths[0]);assert.ok(p.strategyVersion)}}});
